### ISSUE TITLE
Vector field data calculations

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1002]
This is paired with the frontend feature https://github.com/CARTAvis/carta-frontend/issues/1155

Please refer to the google doc https://docs.google.com/document/d/1S8nNvonlowNwX_uPoPspxugUEnw5wRxbAS6y2HScTzs/edit# for details.

**Comment by veggiesaurus** [comment]
adjusting the story points to 5 because HDF5 tile cache needs to be taken into account
