### ISSUE TITLE
cube histogram performance difference with different cube shapes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1017]
The shape of a cube would result in quite different performance when computing cube histogram. For example, there are two cubes as 
- cubeA: 10 x 10 x 10000 (4MB)
- cubeB: 100 x 100 x100 (4MB)

Computing the cube histogram of cubeB would be almost instantly done but for cubeA it would take a long while. What would be the root cause here (overhead when iterating through channels?) and is there a way to improve this? 

[cube_100_100_100.fits.zip](https://github.com/CARTAvis/carta-backend/files/8028844/cube_100_100_100.fits.zip)
[cube_10_10_10000.fits.zip](https://github.com/CARTAvis/carta-backend/files/8028847/cube_10_10_10000.fits.zip)

**Comment by veggiesaurus** [comment]
I think there's a way to _improve_ this, but I think cube A will always be much slower, because it involves 10000 very small reads, compared to 100 larger ones

**Comment by kswang1029** [comment]
close for now as the examples are less realistic. This serves as a note for the future if there is a user feedback on this.
