### ISSUE TITLE
[Concurrence] Frontend sending many events concurrently sometimes get no response from backend.

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#102]
For a performance test, it will let backend response error whenever the front sends too many request concurrently. But it is stable that backend gets requests one after another in order between a short period, likely 20ms.

**Comment by veggiesaurus** [comment]
are there particular events that this happens for?

**Comment by kswang1029** [comment]
Could you elaborate in detail what kind of performance test you are trying to do in such high cadence? 20ms is 50 fps using the animator for example.

**Comment by veggiesaurus** [comment]
I think typical event rates should be below 30 per second (per session). But events should not be missed, so this is a very useful test. We don't want two events that arrive within 20 ms of each other to have unpredictable behaviour

**Comment by kswang1029** [comment]
In real world, messages from different users can arrive very close to each other’s, can’t they? If so this is an important issue.

**Comment by veggiesaurus** [comment]
I think we're most likely to use a system where one backend process is shared by a minimum number of users, but even for one user, messages can arrive within a 20 ms window quite easily (imagine playing back an animation and moving your cursor)

**Comment by zarda** [comment]
After decrease the period of sending `SetImageChannels` on the test "ANIMATOR_PLAYBACK" to 1ms, the test result is the increase of fps. In this case, there is only one user with one session, which send event in order but rapidly. For the current release, the fps is up to 30 Hz. 👍🏻

**Comment by zarda** [comment]
current test is about "image open". The test about other event will be implemented soon.

**Comment by veggiesaurus** [comment]
I think this might have been fixed in PR #259. Could we investigate this again?
