### ISSUE TITLE
Beam position angle incorrectly reported and rendered as degrees instead of radians for CASA image

### ISSUE THREAD

**Issue by nbrunett** [CARTAvis/carta-backend#1025]
**Describe the bug**
For a `CASA` image created in `CASA` with `tclean`, the "file information" in the "file browser" dialog of `CARTA` reports the restoring beam position angle to be -1.44 deg while the "header" tab shows `BPA = -8.235030409149E+01`. Also, the beam ellipse when the image is loaded is using the position angle reported under "file information".

`imhead` in `CASA` shows that the position angle is -1.44 radians, so it looks like `CARTA` is assuming it is in degrees in some places.

**To Reproduce**
1. Click File -> Open image.
2. Click on the image.
3. Note the restoring beam position angle under "file information".
4. Click the "header" tab and note the different value.
6. Click Load and the beam ellipse is drawn with the "file information" position angle.

**Expected behavior**
The "file information" should report the correct position angle value with the appropriate units (either report radians like `imhead` does or convert value to degrees). The beam ellipse should be drawn based on the value and units of the position angle being consistent.

**Platform info (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: N/A (just running `CARTA` app directly in it's own window)
 - Version: 3.0.0-beta.2b

**Additional context**
One of my cubes where I am seeing this issue is fairly small (6 MB) and I can provide it if that would help.

Thanks.

**Comment by kswang1029** [comment]
@nbrunett thanks for reporting this issue. It would be very helpful if you can share with us your test images for debugging.

**Comment by nbrunett** [comment]
Here you go. The `radians` file has the beam position angle in radians, and `degrees` has it in degrees.

Let me know if you have any issues with the files or need anything else.

[radians.tar.gz](https://github.com/CARTAvis/carta/files/8097690/radians.tar.gz)
[degrees.tar.gz](https://github.com/CARTAvis/carta/files/8097691/degrees.tar.gz)

**Comment by kswang1029** [comment]
Here is the header obtained with casa-imhead. "radians.image" has the beam position angle defined in 'rad' in the casa image header format.
![Screen Shot 2022-02-21 at 15 19 08](https://user-images.githubusercontent.com/20819712/154907048-82f21961-1cdb-45c1-8489-a4bb82b2dcb1.png)
In CARTA, the BPA header (as -8.235030409149E+01) in FITS format is displayed correctly in the header tab. In the file information tab, the displayed beam position angle, as -1.43728 deg, is incorrect. This "-1.43728" is actually the value in rad defined in the casa image header. So the issue here is we will need to consider the unit of the positionangle header in casa images when deriving the file information data.

**Comment by kswang1029** [comment]
@nbrunett Do you have any idea why the beam position angle is defined in rad not in degree? Are these test images generated with tclean directly without any other steps? We would like to get some ideas on how many casa images use rad to define the position angle of the beam element (knowing this would help us on scheduling of this bug fix). Thanks.

**Comment by nbrunett** [comment]
I don't have any ideas why the units are different sometimes, sorry. I should say that these cubes were made in an older version of `CASA` (5.6.1) for other compatibility reasons. I did try the `tclean` step in 6.2.1 (the newest I have access to for a quick test) with the same result.

These are cubes that I was making for science, not just for testing `CARTA`. This means there's a series of steps that prepare the measurement sets to be cleaned which should be nearly identical except for the frequency range (the two cubes are centered on two different CN spectral lines with rest frequencies of 113.14415730 GHz and 113.49097020 GHz). The `tclean` calls are identical except for the input measurement sets, pixel sizes, x/y dimensions, and rest frequencies. It's not obvious to me why any of those would cause the beam position angle units to be different.

Sorry this doesn't help with your question of how often the units are radians. I think it's worth noting that a lack of people reporting this issue up to this point may not mean it is rare. If the beam ellipse is small and round enough it would be difficult to notice this problem. The large and fairly elliptical beams in my cubes (that should have nearly identical beams) helped make it stand out when the beam ellipse rotated by almost 90 degrees when switching between cubes.
