### ISSUE TITLE
An offset in the offset axis of a PV image generated with fixed angular separation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1038]
With a test wide field image cube, if the pv cut is sampled with fixed pixel separation, the origin of the offset axis is correct as
![Gaussian_array_wide fits-Gaussian_array_wide_pv fits-image-2022-03-09-15-31-56](https://user-images.githubusercontent.com/20819712/157394042-0dcbc648-ece1-4a06-8823-074fd70b8d11.png)

However, if we simply increase the pv cut of the above example so that it is sampled with fixed angular separation, there seems to have an offset in the offset axis of the pv image as
![Gaussian_array_wide fits-Gaussian_array_wide_pv fits-image-2022-03-09-15-31-27](https://user-images.githubusercontent.com/20819712/157394433-f1bd55e6-ff95-451d-a4bd-65315a72398d.png)

We can see the origin of the offset axis does not overlay with the peak emission of the central gaussian source.

@pford do you have any idea on this? Could it be due to the precision issue when converting pixel coordinate to world coordinate in such noticeably distorted sky field?

**Comment by pford** [comment]
@kswang1029 offset 0 is at the **angular** center of the line, then the pos/neg offsets are calculated from there.  So angular center != pixel center shown on image.

**Comment by pford** [comment]
I think if we use the pixel center of the line, then to make offset 0 at the center of the PV image we will either go past the end of the line on one side or not reach the end of the line on the other side.

**Comment by kswang1029** [comment]
> I think if we use the pixel center of the line, then to make offset 0 at the center of the PV image we will either go past the end of the line on one side or not reach the end of the line on the other side.

I suggest we align the pixel center of the line and the origin of the offset axis as mostly the center and origin serve as the references when users analyze emission structures and kinematics. This is also ensure consistency of visualization of the center of the line and the origin of the offset axis in the pv image. 

Regarding the sampling near the two ends of the line, it is okay to go pass the end or not reach the end _by half of a step_. Mostly users will just focus on features around the center of the offset axis. If the edge features are important, users can just make the line longer and regenerate a pv image for analysis.

**Comment by pford** [comment]
The profiles generated for the PV image (all channels) currently use the same code as the line/polyline spatial profiles (current channel).  Should the pixel center of the line be used for the both the PV generator and the spatial profiles?  I believe the plan is to eventually support PV images from a polyline as well.

The issue with the polyline is that using the pixel center of each line, you may not reach the "vertex" end of the line, resulting in gaps, or overreach the vertex, adding profiles not in the polyline.  I can adjust each line to reach the "vertex end" within half a step and lengthen/shorten the other end, but what to do with the middle line in a 3-segment polyline where you have to choose which vertex end to reach?

**Comment by pford** [comment]
I am planning to fix this issue in the branch for line spatial profiles while I am modifying the fixed angular profiles code for polyline support.

In effect, a line is a polyline with one line segment.  Each line segment is handled individually because each has its own rotation angle, used to determine the points along the line where the box regions are created for the profiles.

But perhaps polylines should be treated differently, and just go from start to end rather than from the center out in each line segment since there is no "line center".

**Comment by kswang1029** [comment]
@pford retested with the branch `pam/796_line_profile` and the issue is fixed. Thanks for addressing this 👍 . This issue can be closed once `pam/796_line_profile` is merged in.
