### ISSUE TITLE
Ensure 2.0 release works with updated casacore dependency

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#1041]
We need to rebuild version 2.0 with the latest casacore dependency, to ensure that it functions correctly.

**Comment by kswang1029** [comment]
packages to check
- [x] ubuntu package on 18.04
- [x] ubuntu package on 20.04
- [x] centos7 rpm
- [x] centos8 rpm
- [x] homebrew on intel Mac Big Sur

**Comment by ajm-ska** [comment]
@kswang1029 I have updated the carta-casacore RPM to 3.4.0+6.5.0+2022.4.12 and rebuilt the carta-backend (v2.0) and carta-backend-beta (v3.0-beta.2) RPMs (both x86-64 and aarch64) to use it. I did a quick test and it appears to work. So maybe we can close this issue now.

**Comment by ajm-ska** [comment]
I just tried this with the even newer carta-casacore-3.4.0+6.5.0+2022.4.22 el7 and el8 RPMs, and carta v2.0 still works. I will close this issue now.
