### ISSUE TITLE
[backend crash] SET_CURSOR and SPECTRAL_PROFILE_DATA

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#105]
With the demo server: CARTA v1.1-alpha | frontend 48fd377 | backend 47854d0

To reproduce:
1) open set_QA/OrionKL_sci.spw19.cube.I.pbcor.fits (84.9 GB)
2) move cursor on the image at few random positions for few seconds (with >200ms stop for each movement; so that SET_CURSOR will be sent to the backend). Don't wait and proceed with the next step.
3) then open another image such as set_QA/S255_IR_sci.spw25.cube.I.pbcor.fits (7.0 GB)
4) repeat step 2) and we should see backend crashed and the server status icon on the top-right corner becomes orange.

Threading issue?

**Comment by pford** [comment]
Possibly same issue as #19 .  When you opened the image in step 3 it closed the image in step 1, which destroys the Frame and underlying classes.  Most likely while something was being calculated in a thread and there is currently no way to cancel.

**Comment by kswang1029** [comment]
Just a thought, can we generate the SPECTRAL_PROFILE_DATA piece by piece? For example, we have a 4000 channel cube. The profile is then generated every 100 channel or so (maybe matching the tile z-depth or multiple of z-depth). If we adopt this way, can it be cancellable, just like the per-cube histogram?

**Comment by veggiesaurus** [comment]
The ICD already specifies a progress field for spectral profiles specifically for delivering updates before the profile is complete. For files that have a large number of channels and no rotated dataset, this will probably be essential.
