### ISSUE TITLE
HDF5 file loader has memory leaks

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#1059]
**Describe the bug**
`Hdf5Loader::GetStatsDataTyped` creatse a `casacore::ArrayBase` raw pointer. This is fine, and we `delete` the pointer in `LoadStats2DBasic` and `LoadStats3DBasic` etc, but if an exception is thrown, this pointer is never deleted. We should make this a `unique_ptr<casacore::ArrayBase>` to get around this.

**Comment by pford** [comment]
Will fix along with memory leak issues in #1058
