### ISSUE TITLE
carta_backend built with ASAN flags crashes when importing a specific region file.

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#1066]
**Describe the bug**
When we run the `DS9_REGION_EXPORT.test.ts` ICD test on macOS12, the carta_backend crashes. We can also trigger it manually.

**To Reproduce**
1. Build the carta_backend with the following flags:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -fsanitize=address -fno-omit-frame-pointer' -DCMAKE_EXE_LINKER_FLAGS='-fsanitize=address' 
```
2. Start the carta-backend with the appropriate ASAN flags (remember to adjust paths for your system). This way proves we are taking the current ASAN suppressions into account):
```
ASAN_OPTIONS=suppressions=/Users/ajm/carta-backend/debug/asan/myasan.supp LSAN_OPTIONS=suppressions=/Users/ajm/carta-backend/debug/asan/myasan-leaks.supp ASAN_SYMBOLIZER_PATH=llvm-symbolizer ./carta_backend --frontend_folder=/Users/ajm/carta-frontend/build --verbosity=5
```
or as normal:
```
./carta_backend --frontend_folder=/Users/ajm/carta-frontend/build --verbosity=5
```

3. Open the `M17_SWex.image` image file.

4. Open the `M17_SWex_handMadeRegions_world.reg` file available [here](https://alma.asiaa.sinica.edu.tw/_downloads/M17_SWex_handMadeRegions_world.reg)
 
5. carta_backend crashes.

**Expected behavior**
The carta_backend should not crash.

**Screenshots or videos**
The full crash log can be viewed here: [asan-region-crash.log](https://github.com/CARTAvis/carta-backend/files/8282636/asan-region-crash.log)
 

**Platform info (please complete the following information):**
- OS: macOS12 M1
- Browser: Firefox
- Version: 98

**Additional context**
If the carta_backend is built without the ASAN flags, i.e. only `cmake ..`, the crash does not occur.

**Comment by acdo2002** [comment]
So far it occurs related to "export region" action, the error messages show between `[protocol] <== EXPORT_REGION` and `[protocol] ==> EXPORT_REGION_ACK`. 
Not related to the image type (happened in all three types: fits, image, and hdf5)
Can trigger manually by export region as "**world coordinates**" for both CRTF region file and DS9 region file. No error if I export region as "pixel coordinates"

update:
The same error messages show on MacOS 11.6 with old carta_casacore (io.5)

**Comment by pford** [comment]
@ajm-asiaa I cannot build on MacOS M1, do you have instructions?

But I looked at the log and it indicated the error is in RegionImportExport.cc:93 where it reads each line of the region file into a string.  Line 93 is a blank line in the code, but the next line is: `if (single_line.back() == '\r')` 

I am wondering if single_line is an empty string and back() causes the crash.  I added this check: `if (!single_line.empty() && (single_line.back() == '\r'))` in branch `pam/1066_ds9_import`.  Could you see if that fixed it?

**Comment by pford** [comment]
The sanitizer log also indicates `READ of size 1` which also suggests back() is the problem.

**Comment by ajm-ska** [comment]
@pford That does indeed fix the problem! Now I can open the `M17_SWex_handMadeRegions_world.reg` file on the M1 Mac. Thank you!

**Comment by ajm-ska** [comment]
@pford To answer your question, we have some original installation instructions in a Google Doc [here](https://docs.google.com/document/d/1QL9zyM1Aj6xcMSGc2Nrr4u91iNSw7N31VJNj8CFNOpg/edit). It is a bit messy as the steps have changed over time, but following the commands in blue should work.

`pam/1066_ds9_import` is ready to be a PR.

**Comment by pford** [comment]
Thanks @ajm-asiaa .  Can we put this doc and the other Mac build [doc](https://docs.google.com/document/d/1STmqf0CaeVTwWfDGI1D0VloSvXHKlS2kcFEAFFqHDn8/edit?usp=sharing) in the shared drive? There is a **build and deploy and CI** folder under **CARTA technical documents**.  I worry that I will lose these links.
