### ISSUE TITLE
carta_backend built with ASAN flags occasionally crashes running Moments ICD tests 

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#1070]
**Describe the bug**
The carta-backend sometimes crashes when running the `MOMENTS_GENERATOR_FITS.test.ts` or `MOMENTS_GENERATOR_HDF5.test.ts` ICD tests. It can happen on Ubuntu 18.04, macOS12, and RHEL8. 
It is rare on Ubuntu 18.04, but occurs more frequently on macOS12 with the HDF5 test.

**To Reproduce**
Build carta-backend with the Address Sanitizer flags. 
Start the carta-backend.
Repeatedly run the `MOMENTS_GENERATOR_HDF5.test.ts` ICD test.
The carta-backend may crash on the 2nd or 3rd try.

**Expected behavior**
carta-backend should not crash.

**Screenshots or videos**
Here is the full crash log when running the `MOMENTS_GENERATOR_FITS.test.ts` test in the Ubuntu 18.04 Docker container [moment-generator-crash-ubuntu-1804.log](https://github.com/CARTAvis/carta-backend/files/8320635/moment-generator-crash-ubuntu-1804.log)
Here is the full crash log when running the `MOMENTS_GENERATOR_HDF5.test.ts` on the M1 macOS12 [moment-generator-crash-macos12.log](https://github.com/CARTAvis/carta-backend/files/8320922/moment-generator-crash-macos12.log)

**Platform info (please complete the following information):**
 - OS: Ubuntu 18.04 Docker container (ajmasiaa/bionic-jenkins-mar2022) and macOS12 

**Additional context**
I tried to trigger the issue through the frontend by manually following the steps in the ICD test, but can not create the crash event manually yet. 

This issue is probably related to other reported issues.

**Comment by acdo2002** [comment]
I confirmed this issue occurs in Ubuntu 20.04 Laptop and macOS12 Desktop.
It **only** occurs with carta_backend with Address Sanitizer flag.
The carta_backend Ubuntu 20.04 log can be download from [MOMENT_HDF5_AS-Ubuntu.log](https://github.com/CARTAvis/carta-backend/files/8322263/MOMENT_HDF5_AS-Ubuntu.log)

The carta_backend macOS12 log can be download from 
[MOMENT_HDF5_AS-Mac.log](https://github.com/CARTAvis/carta-backend/files/8322285/MOMENT_HDF5_AS-Mac.log)


If I use the carta_backend **without** Address Sanitizer flag, this issue will **not occur**.

**Comment by veggiesaurus** [comment]
The ubuntu error seems very odd to me. It looks like it's complaining about a double-free on `std::vector<CARTA::StatsType> _spectral_stats`, which is just handled by the default destructor of `RegionHandler`.

**Comment by Kechil** [comment]
Hi @markccchiang, @jolopezl  
Sorry for confusion about re-assigning. This is Jorge's task but we thought it would be good for Mark to help out.
