### ISSUE TITLE
RPM packages for ARM

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#1077]
This is a placeholder issue for tracking the creation and publication of ARM builds of the RPM packages for the backend and all dependencies. There's a [companion issue](https://github.com/CARTAvis/carta-backend/issues/1078) for Ubuntu packages. This issue should be closed once ARM RPMs are publically available.

**Comment by ajm-ska** [comment]
The aarch64 el7 and el8 RPMs for CARTA v2.0 and CARTA v3.0-beta2 are ready and live on `packages.cartavis.org`. 

Both are also using the new carta-casacore-3.4.0+6.4.4+2022.3.9 even though I know we will need a newer bug-fixed carta-casacore soon. The el7 RPMs have been updated to use carta-gsl 2.5. 

I created and tested the RPMs through Docker containers on an M1 Mac, but I assume they will also work on any Linux ARM-based system.

If you are curious, there are several ways to test, but here is one way:

To test el8:

1. Create a Dockerfile called `Dockerfile-el8-test` with the following contents:
```
FROM almalinux

RUN \
  curl https://packages.cartavis.org/cartavis-el8-aarch64.repo --output /etc/yum.repos.d/cartavis.repo && \
  dnf -y install 'dnf-command(config-manager)' && \
  dnf -y config-manager --set-enabled powertools && \
  dnf -y install epel-release
```
(Note the `cartavis-el8-aarch64.repo` file for aarch64 only)
2. Build the Docker container: `docker build -f Dockerfile-el8-test -t el8test .`
3. Run the Docker container remembering to open port 3002 and mounting your local image directory (in this example /data/images): `docker run -ti -p 3002:3002 -v /data/images:/images el8test`
4. To install CARTA v2.0: `yum -y install carta`
5. To run: `./carta /images`
6. Copy and paste the URL into your local web-browser. On MacOS Docker, you would need to change the IP address to `localhost`.
7. To try CARTA v3.0-beta2 type `yum remove carta` and `yum -y install carta-beta`.
8. Start CARTA `./carta /images` and copy and paste the URL again.

To test el7:

1. Create a Dockerfile called `Dockerfile-el7-test` containing the following:
```
FROM centos:7.9.2009

RUN \
 yum -y update && \
 curl https://packages.cartavis.org/cartavis-el7-aarch64.repo --output /etc/yum.repos.d/cartavis.repo && \
 yum -y install epel-release
```
2. Build the Docker container: `docker build -f Dockerfile-el7-test -t el7test .`
3. Run the Docker container remembering to open port 3002 and mounting your local image directory (in this example /data/images): `docker run -ti -p 3002:3002 -v /data/images:/images el7test`
4. To install CARTA v2.0: `yum -y install carta`
5. To run: `./carta /images`
6. Copy and paste the URL into your local web-browser. On MacOS Docker, you would need to change the IP address to `localhost`.
7. To try CARTA v3.0-beta2 type `yum autoremove carta` then `yum -y install carta-beta`.
8. Start CARTA `./carta /images` and copy and paste the URL again.

For reference, here are the dependencies:

el8 CARTA v2.0:
![Screen Shot 2022-04-04 at 5 24 00 PM](https://user-images.githubusercontent.com/20802551/161514725-14271565-a13f-46fa-86c8-83ee25023cc3.png)

el8 CARTA v3.0-beta2:
![Screen Shot 2022-04-04 at 5 36 29 PM](https://user-images.githubusercontent.com/20802551/161517076-97c5eba5-dfd1-463e-b8f8-cc1bbc563375.png)

el7 CARTA v2.0:
![Screen Shot 2022-04-04 at 5 38 23 PM](https://user-images.githubusercontent.com/20802551/161517456-081c235e-7fbf-40ea-94fe-8af41fd7f38b.png)

el7 CARTA v3.0-beta2:
![Screen Shot 2022-04-04 at 5 44 31 PM](https://user-images.githubusercontent.com/20802551/161518485-7280fcd0-0107-446f-983d-5ffbf1a211dc.png)

**Comment by ajm-ska** [comment]
aarch64 carta-casacore RPMs have since been updated to `3.4.0+6.5.0+2022.4.12`, and carta-backend and carta-backend-beta have been rebuilt to use it.
