### ISSUE TITLE
"box" region loaded from ds9 region file has incorrect angular size

### ISSUE THREAD

**Issue by privong** [CARTAvis/carta-backend#1101]
**Describe the bug**
I have a rectangular ds9 region saved as a file. When I load the region into CARTA the size of the region is significantly smaller than expected and is also significantly smaller than the same region loaded into `ds9`.

**To Reproduce**
1. Use a region file the following contents:
```
# Region file format: DS9 astropy/regions
fk5
box(335.184002,-24.680416,0.000278,0.000278,0.000000) # name=0
```
2. File->"Open Image" to load FITS image including that coordinate in the FOV
3. File->"Import Regions" to load the region file specified in 1) above.

**Expected behavior**
A rectangular region centered on (RA,Dec)=(335.184002,-24.680416) with width and height of 0.000278deg should be showed on the image panel. The region panel of CARTA should show the same information for the region. This is the behavior of loading the region file in `ds9`.

The actual behavior is that a box is shown at the position, but the height and width are 0.000278arcsec. So this seems to be a unit interpretation problem. 

**Platform info (please complete the following information):**
 - OS: MacOS 10.15.17 / Linux
 - Browser: Local CARTA install / Firefox 91.8.0esr 
 - Version: 3.0.0-beta.2b / 2.0.0

**Additional context**
This bug seems to be present in both v2.0.0 and v3.0.0-beta.2b, tested using the combinations listed above (i.e., 3.0.0-beta.2b on MacOS 10.15.17 with a local install, and 2.0.0 run from Linux with `--no_browser` and viewed remotely via Firefox).

**Comment by kswang1029** [comment]
based on the ds9 user manual ("Specifying Positions and Sizes" of http://ds9.si.edu/doc/ref/region.html), in this case the implicit unit for size is degree.

**Comment by privong** [comment]
Thanks, @kswang1029. I created these regions with astropy's regions module and they seemed to load okay in ds9, so those two don't seem to be following the specs in the manual. I'll try to file upstream bug reports with them.
