### ISSUE TITLE
images as fits.gz from ALMA Science Archive not recognized by CARTA

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1130]
**Describe the bug**
Reported by a v3 beta tester. Images as fits.gz downloaded from the ALMA Science Archive are not recognized by CARTA. If we unzip it and re-zip it (in my case with the gzip in macOS "Apple gzip 353.100.22"), the new fits.gz file can be recognized.

test images are attached
[test_by_mac_gzip.fits.gz](https://github.com/CARTAvis/carta-backend/files/8918988/test_by_mac_gzip.fits.gz)
[test_from_alma_archive.fits.gz](https://github.com/CARTAvis/carta-backend/files/8918993/test_from_alma_archive.fits.gz)

**To Reproduce**
1. download the example images above (or download such from the ALMA Science Archive directly)
2. check the file list and we will only see one image showing up

**Expected behavior**
The fits.gz images from the ALMA science archive should be recognized by CARTA.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: v3b3 electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v3b3 electron app
 - Frontend branch [e.g. dev, v3b2 release]: v3b3 electron app

**Comment by kswang1029** [comment]
@markccchiang could you help on this one?

**Comment by markccchiang** [comment]
> @markccchiang could you help on this one?

Ok.
