### ISSUE TITLE
[redhat v3b3 appimage only] backend crash when generating moment images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1132]
**Describe the bug**
With a normal image cube generated with casa-tclean (attached for testing), when requesting a moment image generation, the backend will crash. This happens only with the redhat appimage (haven't tried the rpm) on almalinux8. With macOS v3b3 electron app or ubuntu appimage on ubuntu 20.04, CARTA can generate the moment image successfully. 

[carta_moment_crash.zip](https://github.com/CARTAvis/carta-backend/files/8934628/carta_moment_crash.zip)

**To Reproduce**
1. download the test image above
2. load the image
3. request a moment image generation
4. backend should crash

**Expected behavior**
Backend should not crash when generating moment images from the example test image.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: almalinux8
 - Browser [e.g. chrome, safari, electron app]: firefox 91esr
 - Browser version [e.g. 22]: firefox 91esr
 - Backend branch [e.g. dev, v3b2 release]: v3b3 appimage
 - Frontend branch [e.g. dev, v3b2 release]: v3b3 appimage

**Comment by kswang1029** [comment]
@markccchiang do you have time on investigating this?

**Comment by markccchiang** [comment]
I have tried to build the CARTA backend on the server, which is AlmaLinux 8.5, and tested it. Did not encounter the crash problem. Wondering are there any differences between appimage and building mode?

**Comment by markccchiang** [comment]
> I have tried to build the CARTA backend on the server, which is AlmaLinux 8.5, and tested it. Did not encounter the crash problem. Wondering are there any differences between appimage and building mode?

I have tried to build the CARTA backend on the server (AlmaLinux 8.5) with ASAN and tested it. But still can not reproduce the crash. Wondering it is the packaging problem? @kswang1029 have you tested with the CARTA rpm on almalinux8?

**Comment by kswang1029** [comment]
@markccchiang hmm I cannot reproduce the issue with the rpm on AlmaLinux 8 VM. OK. let's put this on hold and wait until @ajm-asiaa creates the v3-final AppImage which I will test with again. Thanks for investigating this issue 👍

**Comment by kswang1029** [comment]
tested with the v3-rc releases and the issue is gone.
