### ISSUE TITLE
[R&D] on-the-fly visualization of swapped axes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1134]
This is an R&D project.

Use case:
A user loads a usual cube as ra-dec-channel. Then the user selects two of the axes for image visualization. For example, to visualize channel (as x) vs ra (as y) and animate through the dec axis.

Goal:
have a simple code with casacore for performance benchmarking.

**Comment by markccchiang** [comment]
I have created a test branch [mark/1134_test_swapped_axes_animation](https://github.com/CARTAvis/carta-backend/tree/mark/1134_test_swapped_axes_animation) and tested the performances of getting channel-RA or channel-DEC slice data. For example, running the test with `./carta_backend_tests --gtest_filter=SwappedAxesAnimationTest.\*` command and I got the following results: 

<img width="896" alt="截圖 2022-08-30 下午1 46 18" src="https://user-images.githubusercontent.com/5379602/187359534-7bcd5ca4-3fd5-4192-ac7b-fd0516c23f89.png">

Using the casacore to get channel-RA or channel-DEC slice data, the FITS file performs better than the HDF5 file. But if we use HDF5 swizzed data to get channel-RA or channel-DEC images, it is much faster than the FITS file.
