### ISSUE TITLE
one-pixel position offset in both x and y directions seen in ds9 image-coordinate region made in ds9

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1138]
**Describe the bug**
If we made ds9 regions in ds9 and exported them in image coordinates, the resulting region text file is in 1-based image coordinate. When we load the ds9 region text file in CARTA, it appears that CARTA does not apply an 1-pixel offset per direction in the image coordinates so that we see an one-pixel position offset when the regions are rendered as CARTA's image coordinate system is 0-based.

In the following example, a point ds9 region is defined as 
`point(289.99796,75.000813) # point=circle`
and when it is loaded in CARTA, its image coordinate is
`(289.9979553222656, 75.00081634521484)` as seen in the region configuration dialog.
It should be `(288.9979553222656, 74.00081634521484)` instead as CARTA's image coordinate is 0-based.

![Screen Shot 2022-06-27 at 11 51 46](https://user-images.githubusercontent.com/20819712/175856953-8cffa8b1-0ba4-4d36-b276-9172918bc688.png)

**To Reproduce**
1. Make a ds9 region file like

> \# Region file format: DS9 version 4.1
global color=green dashlist=8 3 width=4 font="helvetica 10 normal roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 include=1 source=1
image
point(1.0, 1.0) # point=circle

and load it in CARTA
2. Observe the location of the rendered point region and it is rendered at (1.0, 1.0) in image coordinate. It should be at (0.0, 0,0), the bottom-left corner pixel, instead.

**Expected behavior**
CARTA would need to convert the 1-based image-coordinate ds9 text region definition to 0-based image-coordinate CARTA region definition. 

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 103
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by kswang1029** [comment]
would be nice to fix this for v3-final if time allows.

**Comment by markccchiang** [comment]
@kswang1029 Should we transfer to 1-based image coordinate when CARTA exports ds9 regions as pixel coordinates?

**Comment by kswang1029** [comment]
> @kswang1029 Should we transfer to 1-based image coordinate when CARTA exports ds9 regions as pixel coordinates?

@markccchiang yes! this would have best compatibilities.
