### ISSUE TITLE
3D histogram loaded from HDF5 file is not actually used

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#114]
The cube histogram is requested in a completely different way to per-channel histograms, so the code which would access the data loaded from a HDF5 file is not currently triggered. This needs refactoring in Frame and Session.

**Comment by pford** [comment]
Ideally this would have been moved to Frame along with the other refactoring (PR #103) but I needed to get on with region development.  Session asks Frame (asks Region asks RegionStats) for a stored histogram using Frame::getRegionHistogram; you could modify this to check the loader as well as the Region before returning false.  If you do move the code, note the cancel method Rob added (Session::cancel_SetHistReqs).
