### ISSUE TITLE
[critical for v3-stable release] cannot navigate through file system when trying to load a region file

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1159]
**Describe the bug**
This is considered as a regression which I did not pick up from https://github.com/CARTAvis/carta-backend/pull/1142. Apologies...

With #1142, only region files are listed in the directory. However, if we need to navigate to other parent folders with the breadcrumbs, there is no way to access folders therein as they are filtered out.

**To Reproduce**
1. try to load a region file in a parent directory with the file browser
2. no directory is visible from the file list

**Expected behavior**
We still need to show directories so users can navigate through the file system to load a region file.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey 
 - Browser [e.g. chrome, safari, electron app]: chrome 
 - Browser version [e.g. 22]: 103
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by kswang1029** [comment]
@pford could you have a look please? My bad not being able to pick it up in #1142.

**Comment by veggiesaurus** [comment]
@kswang1029 what is the backend sending to the frontend? Are we sure it's not sending directories and the frontend is filtering them out?

**Comment by kswang1029** [comment]
> @kswang1029 what is the backend sending to the frontend? Are we sure it's not sending directories and the frontend is filtering them out?

It seems so.

![Screen Shot 2022-07-27 at 15 16 41](https://user-images.githubusercontent.com/20819712/181185544-767e1b78-8fba-4231-abd4-ab08f6c51139.png)

**Comment by pford** [comment]
@kswang1029 what should happen when the filter is "All Files" (no content checking) and there is a CASA image?  Should it be (1) listed with other directories, (2) listed as CASA, or (3) determined that it is an image and not list it?

**Comment by pford** [comment]
I went with option 1 since the point of All Files is speed.

**Comment by kswang1029** [comment]
> I went with option 1 since the point of All Files is speed.

Yes 👍
