### ISSUE TITLE
[backend crash] zoom/pan during animation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#117]
with the master branch `2d44acc ` 

When animating set_QA_performance/cube_A/cube_A_06400_z01000.fits or set_QA_performance/cube_A/cube_A_06400_z01000.image with desired fps=15, quick zoom and pan actions may result in backend crash (seg fault).

**Comment by pford** [comment]
@rwjsimmonds can you look at this one?  We had this problem before and it was a concurrency issue with multiple SET_IMAGE_VIEW messages which downsamples the image cache, and in this case they are mixed with multiple SET_IMAGE_CHANNELS which changes the image cache.

**Comment by rwjsimmonds** [comment]
I can look but not today. I will try to look tomorrow if the issue is still there.

Rob

**Comment by pford** [comment]
Hopefully fixed along with zoom issue #180 with PR #181 (release branch) / #182 (dev branch).

**Comment by kswang1029** [comment]
yes, crash is gone. 👍
