### ISSUE TITLE
increase the upper limit of the averaging width for line and polyline regions (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1174]
user feedback from v3 beta test

With the v3 release, the upper limit of the averaging width for line and polyline analytics is 10. Users would like to have a greater upper limit (20) so that they can apply averaging more than one beam width (some users prefer oversampling a beam element).

The companion frontend issue is https://github.com/CARTAvis/carta-frontend/issues/1949

**Comment by markccchiang** [comment]
I think the backend does not stick to the upper limit of averaging width to 10. It could be solved by simply modifying the frontend and setting the max averaging width to 20. I have created a testing frontend branch [mark/1949_increase_the_width_upper_bound](https://github.com/CARTAvis/carta-frontend/tree/mark/1949_increase_the_width_upper_bound) and it works fine to me so far.

**Comment by kswang1029** [comment]
> I think the backend does not stick to the upper limit of averaging width to 10. It could be solved by simply modifying the frontend and setting the max averaging width to 20. I have created a testing frontend branch [mark/1949_increase_the_width_upper_bound](https://github.com/CARTAvis/carta-frontend/tree/mark/1949_increase_the_width_upper_bound) and it works fine to me so far.

I see. Me overthinking the problem! Would you file a frontend PR then?

**Comment by pford** [comment]
I did not think about checking the width since the value comes from the frontend which will not go over the limit.  But the check should be added to the backend if this will be supported by scripting, where the width could be any crazy number.

**Comment by kswang1029** [comment]
> I did not think about checking the width since the value comes from the frontend which will not go over the limit. But the check should be added to the backend if this will be supported by scripting, where the width could be any crazy number.

good point. Shall we hardcode an upper limit of 20? @markccchiang

**Comment by kswang1029** [comment]
this is done.
