### ISSUE TITLE
Having an option to keep or replace generated pv images when a new request is made (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1176]
user feedback from v3 beta test

With v3 release, when a new request made in the pv generator or moment generator, generated images from the previous request will be removed. Users would like to have an option to keep or replace the pv or moment images. 

The companion backend issue is https://github.com/CARTAvis/carta-frontend/issues/1951

**Comment by pford** [comment]
I think for simplicity this should be a boolean "overwrite" field in the PvRequest message.  What should the name of the second PV image be?

Update: field changed to boolean "keep" so that default (false) is current behavior.

**Comment by kswang1029** [comment]
> I think for simplicity this should be a boolean "overwrite" field in the PvRequest message. What should the name of the second PV image be?

Shall we append a number?

**Comment by pford** [comment]
Starting with 1 (pv, pv1, pv2) or 2 (pv, pv2, pv3)?

**Comment by kswang1029** [comment]
> Starting with 1 (pv, pv1, pv2) or 2 (pv, pv2, pv3)?

I prefer option 1 but either way is fine. 🙂

**Comment by kswang1029** [comment]
> > Starting with 1 (pv, pv1, pv2) or 2 (pv, pv2, pv3)?
> 
> I prefer option 1 but either way is fine. 🙂

As users may close one of the in-ram PV images at any time, we can just keep increasing the index and don’t re-use the index.

**Comment by pford** [comment]
I just noticed the `moment` part! I think there should be separate branches and PRs (frontend, backend, and protobuf) for the Moment changes.

@crocka and I have been chatting about this issue, with `keep` = append new PV image with new name, `replace` = close PV image and append new PV image with same name.  But when multiple PV images exist and `replace` is used, which image or images are closed and replaced?

**Comment by kswang1029** [comment]
> I just noticed the `moment` part! I think there should be separate branches and PRs (frontend, backend, and protobuf) for the Moment changes.
> 
> @crocka and I have been chatting about this issue, with `keep` = append new PV image with new name, `replace` = close PV image and append new PV image with same name. But when multiple PV images exist and `replace` is used, which image or images are closed and replaced?

how about we close all generated images associated with the source image when “replace” mode is selected? The idea is similar to how we handle “load image” and “append image”. When it is load image we close all loaded images first then load the new image. When it is append image we do not close any loaded images and append the image.

**Comment by pford** [comment]
> > I just noticed the `moment` part! I think there should be separate branches and PRs (frontend, backend, and protobuf) for the Moment changes.
> > @crocka and I have been chatting about this issue, with `keep` = append new PV image with new name, `replace` = close PV image and append new PV image with same name. But when multiple PV images exist and `replace` is used, which image or images are closed and replaced?
> 
> how about we close all generated images associated with the source image when “replace” mode is selected? The idea is similar to how we handle “load image” and “append image”. When it is load image we close all loaded images first then load the new image. When it is append image we do not close any loaded images and append the image.

Ok, that makes sense.  In this case would the new PV image be simply "pv" (reset index to 0 and future images 1, 2, etc.), or continue incrementing the previous index?

**Comment by kswang1029** [comment]
> > > I just noticed the `moment` part! I think there should be separate branches and PRs (frontend, backend, and protobuf) for the Moment changes.
> > > @crocka and I have been chatting about this issue, with `keep` = append new PV image with new name, `replace` = close PV image and append new PV image with same name. But when multiple PV images exist and `replace` is used, which image or images are closed and replaced?
> > 
> > 
> > how about we close all generated images associated with the source image when “replace” mode is selected? The idea is similar to how we handle “load image” and “append image”. When it is load image we close all loaded images first then load the new image. When it is append image we do not close any loaded images and append the image.
> 
> Ok, that makes sense. In this case would the new PV image be simply "pv" (reset index to 0 and future images 1, 2, etc.), or continue incrementing the previous index?

Maybe we can reset the index if that makes sense to you too. I don’t have preference though.

**Comment by pford** [comment]
@kswang1029 @crocka I created a separate backend issue #1202 for keeping moment images.
