### ISSUE TITLE
Set a range to the spectral axis to generate a pv image (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1177]
user feedback from v3 beta test

With v3 release, a PV image is generated using the entire spectral axis along the pv cut. The enhancement is to be able to set a spectral range to generate a pv image. This is helpful to focus on a certain line feature in the cube.

The companion frontend feature is https://github.com/CARTAvis/carta-frontend/issues/1952

**Comment by pford** [comment]
Added `spectral_range` (channel min and max `IntBounds`) to `PvRequest` message, as in `MomentRequest` message.
carta-protobuf branch `pv_spectral_range`

**Comment by kswang1029** [comment]
@pford regarding https://github.com/CARTAvis/carta-backend/issues/1175 do you think we can also modify the `PvRequest` message to include the axes definition too? Users would like to have the freedom to set x as spatial and y as spectral or x as spectral and y as spatial.

**Comment by pford** [comment]
> @pford regarding #1175 do you think we can also modify the `PvRequest` message to include the axes definition too? Users would like to have the freedom to set x as spatial and y as spectral or x as spectral and y as spatial.

Yes, if that would be easier for the frontend development and testing.

**Comment by kswang1029** [comment]
> > @pford regarding #1175 do you think we can also modify the `PvRequest` message to include the axes definition too? Users would like to have the freedom to set x as spatial and y as spectral or x as spectral and y as spatial.
> 
> Yes, if that would be easier for the frontend development and testing.

@pford ok let's do this. @crocka needs it for https://github.com/CARTAvis/carta-frontend/issues/1950

**Comment by crocka** [comment]
> > > @pford regarding #1175 do you think we can also modify the `PvRequest` message to include the axes definition too? Users would like to have the freedom to set x as spatial and y as spectral or x as spectral and y as spatial.
> > 
> > 
> > Yes, if that would be easier for the frontend development and testing.
> 
> @pford ok let's do this. @crocka needs it for [CARTAvis/carta-frontend#1950](https://github.com/CARTAvis/carta-frontend/issues/1950)

We have three options for x and y axis (spectral, spatial, distance). Do we add two fields to the PvRequest message (string xAxis and string yAxis)?
<img width="657" alt="Screen Shot 2022-09-06 at 11 07 25 PM" src="https://user-images.githubusercontent.com/94193689/188780298-f32d34dd-77ee-4db5-934e-bfda1834ccb9.png">

**Comment by kswang1029** [comment]
> > > > @pford regarding #1175 do you think we can also modify the `PvRequest` message to include the axes definition too? Users would like to have the freedom to set x as spatial and y as spectral or x as spectral and y as spatial.
> > > 
> > > 
> > > Yes, if that would be easier for the frontend development and testing.
> > 
> > 
> > @pford ok let's do this. @crocka needs it for [CARTAvis/carta-frontend#1950](https://github.com/CARTAvis/carta-frontend/issues/1950)
> 
> We have three options for x and y axis (spectral, spatial, distance). Do we add two fields to the PvRequest message (string xAxis and string yAxis)? <img alt="Screen Shot 2022-09-06 at 11 07 25 PM" width="657" src="https://user-images.githubusercontent.com/94193689/188780298-f32d34dd-77ee-4db5-934e-bfda1834ccb9.png">

@crocka we should just use spatial and spectral for users. As the spatial is offset or distance you will be able tell from the image header provided from the backend.
