### ISSUE TITLE
[ROI statistics] backend crash if requesting stats from a region created totally outside the image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#118]
to reproduce the issue:
1) open the image set_noise/noise_10000px_10000px.fits
2) create a rectangle which is totally outside the image
3) bring up the stats widget and default we see the full image stats
4) switch to region 1 and the backend should crash as indicated by the red circle at the top-right corner.
the backend log is "Segmentation fault      (core dumped)"

UPDATE: if the region is created inside the image then is moved outside the image entirely then moving back to the image, the stats widget is still functional. 

UPDATE2: it appears that if the image header does not contain beam information, the above mentioned steps can trigger the crash event.

**Comment by pford** [comment]
Sorry, forgot to mention that outside regions are not supported in initial implementation to start region testing; followup ticket is #110 .  Closing this issue as duplicate.
