### ISSUE TITLE
Error importing region files when extension missing

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-backend#1182]
As observed by @pjmac1105 and shown [here](https://www.dropbox.com/s/caueuymmnlv1ok8/2022-08-12_13-54-30.mp4?dl=0), CARTA v3.0.0-beta.3 claims "Region Type not supported" after exporting a region file without including the extension in the file name and then trying to import it again. When explicitly including the file extension in the name, the regions import just fine. I assume the CARTA developers can reproduce this issue, but please get in touch if you'd like some example data.

**Comment by pford** [comment]
This was fixed after v3b3 for release 3.0.0.  I just tested with my developer build and with a Linux AppImage downloaded from the website.

**Comment by pjmac1105** [comment]
awesome, i'll download the new version. Thanks !
