### ISSUE TITLE
Initial support for saving/restoring of workspaces (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1185]
Associated frontend issue https://github.com/CARTAvis/carta-frontend/issues/1272

This a feature that CARTA can save a snapshot the the state in the GUI and restore it later. Snapshots will be termed "workspaces"

More details will be provided.

**Comment by veggiesaurus** [comment]
Google doc [here](https://docs.google.com/document/d/17OL0pu7WDV9RTLrUZIKFD3-XjjJjuFAcLx0h49eTgOg/edit?usp=sharing)
