### ISSUE TITLE
carta-backend built with ASAN flags crashes on RedHat9 (GCC 11.2.1)

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#1196]
**Describe the bug**

On RedHat9 and AlmaLinux9 (using GCC 11.2.1), if the carta-backend is built with the ASAN flags, then the `FileListTest.SetTopLevelFolder` and `FileListTest.AccessForbiddenFolder` Unit Tests crash with this error:
```
[ RUN      ] FileListTest.SetTopLevelFolder
/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1115: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.
Aborted
```

- The other two FileListTest Unit Tests (`SetStartingFolder` and `AccessFalseFolder`) pass, as do all the other Unit Tests.
- The ASAN flag built carta-backend immediately crashes with the same error if opened normally with a frontend.
- If built without ASAN flags, all Unit Tests pass and the carta-backend runs fine.
- Ubuntu 22.04 uses GCC 11.2.0, and all Unit Tests pass on it with an ASAN flag built carta-backend.

**To Reproduce**
Build the carta-backend with ASAN flags and Unit Tests in RedHat9/AlmaLinux9, then run the FileListTest.SetTopLevelFolder Unit Test. Steps as follows:
```
docker run -ti ajmasiaa/almalinux9-jenkins-sep2022
git clone https://github.com/CARTAvis/carta-backend.git
cd carta-backend
git submodule update --init --recursive
mkdir build
cd build
cmake .. -Dtest=on -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -fsanitize=address -fno-omit-frame-pointer' -DCMAKE_EXE_LINKER_FLAGS='-fsanitize=address'
make -j 4
cd test
ASAN_OPTIONS=suppressions=/root/carta-backend/debug/asan/myasan.supp LSAN_OPTIONS=suppressions=/root/carta-backend/debug/asan/myasan-leaks.supp ASAN_SYMBOLIZER_PATH=llvm-symbolizer ./carta_backend_tests --gtest_filter=FileListTest.SetTopLevelFolder
```

**Expected behavior**
All Unit Tests should run successfully and the carta-backend should not crash.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: AlmaLinux9 (via Docker)
 - Backend branch [e.g. dev, v3b2 release]: dev

**Comment by confluence** [comment]
This was fixed by #1199.
