### ISSUE TITLE
Option to keep or replace generated moment images when a new request is made (backend)

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#1202]
Split from #1176 , now for PV images only.  This is for moment images only.

**Comment by pford** [comment]
Created protobuf branch `moment_keep_option`

**Comment by pford** [comment]
@kswang1029 each moment can be requested individually and has a unique name, i.e. "image.moment.average", "image.moment.integrated", etc.  We can append an index to these names, as in PV image, but are the frontend/backend required to keep track of which moments have been generated? Or is it indexed by generation?

For example, the user requests mom -1 keep=false ("image.average"), then mom 0 keep=true ("image.integrated" or "image.integrated1"?), then mom -1, 0, 1 keep=true ("image.averageX", "image.integratedX" , "image.weighted_coordX" - what is X for each?).

**Comment by pford** [comment]
I just pushed a branch for an initial implementation, where the index is incremented each time keep=true for all generated moment images, but this can be changed.

So in my previous example (assuming I got the names right for the moment numbers!) you would get:

- mom -1 keep=false: `image.average`
- mom 0 keep=true: `image.integrated1`
- mom -1, 0, 1 keep=true: `image.average2, image.integrated2 , image.weighted_coord2`

When keep=false, there is no index appended.  When keep=true, the last-used index is incremented for the new images.  If this is acceptable, I will open a draft PR.

**Comment by kswang1029** [comment]
> I just pushed a branch for an initial implementation, where the index is incremented each time keep=true for all generated moment images, but this can be changed.
> 
> So in my previous example (assuming I got the names right for the moment numbers!) you would get:
> 
> * mom -1 keep=false: `image.average`
> * mom 0 keep=true: `image.integrated1`
> * mom -1, 0, 1 keep=true: `image.average2, image.integrated2 , image.weighted_coord2`
> 
> When keep=false, there is no index appended. When keep=true, the last-used index is incremented for the new images. If this is acceptable, I will open a draft PR.

Yes this sounds good.
