### ISSUE TITLE
[performance] loading casa region text file with 20000 regions is slow and takes lots of RAM

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1216]
based on the test with psrecord, it appears that loading casa region text file with 20000 regions is slow and takes lots of RAM. Loading ds9 region text file is more efficient as a comparison. However, ds9 seems performing even better e2e-wise. 

![Screen Shot 2022-11-17 at 12 59 24](https://user-images.githubusercontent.com/20819712/202360384-0b47cce9-739a-45c1-a78d-fcdaaec2b733.png)

UPDATE: test files https://drive.google.com/file/d/1CFVrkYcthNZlXucqEAVQbbYfYowNI4X6/view?usp=share_link

**Comment by pford** [comment]
@kswang1029 please attach the region file or a link to it

**Comment by kswang1029** [comment]
> @kswang1029 please attach the region file or a link to it

due to file size, sending you via slack

**Comment by pford** [comment]
@YuHsuan-Hwang @veggiesaurus would it be better to send regions in batches with a progress field rather than in one ImportRegionAck message?  Something like 1000 at a time?  Or do you think the frontend time is acceptable once it gets a response?

**Comment by veggiesaurus** [comment]
> @YuHsuan-Hwang @veggiesaurus would it be better to send regions in batches with a progress field rather than in one ImportRegionAck message? Something like 1000 at a time? Or do you think the frontend time is acceptable once it gets a response?

I think that would be useful. However, in order to do that, we would need a new message type in the ICD. At the moment, we have single-request, single-response, and data streams. We'd need something like a single-request, many-responses approach.

I have an idea of how to do this, but we will need to formalise it a bit.
