### ISSUE TITLE
Better way to assign file IDs for generated in-memory images

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#1224]
When an image is opened or appended, the frontend assigns a file ID for the image.  But when a request is made for a generated image, the file ID in the request is for the source image from which the new image is generated.  The backend calculates a file ID for the new, generated image using the input file ID, a multiplier determined by the generated image type, and some offset.  Some requests generate multiple images so multiple file IDs are needed.

These file ID calculations should be simplified and if possible coordinated between the image generators (MomentGenerator, PvGenerator, and ImageFitter when model and residual image options are added).  The new file IDs must not duplicate any file IDs already in use, unless the new image is replacing existing images of the same type.

There is also a need to determine what type of image it is, preferably not from its file ID being in a certain range.

**Comment by pford** [comment]
Currently:
ImageGenerator.h:
`#define MOMENT_ID_MULTIPLIER 1000
#define PV_ID_MULTIPLIER -1000`

MomentGenerator.cc:
`int moment_file_id = (file_id + 1) * MOMENT_ID_MULTIPLIER + (name_index * _moment_map.size()) + moment_type;`

PvGenerator.cc:
`_file_id = ((file_id + 1) * PV_ID_MULTIPLIER) - index;`

**Comment by kswang1029** [comment]
We will also need to consider LEL image. Currently a session cannot be resumed if there is an LEL image. Stokes hypercube, however, works fine in a resumed session. Will file a new issue for LEL resume.
