### ISSUE TITLE
Backend aborts with cfitsio 4.2.0

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#1231]
**Describe the bug**
When the backend is built with cfitsio 4.2.0, it aborts when you open a FITS file

**To Reproduce**
1. Click on FITS file in file list

**Expected behavior**
Get extended file info or open image

**Comment by kswang1029** [comment]
Is it a bug in cfitsio or due to API changes?

**Comment by pford** [comment]
It is a bug in the backend caused by a change in implementation in cfitsio.  The fits_read_key function has the same signature but it now copies the comment to a char array (return value) with `strncpy` instead of `strcat`.  But the `n` in `strncpy` is the max length of a comment not the length of the char array, which was undersized in the backend code.
