### ISSUE TITLE
Backend crash when loading a fits.gz file from GASS survey

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1233]
**Describe the bug**
Via the website https://www.astro.uni-bonn.de/hisurvey/gass/index.php we can retrieve images from the GASS survey. The returned image is in fits.gz format. When we load it in CARTA, the backend will crash. However, if we unzip it, then the fits image can be loaded successfully. (Note the the grid cannot be rendered due to another frontend issue).

[gass_0_0_1673503751.fits.gz](https://github.com/CARTAvis/carta-backend/files/10398739/gass_0_0_1673503751.fits.gz)

macOS crash report

> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   libc++.1.dylib                	    0x7ff8047452cd std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 9
> 1   carta_backend                 	       0x1001d1b1d carta::CompressedFits::ParseFitsCard(casacore::String&, casacore::String&, casacore::String&, casacore::String&) + 397
> 2   carta_backend                 	       0x1001d2a8f carta::CompressedFits::GetDecompressSize() + 911
> 3   carta_backend                 	       0x1001d88ca carta::FitsLoader::OpenFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 106
> 4   carta_backend                 	       0x10013e845 carta::FileExtInfoLoader::FillFileInfoFromImage(CARTA::FileInfoExtended&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 53
> 5   carta_backend                 	       0x10013e668 carta::FileExtInfoLoader::FillFileExtInfo(CARTA::FileInfoExtended&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 504
> 6   carta_backend                 	       0x10034fbf3 carta::Session::FillExtendedFileInfo(CARTA::FileInfoExtended&, CARTA::FileInfo&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 963
> 7   carta_backend                 	       0x10035192c carta::Session::OnOpenFile(CARTA::OpenFile const&, unsigned int, bool) + 620
> 8   carta_backend                 	       0x10037233c carta::SessionManager::OnMessage(uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char> >, uWS::OpCode) + 4044
> 9   carta_backend                 	       0x100380534 uWS::WebSocketContext<false, true, carta::PerSocketData>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*, void*) + 1300
> 10  carta_backend                 	       0x10037f7c7 bool uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData> >::consumeMessage<6u, unsigned char>(unsigned char, char*&, unsigned int&, uWS::WebSocketState<true>*, void*) + 711
> 11  carta_backend                 	       0x10037f450 uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData> >::consume(char*, unsigned int, uWS::WebSocketState<true>*, void*) + 272
> 12  carta_backend                 	       0x10037f2ee auto uWS::WebSocketContext<false, true, carta::PerSocketData>::init()::'lambda'(auto*, char*, int)::operator()<us_socket_t>(auto*, char*, int) const + 142
> 13  carta_backend                 	       0x10042de45 us_loop_run + 133
> 14  carta_backend                 	       0x100373e77 carta::SessionManager::RunApp() + 343
> 15  carta_backend                 	       0x1002bd7bc main + 3788
> 16  dyld                          	       0x101fd252e start + 462

**To Reproduce**
1. download the test image
2. load it in CARTA and we will see the backend crashed

**Expected behavior**
backend should survive

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable

**Comment by confluence** [comment]
I have opened the compressed and uncompressed images from the issue side by side, and while I no longer see the weird value distortion in the compressed image that was happening before when the crash was suppressed, I still can't spatially or spectrally match the compressed image to the uncompressed image or to itself (but I can match the uncompressed image to itself). This suggests that there's still some kind of bug in the parsing of the compressed image's metadata from the header.
