### ISSUE TITLE
backend crash when requesting vector overlay data from computed polarization component

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1235]
**Describe the bug**
This is a bug report from @jott3077.

When we load a Stokes cube and set the intensity source as "current image" and angular source as "computed PA", then generate the vector overlay on the image, if we use the animator to switch to one of the computed polarization component (eg total polarization intensity), the backend will crash. The macOS crash report is attached below.

> Thread 3 Crashed:
0   libsystem_kernel.dylib        	    0x7ff81372e00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8137641ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8136afd24 abort + 123
3   libc++abi.dylib               	    0x7ff813720082 abort_message + 241
4   libc++abi.dylib               	    0x7ff813711245 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	    0x7ff81360de19 _objc_terminate() + 104
6   libc++abi.dylib               	    0x7ff81371f4a7 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	    0x7ff813721d05 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	    0x7ff813721ccc __cxa_throw + 116
9   libcasa_casa.6.dylib          	       0x110914d54 casacore::Slicer::inferShapeFromSource(casacore::IPosition const&, casacore::IPosition&, casacore::IPosition&, casacore::IPosition&) const + 612
10  libcasa_lattices.6.dylib      	       0x11114bdc7 casacore::LatticeRegion::LatticeRegion(casacore::Slicer const&, casacore::IPosition const&) + 167
11  libcasa_lattices.6.dylib      	       0x110f9a73c casacore::SubLattice<float>::setRegion(casacore::Slicer const&) + 60
12  libcasa_lattices.6.dylib      	       0x110fb28cb casacore::SubLattice<float>::SubLattice(casacore::MaskedLattice<float> const&, casacore::Slicer const&, casacore::AxesSpecifier) + 251
13  libcasa_images.6.dylib        	       0x110d0bf80 casacore::SubImage<float>::SubImage(casacore::ImageInterface<float> const&, casacore::Slicer const&, casacore::AxesSpecifier, bool) + 144
14  carta_backend                 	       0x10ee12a27 carta::FileLoader::GetSlice(casacore::Array<float, std::__1::allocator<float> >&, carta::StokesSlicer const&) + 343
15  carta_backend                 	       0x10ed96674 carta::Frame::GetSlicerData(carta::StokesSlicer const&, float*) + 84
16  carta_backend                 	       0x10eda63fb carta::Frame::GetDownsampledRasterData(std::__1::vector<float, std::__1::allocator<float> >&, int&, int&, int, int, CARTA::ImageBounds&, int) + 587
17  carta_backend                 	       0x10edaeca3 carta::VectorFieldCalculator::DoCalculations(std::__1::function<void (CARTA::VectorOverlayTileData&)> const&) + 2611
18  carta_backend                 	       0x10ef8cc1c carta::Session::SendVectorFieldData(int) + 556
19  carta_backend                 	       0x10ef8bfe7 carta::Session::OnSetImageChannels(CARTA::SetImageChannels const&) + 823
20  carta_backend                 	       0x10ef8143d carta::SetImageChannelsTask::execute() + 301
21  carta_backend                 	       0x10efe4050 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0> >(void*) + 176
22  libsystem_pthread.dylib       	    0x7ff8137644e1 _pthread_start + 125
23  libsystem_pthread.dylib       	    0x7ff81375ff6b thread_start + 15

**To Reproduce**
1. load a Stokes cube and enable the vector overlay dialog
2. set the intensity source to "current image" and generator the vector overlay
3. use the animator to switch to Stokes Q. This works fine.
4. use the animator to switch to one of the computed component, such as total polarization intensity, the backend will crash

**Expected behavior**
no crash in step 4.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: electron app
 - Browser version [e.g. 22]: v3-stable electron app
 - Backend branch [e.g. dev, v3b2 release]: v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable

**Comment by markccchiang** [comment]
I think this is a one-line fix, so just fixed it in #1223. @kswang1029 could you please check again does the new commit solve the problem? Thank you!
