### ISSUE TITLE
[animator] channel animation playback hangs at the last channel when computed polarization component is selected

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1238]
**Describe the bug**
When we load a Stokes cube, we can have infinite loop of channel playback for a give Stokes component. However, if a computed polarization component is selected, such as Plinear, the channel playback hangs at the last channel.

**To Reproduce**
1. load a Stokes cube
2. select Stoke Q and trigger channel animation playback. When the last channel is rendered, the next would be the first channel.
3. switch to Plinear or other computed component and select a channel close to the last channel (just to save time for observing)
4. trigger channel animation playback and it will hang at the last channel

**Expected behavior**
channel animation playback for computed polarization component should behave just like regular Stokes.

**Screenshots or videos**

https://user-images.githubusercontent.com/20819712/203480418-cbece892-1b5a-4305-b03f-31364bf17470.mov

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: v3-stable electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v3-stable
 - Frontend branch [e.g. dev, v3b2 release]: v3-stable

**Comment by kswang1029** [comment]
Thanks to @crocka for diagnosing this issue. This seems a backend one.

**Comment by markccchiang** [comment]
Actually, I think this problem is from the incorrect stokes index setting in the `StartAnimation`'s sub-messages `AnimationFrame`, which is sent by the frontend. I will fix it on the frontend side.
