### ISSUE TITLE
[regression] PV generator is not consistent between fits and hdf5

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#1259]
**Describe the bug**
Running the ICD-RxJS test for PR #1253 and found the `PV_GENERATOR_HDF5_COMPARED_FITS.test.ts` is failed, indicating the PV generator images of fits and hdf5 are not conisitent

**To Reproduce**
1. Open `HD163296_CO_2_1.fits` ([link](https://drive.google.com/drive/folders/1Wi1WxXk6gg-aQQXhXTTEN8m8vM4bWMcX?usp=sharing)) and set a line region: controlPoints: [{ x: 79, y: 77 }, { x: 362, y: 360 }], rotation: 135
2. Create the first PV image (width:3) for `HD163296_CO_2_1.fits` and save this image as `HD163296_CO_2_1_pv-fits-pv-preview.image`
3. Open `HD163296_CO_2_1.hdf5`, spatially and spectrally matched to `HD163296_CO_2_1.fits`.
4. Create the second PV image (width:3) for `HD163296_CO_2_1.hdf5` and save this image as `HD163296_CO_2_1_pv-hdf5-pv-preview.image`
5. Append image using LEL: HD163296_CO_2_1_pv-fits-pv-preview.image` - `HD163296_CO_2_1_pv-hdf5-pv-preview.image`, then you can see the residual (i.e. difference)

**Expected behavior**
On the backend dev commit : `f5c9379c`
the LEL subtraction should be all "0" image, like this
<img width="1364" alt="Screen Shot 2023-05-02 at 3 17 09 PM" src="https://user-images.githubusercontent.com/34430648/235616024-7e27bfd8-3ba7-4957-bfbb-abe1ebfeb7c2.png">

**Screenshots or videos**
However in this PR #1253 , there is a residual in the LEL subtraction
<img width="1367" alt="Screen Shot 2023-05-02 at 3 17 21 PM" src="https://user-images.githubusercontent.com/34430648/235616186-26c73209-2d67-49d5-a163-fc99066e3492.png">

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS 11 & 13
 - Browser [e.g. chrome, safari, electron app]:  chrome
 - Browser version [e.g. 22]: Version 111.0.5563.110
 - Backend branch [e.g. dev, v3b2 release]: v4-beta (due to https://github.com/CARTAvis/carta-backend/pull/1253)
 - Frontend branch [e.g. dev, v3b2 release]: v4-beta

**Comment by pford** [comment]
Closing issue via merged PR #1267
