### ISSUE TITLE
[regression] FITS cannot be opened due to Extended file info exception: Unit::check Illegal unit string 'degrees'

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1265]
**Describe the bug**
The attached FITS image is from Herschel space telescope. The image can be loaded successfully in v3-stable but not in v4-beta nor dev.

> 2023-05-16 03:20:11	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> [2023-05-16 03:20:11.140] [CARTA] [debug] Extended file info exception: Unit::check Illegal unit string 'degrees'
> 2023-05-16 03:20:11	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> [2023-05-16 03:20:11.144] [CARTA] [debug] Extended file info exception: Unit::check Illegal unit string 'degrees'
> [2023-05-16 03:20:11.144] [CARTA] [error] Header error or no image HDUs found.

https://drive.google.com/file/d/1mxo4YO6H7zLq9T1eZnHBnGpfe1ITKoEl/view?usp=sharing

**To Reproduce**
1. download the test image and try to load it in carta
2. when we click on the image file in the file browser, we will see error in the file info pane.

**Expected behavior**
The image can be loaded successfully

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: chrome (dev) electron app (v4-beta)
 - Browser version [e.g. 22]: chrome-113
 - Backend branch [e.g. dev, v3b2 release]: v4-beta, dev
 - Frontend branch [e.g. dev, v3b2 release]: v4-beta, dev

**Comment by pford** [comment]
Closed via #1255
