### ISSUE TITLE
[question] maximum number of loaded image 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1287]
**Describe the bug**
It appears that if we load more than 248 images, the 249th onward will fail to load.

> [2023-08-02 01:33:06.575] [CARTA] [error] RegularFileIO: error in open or create of file /Users/kswang/carta_image_pool/set_phangs_alma/mom2/ngc1317_12m+7m+tp_co21_15as_strict_mom2.fits: Too many open files
> [2023-08-02 01:33:06.575] [CARTA] [warning] [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

QUESTION: what's the reason behind this? @markccchiang @pford Is that because the string length (file names) in JSON is too long?

**To Reproduce**
1. load more than 248 images (might be different in your env) at once via the file browser
2. when the 249th image is loading, there will be the error message.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 104
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by markccchiang** [comment]
@kswang1029 Looks like it is the problem with Linux settings. You can use the command `ulimit -n` to check the number of open files limit. To increase the upper limit of opening files, you can use the command, say `ulimit -n 2048` ([reference link](https://www.howtogeek.com/805629/too-many-open-files-linux/)).

**Comment by kswang1029** [comment]
I see! Thanks @markccchiang
