### ISSUE TITLE
histogram data returned is always image histogram

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#129]
(Not sure if this is currently being worked on, apologies if it is actively being fixed)

Currently, histograms returned from the backend seem to always be histograms for the full image. To reproduce bug:
1. Load file
2. Create region
3. Open histogram widget
4. Change widget region to the new region

The same data is sent again, even though the requirements have been updated via `SET_HISTOGRAM_REQUIREMENTS`.

**Comment by pford** [comment]
This issue can be tested along with the other issues for PR #136 for the general region case.

Issue #137 opened specifically for hdf5 region data.  Any new hdf-region-specific issues not already covered by #137 should be added there.
