### ISSUE TITLE
Feature request: custom URL

### ISSUE THREAD

**Issue by appolloford** [CARTAvis/carta-backend#1309]
Following the discussion in PR #1307, we agree to some extent that it is good for CARTA to support custom URL. This function is particularly helpful for setting a reverse proxy (e.g. via Open OnDemand) for CARTA and is also implemented in Jupyter `(ServerApp.base_url)` and Matlab `(MWI_BASE_URL)`. Similar to the two softwares, we propose to have CARTA support adding URL prefix behind the `host:port` for proxy to parse.

**Comment by kswang1029** [comment]
@confluence do you think this is implemented with https://github.com/CARTAvis/carta-backend/pull/1338?

**Comment by confluence** [comment]
@kswang1029 I believe so.
