### ISSUE TITLE
cannot open old IRAM fits image

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#1312]
**Describe the bug**
Cannot open the old IRAM PdBI fits image

**To Reproduce**
1. Open "n7469-co2.fits" or open "n7469-hcn.fits ([link](https://drive.google.com/drive/folders/1t614vkmmIbe8XOYCsnZBQH20A9qgEQUn?usp=sharing))
**please do not distribute these images to other public places**

**Expected behavior**
Should show the header, however there is no information from the ICD message:  
`"Error loading headers or image."`
Following is the header 

> SIMPLE  =                    T / SIMPLE FITS FORMAT                             
> BITPIX  =                    16                                                 
> NAXIS   =                     3                                                 
> NAXIS1  =                   129                                                 
> NAXIS2  =                   129                                                 
> NAXIS3  =                    32                                                 
> BLOCKED =                    T / TAPE MAY BE BLOCKED                            
> CDELT1  =  -5.555555897557E-05 / PRIMARY PIXEL SEPARATION                       
> CROTA1  =   0.000000000000E+00 / PRIMARY ROTATION OF AXIS                       
> CRPIX1  =   6.500000000000E+01 / PRIMARY REFERENCE PIXEL                        
> CRVAL1  =   3.458150000000E+02 / PRIMARY REFERENCE VALUE                        
> CTYPE1  = 'RA---ARC          ' / PRIMARY AXIS NAME                              
> CUNIT1  = 'DEGREE            ' / PRIMARY AXIS UNITS                             
> CDELT2  =   5.555555897557E-05 / PRIMARY PIXEL SEPARATION                       
> CROTA2  =   0.000000000000E+00 / PRIMARY ROTATION OF AXIS                       
> CRPIX2  =   6.500000000000E+01 / PRIMARY REFERENCE PIXEL                        
> CRVAL2  =   8.873888888889E+00 / PRIMARY REFERENCE VALUE                        
> CTYPE2  = 'DEC--ARC          ' / PRIMARY AXIS NAME                              
> CUNIT2  = 'DEGREE            ' / PRIMARY AXIS UNITS                             
> CDELT3  =   2.000000000000E+01 / PRIMARY PIXEL SEPARATION                       
> CROTA3  =   0.000000000000E+00 / PRIMARY ROTATION OF AXIS                       
> CRPIX3  =   1.637500000000E+01 / PRIMARY REFERENCE PIXEL                        
> CRVAL3  =   0.000000000000E+00 / PRIMARY REFERENCE VALUE                        
> CTYPE3  = 'VELO              ' / PRIMARY AXIS NAME                              
> CUNIT3  = 'KM/S              ' / PRIMARY AXIS UNITS                             
> EPOCH   =   2.000000000000E+03 / EPOCH                                          
> INSTRUME= 'PDBI              ' / INSTRUMENT                                     
> BLANK   =               -32768 / TAPE VALUE FOR UNDEFINED PIXELS                
> BSCALE  =          4.589633e-06                                                 
> BZERO   =            0.09871618                                                 
> DATAMAX =         2.490313E-01 / MAXIMUM DATA VALUE                             
> DATAMIN =        -5.160348E-02 / MINIMUM DATA VALUE                             
> ORIGIN  = 'WFITS VERSION 1.3' / VERSION OF THE GIPSY PROGRAM                    
> OBJECT  = 'NGC7469     '               /                                        
> BUNIT   = 'Jy/beam     '               /                                        
> DATE    = '05/03/97'                   / Date written                           
> DEC     =   .8873888888889E+01         / Declination                            
> RA      =   .3458150000000E+03         / Right Ascension                        
> END     

                                                                        

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS 13 M1
 - Browser [e.g. chrome, safari, electron app]: google
 - Browser version [e.g. 22]: Version 114.0.5735.198 (Official Build) (arm64)
 - Backend branch [e.g. dev, v3b2 release]: dev & release 4
 - Frontend branch [e.g. dev, v3b2 release]: dev & release 4

**Comment by kswang1029** [comment]
`Error loading file: Unit::check Illegal unit string 'DEGREE'`
