### ISSUE TITLE
performance issue in spatial profile generation along a line or a polyline 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1339]
as of v4-stable, the spatial profiler generation process along a line or a polyline is not that performant. The impact to users is they will need to wait a while before seeing the results. If performance cannot be improved significantly, we will need to implement "progressive update + cancellation" similar to the region spectral profiler (https://github.com/CARTAvis/carta-frontend/issues/1954 + https://github.com/CARTAvis/carta-backend/issues/1179).

**Comment by pford** [comment]
Related issue #1347, refactoring Region class for better performance using reference image.
