### ISSUE TITLE
Histogram min and max are fixed once region is created

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#134]
Region histograms seem to be keeping the same min and max until the region channel is changed or the region is re-created.

To reproduce issue: 
1) load a file with a bright point source in it
2) create a region around the point source
3) add a histogram widget and set it to the region
4) move the region off the point source

Two possible, but both erroneous, outcomes: 
(a) A histogram with the same lower/upper bounds and contents is sent
(b) A histogram with the same lower/upper bounds is sent, but different bin contents (also incorrect, but at least it's using the right data to form the histogram now)

Brief testing suggests that (a) occurs whenever the number of pixels stays the same, and (b) occurs when pixel size changes, although it could be only when the number of bins changes (i.e. `sqrt(numPixels)` changes).

Below I've made histogram and stats widgets for two regions. Region 1 was created over a bright source, while region 2 was created roughly where it's currently positioned. As you can see, the region definitions are identical, and the stats results are identical, but the histograms are not. Have confirmed via debug log that the histograms being sent are not the same (not just a frontend bug). 

![image](https://user-images.githubusercontent.com/592504/55388070-e29a4e80-5532-11e9-829f-502689233e63.png)

**Comment by pford** [comment]
This should be fixed in my current branch, along with several other issues.  When the region changes, all stored calculations are invalidated.

**Comment by veggiesaurus** [comment]
works great now :+1:
