### ISSUE TITLE
Implement partial data for messages with progress field

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#135]
Region histogram data and spectral profile data.

**Comment by pford** [comment]
The implementation should also enable automatic cancellation if region changes.

**Comment by veggiesaurus** [comment]
Note: cancellation checks should happen more often than partial data messages, since it's more important to early exit unnecessary tasks than sending updates (these can happen at a regular interval, similar to the cube histogram)

**Comment by pford** [comment]
Update: spectral profile and cube histograms done.  Do we need this for per-plane image/region histograms, or can this issue be closed?

**Comment by kswang1029** [comment]
@pford looks good to me. @veggiesaurus ?

**Comment by veggiesaurus** [comment]
I'm fine with closing this. We can consider partial updates of the other long running tasks (histogram and stats) if and when it becomes necessary
