### ISSUE TITLE
Incorrect HDF5 data streams

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#137]
Regions which include NaN values as well as finite values return stats NaN values and spectral profile NaN values.  Region histograms are always identical to image histogram (as reported in issue #129) even though a new message is sent when the region changes.

**Comment by pford** [comment]
Frame::fillRegionHistogramData is used for *all* regions.  The loader is asked for image stats for the current chan/stokes regardless of the region id, and if the stats are valid, the loaded histogram is used.  But this is for the image region so none is calculated for the specified region and the image histogram is always returned.

**Comment by pford** [comment]
This should be fixed in PR #138 and PR #139 , then will be ready to test.

**Comment by veggiesaurus** [comment]
struggling to test due to the other HDF5 issue, which still seems to occur when loading an un-tiled HDF5  image

**Comment by kswang1029** [comment]
Tried some ALMA images converted to HDF5, region stats/spectral profile/histogram works well with different sizes (including/excluding nan pixels). 🥇

**Comment by pford** [comment]
Just pushed branch pam/improve_pixel_mask to use LatticeIterator for the pixel mask rather than reading the entire region data at once.  Also only gets the sublattice mask for statistics (non-point-region spectral profile and region stats data), mask not needed for histogram calculations.

**Comment by veggiesaurus** [comment]
HDF5 regions now work similarly to FITS, closing
