### ISSUE TITLE
[file info] adding HDU name in file info

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#14]
If a FITS image has multiple HDUs, please add HDU type and name in the file info so that users can see which HDU is which. 

test image: set_QA/spire500_ext.fits
There are 8 HDUs in the above case (using gaia from statlink).
<img width="732" alt="screen shot 2018-12-10 at 11 07 30" src="https://user-images.githubusercontent.com/20819712/49708764-f102e880-fc6b-11e8-8fa8-36cb3a9d3d78.png">

**Comment by ChristyReynolds** [comment]
Hi! I will work on this issue. Thanks! Christy

**Comment by pford** [comment]
Kuo Song, I assume for the sample FITS file described above you want the displayed type to be "binary" or "image" and the name to be "image", "History", "error", "coverage", etc. as shown in your table, is that correct?

In casacore the HDUs are 0-based but this could also be easily changed if preferred.

Should the file browser skip the "binary" tables which cannot be displayed by CARTA?  In this case we do not need to list the type, as all listed HDUs would be images.  Should the HDU name/type be in the file list (e.g. "spire500_ext.fits: HDU 7 coverage (image)") or in the File Information section on the right once a file is selected?  But if CARTA cannot open an image the message is "Failed to open image at specified HDU" or "No image at specified HDU".

**Comment by kswang1029** [comment]
@pford I suggest
1) we skip type="binary" in the file list to be consistent with the idea that the file list only contains supported image types (casa, hdf5, fits, and miriad).
2) we use 1-based index for HDU
3) appending hdu index and name/type to the file name is a good idea.

**Comment by pford** [comment]
If we do not list the "binary" HDUs then we do not need to indicate that the others are "image" type, just add the ExtName to the HDU number.

**Comment by pford** [comment]
Got into this ticket while researching FITS keywords for CartaHdf5Image.  Have fix in pam/fits_hdu_name.

**Comment by pford** [comment]
Waiting for feedback from @kswang1029 before issuing pull request for pam/fits_hdu_name branch.

**Comment by kswang1029** [comment]
@pford Thanks for taking care of this enhancement. 
It is good to just show "image" HDUs on the file list. We will also need to check if NAXIS >=2. There are cases that I found it is image but NAXIS = 0.

Examples:
set_OIR/pacs160_js.fits (from Herschel Observatory)
![Screen Shot 2019-05-23 at 9 36 39 AM](https://user-images.githubusercontent.com/20819712/58219967-7ae8ce80-7d3f-11e9-983e-17f561e59017.png)
There are 7 HDUs and only HDU2 and HDU3 are true images. Note HDU4 "History" is "image" with NAXIS=0. (Don't know why...) Now it is shown on the file list. 

set_OIR/spire500_ext.fits (from Herschel Observatory)
![Screen Shot 2019-05-23 at 9 37 01 AM](https://user-images.githubusercontent.com/20819712/58220042-d0bd7680-7d3f-11e9-867d-8da00627e589.png)
There are 8 HDUs and only HDU2, HDU7, and HDU8 are true images. 

$BASE/jcmts20091208_00085_450.fits (from JCMT)
![Screen Shot 2019-05-23 at 9 39 27 AM](https://user-images.githubusercontent.com/20819712/58220085-095d5000-7d40-11e9-9a7d-dbf7dd135d4e.png)
There are 17 HDUs and only HDU 1, 2, 3, 4, 14 are true images.

**Comment by pford** [comment]
Fixed now, ready for a UI review before pull request.

**Comment by kswang1029** [comment]
@pford Yes, looking good!

**Comment by pford** [comment]
Merged into dev, ready to test and close this issue.

**Comment by pford** [comment]
Closing this issue since it has been merged for a month.
