### ISSUE TITLE
crash when loading single channel image and move cursor on

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#140]
tried with backend master commit 023ce6c and frontend master. 
try: set_G14/G14.114-0.574.continuum.image.pbcor.fits

Crash happens when loading single channel image and move cursor on the image.  It appears that it is the surrounding masked pixels trigger the crash. Tested with other images without surrounding masked pixels, it works fine.

UPDATE: not necessary due to those surrounding masked pixels

**Comment by markccchiang** [comment]
I guess this is the problem in `Frame::getSpectralData()`. Will check and fix it.

**Comment by veggiesaurus** [comment]
@kswang1029 does the crash happen if you close the spectral profile widget before loading the file?

**Comment by kswang1029** [comment]
nope. I use the default layout.

**Comment by veggiesaurus** [comment]
> nope. I use the default layout.

I mean does it still occur if you remove the spectral profile first?

**Comment by markccchiang** [comment]
This is the problem in `Frame::getSpectralData()` that a single channel image will pass a non-meaningful upper bound while getting the raw data. I will fix it and merge it into the master branch directly.

**Comment by kswang1029** [comment]
Hmm, if I remove spectral profiler first, then it works fine without crash

**Comment by markccchiang** [comment]
I have pushed the fixed code in the master branch. Please check it after the build is done. Thank you!

**Comment by kswang1029** [comment]
awesome, issue gone. close.
