### ISSUE TITLE
[performance improvement] multiple identical SPECTRAL_PROFILE_DATA sent to frontend 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#142]
To reproduce the case:
1) open set_HDF5/OrionKL_sci.spw19.cube.I.pbcor.hdf5
2) make a region and check region spectral profile 
3) as this is a big image cube, it takes time to generate profile. Now change the stats type three times (different for each). 
4) The backend should only work on the latest request and it appears so 👍 
5) Then once the backend is done, it sends three identical copies of SPECTRAL_PROFILE_DATA to the frontend. Not a big deal for usage but there is performance concern.

**Comment by pford** [comment]
Related to issue #19 .  Similar to multiple SET_CURSOR and SET_IMAGE_VIEW messages, only need to process the last one.

**Comment by kswang1029** [comment]
@pford Issue solved. 👍 Close the issue.
