### ISSUE TITLE
WCS single group (image overlay)

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#144]

**Comment by kswang1029** [comment]
Complexity:
- strategy of overlaying images with different projections, coordinate reference, pixel size, etc
- strategy of aligning different channel widths

**Comment by veggiesaurus** [comment]
@kswang1029 raster transparency isn't scheduled for 1.3 anymore is it?

**Comment by kswang1029** [comment]
no. no raster transparency for v1.3.
