### ISSUE TITLE
WCS Group Region of Interest Analysis

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#146]
Regions of interest need to be defined for a single WCS group, and analysis products from a region of interest (profile, stats, histogram) need to be determined for each required frame in the WCS group.

- [ ] Modify ICD to support WCS groups region of interest
- [ ] Convert region definitions between frames
- [ ] Determine analysis products based on updated region requirements
- [ ] Send analysis products for different files

**Comment by veggiesaurus** [comment]
@pford I think we should arrange a time to chat about this feature. It would be good to start development on this before the rest of the WCS stuff (my side of things) is finished

**Comment by pford** [comment]
Requirements doc: https://docs.google.com/document/d/1wVidLdGQOflxGPl4wb7X7v0FEJJx63IenXlkxkbbB40/edit#heading=h.7zehartallcq
