### ISSUE TITLE
2d image fitting

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#150]
related frontend issue https://github.com/CARTAvis/carta-frontend/issues/1397

This is to provide users the ability to select a region and fit a 2D function such as 2D Gaussian to get feature properties. Note that full resolution image data need to be used as fitting input, instead of downsampled data.

Requirement document:
https://docs.google.com/document/d/1E9kL7FOhVtkDDit8VIYle61tU5PzSYXjnLpxZBCHliY/edit?usp=sharing

Implementation plan:
- [x] Basic single/multiple gaussian fitting and text outputs
- [x] Gaussian fitting with fixed initial values
- [x] Gaussian fitting of the current view in frontend
---- target for v3b3 ----
- [x] Output model/residual images
- [x] Estimate progress and listen for cancellation messages
- [ ] Gaussian fitting of selected regions
- [ ] support a background level in the fitting
- [ ] support different solvers in the fitting
- [X] ~also use beam deconvolved image as the input data for fitting~ moved to new issue https://github.com/CARTAvis/carta-backend/issues/1236

**Comment by kswang1029** [comment]
Requirements:
- provide 2d gaussian function as a start.
- capability to define initial guess of fitting parameters 
- capability to fix part of fitting parameters
- provide fitting results in convenient units (e.g., gaussian center in pixel and wcs coordinates)
- provide fitting errors
- capability to fit multiple gaussians (could consider to have an upper limit, say 3 or 5) in a single shot
- export fitting results as a text file

**Comment by Kechil** [comment]
v1.5
