### ISSUE TITLE
Moments generator

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#154]
To define a rectangle region, a range of channels, and a clip level to create moment images.
moments include (c.f. casa "immoments"):
moments=-1  - mean value of the spectrum  
moments=0   - integrated value of the spectrum  
moments=1   - intensity weighted coordinate;traditionally used to get ’velocity fields’  
moments=2   - intensity weighted dispersion of the coordinate; traditionally used to get "velocity dispersion"  
moments=3   - median of I  
moments=4   - median coordinate 
moments=5   - standard deviation about the mean of the spectrum  
moments=6   - root mean square of the spectrum  
moments=7   - absolute mean deviation of the spectrum  
moments=8   - maximum value of the spectrum  
moments=9   - coordinate of the maximum value of the spectrum 
moments=10  - minimum value of the spectrum  
moments=11  - coordinate of the minimum value of the spectrum

**Comment by pford** [comment]
Requirements doc: https://docs.google.com/document/d/1RciBmqsa_bZw1vgC4J0-YSOxnlIMDQyP-MINL81MYOs/edit#heading=h.pd8c2kw8bdfy
