### ISSUE TITLE
[image viewer] backend crashes when multiple sessions access same dataset

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#17]
Image locking for disk access is within Session, not across Sessions

**Comment by veggiesaurus** [comment]
@kswang1029 can you remember how to reproduce this?

**Comment by kswang1029** [comment]
@veggiesaurus with the help from @ajm-asiaa for setting up the demo server, I did the following tests with one backend and two sessions from two different computers:
1) requesting a file list from the same folder ==> crash
2) requesting file info of the same file ==> appears fine
3) opening same big image ==> appears fine
4) playing animation at low and high fps ==> appears fine.
