### ISSUE TITLE
[Test] CURSOR_Z_PROFILE.test.ts failed since commit 023ce6c

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#170]
Cannot get response after sending set cursor.
Currently this test is not included in CI test.

**Comment by kswang1029** [comment]
it is timeout (how many seconds?) or never get returned even with a longer timeout?

**Comment by markccchiang** [comment]
@zarda please provide the detail description. Is the image file `S255_IR_sci.spw25.cube.I.pbcor.fits` you are testing? From my test, the spectral profile layout works smoothly.

**Comment by zarda** [comment]
After sending set cursor, never get returned even with a very long timeout. After several A-B tests to find out this issue is start from commit [023ce6c](https://github.com/CARTAvis/carta-backend/commit/023ce6cb7944a28d86f0ab6b14fd9ecd918b59db).

**Comment by pford** [comment]
New data is sent only when a region changes (control points, rotation), or stokes/channel changes depending on the message type and requirements.  This test sets the same cursor repeatedly so the spectral profile is sent the first time only.  The test should set different cursor or expect not to receive a profile.

**Comment by zarda** [comment]
Correct the CURSOR_Z_PROFILE.test and tested well.
