### ISSUE TITLE
Resume support for dropped connections

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#172]
Currently, when the server connection is dropped, the CARTA frontend and backend are in inconsistent states, as the previous session is not resumed, but rather replaced by a new session. 

The following features need to be added to support resumed sessions:
- [ ] Persisting sessions for a small duration (customisable by command line argument) after a "dirty" disconnect
- [x] Correctly detecting resume requests from the frontend
- [ ] Finding existing sessions with the same ID
- [x] Basic handshaking to ensure that states are consistent

This should not handle the much more difficult task of resuming a session after the backend _crashes_, but rather a situation where the client connection drops. 

Alternatively, work could instead be done to resume a session by sending all state stored in the frontend (open files, channels, view parameters, regions, requirements) to the backend, which would then construct a new session with the same state as the previous session. This would require the backend to re-open any files listed in the state and re-create any regions associated with these files.

**Comment by kswang1029** [comment]
Tested. If the backend has been time out and users click the resume button on the GUI, nothing will happen and users see a loading bar forever. Reported to https://github.com/CARTAvis/carta-frontend/pull/617

**Comment by veggiesaurus** [comment]
@kswang1029 is the backend still running?

**Comment by kswang1029** [comment]
no. The case here would be that user did not click the resume button **before** the backend session is removed. The frontend should somehow provide a way to notify users that the session cannot be resumed.

**Comment by veggiesaurus** [comment]
The backend _session_ or the backend process itself?

**Comment by markccchiang** [comment]
When backend time out, the session is closed. The frontend should be aware
of the backend does not exist (green light on the top right of the panel
becomes red)?

Angus Comrie <notifications@github.com> 於 2019年12月11日 週三 下午2:42寫道：

**Comment by veggiesaurus** [comment]
> When backend time out, the session is closed. The frontend should be aware of the backend does not exist (green light on the top right of the panel becomes red)?

@kswang1029 in this case, was the indicator light still green?

**Comment by kswang1029** [comment]
@veggiesaurus @markccchiang allow me to try again to reproduce it and observe more carefully.

**Comment by kswang1029** [comment]
ok, looks likely it was because the backend process was gone due to dev update. I just tried again with a long wait, session resume still works.
