### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#173]
Need debug logging added to backend so that when tests fail there is an indication of what code was being executed or where the failure/crash/hang happened.  Enabled when backend parameter verbose=True.

**Comment by kswang1029** [comment]
For ICD tests specifically it might be good to log what messages are being sent (c.f. js console).

**Comment by pford** [comment]
Just log basic message types such as "Received SET_STATS_REQUIREMENTS" then "Sending REGION_STATS_DATA", or print message fields as well?

**Comment by kswang1029** [comment]
sometimes the message fields can be long (spectral profile for example, or raster image data), so if this won’t make debugging even harder I would say it is good to have. Just message name is certainly useful too at some level.
