### ISSUE TITLE
session with unfinished jobs is not killed when reload CARTA

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#179]
To reproduce the issue:
1) open set_QA/orion_12co_hera.fits and enable spectral profiler
2) move cursor around to see profiles, should update quickly as the image is small
3) reload CARTA, then the backend console will show Num sessions: 1 
4) open set_QA/OrionKL_sci.spw19.cube.I.pbcor.fits and move cursor around to see spectral profiles 
5) don't wait the profile update and reload CARTA, now the backend console shows Num sessions: 2. This suggests the session associated with step 4 is still alive but CARTA has been reloaded.

**Comment by markccchiang** [comment]
Currently, the backend cannot kill the spectral profile instantly. It only set the checkpoint per 100 channels and stop it early if the cursor's position changed. It is possible that the closed file's cursor position does not change anymore and leads to its spectral profile process continuous. I will check it. Does this case crash the backend?

**Comment by kswang1029** [comment]
if the first image is large enough, likely yes.

**Comment by veggiesaurus** [comment]
@markccchiang we need to wait until the task is finished before destroying the objects. @robsimmonds any ideas? Maybe in the destructor for `Region` or `Frame`, wait for the task to exit?

**Comment by markccchiang** [comment]
For region spectral profile data, backend sends four messages `Session::sendSpatialProfileData()`, `Session::sendSpectralProfileData()`, `Session::sendRegionHistogramData()` and `Session::sendRegionStatsData()` a time when we update a region status. That means Session will call the same Frame four times for calculations. Destroy the Frame during this process (for example one a new image file) will carsh the backend. This is the casa which @kswang1029 has experienced.

**Comment by markccchiang** [comment]
I think this issue is already solved. @kswang1029 could you please confirm it? Thank you!

**Comment by kswang1029** [comment]
@markccchiang with the help from @ajm-asiaa I think the issue is fixed. 👍 Close the issue.
