### ISSUE TITLE
[backend crash] zooming large image (30k)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#180]
tested with v1.1-beta on mac

test image is cluster_32768.fits (single channel, 32768x32768 px)
zooming can trigger backend crash.

update: cluster_16384.fits too, cluster_08192.fits appears fine.
update2: cluster_32768.fits works fine with v1.0.1

**Comment by veggiesaurus** [comment]
@kswang1029 I presume this needs to be fixed for 1.1?

**Comment by kswang1029** [comment]
Yes I think so. It is regression

**Comment by pford** [comment]
Possibly related to #117

**Comment by kswang1029** [comment]
Yes maybe related. This case is simply zooming a large single channel image. So it is isolated to SET_IMAGE_VIEW.

**Comment by pford** [comment]
Panning is also SET_IMAGE_VIEW, changes the image bounds

**Comment by pford** [comment]
Ready to test, merged into 1.1 branch and dev branch.

**Comment by kswang1029** [comment]
yes, crash is gone. 👍
