### ISSUE TITLE
spectral profiles displays zero for nan channel

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-backend#184]
The spectral profiler is showing  channels that are nan’s as zero.  Should instead not display values for nan channels. 

![Screen Shot 2019-04-15 at 12 31 51 PM](https://user-images.githubusercontent.com/9055533/56126143-cc50b180-5f7a-11e9-97ee-ac1d1e71b38f.png)

**Comment by veggiesaurus** [comment]
@arusstaylor moved this to the carta-backend repo, as it's sending incorrect data (rather than the frontend displaying incorrect data)

**Comment by veggiesaurus** [comment]
@kswang1029 this seems pretty essential to get into 1.1, what do you think?

**Comment by arusstaylor** [comment]
Agreed.  The current behaviour is incorrect. I have labelled the issue “invalid”.

Russ

**Comment by kswang1029** [comment]
Yes, let’s fix this for v1.1

**Comment by kswang1029** [comment]
does the issue remain? I see it works.
![Screen Shot 2019-04-16 at 11 37 40 AM](https://user-images.githubusercontent.com/20819712/56180508-2ebdb680-603c-11e9-913c-01ecbf512311.png)

**Comment by veggiesaurus** [comment]
Cursor region behaves correctly, other regions don't

**Comment by kswang1029** [comment]
Right, region spectral profiler treats nan as zero.

![Screen Shot 2019-04-16 at 12 26 18 PM](https://user-images.githubusercontent.com/20819712/56182059-ddfd8c00-6042-11e9-8147-8dfad756f0a3.png)

**Comment by markccchiang** [comment]
According to @kswang1029's test, the spectral profile for the cursor can send NaN to the frontend. But the spectral profile for the `region` sends zero instead of NaN to the frontend. For example, open the image file `GALFACTS_N4_cube_Q_DQA3.3.1.fits` and present the spectral profile at the pixel coordinate (4182, 567).

**Comment by pford** [comment]
PR #187 merged into release/1.1 branch, PR #188 merged into dev branch.  Ready to test.

**Comment by kswang1029** [comment]
Yes, confirmed the fix! 👍
![Screen Shot 2019-04-17 at 9.11.19 AM.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/737de56f-1eff-4f82-8ba0-ebfb0e82636c)

**Comment by pford** [comment]
We can close this issue?

**Comment by kswang1029** [comment]
yes. closing.
