### ISSUE TITLE
disk cache of image stats data

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#186]
The main idea of this issue is to use disk cache for image stats of non-hdf5 images (casa, fits, miriad) to speed up image loading process. The persistent cache should store per-frame histogram, per-frame statistics, and per-cube histogram once they are calculated for the first time. If the same image is loaded again, the backend should check if cached data are available and applicable to the image first. If not, then compute and save the results in the cache for re-use.

**Comment by Kechil** [comment]
Closed for now - may arise again in consideration of performance
