### ISSUE TITLE
[threading] add ability to cancel threads

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#19]
Threads need to be canceled when:
- image or region is closed - stop processing
- region is changed (control points or rotation) - process new region only
- requirements change - process new requirements only

**Comment by kswang1029** [comment]
Is this the case that with the demo server https://acdc0.asiaa.sinica.edu.tw:47568 , crash happens when doing
1) open h_m51_b_s05_drz_sci.fits
2) then open supermosaic.10.fits (not append)
3) should crash

**Comment by pford** [comment]
No, it happens even with 2 threads (1 "working", other polling for new messages).  Looking into the crash you describe, which seems to happen only in Docker (OSX build was OK).

**Comment by pford** [comment]
This should be looked at along with concurrency issues.

**Comment by pford** [comment]
Not only for closing an image, would improve message handling for multiple SET_CURSOR and SET_IMAGE_VIEW messages where only the latest one needs to be processed and earlier ones canceled.
