### ISSUE TITLE
Tiled rendering: Tile queue

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#226]
In order to deliver tiles to the frontend efficiently, three features are required from the backend:
- [ ] An appropriate queueing mechanism should be used to process tiles. This means that multiple threads can remove tiles from the queue and and crop, downsample and compress them before sending to the frontend.
- [ ] `REMOVE_REQUIRED_TILES` messages need to be handled (on the main thread) to remove matching tile requests from the required tile queue
- [ ] Since changing the channel invalidates all currently required channels, this needs to be handled (again on the main thread) to clear the required tile queue when `SET_IMAGE_CHANNELS` is recieved.

**Comment by veggiesaurus** [comment]
@robsimmonds @confluence This is the extent of the documentation for the tiled rendering backend tasks. Let me know if more detail is required.

**Comment by kswang1029** [comment]
Just a note about the sequence of returned tiles. By requesting 49 tiles in a spiral pattern inside out, the returned sequence is (1-indexed): 
[3,15,12,11,41,19,1,14,47,9,20,5,8,6,30,49,18,31,13,4,48,16,22,17,10,36,32,27,34,39,7,45,28,2,25,40,21,46,29,23,26,42,24,35,38,44,43,37,33]
This means the first requested tile returned in the 7th place in this example. Each measurement should return a different sequence.

**Comment by veggiesaurus** [comment]
@kswang1029 are those tiles all identically sized?

**Comment by kswang1029** [comment]
yes, I believe so. The image is 4096x4096 in size, and we set tile_size=256 and layer_id=3. 

Following is just for reference.
<img width="543" alt="Screen Shot 2019-07-23 at 16 54 30" src="https://user-images.githubusercontent.com/20819712/61697866-b79a6b80-ad6a-11e9-8094-2b20c6ad9155.png">
