### ISSUE TITLE
animator hangs in playback mode if moving cursor inside the image viewer

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#236]
using the dev branch as of May 30, 2019, the animation may hang if we move cursor inside the image viewer (no further cursor movement). The backend seems still alive. After clicking stop then, play, animation continues.

please try supermosaic.10.fits at 15 fps

**Comment by kswang1029** [comment]
after clean up browser cache, the symptom is gone. close this issue for now.

**Comment by veggiesaurus** [comment]
can reproduce this with it running on a local machine. @robsimmonds possibly flow control related? Are we handling flow control messages as a task or on the main thread?

**Comment by robsimmonds** [comment]
@veggiesaurus it is handled in the main thread. Annoyingly I have not reproduced this yet, but maybe that is because I have compiled with the Debug environment.

**Comment by kswang1029** [comment]
@robsimmonds you may try with zoom/pan actions then move cursor around. sometimes this can trigger animator hanging.

**Comment by robsimmonds** [comment]
@kswang1029 ok. I can see some strange behaviour. The animation can slow down after moving the mouse around, but I have not seen it stop. I can disable flow control and see if that behaviour changes just as a tests. There is quite a bit of logic in there se we were expecting a few problems once it was tested more.

**Comment by robsimmonds** [comment]
well that didn't change it, but I have still not got it to actually stop. Again could be due to running with Debug build. Are you using Production build? Also how many threads are you using?

**Comment by kswang1029** [comment]
try to move your cursor *slowly* in the image. I can reproduce hanging with this way.

**Comment by robsimmonds** [comment]
@kswang1029 ok, I do get the animation stop, but as soon as I move the mouse out of the viewer it starts again. You had reported that you went to the stop and play again for it to start. Are you sure that is the case?

**Comment by kswang1029** [comment]
> well that didn't change it, but I have still not got it to actually stop. Again could be due to running with Debug build. Are you using Production build? Also how many threads are you using?

I believe it is debug build and we use 16 threads on the demo server.

**Comment by kswang1029** [comment]
> @kswang1029 ok, I do get the animation stop, but as soon as I move the mouse out of the viewer it starts again. You had reported that you went to the stop and play again for it to start. Are you sure that is the case?

while I am trying to reproduce it again, now the backend can crash with slowly moving cursor.

**Comment by robsimmonds** [comment]
Also the X and Y profile don't appear to stop for me. Do they for you? i think that implies that the animator is running but the images are not being updated.

**Comment by kswang1029** [comment]
Tested, even if I move the cursor out of the image, the animator does not resume.

**Comment by kswang1029** [comment]
what I see is when the animation freezes, xy profiles freezes too (but moving cursor around we can still see profiles from local raster image data I believe).

**Comment by kswang1029** [comment]
ok, when animation freezes, the backend does supply full resolution xy profiles.

**Comment by robsimmonds** [comment]
Still have not managed to crash it but the VM that I am using only has 8 vcpus. Later I can restart it with 32 vcpus. When I went to the production build of the backend, I was still seeing exactly the same behaviour as I reported before. With the production build of the frontend I don't get the animation to restart without going to going stop/start. I do keep since the X/Y profile information which @kswang1029 does not. I suspect this needs some investigation in the JS console to understand what is going on... However, not good that it is crashing and that I have not yet been able to reproduce that.

**Comment by veggiesaurus** [comment]
@kswang1029 can you reproduce this bug after animation integration with tiled rendering?

**Comment by kswang1029** [comment]
@veggiesaurus after trying a while, I cannot reproduce the issue now. When the cursor is moving, the fps drops a little bit (supermosaic at intended 15 fps) but not completely drops to 0. Once cursor stops moving, the fps increases back. 👍

**Comment by veggiesaurus** [comment]
@kswang1029 might be related to additional overhead of sending spatial profiles. Shall I close this for now?

**Comment by kswang1029** [comment]
Yes. Let’s close it.
