### ISSUE TITLE
backend crash when playing animation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#237]
using the dev branch as of May 30, playing animation with cursor moving in the image viewer may trigger the backend crash (not always reproducible). Zooming while playing animation may trigger the backend crash too.

tried with supermosaic.10.fits at 15 fps

**Comment by kswang1029** [comment]
after clean up browser cache, the symptom is gone. close this issue for now.

**Comment by robsimmonds** [comment]
As with the other issue from yesterday I am not managing to reproduce yet. I assume due to some differences in our environment. With a crash it would be very useful of we could get a stacktrace after the crash, just in case it is hard to reproduce.
