### ISSUE TITLE
inconsistent full-frame statistics

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#257]
with the current dev+dev branches as of July 10

While testing region statistics, I spotted a weird issue in statistics widget. In some cases, the full image statistics are not consistent with the region statistics if the region (ellipse or rectangle) covers the entire image. Examples are shown below:

consistent:
![Screen Shot 2019-07-10 at 9 19 35 AM](https://user-images.githubusercontent.com/20819712/60933539-3a481300-a2f5-11e9-9c48-459d1daeb8f4.png)
![Screen Shot 2019-07-10 at 9 31 04 AM](https://user-images.githubusercontent.com/20819712/60933577-79766400-a2f5-11e9-9ba1-078e97ebf738.png)

inconsistent:
![Screen Shot 2019-07-10 at 9 25 28 AM](https://user-images.githubusercontent.com/20819712/60933585-81ce9f00-a2f5-11e9-86c6-42f835959503.png)
![Screen Shot 2019-07-10 at 9 24 19 AM](https://user-images.githubusercontent.com/20819712/60933600-8f842480-a2f5-11e9-884e-78bd9e938f73.png)

Same h_m51 image with v1.1 does not have this issue:
![Screen Shot 2019-07-10 at 9 33 03 AM](https://user-images.githubusercontent.com/20819712/60933654-cd814880-a2f5-11e9-85e8-2a68bd6662fa.png)

**Comment by confluence** [comment]
It looks like the number of pixels is incorrect in one of the calculations. I think all the values that differ depend on this value (number of pixels, mean, rms, std dev).

**Comment by confluence** [comment]
I have encountered the same discrepancy in my branch, where I am adding the use of cached HDF5 stats for full channels. The HDF5 stats disagree with the calculated image stats, but agree with the region stats (except for the standard deviation, which may be a precision issue). If you look at `miniCube_5px_5px_IQU_4ch.fits`, it's clear that the image calculation results in the incorrect number of pixels (5x5 with no NaNs = 25, not 21).

I suspect that some kind of rounding error is happening in the creation of the image region in `Frame::SetImageRegion` (this may explain why it affects some images and not others; it would depend on the X and Y dimensions), but I can't see how this would result in the number of pixels being 21 and not 20.

**Comment by confluence** [comment]
Here's the boolean mask of the minicube full image region: 

```
1 1 1 1 1 
0 1 1 1 1 
0 1 1 1 1 
0 1 1 1 1 
0 1 1 1 1
```

I'm not entirely sure where the asymmetry is coming from, but this is clearly what is causing the incorrect results.

Is there any reason not to deliberately extend the full-image region a pixel past the edge of the image, to ensure that it encompasses all the pixels?

**Comment by confluence** [comment]
Adding a pixel margin to the second control point used to construct the region appears to fix the problem (at least for this image). I will test with other images to confirm, and commit the fix in my PR.

**Comment by confluence** [comment]
Can you confirm that this is now fixed in `dev`?

**Comment by kswang1029** [comment]
@confluence YES! 👍👍👍
