### ISSUE TITLE
Point region get no z-profile

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#263]
Confirmed on frontend [branch](https://github.com/CARTAvis/carta-frontend/tree/hj/%23239_Support_point_region) and ICD test [branch](https://github.com/CARTAvis/carta-backend-ICD-test/tree/hj/issue%2315_region_spectral_point).

Reproduce : After setting up a point region 2 and any region 1, changing from another region 1 to point region 2 should SetSpectralRequirements to let region 1 be null, SetSpectralRequirements to call point region 2, and then backend send SpectralProfileData but with empty z-profile. The ICD test [REGION_SPECTRAL_PROFILE.test.ts](https://github.com/CARTAvis/carta-backend-ICD-test/blob/hj/issue%2315_region_spectral_point/src/test/REGION_SPECTRAL_PROFILE.test.ts) asserts this issue.

**Comment by veggiesaurus** [comment]
@pford can you look into this? We can't test the frontend point regions feature until this is fixed

**Comment by pford** [comment]
I added a note in the weekly meeting page: backend dev, backend master, and ICD-test are all on different protobuf commits.  I cannot get **any** tests to pass in REGION_SPECTRAL_PROFILE.test.ts.

**Comment by pford** [comment]
Tested with frontend hj/#239_Support_point_region branch.  The backend was comparing the Point region's subimage xy point with the cursor position instead of its own region control point.  Since they differed, it exited the spectral profile.

**Comment by pford** [comment]
Side note in issue #273, backend was marking profile as sent after first partial profile, so it did not send profile updates.  Fixed in this branch pam/point_region, profile sent = false until progress is complete.

**Comment by pford** [comment]
There are still issues with interrupting spectral profiles but they will be dealt with separately.  Ready to test that a point region gets a spectral profile.

**Comment by zarda** [comment]
Tested well on both frontend and testing.
