### ISSUE TITLE
hanging backend 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#264]
with dev branch as July 16

the backend hangs if we define a region which is completely outside the image. To reproduce:

1. make a region inside the image (FITS)
2. request region spectral profile
3. seeing it updating the profile
4. when it completes, move the region to be completely outside the image
5. check the profile (it is not updating)
6. move the region back inside the image, it is still not responding.
7. changing channels is not working, neither. The backend hangs.

**Comment by veggiesaurus** [comment]
@markccchiang can you look into this?

**Comment by veggiesaurus** [comment]
this is now fixed, but a quick question related to this: If the region is entirely outside the image, then we simply don't return any spectral data. Should we not instead return an empty profile? (or a profile with `NaN`?) Otherwise the existing profile will remain there.

**Comment by markccchiang** [comment]
Maybe we can. I will modify the code and send another PR.

**Comment by kswang1029** [comment]
Yes, issue solved and when a region is totally outside the image, we see NaN profile. 👍👍👍
