### ISSUE TITLE
[Session API key]Backend not return error message

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#27]
In case an user access backend with an unknown API key, it should return REGISTER_VIEWER_ACK.success == "False" and corresponding error message. But the latest backend returns no error message.

**Comment by veggiesaurus** [comment]
The API key is optional (reserved for future use when handling permissions), so the backend should not return `sucess == false` if it is missing or unknown.

**Comment by pford** [comment]
The backend must be started with permissions=true and a permissions.txt file.  If there is no permissions.txt file, the backend logs this error and continues without permissions.  This has not really been tested and debugged.

**Comment by pford** [comment]
Opened issue #72 to handle all test failures, to be fixed in one branch/pull request.  Closing this as duplicate.
