### ISSUE TITLE
unexpected profile update with multiple spectral profile widgets and multiple regions

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#273]
with dev+dev July 18, 2019

Spectral profiles are updated unexpectedly when switching to different regions.

To reproduce:
1. create three regions on the image
2. create three spectral profile widgets and 
     2.1 assign widget 1 to region 1 with "mean"
     2.2 assign widget 2 to region 2 with "StdDev"
     2.3 assign widget 3 to region 3 with "min"
3. once all profiles are delivered, switch to region 2 in widget 1
==> now the profiles in widget 1 and widget 2 are updated simultaneously (this is probably okay)
4. once all profiles are delivered, switch to region 1 in widget 1
==> now widget 1 updates first, then widget 2 updates (widget 2 seems updates unnecessarily) 

also see the demo
![regionSpecProUpdate](https://user-images.githubusercontent.com/20819712/61425990-6265f080-a94b-11e9-8be3-e56a2f979862.gif)

**Comment by veggiesaurus** [comment]
@pford can you investigate? A diff on the server side between existing and incoming requirements seems to be needed

**Comment by pford** [comment]
Currently, the statistics in the REGION_STATS_DATA are cached, but not the spectral profiles.  When a region's requirements are set, no diffs are made and all profile data is sent.  Will fix this.

**Comment by veggiesaurus** [comment]
if they're cached, then it should be sufficient to just return all, instead of a diff, I guess (if the diff process is too messy)

**Comment by pford** [comment]
I started with the spatial profiles and have a problem, but I think it is in the frontend.  If you have one profile displayed (e.g. "x") then you add the other profile "y", backend only sends y-profile (the diff in requirements) but then x-profile goes blank.  I pushed the branch for issue 273 (spatial profiles only, so far).

**Comment by veggiesaurus** [comment]
Yes, currently the frontend still expects you to send all the spatial profiles instead of the diff (because they were previously all being sent). I'll sort that out tomorrow. For now, you might have to use the dev console to ensure that profiles are being delivered properly

**Comment by veggiesaurus** [comment]
@kswang1029 can you verify that this is fixed in the latest `dev`? (`398fc62`)

**Comment by pford** [comment]
This broke the partial spectral profiles (backend thinks it is sent after first update), fixing in branch for issue #263.

**Comment by kswang1029** [comment]
Issue solved! Nice. 👍
