### ISSUE TITLE
backend crash when requesting region spectral profile from an HDF5 cube

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#280]
to reproduce:
1) define a region which includes zero NaN pixel
2) request to see region spectral profile
3) while the profile is updating, move the region to be totally outside the image
4) then move the region to cover non-NaN pixels, NaN pixels and empty space.
5) possibly the backend will crash, if not, repeat 2) to 4)

The following is just to indicate the three different types of regions. To reproduce this issue, we just need one region and move it around.
![Screen Shot 2019-07-23 at 10 33 46 AM](https://user-images.githubusercontent.com/20819712/61678555-bbf86180-ad35-11e9-8c6c-1e25eff8aaf2.png)

FITS cube does not have this issue.

**Comment by markccchiang** [comment]
It is possible that we have to add a lock while calling the region mask `region->XyMask()`. I will fix it.

**Comment by kswang1029** [comment]
with dev 36d6a07, i think the issue is gone. Shall we close this issue?

**Comment by markccchiang** [comment]
Ok.
