### ISSUE TITLE
Implement region file browser

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#285]
Subtask of issue #171

**Comment by pford** [comment]
The region file browser is good to go.  I tested branch pam/285_region_browser with protobuf branch pam/icd7_region_io by temporarily hijacking the file list/info messages and calling the region list/info functions instead.

**Comment by veggiesaurus** [comment]
@pford thanks, I'll start implementation of the region browser tomorrow.

**Comment by pford** [comment]
Feature included in branches pam/285_region_browser and pam/region_browser_import_crtf.  Ready to test when frontend/ICD tests are compatible.

**Comment by pford** [comment]
Included in issue #286 and PR #312
