### ISSUE TITLE
backend crash if requesting spectral profile from a point region totally outside the image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#292]
this happens to all image format.

**Comment by veggiesaurus** [comment]
@confluence and I were discussing this yesterday. I think the best solution would be to simply check whether the point is outside the image before attempting to calculate the profile, rather than trying to catch a casacore exception (which is how it's handled for other regions)

**Comment by kswang1029** [comment]
right, it would be good to have a checker at the frontend. For point and polygon, we can check if points are all outside the image (image coordinate). For rectangle, we can check the four corner coordinates. For ellipse, it is less straightforward, perhaps?

**Comment by veggiesaurus** [comment]
I'm not sure if it's a good idea to have the check on the frontend. For WCS groups, a region might be within one image, and outside another. The frontend should still request it

**Comment by kswang1029** [comment]
Good point.

**Comment by veggiesaurus** [comment]
@pford or @confluence can you please have a look at this?

**Comment by confluence** [comment]
This should be fixed in #296.
