### ISSUE TITLE
requesting point region spectral profile but the backend responses nothing

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#294]
with the dev as of July 29, 2019

backend may not respond to the request of spectral profile from a point region
to reproduce:
1) open set_QA/M17_SWex.image (only hdf5 works)
2) define 5 point regions
3) enable spectral profiler widget
4) should see cursor spectral profile
5) switch to region 1 and 2 and 3 and so on
 ==> _not_ always seeing the corresponding profiles.

It works normally if we repeat the steps with 5 rectangle regions.

UPDATE: when we see no point spectral profile and reload carta, the new carta session may crash when requesting region spectral profile.

**Comment by pford** [comment]
I could not reproduce this with latest local backend 2c217e9 and docker frontend 4627333 (mix 'n match offline).

**Comment by kswang1029** [comment]
with dev backend 36d6a07, the issue is gone. Close this issue for now but i will keep an eye on it.
