### ISSUE TITLE
incorrect and inconsistent per-frame histogram

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#307]
with the dev backend/frontend as of Aug 8, 2019

With the test image set_StokesCube/image_IQU.im, we see inconsistent and incorrect per-frame histogram. A region is created to cover the entire image. In some cases (at different channel), the histogram in the render config widget is correct. But in some other cases, the histogram widget is correct. Moreover, both can be incorrect. 

![Screen Shot 2019-08-08 at 11 42 48 AM](https://user-images.githubusercontent.com/20819712/62673712-15b58880-b9d2-11e9-8aa3-1a3b299bd162.png) 

![Screen Shot 2019-08-08 at 11 43 19 AM](https://user-images.githubusercontent.com/20819712/62673710-151cf200-b9d2-11e9-83c7-7de30efd16a1.png)

![Screen Shot 2019-08-08 at 11 42 57 AM](https://user-images.githubusercontent.com/20819712/62673711-151cf200-b9d2-11e9-80fa-3377f637bdf8.png)

Here I attach another example fits image which is 8x8x100 (https://drive.google.com/open?id=1V5VUX79NWSiUAv82_adpPcQfOR-rC1iY). For each channel, there is a pixel ~1 with all other channel ~0.1. So the histogram would be similar to
![Screen Shot 2019-08-08 at 12 19 29 PM](https://user-images.githubusercontent.com/20819712/62674842-d2a9e400-b9d6-11e9-9d06-e60071894d16.png)
That is, a bump on the left and a one-count bin on the right.
However, by changing channels, sometimes we will see the one-count bin on the right is missing. In other word, there is just a bump. 
![Screen Shot 2019-08-08 at 12 24 14 PM](https://user-images.githubusercontent.com/20819712/62674989-78f5e980-b9d7-11e9-951d-60b0f1e769a2.png)

Could it be memory leakage?

**Comment by veggiesaurus** [comment]
@markccchiang or @confluence can you look into this? @kswang1029 have you found a way to consistently reproduce this?

**Comment by pford** [comment]
Looking at the histogram messages, the histograms for both regions have the same number of bins.  When the histograms match, the histograms for each region have the same bin width; when they differ, the bin widths differ.

**Comment by kswang1029** [comment]
> @markccchiang or @confluence can you look into this? @kswang1029 have you found a way to consistently reproduce this?

@veggiesaurus with set_StokesCube/image_IQU.im we can see the issue quite easily.

**Comment by markccchiang** [comment]
That is probably the mismatch of Min/Max calculation results.
