### ISSUE TITLE
cancelable region spectral profiler with hdf5 images?

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#311]
With dev as of Aug 12 2019

backend team please confirm the following issue.

It appears that the backend is still busy on region spectral profile calculations even if there is no profile update messages being sent when the frontend no longer needs the profile.

To reproduce the issue:
1) open a large enough hdf5 image
2) freeze cursor and launch one spectral profile widget. we should see a profile now.
3) make a region (region 1)
4) request profile from region 1
5) while profile of region 1 is updating, switch back to cursor and unfreeze cursor and move around, now we should see cursor profile updates along with the cursor movement but we don't. We will start to see it update _once_ the backend completes the region 1 profile calculations.

**Comment by markccchiang** [comment]
It appears the hdf5 image is not included in the cancellation while the region id is removed from the frontend. I will fix this issue.

**Comment by markccchiang** [comment]
Fixed it in the commit 2a42f613db5bb0c9b185b452828976832e3f41b1 (in PR #288).

**Comment by pford** [comment]
Merged into dev

**Comment by kswang1029** [comment]
@pford Yes, issue solved. 👍
