### ISSUE TITLE
region import: missing point region

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#316]
The CRTF point region
`symbol[[320pix, 200pix], '.']`
is missing when importing.

**Comment by pford** [comment]
In imageanalysis this is a display definition, along with line, vector, and text.  AnnotationBase::isRegion() returns false since AnnSymbol is not derived from AnnRegion.  I thought for carta a point region would be a rectangle with blc=trc.

**Comment by kswang1029** [comment]
If we define a point region with casaviewer can export it as a crtf file, we see it is “symbol”. The same file can be imported to casaviewer and we will see a point region.
