### ISSUE TITLE
Crash when exporting point regions or polygons outside image

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#317]
At the moment, if you try to export a point region, the backend will crash with the error 
`Error: LCPolygon - entire polygon is outside the lattice`

The same occurs if you create a region of any type that is entirely outside the image (see below)

![image](https://user-images.githubusercontent.com/592504/62950118-bd262700-bde7-11e9-8489-fded5a627d35.png)

We could work around the second crash, but it would probably mean ignoring regions that are outside of the image. @kswang1029 is this an issue?

**Comment by kswang1029** [comment]
@veggiesaurus no for v1.2, yes for v1.3.
What if the region is half outside the image? Can it be exported successfully? I cannot test this case with casaviewer....

**Comment by veggiesaurus** [comment]
@kswang1029 if it is partially off, then it still works. I guess the solution for 1.2 is to prevent the _crash_ and then to sort out the casa issue before 1.3

**Comment by veggiesaurus** [comment]
Even if the crash is fixed, is should still be a "known issue"
