### ISSUE TITLE
Regions entirely outside image cannot be imported or exported

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#320]
_(likely has a casacode / casacore dependency and can be listed as known issue for 1.2 and fixed in  a patch release)_

Currently, any regions that are entirely outside the image are ignored when exporting or importing. This will become a critical issue for 1.3's WCS group feature.

**Comment by pford** [comment]
I sent Dave Mehringer an email explaining what carta needs.  If the imageanalysis annotation regions could do everything but set an underlying lattice region (getRegion() returns nullptr) that would be perfect.  But I don't know the impact of such a change on other CASA code.

The casaviewer will not let you set a region outside the image.  An export of such a region (e.g set in a larger region, outside a smaller region, exported from the smaller region) results in a CRTF file with just the header.

**Comment by pford** [comment]
Dave and I have a plan to fix this, but the casacode change won't make it in for release 1.2.  I will make the change and have the PR waiting for Dave to review when he gets back from vacation.

**Comment by veggiesaurus** [comment]
@pford thanks for following up on this. Sounds promising. It's not a problem aiming for 1.3.

**Comment by pford** [comment]
Completed development in casacode branch.  Once tests pass, will open PR for Dave to review.  In the meantime, I will continue carta development against this branch.
