### ISSUE TITLE
empty histogram if all pixels are negative in a frame

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#321]
test image: set_noise/noise_negative2.miriad which has pixel values of ~-10

**Comment by veggiesaurus** [comment]
@markccchiang it's because `_max_val` is being initialised to `std::numeric_limits<T>::min()` instead of `-std::numeric_limits<T>::max()`

**Comment by markccchiang** [comment]
Yes, may be use `std::numeric_limits<T>::lowest()` instead of `std::numeric_limits<T>::min()` for initializing the `_max_val`.

**Comment by veggiesaurus** [comment]
yes, good idea.

**Comment by markccchiang** [comment]
Will push later, I am trying to build the casacode.
