### ISSUE TITLE
backend hangs when trying to open a position-velocity image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#326]
Dev 43289d9
Although PV is not currently supported, the backend hangs if we try to open a PV image. Perhaps we need a way to not allowing pv image to be loaded until we support it.

**Comment by pford** [comment]
For this issue, the backend uses the coordinate system to determine which pixel axes are linear (p) and spectral (v).  In general (but found in some test pv images), if the image has an incomplete header, the coordinate system only processes the existing information so its number of pixel axes does not match the number of axes in the image data.  This will cause a problem later in pixel/world coordinate conversions to create regions, so the backend sends the error message "Image coordinate system does not match data shape"  which I think may be confusing to users.  Should it just say something like "Problem loading file: incomplete header"?

**Comment by kswang1029** [comment]
> Should it just say something like "Problem loading file: incomplete header"?

Yes, this sounds a good idea and useful for users.

In the warning message, it says "Position-velocity (pv) images not supported.". Could we add "yet". This may make users feel better. : )

**Comment by pford** [comment]
Messages updated.

**Comment by kswang1029** [comment]
fixed. 👍
