### ISSUE TITLE
export a rotated rectangle in crtf but when import back, the result is incorrect

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#342]
with dev frontend+backend branches as of Sep 10, 2019

To reproduce the issue, create two rotated rectangles, one inside the image and the other outside the image.
![Screen Shot 2019-09-10 at 10 53 38 AM](https://user-images.githubusercontent.com/20819712/64580760-1cad2d80-d3ba-11e9-8158-17fcebdcf8bf.png)

Then, export the regions as a crtf file in world coordinate. It would look like
#CRTFv0 CASA Region Text Format version 0
rotbox [[275.08815702deg, -16.21520299deg], [49.7087arcsec, 17.6052arcsec], 30.00000000deg] coord=ICRS, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=green, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
rotbox [[275.03797647deg, -16.21620408deg], [46.6019arcsec, 17.6052arcsec], 30.00000000deg] coord=ICRS, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=green, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false

The rotation angles are correct in the crtf file.

Then, import the same crtf region file. We see (note that in the example below the original two regions have been moved up just for clarity)
![Screen Shot 2019-09-10 at 10 54 40 AM](https://user-images.githubusercontent.com/20819712/64580948-da382080-d3ba-11e9-8dee-8c0fcc70ad14.png)

Issues:
1) Only one region is imported (should have two with index 3 and 4). The region outside the image is not imported successfully. 
2) Region 3 does not have a rotation applied.

It appears that REGION_FILE_INFO_RESPONSE shows the syntax correctly. IMPORT_REGION_ACK, however, does not contain correct region info.
![Screen Shot 2019-09-10 at 11 11 01 AM](https://user-images.githubusercontent.com/20819712/64581257-e5d81700-d3bb-11e9-8eab-74f6ae2a3450.png)

**Comment by pford** [comment]
Ready to test in release and dev.

**Comment by kswang1029** [comment]
Yes, issue gone. 👍 Close this issue.
