### ISSUE TITLE
checking file name of a region file when exporting

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#344]
@kswang1029 commented on [Wed Sep 11 2019](https://github.com/CARTAvis/carta-frontend/issues/526)

Currently the frontend checks the input file name of a region file with all other existing region files (via REGION_LIST_RESPONSE) when exporting. However, the input name may coincide with other image files or other file types. If this happens, the frontend shows successful but actually there is no region file saved. Luckily existing file is not overwritten based on my test.

If we don't want to add a field in REGION_LIST_REQUEST to include all files in the directory, we could consider to enable adding .crtf or .reg extension to lower the chance of having identical name. Not ideal though.

@veggiesaurus @pford thoughts?

---

@veggiesaurus commented on [Wed Sep 11 2019](https://github.com/CARTAvis/carta-frontend/issues/526#issuecomment-530247235)

we shouldn't associate the extension with the file type. Perhaps we should simply list all files.
I think this is more of a backend issue though. If the backend returns all files in the list, the frontend should display them

---

@kswang1029 commented on [Wed Sep 11 2019](https://github.com/CARTAvis/carta-frontend/issues/526#issuecomment-530247640)

Yes, if the frontend is aware of all files in the backend directory, we can use the current approach to warn users. We will need to make sure if users really want to use a region file to overwrite a image file or else, things are handled properly at the backend. 

---

@kswang1029 commented on [Wed Sep 11 2019](https://github.com/CARTAvis/carta-frontend/issues/526#issuecomment-530248117)

@veggiesaurus shall we migrate this to backend?

**Comment by pford** [comment]
All files or all **image** files along with the region files?

**Comment by kswang1029** [comment]
I suggest we check for all files.

**Comment by kswang1029** [comment]
Yes, it works well. 👍 Close this issue.
