### ISSUE TITLE
Inconsistent handling of symlinks

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#358]
File info hangs on file symlink outside of root filesystem, but is listed and opens on double-click.  Make this consistent by allowing file info.

**Comment by pford** [comment]
@kswang1029 is this still an issue?  I copied a FITS image to our NRAO lustre filesystem and created a symlink to it in my home directory.  Both are mounted filesystems (different ones).  Using both the RHEL7 CARTA.AppImage and the NRAO network carta installation, I could see the image in the file list, show its file info, and open it.

**Comment by kswang1029** [comment]
@kswang1029 Double check again!

**Comment by kswang1029** [comment]
@pford @veggiesaurus I re-tested and this is still an issue in v1.4.
