### ISSUE TITLE
Support for fz

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-backend#360]
Support for fz files (e.g. img.fits.fz) without the need to "funpack".

See: http://archive1.dm.noao.edu/tutorials/fpack

**Comment by veggiesaurus** [comment]
@pford are we using `cfitsio` underneath to read FITS files? If so, `.fz` images _should_ work properly, or it should be reasonably easy to add support for them.

**Comment by Jordatious** [comment]
@arusstaylor and I found out from ThunderKAT that they plan to use this compression for their images too. Apparently they get a 5-6x reduction in volume by doing so! So seems like a good use case to support.

**Comment by pford** [comment]
This requires casacore to support the 64-bit integer type in binary tables.  (Internal note: updating casacore requires updating casa6 then updating carta-casacore.)  We could use cfitsio directly for the file browser but then the casacore::FITSImage will also require this change.

**Comment by pford** [comment]
Possibly the same int64 issue as #635, but astropy shows this hdu as a CompImageHDU (not a FITS standard type) with type float32.  Needs more investigation.

**Comment by kswang1029** [comment]
test images are available via #682
