### ISSUE TITLE
backend stops responding when stop animating raster+contour images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#366]
frontend: 9a74dbc
backend: 9ca101c

to reproduce:
1) load a large image cube in spatial domain (e.g. 2800x2800)
2) generate contours at 99.9%
3) start animation at 5 fps or higher and stop any time and repeat.
4) the backend may stop responding and we see a persistent streaming indicator
![Screen Shot 2019-10-28 at 15 06 32](https://user-images.githubusercontent.com/20819712/67658481-a5951e00-f994-11e9-8d07-4901310d6c63.png)

UPDATE: when the backend stops responding, it is actually very busy.
![Screen Shot 2019-10-28 at 15 36 01](https://user-images.githubusercontent.com/20819712/67660283-6ae1b480-f999-11e9-9f1d-83208a0cc3cf.png)

**Comment by Kechil** [comment]
@veggiesaurus to investigate

**Comment by Kechil** [comment]
Might be same bug as #? (Angus to write description)

**Comment by veggiesaurus** [comment]
This could also be due to the backend sending far too many frames ahead (the control flow window is much too large at the moment: 10x the frame rate).

**Comment by kswang1029** [comment]
@robsimmonds @veggiesaurus with the described test method and with 
origin/rwjs/update_ani_perams 045bd2e 5034 2020-07-28 16:24:19 UTC
the backend is less busy and can restore the idle state much quickly than the dev backend. 👍

**Comment by veggiesaurus** [comment]
@kswang1029 please confirm that this is fixed when mix 'n match is back

**Comment by kswang1029** [comment]
@veggiesaurus will do. I haven’t seen this issue recently but I will try again on Monday

**Comment by kswang1029** [comment]
Not able to reproduce the issue with dev+dev (as of April 13 2021). Close the issue.
