### ISSUE TITLE
support additional animator playback modes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#367]
referencing https://github.com/CARTAvis/carta-frontend/issues/265

The backend needs to support the following animation playback modes:

- [x] forward
- [x] backward
- [x] bouncing
- [x] blink

**Comment by veggiesaurus** [comment]
I think the backend already supports backward and bouncing. At least, they are defined in the ICD and seem to be handled in the code, but I'm not sure if there are any tests for them. @zarda , are there any ICD tests for animation modes?

**Comment by zarda** [comment]
Please refer to [#11](https://github.com/CARTAvis/carta-backend-ICD-test/issues/11), forward and bouncing are good. I have no idea about the behave "blink", does it mean jump?

**Comment by kswang1029** [comment]
@zarda if the range is 3~10, blinking results in 3 10 3 10 3 10 and so on.

**Comment by veggiesaurus** [comment]
I wonder if we could recreate this by using an appropriate delta channel definition and loop + reverse?

e.g. if we set startFrame to 3, endFrame to 10 and deltaFrame to 7, and then set the reverse and loop flags?

**Comment by zarda** [comment]
The "backward" action can be implemented by setting a delta = -1, what is tested by revised ICD test.
