### ISSUE TITLE
backend hangs if requesting file info of a non region file in the region file browser

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#369]
currently the region file browser lists up _all_ files regardless it is region file or not. If we click on a non region file (e.g., png, pdf, etc), the backend will hang.

**Comment by pford** [comment]
Included in pull request #387

**Comment by pford** [comment]
Fix merged into dev.

**Comment by kswang1029** [comment]
@pford Verified. 👍
