### ISSUE TITLE
missing PC header keywords from the backend

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#372]
The attached file is an image with rotation (thus the PC matrix is not unity).
[rotated.fits.zip](https://github.com/CARTAvis/carta-backend/files/3802874/rotated.fits.zip)

Its header looks like
SIMPLE  =                    T /Standard FITS                                   
BITPIX  =                  -32 /Floating point (32 bit)                         
NAXIS   =                    2                                                  
NAXIS1  =                  113                                                  
NAXIS2  =                   76                                                  
EXTEND  =                    T                                                  
BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 
BZERO   =   0.000000000000E+00                                                  
BMAJ    =   1.486111200000E-02                                                  
BMIN    =   9.499999700000E-03                                                  
BPA     =   6.000000000000E+00                                                  
BTYPE   = 'Intensity'                                                           
OBJECT  = '        '                                                            
BUNIT   = 'Jy/beam '           /Brightness (pixel) unit                         
EQUINOX =   2.000000000000E+03                                                  
RADESYS = 'FK5     '                                                            
LONPOLE =   1.800000000000E+02                                                  
LATPOLE =   0.000000000000E+00                                                  
PC1_1   =   7.071067811865E-01                                                  
PC2_1   =  -7.071067811865E-01                                                  
PC1_2   =   7.071067811865E-01                                                  
PC2_2   =   7.071067811865E-01                                                  
CTYPE1  = 'RA---SIN'                                                            
CRVAL1  =   0.000000000000E+00                                                  
CDELT1  =  -2.222222308810E-03                                                  
CRPIX1  =   5.600000000000E+01                                                  
CUNIT1  = 'deg     '                                                            
PV2_1   =   0.000000000000E+00                                                  
CTYPE2  = 'DEC--SIN'                                                            
CRVAL2  =   0.000000000000E+00                                                  
CDELT2  =   3.333333234031E-03                                                  
CRPIX2  =   3.800000000000E+01                                                  
CUNIT2  = 'deg     '                                                            
PV2_2   =   0.000000000000E+00                                                  
DATE    = '2019-11-04T06:30:53.875825' /Date FITS file was written              
TIMESYS = 'UTC     '           /Time system for HDU                             
ORIGIN  = 'CASA 5.5.0-149'                           
With ds9, it looks like
<img width="771" alt="Screen Shot 2019-11-04 at 14 47 30" src="https://user-images.githubusercontent.com/20819712/68103585-75a8c600-ff12-11e9-831b-e11766ebcbbc.png">

In CARTA, "PC" keywords are missing thus the frontend cannot render the grid line properly.
<img width="853" alt="Screen Shot 2019-11-04 at 14 49 43" src="https://user-images.githubusercontent.com/20819712/68103573-5f9b0580-ff12-11e9-9eb5-a730ee3b659b.png">

**Comment by veggiesaurus** [comment]
shouldn't the backend be sending _all_ headers, rather than some subset? Not sure why the PC entries would be missing.

**Comment by pford** [comment]
Included in pull request #387

**Comment by pford** [comment]
Fix merged into dev.

**Comment by kswang1029** [comment]
@pford Verified. 👍
