### ISSUE TITLE
TabularCoordinate - start and end values in table must differ 

### ISSUE THREAD

**Issue by teuben** [CARTAvis/carta-backend#373]
I have a FITS file, which to me looks quite ok. It works in ds9, but carta refuses to load it with the error:

Failed to open image at specified HDU: TabularCoordinate - start and end values in table must differ 

The fitsheader reads as follows (file available upon request):

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    4 / number of array dimensions                     
NAXIS1  =                  384                                                  
NAXIS2  =                  384                                                  
NAXIS3  =                   50                                                  
NAXIS4  =                    1                                                  
CDELT1  =  -0.0027777777777778                                                  
CRPIX1  =                192.5                                                  
CRVAL1  =                  0.0                                                  
CTYPE1  = 'RA---TAN'                                                            
CUNIT1  = 'deg     '                                                            
CDELT2  =   0.0027777777777778                                                  
CRPIX2  =                192.5                                                  
CRVAL2  =                  0.0                                                  
CTYPE2  = 'DEC--TAN'                                                            
CUNIT2  = 'deg     '                                                            
CDELT3  =              16000.0                                                  
CRPIX3  =                 25.0                                                  
CRVAL3  =      271079.99324799                                                  
CTYPE3  = 'VOPT    '                                                            
CUNIT3  = 'm s-1   '                                                            
CDELT4  =                  1.0                                                  
CRPIX4  =                  0.0                                                  
CRVAL4  =                  0.0                                                  
CTYPE4  = 'STOKES  '                                                            
CUNIT4  = 'PAR     '                                                            
EPOCH   =                 2000                                                  
INSTRUME= 'MARTINI '           / 1.0.5_commit_3e93a1a                           
DATAMAX =    488.6826746584455                                                  
DATAMIN =  -0.5763670411812526                                                  
ORIGIN  = 'astropy v3.1.2'                                                      
OBJECT  = 'MOCK    '                                                            
BPA     =                  0.0                                                  
OBSERVER= 'K. Oman '                                                            
BUNIT   = 'beam-1 Jy'                                                           
DATE-OBS= '2019-11-04T12:44:05.4'                                               
BMAJ    = 0.008333333333333333                                                  
BMIN    = 0.008333333333333333                                                  
BTYPE   = 'Intensity'                                                           
SPECSYS = 'TOPOCENT'                                                            
END

**Comment by veggiesaurus** [comment]
Did some digging, the error shows up in the following line:
```
casacore::FITSImage fits_img(_filename, 0, hdu_num);
```
so it's a casacore error, rather than a CARTA error :thinking: @pford will you look into this?

**Comment by pford** [comment]
FITSImage tries to create a casacore::CoordinateSystem with a casacore::SpectralCoordinate by parsing the FITS headers with WCSLIB.  Then the optical velocities are converted to frequencies using:
`frequencies(i) = restFrequency/(vel/C::c+1.); // in Hz`
restFrequency is determined from the FITS headers restfreq or restwav, but since these headers do not exist all frequencies for the spectral axis are 0 Hz.  These frequencies are given to the TabularCoordinate class, resulting in the error message.

The CASA viewer, which also uses casacore, gives the same error.

**Comment by veggiesaurus** [comment]
@pford so what are the next steps? Do we file a casa bug and keep this in the icebox? @kswang1029 do we mark this as a known issue?

is there a default `restfreq` or `restwav` value we could insert?

**Comment by kswang1029** [comment]
I can mark this as a known issue in the user manual.

**Comment by veggiesaurus** [comment]
@pford can we try to work around this? Preventing users from opening certain FITS files entirely is quite an issue. 

Here's a simple example of the type of header that is causing this issue:

```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -32 / array data type                                
NAXIS   =                    3 / number of array dimensions                     
NAXIS1  =                  472                                                  
NAXIS2  =                  392                                                  
NAXIS3  =                 2048                                                  
CRPIX3  =                  1.0                                                  
EQUINOX =                 2000                                                  
CTYPE1  = 'RA---TAN'                                                            
CRPIX2  =                196.5                                                  
CRVAL1  =        128.943935587                                                  
CDELT1  =         -0.006666667                                                  
CROTA2  = '359.984194193'                                                       
CTYPE2  = 'DEC--TAN'                                                            
CRVAL2  =        -55.583803136                                                  
CDELT3  =     -11027.522471028                                                  
CDELT2  =          0.006666667                                                  
CRPIX1  =                236.5                                                  
CRVAL3  =      23182194.541397                                                  
CTYPE3  = 'VELO-HEL'                                                            
END                                                                             
```

**Comment by veggiesaurus** [comment]
@pford can we work around casa for this case?
