### ISSUE TITLE
improper handling of masked values in CASA images

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#374]
CASA images with masked values are treated differently in CARTA. Sometimes masks are reported as zeros in the image plane, NaN in the statistics, and I saw a case where masked values are simply ignored and the values behind the mask is displayed. 
Need to sort this out for all image formats.

**Comment by jott3077** [comment]
I added a few files to my home directory. Please download 
www.nrao.edu/~jott/cartamaskissues.tar.gz
There are few files in there: 

miriad-mask
The image is a miriad image, siome values are constant, then there's a transition, and the outer values are all masked. In CARTA they appear as zeros and not as masks. 

testmask-casamaskfirstplane.im
a CASA image with a fully masked first plane. CARTA shows them as zeros, not masks. 

testmask-casapartial.im 
a CASA image with a partially masked image. CARTA ignores all the masks and shows the unmasked values.

I added fits images to all of them. They seem to be ok with NaNs where the other formats have masked values. 

I would strongly consider that CARTA also calls the values masks, and not NaNs to be consistent with our usage in astronomy. Proper NaN values can be shown as masked.

**Comment by jott3077** [comment]
I should mention that I haven't tested on HDF5 since I don't have such images.

**Comment by veggiesaurus** [comment]
@jott3077 I'm not that familiar with masks other than NaN masks in FITS images, so I want to make sure that I'm understanding what you're requesting:

- Masked and NaN/INF pixels should be _rendered_ as the specified NaN color value (defaults to blue, I thnk)
- The _cursor_ value displayed when the user moves their cursor over a masked pixel should display the actual value, rather than just `NaN` or `Masked`?
- Consistent handling between image formats (assuming this is possible, as different formats may have different conventions)

Is that correct?

**Comment by jott3077** [comment]
I was thinking about the following: 

- masks in CASA and MIRIAD images are stored in separate subtables. So they can be distinguished from NaN/INF or other magic values

- when hovering over a masked value with the cursor, it should show 'masked', NOT the actual value  and NOT zero (this is why the current behavior is a bug) also when NaNs are masked they should be shown as 'masked' (e.g. in CASA fitting, when the fit fails, the image may have NaNs but the tasks mask them additionally so they do no harm. 

- calculations (e.g. statistics) should not consider any 'masked', NaN, INF

- on colorization, I suggest to give 'masked' a different color from NaN, masks are usually some kind of transparent, but can be any color, like black or blue, or white (depending on the color scheme), we can give a default and make it a preference 
NaN/INF are frequently a different color, I usually see a bright red (could also be settable as preference). 

- on the consistency side, I am not sure how masked values are stored in fits, but if fits does not distinguish between them, I suggest that they are all treated as 'masked'. 

I am also not sure how HDF5 stores masks. If they are special values inside the data like fits, then I suggest to treat them all as 'masked'. If masked values are in a separate subtable like in CASA or MIRIAD, we can distinguish between masked values and NaN/INF 


Alternatively, we can also lump all of the 'masked', NaN, INF into the same 'masked' bag. That would not give us the flexibility as described above, but I would be ok with it. CASA, MIRIAD etc, they all create a mask for the NaNs etc anyways. The only problem is then that this could lead to some small confusion when e.g. saving images as they may have then show additional masked values that originated from NaN and INF. The masks would also not necessarily be the exact shape as possibly defined by the user earlier. And it would be difficult, e.g. to distinguish between no solutions and failed solutions when the image comes from a fitting or other image manipulation procedure. But there's no _science_ case where one really likes to distinguish between masks and NaN.

**Comment by veggiesaurus** [comment]
> I suggest to give 'masked' a different color from NaN

That would require a substantial change to the data delivery and rendering, because we'd then need to send a separate mask layer from backend to frontend. 

Hdf5 files handle masks the same way as FITS: either you supply an explicit mask value in the headers (for integer based images) or you mask values by replacing them with NaN

**Comment by pford** [comment]
Noting here that miriad-mask outer values are 0 not masked (shown as 0 in casaviewer), so CARTA also shows them as 0 after this fix.  The masked values in miriad-mask.fits are shown as NaN in CARTA.

**Comment by pford** [comment]
Ready to test in dev.  Working on patch for release/1.2 branch to backport this change.

**Comment by kswang1029** [comment]
@pford Thanks for the fix. 
For casa image, yes, mask works (e.g., set_QA/M17_SWex.image vs set_QA/M17_SWex_masked.image)
![Screen Shot 2019-12-17 at 10 55 27 AM](https://user-images.githubusercontent.com/20819712/70961065-c1c35a80-20bb-11ea-9c05-0b58908d2665.png)


For miriad image, it seems not working. (e.g., set_QA/M17_SWex.miriad vs M17_SWex_masked.miriad)
Expected mask looks like this (from MIRIAD/cgdisp):
![Screen Shot 2019-12-17 at 10 56 12 AM](https://user-images.githubusercontent.com/20819712/70961121-e1f31980-20bb-11ea-8310-4ef6c89c8051.png)


Could you have a look?

**Comment by pford** [comment]
MiriadImage returns isMasked = false.  Added casa label, will investigate further.

**Comment by pford** [comment]
casacore::MIRIADImage doesn't even try to handle masks.

**Comment by pford** [comment]
Created issue #404 for casacore::MIRIADImage issues, revising this issue for CASA images only. @kswang1029 , please review whether this issue can be closed for CASA.
