### ISSUE TITLE
CARTA does not start from '.'

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#378]
when I re-start CARTA from the command line in desktop mode, it will always start the file bowser in the last directory I looked at an image, not in '.', where it should, I think.

**Comment by pford** [comment]
@ajm-asiaa startup script issue?

**Comment by ajm-ska** [comment]
@jott3077 I tried to reproduce your issue using the Desktop versions of CARTA on MacOS, RHEL, and Ubuntu, but I can not. In all cases I start CARTA using the command line, use the file browser to browse to a folder, and open an image. Then I quit CARTA and re-open it. The file browser does not remember the last directory used. Are you sure that you are really closing CARTA and starting up a new session?

**Comment by jott3077** [comment]
@ajm-asiaa I tried it in a fresh terminal and I agree, the behavior seems to be fine. I cannot reproduce it either anymore. I will close the issue, until it reappears consistently.
