### ISSUE TITLE
backend support of catalogue overlay

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#383]
placeholder of all backend work related to catalogue overlay (frontend #571). Joint efforts from @markccchiang and @zarda, and discussions with @panchyo0 and @veggiesaurus

**Comment by markccchiang** [comment]
We may have a document to specify what data that frontend needs from the backend with respect to their protobuf messages.

**Comment by veggiesaurus** [comment]
@panchyo0 has put together a design document [here](https://docs.google.com/document/d/1DD-_AXg7Nk5fzBAXLdXqkAOqyV-R40Wep7X2K0ymp4A/edit#heading=h.get8b5g447o), which should server as a good starting point. @panchyo0, can you move the document into the CARTA team drive's technical documents folder?

**Comment by veggiesaurus** [comment]
@markccchiang @zarda I think the best starting point is to work out what our options are in terms of loading and parsing VOTables. Given that VOTables are simply a specific schema of XML, we have a few options:
1) use an existing VOTable library for c++ (there are very few, and none are maintained)
2) use an XML library for c++ (there are lots of excellent, well-maintained ones) and handle the "VO" stuff ourself
3) delegate to a CASA library if one exists. I've not investigated that, but it would make me a bit nervous to delegate to CASA unless their VOTable loading/parsing is widely used, well-documented and compatible.

My personal preference is (2), but am open to suggestions. Xerces, libXML2 or tinyXML seem like viable options.

**Comment by panchyo0** [comment]
The document is under CARTA team drive's technical documents folder/ frontend development/catalog overlay

**Comment by markccchiang** [comment]
Looks Xerces has the most support of XML parsing (SAX and DOM), but it is a little bulky. TinyXML is very tiny, not sure does it fit our future requirements. LibXML2 looks promising so far. 

@kswang1029 mentioned two VOTable tools: [VO-India](http://voi.iucaa.in/voi/downloads.htm) and [VOTPP](http://ross.iasfbo.inaf.it/votpp/main.html). For the first link, it contains some java based libraries which are not for us. It also contains some C++ libraries. I do not read them in detail but they look outdated. 

For the second link VOTPP, it is C++ based and the version is 2007 (0.3.2-alpha1). It needs to work with another library [MCS](http://ross.iasfbo.inaf.it/mcs/). So it seems not suitable for us. But I found the code is not so large and it also utilizes LibXML2 which provides a good reference for us. I may try to write the VOTable parser based on its concept.

PS: [What XML parser should I use in C++?](https://stackoverflow.com/questions/9387610/what-xml-parser-should-i-use-in-c)

**Comment by veggiesaurus** [comment]
> For the second link VOTPP, it is C++ based and the version is 2007 (0.3.2-alpha1). It needs to work with another library [MCS](http://ross.iasfbo.inaf.it/mcs/). So it seems not suitable for us. But I found the code is not so large and it also utilizes LibXML2 which provides a good reference for us. I may try to write the VOTable parser based on its concept.

We should avoid that library, it's very out of date, and not well maintained. Fine to base your VOTable parser on it, but do remember that we're not trying to write a fully-fledged VOTable library which supports every possible feature, so our parser can probably be a bit simpler. 

Based on the flowchart you linked, it looks like LibXML2 is the answer.

**Comment by zarda** [comment]
The XML data binding framework allow us easy to maintain codes, likes [CodeSynthesis XSD](https://en.wikipedia.org/wiki/CodeSynthesis_XSD). We can unserialize data to be an object only.

**Comment by veggiesaurus** [comment]
> The XML data binding framework allow us easy to maintain codes, likes [CodeSynthesis XSD](https://en.wikipedia.org/wiki/CodeSynthesis_XSD). We can unserialize data to be an object only.

I wonder if that would support something with as flexible a schema as votable

**Comment by kswang1029** [comment]
It might be good to check what astropy adopts.

**Comment by veggiesaurus** [comment]
> It might be good to check what astropy adopts.

astropy is all written in python, so we probably can't reuse any of the libraries they use. However, the code looks like it creates a custom object after parsing the XML document. I think that's the direction we should go, whether it's by introducing another library to automatically deserialize to our custom objects, or just creating the objects manually (probably simpler, considering that our objects are basically a table).

**Comment by markccchiang** [comment]
I am writing a VOTable parser, which utilizes the LibXML2. There would be an iterator that iterators through a whole VOTable file. The filtered data will be collected by a callback function or an object. I will refer to a mock-up example in @panchyo0's doc. Please remind me if there are more functionalities (or the detail cases) that we want to apply.

**Comment by veggiesaurus** [comment]
> I am writing a VOTable parser, which utilizes the LibXML2. There would be an iterator that iterators through a whole VOTable file. The filtered data will be collected by a callback function or an object. I will refer to a mock-up example in @panchyo0's doc. Please remind me if there are more functionalities (or the detail cases) that we want to apply.

Are you parsing and iterating _each time_ the user changes the filter, or are you building the parsed object once, and then applying the filter to it? I don't think we're looking at catalogues that are too large to fit in main memory after being added to our custom structure, so we should do the reading and parsing once (when the file is opened), and then apply the filter to our custom-constructed object. This means the initial opening of the catalogue file will take a bit longer, but adjusting the filter will be much faster

**Comment by markccchiang** [comment]
Ok, I will adopt the way that reading and parsing once and then apply the filter to our custom-constructed object.
