### ISSUE TITLE
recognize and display gzipped fits files

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#384]
fits files are frequently stored in a gzipped format. It would be great if CARTA could recognize them and  display them, so they can be viewed without the user having to gunzip (CARTA would gunzip on the fly - cf kvis has this feature).

**Comment by veggiesaurus** [comment]
somewhat related to #360. This would probably require changes to casacore

**Comment by kswang1029** [comment]
What happens to a read-only file system? And security? performance?

**Comment by veggiesaurus** [comment]
> What happens to a read-only file system? And security? performance?

There are ways to open gzip'd files without writing to disk, but that would obviously require more memory. No major security issues, other than the common security issue with compressed files: it's possible to create a small compressed file that decompresses to an infinitely large (at least from a practical perspective) file.

**Comment by pford** [comment]
Test files in #648

**Comment by kswang1029** [comment]
test images are available via #682
