### ISSUE TITLE
calculate mean and standard deviation while calculating histogram

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#385]
@kswang1029 has a suggestion that we allow the user to determine automatic contour levels based on mean and standard deviations of the image (either channel or cube). This requires _calculating_ the mean and standard deviation of either the image region or the cube region. However, since we already need to calculate the histogram anyway, we should just add the mean and standard deviation to the calculated quantities. This should not slow things down at all, since the main bottleneck in calculating the image histogram is sequential memory reads and random memory writes, while updating a running total of `sum(x)` and `sum(x^2)` would not require any additional reads (assuming the sum values would end up in L1 cache).

This could be done by modifying the `MinMax` class to include a `sumX` and `sumX2` result.

Another advantage of this is that we can easily display the mean and standard deviation on the histogram graph.

**Comment by veggiesaurus** [comment]
noting that this is a story point of "2" purely because it will require some ICD adjustments to send the mean and standard deviation to the frontend as well.

**Comment by kswang1029** [comment]
if min and max can be included, that would be very useful as the default parameter set if users select min-max-n_level-scaling level generator. I suppose the histogram has provided the answer.

**Comment by veggiesaurus** [comment]
initial tests show that this increases the time taken to calculate histograms by about 10-20%. @kswang1029 and I agree that this tradeoff is worth it in terms of the additional functionality it provides. Mean and standard deviation indicators will also be useful for deciding on clip bounds for raster images.
