### ISSUE TITLE
regions away from the reference pixel are distorted and give the wrong pixel count

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#389]
I am trying a region like: 

#CRTF v0
centerbox[[400pix,400pix],[4pix,4pix]]

on a really big image, where the reference coordinate is very far away (2028,790). 
The region should cover 25 pixels, including those that sit right on the edge of the region. 
If it would count the ones on the edges as outside, then the number should be 9. 
Statistics, however, gives me 15, which is neither. At [1400pix,400pix], so at a different position, I get 18. 
Right on the reference pixel, I get the 25 as expected. 
So there seems to be some WCS dependency even though the box is expressed entirely in pixel coordinates. 
The image I used is 
111.nrao.edu/~jott/NH3_3-3.2kms.clean.gal.map.m-2.fits
It's actually in Galactic coordinates, but I don't think that matters.

**Comment by veggiesaurus** [comment]
I tried to reproduce this, but it gives me 25 pixels each time, as long as my center is exactly an integer. As soon as it is non-integer, it becomes 16 pixels, which makes sense, since pixels along two of the edges no longer have their centres covered by the region.

@jott3077 how were you constructing these regions? Were you importing them or manually typing in the center and size values?

**Comment by jott3077** [comment]
I was creating a crtf file and imported it into CARTA. 

This is the content of the file

#CRTF v0
centerbox[[2028pix,790pix],[4pix,4pix]]
centerbox[[400pix,400pix],[4pix,4pix]]
centerbox[[1400pix,400pix],[4pix,4pix]]


Did you get the image? I see I had a typo, the URL is 
www.nrao.edu/~jott/NH3_3-3.2kms.clean.gal.map.m-2.fits
I just tried again and I get 
Region 1: 25 pix
Region 2: 15pix
Region 3: 18pix

When I manually added a region (close to region 2), I also see that it is 25pix. So it appears to happen with loaded regions only. Exporting regions and importing them again, shows the different pixel numbers.

**Comment by veggiesaurus** [comment]
@pford can you look into this? Is it because we're converting the regions from pixel to WCS?

**Comment by pford** [comment]
The CRTF import is done by the imageanalysis code, which converts the input parameters (pixel or WCS) to the coordinate system of the image the region is applied to. Dave indicates in a CASA ticket that machine precision in these conversions may result in fractional pixels greater/less than .0 (the pixel center) that would exclude expected pixels.

The backend queries the imported AnnotationRegion (AnnPolygon for centerbox) for the four pixel vertices (as double values), then computes the center pixel, width (px), and height (px) to send to the frontend using the first (blc) and third (trc) pixel vertices.  These values are shown in the "Editing Region X" widget.  The imported AnnotationRegion also returns a WCRegion which is applied to the image to create a SubImage for region calculations such as statistics.  The blc, trc IPositions (integer values) returned by ImageStatistics are in agreement with the region shape and the number of pixels.

For Juergen's example:
```
Region 1 centerbox[[2028pix,790pix],[4pix,4pix]]
AnnPolygon pixel vertices [0] = 2026, 788  [2] = 2030, 792
SubImage shape=[5, 5, 1]
ImageStats region blc=[2026, 788, 0] trc=[2030, 792, 0]
All values masked, npixels = 25
```
```
Region 2 centerbox[[400pix,400pix],[4pix,4pix]]
AnnPolygon pixel vertices [0] = 398.001, 398  [2] = 401.999, 402
SubImage shape=[3, 5, 1]
ImageStats region blc=[399, 398, 0] trc=[401, 402, 0]
All values masked, npixels = 15
```
```
Region 3 centerbox[[1400pix,400pix],[4pix,4pix]]
polygon pixel vertices [0] = 1398, 398  [2] = 1402, 402
SubImage shape=[5, 5, 1]
ImageStats region blc=[1398, 398, 0] trc=[1402, 402, 0]
18 values masked, 7 values unmasked, npixels = 18
```

**Comment by pford** [comment]
Noting here that Region 2 statistics agree with imstat, which was used for the expected values for statistics in the ICD tests.  For now, CASA will be adding a note in the documentation and known issues for "centerbox" use.

```
CASA <1>: imstat('NH3_3-3.2kms.clean.gal.map.m-2.fits', region="centerbox[[400pix,400pix],
4pix,4pix]] range=[0chan, 0chan]")
Out[1]: 
{'blc': array([399, 398,   0], dtype=int32),
 'blcf': '1.752936deg, -0.396474deg, 23870210158.608142852783203125Hz',
 'flux': array([ 0.03178825]),
 'max': array([ 0.12581864]),
 'maxpos': array([399, 401,   0], dtype=int32),
 'maxposf': '1.752935deg, -0.393974deg, 23870210158.608142852783203125Hz',
 'mean': array([ 0.1184174]),
 'medabsdevmed': array([ 0.0047979]),
 'median': array([ 0.12076805]),
 'min': array([ 0.10798555]),
 'minpos': array([399, 398,   0], dtype=int32),
 'minposf': '1.752936deg, -0.396474deg, 23870210158.608142852783203125Hz',
 'npts': array([ 15.]),
 'q1': array([ 0.11303743]),
 'q3': array([ 0.12257408]),
 'quartile': array([ 0.00953665]),
 'rms': array([ 0.11854135]),
 'sigma': array([ 0.00560991]),
 'sum': array([ 1.77626093]),
 'sumsq': array([ 0.21078079]),
 'trc': array([401, 402,   0], dtype=int32),
 'trcf': '1.751268deg, -0.393141deg, 23870210158.608142852783203125Hz'}```

**Comment by pford** [comment]
@kswang1029 should CARTA be consistent with imstat, or override the imageanalysis region import behavior so that the region pixel coordinates match the CRTF pixel coordinates?

**Comment by kswang1029** [comment]
@pford I would suggest we to be consistent with imstat. @jott3077 comments?

The ambiguity here I think is that all regions are defined in cartesian coordinate and when they are rendered, we don't consider projection effect at the moment. When we define a region with angular size (for example, a box centered at (100deg, -10deg) with width 10 arcmin and height 5 arcmin), the region looks the same at any part of the image. Depending on projection type, a unit angular size corresponds to different size in image coordinate (pixel) at different places. Not sure if imstat handles this properly or not. If projection effect is considered by imstat while we don't render a region with projection effect, users may get confused by the values reported with the statistics widget. Ideally, if projection effect is handled properly, we should see a region changing its appearance while it is moved to other locations, but this capability is beyond the current release goal.

**Comment by Kechil** [comment]
Needs checking with Juergen

**Comment by jott3077** [comment]
I think that if a region is in units of pixels this should be independent of any projection whatsoever, and reflect the actual pixels of the image.
I had also opened a ticket for CASA: 
 https://open-jira.nrao.edu/browse/CAS-12824

in the hope that maybe a fix there would propagate also into CARTA. Looks like CASA (which I am no longer a part of) has decided to just tell people to use odd numbered pixel widths for their boxes, and closed the issue....  
So we could go the same route in CARTA and just make a note in the documentation.

**Comment by kswang1029** [comment]
@jott3077 could you try v3-beta3 release and see if this is still an issue? With images like the following and with a square region of 4pix x 4pix, I see consistent pixel count at different places with different space distortions. 

![Gaussian_array_wide fits-image-2022-05-17-13-48-11](https://user-images.githubusercontent.com/20819712/168738421-8aa32c8b-9fc6-4097-b8c7-7b3b41c6c347.png)

![g_deg miriad-image-2022-05-17-13-52-06](https://user-images.githubusercontent.com/20819712/168738706-99f20e2c-45fd-47c5-9d40-8c5a1a7871e0.png)

**Comment by pford** [comment]
@kswang1029 with my developer build and with the NRAO system-installed carta (2.0.0), I opened the image and imported the 3 regions; all had 25 pixels.  I exported the regions in pixel coordinates then imported them again, and all 3 imported regions also had 25 pixels in both carta versions.  Can we close this issue?

**Comment by kswang1029** [comment]
> @kswang1029 with my developer build and with the NRAO system-installed carta (2.0.0), I opened the image and imported the 3 regions; all had 25 pixels. I exported the regions in pixel coordinates then imported them again, and all 3 imported regions also had 25 pixels in both carta versions. Can we close this issue?

@pford thanks for double checking. 👍
