### ISSUE TITLE
Do not round in 'File Information'

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#394]
Loading an image in Galactic coordinates (same image as in #392) I find that 'file information' in the loading window displays the following lines: 

Image reference coordinates = [0.3961 , -0.0707 ]
Image ref coords (coord type) = [0.39611 , -0.0706588 ]

Is there a reason why the first line is just a rounded version of the second line?  I suggest not to round the first line and just copy the full precision header to avoid users using wrong values. In the Galactic coordinate case the rounding is obvious, but for other coordinate systems, where the second line is e.g. sexagesimal, the rounding will not be obvious anymore. Best to not perform rounding for this critical information.

**Comment by veggiesaurus** [comment]
@pford does the rounding happen on the backend? I can't see any rounding in the frontend code (although I didn't look too carefully)

I think @duidae wrote the computed info part in the backend.

**Comment by pford** [comment]
I will change the fixed point format to general format, where precision depends on the input value.

**Comment by kswang1029** [comment]
@pford Looks good to me (please see my other comments in https://github.com/CARTAvis/carta-backend/issues/13 point (4)). 

@jott3077 Could you check too (http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev)?

**Comment by veggiesaurus** [comment]
can we close this issue?
