### ISSUE TITLE
support VLT MUSE FITS cubes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#396]
From user feedback:
--
Hello,

I was playing around with CARTA, which is quite good-looking, and I wanted to use it on my MUSE datacubes. But this does not work - I get:

Error loading file: File DATACUBEFINALexpcombine_20190505T042946_5234143d.fits does not exist.

The same cube loads nicely with ds9 and no problem loading it with astropy or IDL either:

In [1]: from astropy.io import fits 

In [2]: fits.info('DATACUBEFINALexpcombine_20190505T042946_5234143d.fits') 
Filename: DATACUBEFINALexpcombine_20190505T042946_5234143d.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
 0  PRIMARY       1 PrimaryHDU    1550   ()
 1  DATA          1 ImageHDU        40   (319, 318, 3681)   float32
 2  STAT          1 ImageHDU        41   (319, 318, 3681)   float32
 3  white         1 ImageHDU        31   (319, 318)   float32
 4  Johnson_V     1 ImageHDU        33   (319, 318)   float32
 5  Cousins_R     1 ImageHDU        33   (319, 318)   float32
 6  Cousins_I     1 ImageHDU        33   (319, 318)   float32

The version of CARTA I used right now is CARTA Viewer version 1.2.0 for Red hat (20190827) but it also happened with version 1.2.1 for Ubuntu. My Linux version is Fedora 28 but CARTA works nicely for images.

Is this a known problem with a work-around, or is there modifications needed for CARTA? Just browsing the source it seems to go back to casacore?

	Cheers,
	     Jarle.

**Comment by kswang1029** [comment]
I have obtained a MUSE cube from ESO archive. Also replied Jarle to see if we could get a small sub cube of his data for further diagnostics. This feels like a header issue.

**Comment by pford** [comment]
The "does not exist" message appears when CARTA tries to resolve the filename into an absolute path then stat/lstat fails on that path.

**Comment by veggiesaurus** [comment]
> I have obtained a MUSE cube from ESO archive. Also replied Jarle to see if we could get a small sub cube of his data for further diagnostics. This feels like a header issue.

Does the MUSE cube load ok for you?

**Comment by kswang1029** [comment]
@veggiesaurus not even shown in the file list.... I doubt there might be different versions of MUSE cube structure/header.

**Comment by veggiesaurus** [comment]
I've done some digging into this. The reason it's not shown in the file list is because CARTA thinks there are no valid image HDUs. Digging deeper, I suspect what's happening is that it's failing to skip through HDUs, because it detects the number of HDUs correctly (3), but `fits_input.hdutype()` (line 38 of FitsHduList.h [which we should probably move into a source file]) returns `PrimaryArrayHDU` each time, and `fits_input.datatype()` (line 74) returns `BYTE` each time, even though only the _first_ HDU is `BYTE` type. 

On that note, it's not clear to me why it's showing up as `BYTE` instead of `CHAR`

**Comment by pford** [comment]
I added the BYTE datatype to be treated the same as CHAR, with `<T>` = `<unsigned char>`.  Merged into dev and ready to test.

**Comment by kswang1029** [comment]
@pford I am retrieving more MUSE image cubes from ESO archive. It will take a while.

**Comment by kswang1029** [comment]
With few more MUSE fits cubes from the ESO archive, I think this fix works well now. 👍

**Comment by veggiesaurus** [comment]
> With few more MUSE fits cubes from the ESO archive, I think this fix works well now.

I guess we won't know if the user's issue is fixed until 1.3?

**Comment by kswang1029** [comment]
No, unless we proactively provide a new package to the user. To do this or not, I think we need further insight from PM and the management team.
