### ISSUE TITLE
cursor spectral profile not working

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#401]
frontend: origin/dev 1d32861 2019-12-13 14:08:48 CST
backend: origin/dev c01bbb8 5034 2019-12-17 10:09:24 CST

With c01bbb8, cursor spectral profile does not work. Region spectral profile still works.

Tracing back with mix n match page, it seems from pam/374_image_mask branch.

**Comment by pford** [comment]
FIx merged into dev.

**Comment by kswang1029** [comment]
verified. 👍
