### ISSUE TITLE
MIRIAD image issues: velocities, masks, etc.

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#404]
See notes in #374 and #377, which are being revised to refer to CASA only.  The casacore::MIRIADImage is incomplete, resulting in an incorrect FITS header sent to the frontend and no mask handling.

- [ ] incorrect frequency conversion for spectral axis results in incorrect velocity in render widget heading
- [ ] projection is incorrect
- [ ] masks are ignored

I recommend creating a CartaMiriadImage like the CartaHdf5Image, in which the miriad headers are read with mirlib and used to set up the image, and masks are detected and available.

**Comment by kswang1029** [comment]
@pford 
@veggiesaurus and I had some discussions about the unification of headers and we think we should not perform any conversion for the frequency axis. If a miriad image or a  fits image has CTYPE3 = VELO, we should keep it as VELO. 

If you think we need a separate issue for this, please do.

**Comment by pford** [comment]
@kswang1029:

Re: frequency/velocity conversion:
I opened PR #410 .  However, with the casacore SpectralCoordinate, a VELO axis will result in a "native type" of either VRAD or VOPT.  If this is unacceptable, we will have to go back to reading headers with third-party libraries for each image type (HDF5, mirlib, wcslib, casacore).

Re: MIRIAD projection in issue #377 
There is code in casacore::MIRIADImage which reassigns NCP to SIN with parameters; a log message says "NCP projection is now SIN projection in WCS. miriad readers will not handle this correctly." -- ???  I can put in a workaround to read the header with mirlib and restore the original projection type.
