### ISSUE TITLE
missing raster tiles when loading an 80k x 80k image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#408]
![hugeGaussian80k fits-image-2019-12-25-9-17-9](https://user-images.githubusercontent.com/20819712/71427826-7b8f7c00-26f7-11ea-8f17-41bf9f5bf688.png)

**Comment by kswang1029** [comment]
I made two test images: a) 65536x100 and b) 65537x100. With Mac desktop version, a) can be loaded and rendered properly. For b), the backend spends much longer time to load then crashes.

**Comment by pford** [comment]
@kswang1029 commented in Slack that this issue can be fixed in 1.3 and not backported to the 1.2.2 patch.  PR #409 for dev branch.

**Comment by kswang1029** [comment]
fixed! 👍
