### ISSUE TITLE
backend keeps streaming image data repeatedly after animation has stopped

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#420]
frontend: origin/angus/contour_dialog 2984c6b 2020-01-14 02:45:42 CST
backend: dev
This happens when contour layer is enabled.

[Jan-14-2020 11-42-05.mp4.zip](https://github.com/CARTAvis/carta-backend/files/4057241/Jan-14-2020.11-42-05.mp4.zip)

**Comment by veggiesaurus** [comment]
This is a flow-control issue with animations.

**Comment by kswang1029** [comment]
@robsimmonds @veggiesaurus this issue is much improved by
origin/rwjs/update_ani_perams 045bd2e 5034 2020-07-28 16:24:19 UTC

After pressing the stop button of the animator, we still see ~2-channel updates of the contour layer, then it jumps back to the channel we intended to stop at (should be no impact to usability). With the current dev, we will see lots of channel updates of the contour layer. 👍 👍 👍
