### ISSUE TITLE
session resume when contours are enabled

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#421]
It appears that with the current dev backend once a session is resumed, contours are not sync'd with raster image anymore when changing channels. Could it be because contour messages are not included in the resuming messages yet? @markccchiang Could you have a look?

**Comment by markccchiang** [comment]
Yes. Contour messages are not included in the resuming messages. I will add them.

**Comment by kswang1029** [comment]
@markccchiang could you help to fix this? I think this one needs to be backported to v1.3
