### ISSUE TITLE
peculiar histogram distribution

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#423]
We have a set of small FITS images (256x256) from VLBI imaging training page http://vlbiimaging.csail.mit.edu/train_01_staticCelestial_20

With the current dev branch, some images show perculiar histograms with periodic dips such as the following examples. However, it is not always the case with other images in the set.
![Screen Shot 2020-01-15 at 15 17 23](https://user-images.githubusercontent.com/20819712/72413917-e0486e80-37ab-11ea-918d-83812991ab1e.png)
![Screen Shot 2020-01-15 at 15 16 55](https://user-images.githubusercontent.com/20819712/72413919-e0486e80-37ab-11ea-835f-6a5820931608.png)
![Screen Shot 2020-01-15 at 15 16 36](https://user-images.githubusercontent.com/20819712/72413920-e0486e80-37ab-11ea-9284-f333ceefcd59.png)
![Screen Shot 2020-01-15 at 15 16 20](https://user-images.githubusercontent.com/20819712/72413922-e0e10500-37ab-11ea-925d-bdaba4935cbe.png)
![Screen Shot 2020-01-15 at 15 16 06](https://user-images.githubusercontent.com/20819712/72413924-e0e10500-37ab-11ea-98d1-5e05217b9f85.png)

Test images are attached. 
[tmp.zip](https://github.com/CARTAvis/carta-backend/files/4063543/tmp.zip)

**Comment by veggiesaurus** [comment]
what do the histograms look like in other programs? Are they definitely wrong, or just a matter of some sort of quantization?

**Comment by kswang1029** [comment]
@veggiesaurus Interesting! You are right. It seems to be quantization. I tried with python and see the same. I guess we can safely close this issue now?
![Figure_1](https://user-images.githubusercontent.com/20819712/72486912-4a622180-3847-11ea-9f97-43037509923e.png)
![Figure_2](https://user-images.githubusercontent.com/20819712/72486914-4a622180-3847-11ea-8d4d-48d00af17c4c.png)
![Figure_3](https://user-images.githubusercontent.com/20819712/72486915-4afab800-3847-11ea-90b7-53a0e3fe2f94.png)
![Figure_5](https://user-images.githubusercontent.com/20819712/72486916-4afab800-3847-11ea-91db-8f7d8803cbba.png)
![Figure_35](https://user-images.githubusercontent.com/20819712/72486917-4afab800-3847-11ea-8aca-146bae23d7cb.png)
