### ISSUE TITLE
flux density of a region spectral profile

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#424]
now with the frontend branch done by @TienHao 
origin/thchang/add_flux_density_602 009dd6e 2020-01-15 16:22:39 CST
we can request the backend to provide statistic="flux density" of a region spectral profile. However, this works only when using statistics widget. With the spectral profile widget, it returns nothing.

**Comment by veggiesaurus** [comment]
@kswang1029 have you looked at the protocol buffer messages being sent from the frontend? Is it requesting them correctly?

**Comment by kswang1029** [comment]
I tried this branch origin/thchang/add_flux_density_602 5ef742f 2020-01-15 17:16:54 CST
and see flux density (enum=3) is requested via the protocol buffer message.
<img width="479" alt="Screen Shot 2020-01-16 at 13 24 16" src="https://user-images.githubusercontent.com/20819712/72496119-a89cfd80-3863-11ea-89bc-e69800539ba5.png">

**Comment by veggiesaurus** [comment]
@pford can you look into this? I think it's probably quite simple to implement, since it's working for statistics already. @confluence might have to alter the HDF5 codepath a little bit though.

**Comment by pford** [comment]
I fixed the stats list (spectral profile stats types) in Region.h in branch **424_spectral_flux**.  Assigning to Adrianna for HDF5 support.

**Comment by kswang1029** [comment]
@pford Thanks for fixing this. I tried with a test image and it works consistently comparing to CASA viewer. 👍 Once HDF5 is also supported, I will perform more tests with different images.

**Comment by confluence** [comment]
I think that the correct thing to do here is to try to reuse the flux density calculation from casacore with the sum and number of pixels read from the HDF5 file. I'm going to have a look at this. This is a good time to do some refactoring and simplification and try to integrate the HDF5 stats with the rest of the system a bit better.

**Comment by confluence** [comment]
For now I have added a minimal implementation of the flux density calculation to the HDF5 stats code.
