### ISSUE TITLE
missing spectral profile with flux density as stat

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#432]
<img width="550" alt="Screen Shot 2020-01-31 at 9 54 56 AM" src="https://user-images.githubusercontent.com/20819712/73525613-d8c1d000-440f-11ea-93ea-8eeb3cb07c66.png">

**Comment by pford** [comment]
@kswang1029 is this still an issue?  A PR for HDF5 flux density was merged after this.  Please give more info.

**Comment by kswang1029** [comment]
Fixed 🙂
