### ISSUE TITLE
Support PI (polarized intensity) and PA (polarized angle) request from the frontend

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#433]
Currently the backend can supply profiles and images of any Stokes parameter. We need to extend this to PI (polarized intensity) and PA (polarized angle) so the backend will use Q and U profiles to derived PI and PA profiles. Fractional quantities should be supported too.

This includes:
- [x] profiles
- [x] contours
- [x] raster image

ref: https://github.com/CARTAvis/carta-frontend/issues/713

**Comment by markccchiang** [comment]
Is it similar to the way in image moments generation? First, the frontend sends requirements to the backend, generating polarized intensity, fractional polarized intensity, or polarized angle raster images. Then, the backend opens these generated raster images and sends open files acks to the frontend. Using these raster images, we can do profiles or contours analysis.
