### ISSUE TITLE
region analytics with multiple image overlay

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#435]
in v1.3 multiple images can be matched spatially and spectrally. Spatially this is achieved by translating, rotating, and scaling of raster tiles. As a consequence, region of interest needs to be enhanced to support multiple images involving the above approach of spatial matching.

Analytics including:
- [ ] spectral profile
- [ ] statistics
- [ ] histogram

**Comment by pford** [comment]
Duplicate of #146 ?
