### ISSUE TITLE
Regression: Opening certain files results in invalid WCS

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#436]
There's a regression since CARTA 1.2.2, where opening some HST images (e.g. this 1.6 GB file [here](https://archive.stsci.edu/missions/hlsp/candels/goods-n/gn-tot/v1.0/60mas-all/hlsp_candels_hst_acs_gn-tot-60mas_f606w_v1.0_drz.fits)) results in cassacore giving up the parsing of WCS information and instead just using dummy WCS. 

The output from the backend is shown below. The file loads fine with CARTA 1.2 an 1.2.2

```
2020-02-07 06:47:02	INFO	FITSCoordinateUtil::fromFITSHeader	celfix incurred the error Invalid parameter value
2020-02-07 06:47:02	INFO	FITSCoordinateUtil::fromFITSHeader	cylfix incurred the error Invalid parameter value
2020-02-07 06:47:02	WARN	FITSCoordinateUtil::fromFITSHeader	The wcs function failures are too severe to continue ...
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	No proper coordinate system defined in FITS file. Using dummy linear system instead.
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)	FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
2020-02-07 06:47:02	WARN	FITSImage::getImageAttributes (file /home/angus/repos/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
```

**Comment by pford** [comment]
I believe this is a FITS-specific issue.  There is a setup error in wcslib with the headers in this file.  When it tries to set the wcsprm structure, the wcsprm.lin (linprm struct for linear transformation parameters) fails. I don't know yet if this is a wcslib bug or a missing header issue.  Juergen downloaded another test HST FITS image for me which opens with no issues. 

The wcsprm setup does modify the coordinate system information, converting CD to PC headers and setting the linear coordinate axes, which are returned from FITSImage. I can read the original headers from the FITS image and send them to the frontend in the file info header entries.  At least the image will be displayed as before with RA/Dec axes.  Some features which depend on a direction coordinate will fail.

**Comment by pford** [comment]
Update: wcslib is attempting to set the disprm struct (parameters for prior distortion functions) in the linprm struct, using the CPDISja, DPja, and CPERRja headers.  For this image, these headers are:
CPDIS1  = 'Lookup  '
CPDIS2  = 'Lookup  '
DP1     = 'AXIS.2: 2'
DP2     = 'AXIS.2: 2'
CPERR1  =   6.090749055147E-02
CPERR2  =   7.344448566437E-02.

The problem is the 'Lookup' value; wcslib accepts 'TPD', 'TPV', 'SIP', 'DSS', 'WAT', or 'Polynomial*'. It throws a BAD_PARAM error for this header, which shows in the log as "celfix incurred the error Invalid parameter value." and "cylfix incurred the error Invalid parameter value." Both functions call wcsset() which calls linset() which calls disset().  Since setting the wcsprm struct fails, FITSImage sets up a dummy coordinate system.

**Comment by pford** [comment]
I am sending the original headers from casacore::FitsInput as header_entries, then using them to create computed_entries, but the frontend still displays generic X Coordinate and Y Coordinate axes.  What am I missing?
![fileinfo](https://user-images.githubusercontent.com/856604/75828939-36786d80-5d6a-11ea-90e0-70cb87b2932b.png)
![render](https://user-images.githubusercontent.com/856604/75828950-3d06e500-5d6a-11ea-8738-fc38bca6e904.png)

**Comment by veggiesaurus** [comment]
@pford with your branch `pam/436_invalid_csys` I can confirm that the issue moves to the _frontend_ once the original headers are sent. 

The issue seems to be that we're adding `'` quotes around string values _and_ their comments, rather than just around the string values. This can bring an entry length up to 82 characters, if the header was originally already at the maximum length of 80 characters. This mucks up AST's parsing.

I've tried trimming the comments using @duidae's function he wrote for the spectral conversion stuff, and that seems to solve the issue. 

@pford I wonder if we should just insert the correct quotes on the backend side? So instead of values being
```
{
    name: "D001KERN"
    value: "square /  Drizzle, form of weight distribution kernel"
}
```
we change it to 
```
{
    name: "D001KERN"
    value: "'square' /  Drizzle, form of weight distribution kernel"
}
```

(on the frontend side, we can then stop adding the quotes ourselves)

Alternatively (and this might be a cleaner solution), we could add a `comment` field to the `CARTA::HeaderEntry` message, and then the frontend could handle things properly

**Comment by pford** [comment]
For now (close to 1.3 release) I just shortened the HeaderEntry value string to 67 characters so it works with the current frontend.  We can discuss reformatting these strings for 1.4.

**Comment by kswang1029** [comment]
@pford I tried origin/pam/436_for_1.3 e4d1707 and tried pacs160_js.fits. The file info gives proper image WCS properties as 

> Name = pacs160_js.fits
Shape = [3624, 3753]
Coordinate type = Right Ascension, Declination
Projection = TAN
Image reference pixels = [1812, 1876.5]
Image reference coordinates = [07:09:44.3610, -010.41.11.2097]
Image reference coords (deg) = [107.435, -10.6864]
Celestial frame = FK5, J2000
Pixel increment = -3.200", 3.200"
Pixel unit = Jy/pixel

However, the rendered coordinate grid is still linear and the header has something wrong with NAXIS1 and NAXIS2.

> NAXIS = 2 / Dimensionality
NAXIS = 3624
NAXIS = 3753

The headers should be (from ds9)

> NAXIS   =                    2 / Dimensionality                                 
NAXIS1  =                 3624                                                  
NAXIS2  =                 3753 

Could you have a look?

**Comment by pford** [comment]
Fixed that issue, but still get a frontend parsing error:
`astRead(FitsChan): FITS keyword 'CTYPE1' refers to an unknown projection type 'EAR"'.`
From the headers:
`CTYPE1 = RA---TAN / WCS: Projection type axis 1, default="LINEAR"`

Should we abandon this for 1.3?  @veggiesaurus suggested we put the comment in a separate field or enclose the string value in single quotes to simplify the parsing.  Either one would require frontend development.

**Comment by pford** [comment]
Updated protobuf to add comment field to HeaderEntry, and updated this branch to use it in header_entries.  Need frontend support to merge PR #454 .
