### ISSUE TITLE
add "extrema" to stats drop down options

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-backend#438]
In the case that I am looking at  z-profile in a Stokes cube values of Q, U and V can be negative.  So if I want to look at a profile of maximum Q, U or V polarised intensity in a region I cannot do that by selecting "max".  We need another option "extrema" which will plot the value of the extrema in a region whether it is positive or negative.

**Comment by veggiesaurus** [comment]
transferred to backend as it is primarily a backend/cassacore issue.

**Comment by pford** [comment]
Ready to test when frontend supports new type or ICD test added.

**Comment by kswang1029** [comment]
@arusstaylor Thanks to @pford and @TienHao, now the stat type "extrema" is implemented. Could you have a look with http://carta.asiaa.sinica.edu.tw/frontend/84ad950/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socket5028 with images in set_StokesCube?

Thanks.
