### ISSUE TITLE
Dynamically detect location of casacore / casacode in cmake

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#439]
At the moment the `casacode` include location in  `CMakeLists.txt` is incompatible with the install locations of the Ubuntu package, which should now be the preferred way of installing the casa dependencies in Ubuntu. So to install the backend while using the package, we have to either pass an additional flag to cmake or edit the file. This should not be necessary. We haven't edited the file permanently because (to the best of my knowledge) the MacOS and CentOS installs still use casacode installed in `/usr/local`.

It should be possible to modify the file to cover both cases. The correct way to do this is probably to create a cmake extension to locate casa; we may be able to repurpose something like [this](https://github.com/casacore/casarest/blob/master/cmake/FindCasaCore.cmake). But we may be able to do something much simpler, like add both directories, but this requires some investigation (if they both exist, which one will be prioritised? Etc.).

**Comment by ajm-ska** [comment]
@confluence Thank you. That is a good idea. It was a lot easier back in the day when we just needed to do `cmake ..` 

Even on MacOS, I still need to manually set the casacode/casacore include locations in the cmake command (plus the lib location, but that also necessary for at least libuv). 

For reference, here is the cmake command I currently use on MacOS:
`cmake .. -DCMAKE_CXX_FLAGS="-I/usr/local/include/casacode -I/usr/local/include/casacore -I/usr/local/include -I/usr/local/opt/openssl/include" -DCMAKE_CXX_STANDARD_LIBRARIES="-L/usr/local/lib -L /usr/local/opt/openssl/lib -lcasa_imageanalysis" `

(You can see it is also necessary to set the openssl location). I guess this could be considered as the standard for everyone using MacOS. I let casascore/code install to its default location, and installed all other dependencies with Homebrew.

What is the preferred way to install the dependencies in Ubuntu? If it is the Ubuntu carta-casacore ppa, that also installs to /usr/local, doesn't it?

**Comment by confluence** [comment]
The preferred way to install casacore / casacode on Ubuntu should be the `carta-casacore` PPA package. It installs into `/usr/`, not `/usr/local/`, which is as it should be -- that is the standard install location for system packages.

On Ubuntu we can use `cmake ..` with no additional flags (apart from flags that actually set compilation options) -- except for this current issue with casacode. It should be possible to make this happen on any OS, even if we need to add OS-specific sections to the cmake configuration file.

**Comment by ajm-ska** [comment]
OK. I suppose the easiest way is just to make it look in both places; `/usr` first, then `/usr/local`. I guess eventually it would be unlikely that someone would have it in both places, but if they do (say they are actively testing different casacore versions or fixes) then they should know to manually define the location with the -I and -L flags.

**Comment by ajm-ska** [comment]
@confluence How is [this](https://github.com/CARTAvis/carta-backend/commit/2a86b509a78272d8df4eec65d20aaab7f1697fa8) change? 

```
INCLUDE_DIRECTORIES(/usr/include/casacore /usr/local/include/casacore)
INCLUDE_DIRECTORIES(/usr/include/casacode /usr/local/include/casacode)
```

I think this means it will look in `/usr/include` first. If it doesn't find what it is looking for it will look in `/usr/local/include`. So on ubuntu it should pick up the PPA installation of casacore and casacode in `/usr/include`. On RedHat and MacOS, it won't find it in `/usr/include`, but then will find it in `/usr/local/include`.

I was wondering if it is worth adding MacOS specific search locations too. The MacOS cmake command needs two things from `/usr/local/Cellar` e.g.  
`-DCMAKE_CXX_FLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libomp/9.0.0/include". `
I guess we assume that Homebrew is the official way to install MacOS dependencies, but the problem here is that the openssl and libomp versions from Homebrew will change and old versions may eventually be removed, so we better not add `/usr/local/Cellar/openssl@1.1/1.1.1d/` and `usr/local/Cellar/libomp/9.0.0/` to the CMakeLists.txt in this case.

**Comment by confluence** [comment]
Can we test the change in docker containers?

Are there no generic symlinks to those version-specific Homebrew paths, as suggested [here](https://cmake.org/pipermail/cmake/2016-November/064613.html)?

**Comment by ajm-ska** [comment]
OK. I'll try to test in docker soon.

Thanks for finding that information about Homebrew paths. On MacOS, I see sym-links to the Homebrew installed packages are indeed in `/usr/local/opt` and sim-links to their include directories are in `/usr/local/include` e.g.
```
omp.h -> ../Cellar/libomp/9.0.1/include/omp.h
``` 
Our CMakeLists.txt didn't have a `INCLUDE_DIRECTORIES(/usr/local/include)` line. By adding that line, now a basic `cmake ..` gets past omp.h, but brings us to a slightly different problem:
```
/usr/local/include/uWS/Networking.h:7:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
```
In my customised cmake command I was doing `-I/usr/local/Cellar/openssl@1.1/1.1.1d/include`.

This one is a bit unusual. Somehow there is no link to openssl in `/usr/local/include`. 
In `/usr/local/opt` there is `openssl -> ../Cellar/openssl@1.1/1.1.1d`. But that path full path would be `/usr/local/opt/openssl/include/openssl/opensslv.h`.

So adding `INCLUDE_DIRECTORIES(/usr/local/opt/openssl/include)` works, but maybe it is not the most generic way to do it?

Finally, to handle the linking part, we need to add:
```
LINK_DIRECTORIES(/usr/local/lib /usr/local/opt)
```
After that, a simple `cmake ..` works on MacOS.
