### ISSUE TITLE
back end disconnects on file load error

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-backend#441]
I am having issues where a problem with a file load is leading to a disconnection of the backend.    It would be better if there as a more graceful handling when there is a problem with loading a file.  Better for an error message to be sent to the front end user "File Error", and the backend to stay connected.

**Comment by kswang1029** [comment]
this feels like a backend crash. Which image is it?

**Comment by arusstaylor** [comment]
It is a badly formed hdf5 file on the ILIFU systems.  We discovered after the fact that the file is incorrectly formatted.  

Russ

**Comment by veggiesaurus** [comment]
duplicate of #452
