### ISSUE TITLE
HDF5-IDIA format support

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#45]
As for v1.0, the support of the HDF5-IDIA image format is limited. Need to refine this and utilize its extra dataset to speed up some calculations (histogram, z-profile, etc).

**Comment by pford** [comment]
https://docs.google.com/document/d/1T1T85zvGHy7IsePwztN7SjrMPJ4hQJv8X5ihZKf5XA8

**Comment by confluence** [comment]
I will create separate issues for the individual features and bug fixes.

**Comment by Kechil** [comment]
Turn this into an epic with separate issues.
