### ISSUE TITLE
crash when loading a MIRIAD image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#450]
Possibly due to that we switch to casacore for header processing.
[a.tar.gz](https://github.com/CARTAvis/carta-backend/files/4266942/a.tar.gz)

**Comment by veggiesaurus** [comment]
_all_ MIRIAD images?

**Comment by kswang1029** [comment]
No, this specific one. It works with 1.2.2

**Comment by veggiesaurus** [comment]
Possibly related to #436 ?

**Comment by kswang1029** [comment]
Maybe. Was this a crash too?
