### ISSUE TITLE
performance degradation of images with per-plane-beam

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#46]
test image (on the demo server): SDC335.579-0.292.spw0.line.image 

This test image has a per-plane-beam table. (one beam per channel) Generating its file info via the file browser takes much longer time compared to image cubes with similar sizes. Loading the image also takes much longer time, too.

**Comment by kswang1029** [comment]
Suggest to fix this in v1.2. This might be a casacore issue.

**Comment by Kechil** [comment]
Need to determine whether this is a casacore bug

**Comment by pford** [comment]
Removed estimate, included in Epic estimate.

**Comment by pford** [comment]
This is improved by using the Image object to create the FITS-like header.

**Comment by pford** [comment]
@kswang1029 , for multiple-beam images do you want a list of all beams or the just the beam with the median area?

**Comment by kswang1029** [comment]
For the file info, we need a median size. For beam rendering, we will need a full table.

**Comment by pford** [comment]
Re: performance issue, most CASA images take 4-8 ms for the PagedImage object to be created; this image takes 127 ms.  I do not see any way to create a PagedImage without reading the beams so I marked this as a `casa` issue.  With a recent pull request to refactor the file info, the PagedImage is reused in Frame so loading is much faster.

**Comment by kswang1029** [comment]
@pford Yes, confirmed and the performance is great! 👍 👍 👍

**Comment by kswang1029** [comment]
Now loading cube with per-plane-beam is much much faster than before. Close this issue.
