### ISSUE TITLE
Handling of NaN values during Gaussian smoothing

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#463]
When smoothing, there are a few options for how to handle `NaN` values:
1. Propagate them, so that every pixel that has a `NaN` within its smoothing kernel becomes a `NaN`. This is the route DS9 takes, and it's not a good idea, because you lose a lot of real data around NaNs
2. Suppress them, so that `NaN` pixels are skipped during the smoothing. Only pixels that have _no_ non-`NaN` pixels within its smoothing kernel persist as `NaN`. This is the default behaviour of astropy (see [here](http://docs.astropy.org/en/stable/convolution/) for a detailed discussion on this issue). This is the current approach used in CARTA. 
3. Suppress them, but persist `NaN` values where the original data is `NaN`.

Option 2 is quite nice for _displaying_ an image, because it "recovers" data that is missing due to `NaN`s, and doesn't generate a whole bunch of contours surrounding `NaN` values, as shown in the top image in each set below. However, there's an issue with this approach: it can result in contours that pass through what is originally `NaN` data, which is misleading, as shown in the bottom image in each set below. For block smoothing, since we are effectively reducing the image size, there's no way to implement Option 3, but for Gaussian smoothing, we can put `NaN` values in their original location after smoothing, ensuring that contours never cross a `NaN` value.

@kswang1029 and I have discussed this and settled on changing it to Option 3, but I never got round to it (until today), and thought we should check with @arusstaylor @low-sky and @jott3077 before making this change (does CF not have GitHub?)

### No smoothing (`dev`):
![image](https://user-images.githubusercontent.com/592504/76101995-fcac9e80-5fd7-11ea-9d0d-a72b3065885a.png)
![image](https://user-images.githubusercontent.com/592504/76103214-fb7c7100-5fd9-11ea-8363-f3cc735d8f86.png)

### 4x Block smoothing (`dev`, Option 2):
![image](https://user-images.githubusercontent.com/592504/76103389-4e562880-5fda-11ea-92cc-b92de5045220.png)
![image](https://user-images.githubusercontent.com/592504/76103308-249d0180-5fda-11ea-9a9c-d244fc67a11b.png)

### 4x Gaussian smoothing (`dev`, Option 2):
![image](https://user-images.githubusercontent.com/592504/76101770-a0497f00-5fd7-11ea-92c2-f925d7672bd0.png)
![image](https://user-images.githubusercontent.com/592504/76103705-cc1a3400-5fda-11ea-969b-d00be53c08c4.png)

### 4x Gaussian smoothing (`angus/issue_463`, Option 3):
![image](https://user-images.githubusercontent.com/592504/76102040-0f26d800-5fd8-11ea-992d-d7fb2fe0bb1a.png)
![image](https://user-images.githubusercontent.com/592504/76103180-ebfd2800-5fd9-11ea-9389-f440102e83a8.png)

**Comment by low-sky** [comment]
I think this is a good compromise position; I'm happy with Option 3.  Users who want Option 2 should probably process the images themselves to interpolate across the NaN data.
