### ISSUE TITLE
[question] logging ICD message history in verbose mode

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#475]
Currently when verbose mode is enabled, the log seems not providing sufficient information when the backend crashed (well, it is seg fault but it is not trivial to see which step caused the crash). I am wondering if it is possible to log all ICD messages in the log as well? @veggiesaurus @pford @ajm-asiaa

**Comment by Kechil** [comment]
Multiple verbosity levels?

**Comment by kswang1029** [comment]
possibly one level for logging messages and another level for performance timers.

**Comment by kswang1029** [comment]
@markccchiang could you help on getting this implemented for v1.4?

**Comment by kswang1029** [comment]
@veggiesaurus other requirements from server point of view are needed. Please help to address those.

**Comment by veggiesaurus** [comment]
I think the main thing we need from logging is a number of verbosity levels and support for tags. [Boost.log](https://www.boost.org/doc/libs/1_73_0/libs/log/doc/html/log/tutorial/formatters.html) provides that, as well as a fair amount of other nice things (automatically rotating log files, etc). We could also use it to eventually have optional integration with something like syslog.

I’m not sure that just logging ICD messages is helpful other than in the most verbose log level

**Comment by markccchiang** [comment]
So we have a log file with a fixed maximum size. In a log file, we have a tag for ICD messages, a tag for performance (like elapsed time for some expensive calculations), and the other tags if we are interested. Is that the way?

**Comment by veggiesaurus** [comment]
> So we have a log file with a fixed maximum size. In a log file, we have a tag for ICD messages, a tag for performance (like elapsed time for some expensive calculations), and the other tags if we are interested. Is that the way?

Yes. Messages can have multiple tags, so they can be ICD, performance, etc and also tagged with the class they're emitted from

**Comment by markccchiang** [comment]
Besides Boost.log, another popular tool is [spdlog](https://github.com/gabime/spdlog). It seems this library also fits our requirements. Will choose one of them for implementation.

**Comment by veggiesaurus** [comment]
Spdlog looks good. Does it support multiple tags?

**Comment by markccchiang** [comment]
> Spdlog looks good. Does it support multiple tags?

I think yes. Users can define a custom format via [this way](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting). Spdlog is a lightweight package and easy to use, compared to Boost.log. But Boost.log has many functionalities. I may try Spdlog first and see if it works fine. BTW, where are we going to save the log file? CASA viewer's log file is saved in a user's home directory. Or just save the log file in the same directory where the executor is?

**Comment by veggiesaurus** [comment]
We currently log to the CARTA/logs folder, but we may need to allow this to be changed by a command line parameter

**Comment by veggiesaurus** [comment]
Spdlog uses fmt underneath, so it would be easy to change our code to use that

**Comment by kswang1029** [comment]
if someone installed the desktop version on a server and made an alias for all other users, how are the log files managed? All log files go to the same place?

**Comment by markccchiang** [comment]
Yes. They will go to the same log file. But I guess this is not the condition we would expect.

**Comment by veggiesaurus** [comment]
> if someone installed the desktop version on a server and made an alias for all other users, how are the log files managed? All log files go to the same place?

It should go to the users home directory (i.e. $HOME/CARTA/log)

For the server version we will use /var/log/carta. But this would need to be a command line argument

**Comment by veggiesaurus** [comment]
> Yes. They will go to the same log file. But I guess this is not the condition we would expect.

No, the default location should be based on the home directory of the user running the application
