### ISSUE TITLE
Improve performance: load image to cache

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#478]
From #95, to improve the performance of loading image file to the cache. There we have the testing results, which might give us some hints. The elapsed time was measured by https://github.com/CARTAvis/carta-backend/blob/084bbf2bbb0094599220808ce730a2518ee08bb0/Frame.cc#L703-L716

Configuration:
4 tbb threads and 32 OMP threads on server with 32 physical cores
We disabled the hyper threading and set the number of physical core as CARTA configuration on server to avoid the unstable result. Testee image file: cube_A_xxxx_z00001.fits, which stores a single channel image and where “xxxx” denotes image size e.g. 1600, 3200.

The image is read from Lustre to client server, thus there will be a disk cache in server RAM. This process, load image to cache, will make a carta cache after the disk cache is ready. We here will measure the elapsed time 1) whenever the disk cache is ready and 2) while the pagecache is disabled to avoid an unstable factor in the data transmission from Lustre to the client server. 
In the first test, the following results were collected above ten trials after several dry runs because the pagecache is enabled.
![Load with cache](https://user-images.githubusercontent.com/10767557/79180171-cfa3a500-7e3b-11ea-87b2-cc8484bdfeef.png)(With pagecache)
In the second test, we turned off the pagecache functionality to avoid bias. Here applied the [tool](https://github.com/svn2github/pagecache-management) to forbid the functionality of pagecache.
![Load without cache](https://user-images.githubusercontent.com/10767557/79180233-fe218000-7e3b-11ea-8dde-609d04189c6d.png)(Without pagecache)

The performance is estimated in unit mega pixels per seconds (MPix/s). The results for “load image to cache” are stable because of a low standard deviation. We estimated here the performance in pixels per second to normalize the factor of image size. The time complexity of this process approaches N. Most part of this process is in a single thread and there are a few steps in the multiple threads just after the carta cache is ready. A best performance happens for the images in size of 12800x12800. The performance rank is CASA>FITS>HDF5. This process can be benefited from the pagecache. The RAM usage is exactly the image size, which meant no cache issue. The CPU usage starts from single core to all cores at maximum but finished as about ten cores.

Replace testee image file to cube_A_xxxx_z00100.fits, which a stacks multiple channel image. We here will measure the elapsed time while the pagecache is disabled.
![load wo cache N channel](https://user-images.githubusercontent.com/10767557/80183399-5c6c1100-863b-11ea-9837-db69cc8b79c5.png)
This result shows that a few performance reduce for small images. There is no significant difference between the cube image and single-plane image in a large size. 

Todo:
Will update the test for HDF5 after the code with mipmap functionality being merged.

**Comment by kswang1029** [comment]
@zarda few questions:
1) how many times did you repeat the test?
2) did you clear system cache for each image before repeating this test?
3) what kinds of images do you use for this test? Just one channel or multiple channel? I think we need both
4) could you also include HDF5 format as well?
5) loading image is single thread or multi-thread?
6) what are the ram usages in the test?

**Comment by zarda** [comment]
1. at least ten times per result (fixed)
2. will clear cache. (done)
3. single channel (fixed)
4. tested HDF5 (done)
5. most part of this process is single thread (more description)
6. will do

**Comment by kswang1029** [comment]
Would the results be the same if cubes are used in this test? ie image with multiple channels.

**Comment by veggiesaurus** [comment]
> 1. at least ten times per result (fixed)
> 2. did not clear cache. (changed method)
> 3. single channel (fixed)
> 4. tested HDF5 (done)
> 5. most part of this process is single thread (more description)
> 6. will do

if you're not clearing the cache between each run of the test, you're severely biasing the results.

**Comment by zarda** [comment]
supposed that the efficiency of disk cache from Lustre doesn't depend on this codes so that I only measure the elapsed time from the disk cache to carta cache.
will disable the functionality of disk cache and re-test this item.

**Comment by zarda** [comment]
tested the condition with/without pagecache.
![Load w cache](https://user-images.githubusercontent.com/10767557/79085986-1f676b00-7d6d-11ea-9457-197f455061e4.png)
Applied the [tool](https://github.com/svn2github/pagecache-management) to forbid the functionality of pagecache.
![load wo cache](https://user-images.githubusercontent.com/10767557/79085990-20989800-7d6d-11ea-9154-0d956e6bca9e.png)
the pagecache benefits this process.

**Comment by zarda** [comment]
Updated for the question from @kswang1029 : will the result be different for the image with multiple channels?
This result shows that a few performance reduce for small images. There is no significant difference between the cube image and single-plane image in a large size.

**Comment by kswang1029** [comment]
Should have some differences. Could you visualize the differences? By how much % are they?

**Comment by zarda** [comment]
Single channel image to multiple channel image, the difference in percent is labeled on plot.
![Load casa](https://user-images.githubusercontent.com/10767557/81165453-971f6300-8fc4-11ea-985a-a8e500f3134e.png)
![Load fits](https://user-images.githubusercontent.com/10767557/81165802-304e7980-8fc5-11ea-9ff5-17d056d5045f.png)
![Load hdf5](https://user-images.githubusercontent.com/10767557/81165465-9b4b8080-8fc4-11ea-9978-6f21fba37ad4.png)

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
