### ISSUE TITLE
Improve performance: calculate min/max value

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#479]
From #95, to improve the performance of calculate min/max value. Here are some testing results, which might give us some hints. The elapsed time was measured by https://github.com/CARTAvis/carta-backend/blob/084bbf2bbb0094599220808ce730a2518ee08bb0/Region/RegionStats.cc#L75-L88
Configuration:
4 tbb threads and 32 OMP threads on server with 32 physical cores
We disabled the hyper threading and set the number of physical core as CARTA configuration on server to avoid the unstable result. Testee image file: cube_A_xxxx_z0001.fits, which stores a single channel image and where “xxxx” denotes image size e.g. 1600, 3200. In practice, the following results were collected above ten trials after several dry runs.

This process runs in multiple threads. There is no need to calculate min/max value for HDF5.
![Calculator_all](https://user-images.githubusercontent.com/10767557/78546526-26075700-7830-11ea-8ac7-19a907540bb9.png)
The performance is estimated in unit mega pixels per seconds (MPix/s). The performance results for “Calculate min/max value” shows us that a better efficiency happens for large images. The performance in CASA is better than FITS.

**Comment by kswang1029** [comment]
@zarda for casa image 51200x51200, how much time does it take? <1s? 
51200**2/1E6 = 2621Mpix. In the chart, the speed is ~3200Mpix/s. So it takes ~0.8s to get min and max?

**Comment by zarda** [comment]
Yes, the process  spent about 0.8 seconds for the image in size of 51200x51200. [casa](https://docs.google.com/document/d/12r1nIGocxt-mjPAXtJhg_t8oBq7CCwnrA_o7t54rlgQ/edit?usp=sharing)

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
