### ISSUE TITLE
improved file navigation support

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#48]
Currently, CARTA's top level directory is $HOME, which means files not stored in this subdirectory are inaccessible, unless a symbolic link is created. 

- [ ] The top level directory the root directory, in order to ensure that users can access any files in their filesystem
- [ ] The _default_ directory should be either $HOME or $PWD. Support for default directories will have to be added to the frontend, to make sure the frontend requests the correct directory
- [ ] Once a file is opened in CARTA, the file browser should open in the same directory the next time the user opens a file (this may require some testing. For example, what happens if the directory no longer exists?) This will also need some minor frontend changes

**Comment by pford** [comment]
Testing with carta-backend-ICD-tests FILEINFO.test.ts and GET_FILELIST.test.ts.

**Comment by pford** [comment]
Requirements document:
https://docs.google.com/document/d/10RKx6jtxrsf6tqhovGYRoH3r2K7p7S_3o7OIyORku10

**Comment by kswang1029** [comment]
Verified with the v1.0.1 packages.
