### ISSUE TITLE
Improve performance: fill image histogram

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#480]
From #95, to improve the performance of filling the image histogram. Here is the testing result, which might give us some hints. The elapsed time was measured by 
https://github.com/CARTAvis/carta-backend/blob/084bbf2bbb0094599220808ce730a2518ee08bb0/Frame.cc#L1075-L1116

Configuration:
4 tbb threads and 32 OMP threads on server with 32 physical cores
We disabled the hyper threading and set the number of physical core as CARTA configuration on server to avoid the unstable result. Testee image file: cube_A_xxxx_z0001.fits, which stores a single channel image and where “xxxx” denotes image size e.g. 1600, 3200. In practice, the following results were collected above ten trials after several dry runs.

This process runs in multiple threads. HDF5 file contains image histogram as well.
![Fill_all](https://user-images.githubusercontent.com/10767557/78622914-fc464280-78b8-11ea-8320-d9fa211e9486.png)
The performance results for “Fill image histogram” shows that a better efficiency happens for large images. The performance for CASA is better.

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
