### ISSUE TITLE
Improve performance: get tile data group

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#481]
From #95, to improve the performance of getting tile data group. Here are some testing results, which might give us some hints. The elapsed time was measured by 
https://github.com/CARTAvis/carta-backend/blob/084bbf2bbb0094599220808ce730a2518ee08bb0/Frame.cc#L781-L812
Configuration:
4 tbb threads and 32 OMP threads on server with 32 physical cores
We disabled the hyper threading and set the number of physical core as CARTA configuration on server to avoid the unstable result. Testee image file: cube_A_xxxx_z0001.fits, which stores a single channel image and where “xxxx” denotes image size e.g. 1600, 3200.

![GetTile](https://user-images.githubusercontent.com/10767557/78637164-6c19f480-78dc-11ea-9318-1abd13555634.png)
The running time depends the image size for the CASA and FITS files.

**Comment by kswang1029** [comment]
it is MPix per second per core or else?

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
