### ISSUE TITLE
backend crashes when creating a region on a single channel image while the spectral profiler is launched

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#487]
v1.3 bug report from https://github.com/CARTAvis/carta/issues/13

to reproduce,
1) load a single channel image
2) enable spectral profiler widget
3) create a region and the backend will crash

Update: if before 3) we select "cursor" in the region dropdown, the backend will survive for cursor but if we switch to "active", the backend will crash. Not sure if this is a frontend issue instead.

Update: if the image is W x H the backend will crash. However, if the image is W x H x 1 or W x H x 1 x 1, the backend will survive. Thanks @veggiesaurus for spotting this.

**Comment by kswang1029** [comment]
I suggest we have a patch (v1.3.1) for this once fixed.

**Comment by veggiesaurus** [comment]
This occurs when the frontend requests a spectral profile from a region of a 2D image (but does _not_ occur when requesting a spectral profile from a `W x H x 1` image. 

The crash seems to occur in `casacore::LCExtension::region()` (line 162). Here's the stack fromt he crash in the `dev` branch:

```
casacore::LCExtension::region() const LCExtension.h:162
carta::Region::XyMask() Region.cc:937
Frame::FillSpectralProfileData(std::function<void (CARTA::SpectralProfileData)>, int, bool, bool) Frame.cc:1289
Session::SendSpectralProfileData(int, int, bool, bool) Session.cc:1111
SpectralProfileTask::execute() OnMessageTask.cc:104
<unknown> 0x00007f4173a9009d
<unknown> 0x00007f4173a89816
<unknown> 0x00007f4173a88158
<unknown> 0x00007f4173a84710
<unknown> 0x00007f4173a8491d
start_thread 0x00007f4171400669
__GI___clone 0x00007f4170f97323
```
@pford can you look into this? We could work around this by not adding spectral profiles to the requirements messages of 2D files, but we really shouldn't have a hard crash in the backend

**Comment by veggiesaurus** [comment]
My guess  is it's failing to create an extended region because the image is 2D.

**Comment by pford** [comment]
I assume it's acceptable to simply reject (not set) the spectral requirements in the backend?

**Comment by veggiesaurus** [comment]
> I assume it's acceptable to simply reject (not set) the spectral requirements in the backend?

Yes, I think that should be fine.

**Comment by veggiesaurus** [comment]
@pford can you do a PR for `dev` as well?
