### ISSUE TITLE
Improve performance: contour & smooth

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#490]
From #95, to improve the performance of contouring & smoothing. There we have the testing results, which might give us some hints. The elapsed time of contouring was measured by
https://github.com/CARTAvis/carta-backend/blob/e2d2f355ee93a4125df0f57661230b2de2b7b2ce/Contouring.cc#L215-L245

Configuration:
4 tbb threads and 32 OMP threads on server with 32 physical cores
We disabled the hyper threading and set the number of physical core as CARTA configuration on server to avoid the unstable result. Testee image file: cube_A_xxxx_z0001.fits, which stores a single channel image and where “xxxx” denotes image size e.g. 1600, 3200. Generator: min-max-scaling, N = 5, scaling: linear, and smoothing: gaussian with factor = 4.
![contour_all](https://user-images.githubusercontent.com/10767557/78856757-271bcc80-7a5a-11ea-8f0c-da73f0ceef8c.png)
The performance results are independent of size in the process of “contouring”. The CPU usage is high but only 5 cores are used only.

The elapsed time of gaussian smoothing was measured by
https://github.com/CARTAvis/carta-backend/blob/e2d2f355ee93a4125df0f57661230b2de2b7b2ce/Smoothing.cc#L108-L160

![smooth_all](https://user-images.githubusercontent.com/10767557/78856992-c3de6a00-7a5a-11ea-8732-f44b65d62ad2.png)
The performance for large images is even in the process of “Smoothing”. The CPU usage is always high and all cores are running because this process runs in multiple threads.

**Comment by veggiesaurus** [comment]
Contouring is split per level, which explains the limit to 5 cores. If we were to take a tiled approach to contouring, it would allow for better CPU usage. But both contouring and smoothing will tend to be heavily memory bandwidth limited.

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
