### ISSUE TITLE
Add mip and range to spectral and spatial profile requests (backend)

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#491]
I am currently integrating support for several new HDF5 schema features (mipmaps and chunked datasets) into the backend. These features allow us to use much less memory when loading large files. However, a drop in the performance of spatial profiles has become the major outstanding sticking point.

For HDF5 files which have these schema features, we no longer cache an entire full-resolution channel (unless we need to calculate contours) or downsample data on demand. Instead, we load precalculated downsampled data from mipmap datasets, or load tiles of full-resolution data as they are needed. Recent tiles are stored in an LRU cache so that they can be reused.

This works pretty well for rendering the image view. However, to calculate spatial profiles, we need a full row and column of tiles. For very large images, when the view is zoomed out all the way, small changes in cursor position translate to large distances in the image, which cross tile boundaries and thus require frequent reads of new tile data from the file. This adds a very large delay to the spatial profile widget which cannot easily be mitigated -- whether we abort calculations for old positions when the cursor moves, or allow some of them to be completed, we display data with a considerable lag, which is confusing and makes the widget feel very unresponsive.

I think that we could improve this by allowing the backend to send approximate profiles (which could be produced much more quickly, for example by being read from mipmaps) in addition to the slower, exact profiles. I understand that there are important differences between the exact profiles and their approximations, but I believe that displaying approximate profiles for the current cursor position, as a preview, would feel more responsive and intuitive than displaying exact profiles with a lag. The frontend could render approximate profiles slightly differently, for example with a paler line colour, to indicate that they are approximate. We could also perhaps delay saving data from the widget until we have received an exact profile.

A possibility is to add a `mip` field to the `SPATIAL_PROFILE_DATA` message. It would be up to the backend to send both approximate and exact profiles, or just exact ones, depending on the file format and the situation. Nothing would need to change for FITS and other formats.

**Comment by kswang1029** [comment]
Just a quick thought: if we show approximate profiles first then show exact profiles when cursor stops moving for a certain amount of time (200ms?), we could use the screen resolution of the profile chart to decide which layer of tiles is needed to extract approximate profiles. Note that currently, before rendering profiles, the frontend applies decimation to the full profiles based on the screen resolution of the chart.

**Comment by kswang1029** [comment]
Another (crazy) thought, is it possible to predict/extrapolate the movement of cursor to preload tiles for approximate profiles?

**Comment by confluence** [comment]
I think @veggiesaurus has a similar suggestion, which I will leave up to him to describe. I was looking at this as additional optional information driven by the backend, but perhaps it makes more sense for the frontend to request certain things depending on the user behaviour.

**Comment by veggiesaurus** [comment]
> Just a quick thought: if we show approximate profiles first then show exact profiles when cursor stops moving for a certain amount of time (200ms?), 

This was the suggestion I was about to write up. It similar to what we've discussed before, in order to reduce network usage with large files, so it wouldn't be specific to HDF5. 

> we could use the screen resolution of the profile chart to decide which layer of tiles is needed to extract approximate profiles. Note that currently, before rendering profiles, the frontend applies decimation to the full profiles based on the screen resolution of the chart.

This gets a _little_ tricky because different widgets might have different sizes, but I guess that might be an appropriate solution. If there are multiple widgets, we'd use the highest resolution one. We could also use the current FoV of the spatial profile viewer to limit the spatial profile request to a subset of the entire image. 

After the cursor comes to a stop for a certain period of time (200 ms, 500 ms, whatever we decide is an appropriate delay), it could then send another `SET_CURSOR` message, but this time with a request for full resolution data.

I know @arusstaylor has complained about spatial profile performance when viewing large files over poor internet connections, this would make a big difference in that regard

**Comment by kswang1029** [comment]
In v1.0 we use downsampled image data for profile preview (no additional data transfer from the backend) when cursor is moving and full resolution profile comes in from the backend after a stop of 200ms. Now we have tile data, is it possible to do the same like v1.0?

**Comment by veggiesaurus** [comment]
> In v1.0 we use downsampled image data for profile preview (no additional data transfer from the backend) when cursor is moving and full resolution profile comes in from the backend after a stop of 200ms. Now we have tile data, is it possible to do the same like v1.0?

It would require a lot of work, but possible. Although it would be difficult to de-couple the cursor updates for spatial profiles from those of the spectral profiles.

**Comment by confluence** [comment]
I think that the solution which is conceptually simplest to implement is the frontend making requests for profiles with a particular resolution / sample size. At least on the backend side; this would require the frontend to add logic for determining what resolution is needed. But perhaps that is the most sensible place for that logic.

The backend would then either downsample data from the channel cache (FITS) or read from a mipmap (HDF5) to produce a profile at the desired resolution.

For simplicity of integrating this with existing downsampling logic I would suggest that we use a downsampling factor for the number of samples as well, instead of using a different scale.

**Comment by veggiesaurus** [comment]
> I think that the solution which is conceptually simplest to implement is the frontend making requests for profiles with a particular resolution / sample size. At least on the backend side; this would require the frontend to add logic for determining what resolution is needed. But perhaps that is the most sensible place for that logic.
> 
> The backend would then either downsample data from the channel cache (FITS) or read from a mipmap (HDF5) to produce a profile at the desired resolution.
> 
> For simplicity of integrating this with existing downsampling logic I would suggest that we use a downsampling factor for the number of samples as well, instead of using a different scale.

yes, a power-of-two downsampling factor and a start-end range would be sufficient I guess.

**Comment by confluence** [comment]
I have converted this into the companion backend issue to [this frontend issue](https://github.com/CARTAvis/carta-frontend/issues/955).
