### ISSUE TITLE
Usage monitor: CPU & RAM

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#493]
From #95, report carta backend CPU & RAM usage.
Option:

1. repeating update single or series data over time  as verbose is on.
2. report until event as verbose is on, e.g. heavy compute or memory allocate.
3. report single or series data until requested from frontend.

**Comment by veggiesaurus** [comment]
Why not just use a tool specially designed for this?

**Comment by zarda** [comment]
Yes, Valgrind, for example, is a powerful checker for memory issue offline.
Besides, I suppose to have an easy monitor for user,
![Screen Shot 2020-04-15 at 15 39 15](https://user-images.githubusercontent.com/10767557/79310934-47063100-7f2f-11ea-864b-2d60722e26a2.png)

or to get a report coupled with an event or function for programmer.

**Comment by veggiesaurus** [comment]
`perf` is also handy for determining what's actually taking up that CPU time, and is integrated very nicely into a number of IDEs (e.g. CLion)

**Comment by zarda** [comment]
@veggiesaurus 
I tried to use perf to get CPU usage, like the 'top' gives us. Is there any trick to get the CPU usage of one function inside CARTA while the backend is running? I ran 'perf record -g' and 'perf report -g --show-cpu-utilization -n' to get CPU usages, which doesn't like the common usage I know. Or maybe I use wrong way.
My purpose is to get the usage to make a benchmark for a bottleneck function.

**Comment by veggiesaurus** [comment]
> I tried to use perf to get CPU usage, like the 'top' gives us. 


I've never used perf like that. I've always used it in sampling mode. The sampling process itself increases CPU usage, but it allows you to see the relative CPU usage between functions when you view the results. This is best done with a GUI-based tool. Either an IDE or one of the standalone perf frontends

**Comment by kswang1029** [comment]
close for now until we devote time on performance test.
