### ISSUE TITLE
truncated header values in the hdf5 images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#494]
we see values are truncated in the FILE_INFO_RESPONSE.fileInfoExtended.headerEntries of an HDF5 image.
![Screen Shot 2020-04-15 at 9 13 36 PM](https://user-images.githubusercontent.com/20819712/79341392-4e90fe80-7f5e-11ea-8abc-4fb6ade7d399.png)
and in fits format it should be
![Screen Shot 2020-04-15 at 9 14 04 PM](https://user-images.githubusercontent.com/20819712/79341420-581a6680-7f5e-11ea-9ecc-785276759a88.png)

This is considered as a critical bug as position offset (CRVAL1 and CRVAL2) and frequency offset (CRVAL3) are introduced.

**Comment by confluence** [comment]
This should be fixed in #496. The default precision used by `std::ostringstream` to format floats is too low. I have set it to 13, which appears to match the precision used in FITS headers.

**Comment by kswang1029** [comment]
Confirmed!
