### ISSUE TITLE
support sorting of catalog table

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#500]
When users click the column head in the catalog table, sorting should be applied to the catalog.
If no filter is applied, sorting should be applied to _all_ data and backend delivers partial data of the sorted ones.
If there is filter applied, sorting should be applied to the _filtered_ data and backed delivers partial data of the filtered and sorted ones.

related to frontend issue https://github.com/CARTAvis/carta-frontend/issues/878

**Comment by markccchiang** [comment]
The backend logic is to sort `all` data once the sorting column name is set by users. So I think whether the filter is applied or not, it won't change the results.

**Comment by kswang1029** [comment]
Then we will need to support that. That is, for example, if there are 200 data out of 2000 survived after a filter is applied, when users click the column head, the backend should sort those "200" data then deliver partial results.
