### ISSUE TITLE
[spatial profiler] incorrect backend xy profiles

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#51]
Open set_Gaussian2D/hugeGaussian80k.fits. When the image is successfully displayed, move cursor to get the full-resolution spatial profiles. 

Is it memory leakage?
![screen shot 2019-01-07 at 3 01 44 pm](https://user-images.githubusercontent.com/20819712/50753715-daad7400-128d-11e9-9a3d-e7ba9f51d87d.png)
 

![screen shot 2019-01-07 at 3 45 12 pm](https://user-images.githubusercontent.com/20819712/50755258-755c8180-1293-11e9-867b-41b67429bb6c.png)

**Comment by veggiesaurus** [comment]
the fact that the issue occurs with an 80k x 80k image, and not a 40k x 40k image suggests that it's related to indexing the image aray (_N_ = 2^32.6 for 80k x 80k) with a 32-bit integer, rather than a 64-bit integer.

**Comment by kswang1029** [comment]
@pford Thanks for fixing this issue. Verified 👍 and close this issue.
