### ISSUE TITLE
Cannot import ICRS regions to FK5 image

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#528]
Importing ICRS regions into an FK5 image results in a backend error message:  `The error message when using CRTF or DS9 region files is Unsupported coordinate frame for regions ICRS`

Steps to reproduce:
1. Open an ICRS image
2. Create some regions
3. Export regions in either CRTF or DS9 format, with world coordinates. These will get exported in ICRS
4. Open an FK5 image
5. Import created regions

Will leave it up to @kswang1029 to decide whether this counts as critical or not. It doesn't result in a hard crash, but as far as I can see, there's no workaround for getting the regions into an FK5 image, short of manually converting them to FK5 elsewhere.

**Comment by kswang1029** [comment]
Hmm this indeed causes bad UX. The only possible solution is to manually modify the region text file with correct world coordinates at a specific reference system. Not very critical though. I suppose when wcs region is in place, this should be solved. For example, a region file in galactic coordinates could be applied to few matched images with different coordinate systems such as FK5, Ecliptic, etc).

**Comment by veggiesaurus** [comment]
> I suppose when wcs region is in place, this should be solved. 

I'm not sure that will fix the issue. This occurs when loading a single set of regions onto a single open image. 

Am I misunderstanding the issue? It seems like quite a fundamental limitation (not being able to load ICRS regions onto anything other than ICRS images)

**Comment by pford** [comment]
This is thrown by imageanalysis code (Annotations/AnnotationBase.cc).  When the region coordinates must be converted because the file frame (_directionRefFrame) does not match the image coordinate system (_csys) frame, only the following types are supported:

	if (_directionRefFrame != _csys.directionCoordinate().directionType(false)
		&& _directionRefFrame != MDirection::B1950
		&& _directionRefFrame != MDirection::B1950_VLA
		&& _directionRefFrame != MDirection::BMEAN
		&& _directionRefFrame != MDirection::DEFAULT
		&& _directionRefFrame != MDirection::ECLIPTIC
		&& _directionRefFrame != MDirection::GALACTIC
		&& _directionRefFrame != MDirection::J2000
		&& _directionRefFrame != MDirection::SUPERGAL) {
		throw AipsError(preamble + "Unsupported coordinate frame for regions "
			+ MDirection::showType(_directionRefFrame));
	}

**Comment by veggiesaurus** [comment]
what is `MDirection::DEFAULT`? Isn't ICRS _the_ standard when it comes to coordinate systems? Seems odd that it's missing :thinking:

**Comment by pford** [comment]
Default is J2000.  Dave said ICRS is not on the list because it wasn't in the requirements at the time.  I will add it and recompile casacore and see what happens.

**Comment by pford** [comment]
My simple test (add ICRS to the list of accepted frames) worked, will submit a CASA pull request.

**Comment by pford** [comment]
CASA ticket CAS-13074 is waiting for validation.

**Comment by veggiesaurus** [comment]
@pford what's the state of this?

**Comment by pford** [comment]
Still in testing.  I sent an email to Ryan and pinged the validation lead in the ticket.

**Comment by pford** [comment]
This should be complete when carta-casacore is updated to include the ICRS fix.  A quick test on my branch was successful.

**Comment by pford** [comment]
carta-casacore PR 11 under review includes this fix.

**Comment by kswang1029** [comment]
confirmed that with https://github.com/CARTAvis/carta-casacore/pull/17, region files with the coordinate system as ICRS in ds9 format and casa format (crtf) can be loaded in CARTA successfully.
