### ISSUE TITLE
Remove deprecated TBB features

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#531]
https://www.threadingbuildingblocks.org/docs/help/index.htm#reference/appendices/deprecated_features/cpp_obsolete/atomic_cls.html

Warnings when building backend for:
- tbb/atomic.h
- tbb/mutex.h
- tbb/task_scheduler_init.h
- tbb/tbb.h (contains deprecated functionality)

For example:
/usr/include/tbb/mutex.h:21:140: note: #pragma message: TBB Warning: tbb/mutex.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.

**Comment by veggiesaurus** [comment]
`task_scheduler_init`  is the tricky one to replace, I think :thinking:  The other ones can be replaced trivially by `std::atomic` and `std::mutex`

**Comment by veggiesaurus** [comment]
Assigning this to @robsimmonds because his `tbb-be-gone` branch should solve this.
