### ISSUE TITLE
Support Different dimensionalities of Stokes data

### ISSUE THREAD

**Issue by low-sky** [CARTAvis/carta-backend#535]
Current, CARTA's polarization widget targets visualization of 4D Stokes data cube with axes Lat, Lon, Freq, Stokes.  There are other dimensionalities of Stokes data used in the community:

1. 3D Stokes image (Lat, Lon, Stokes)
2. 4D Stokes image (Lat, Lon, Freq, Stokes) **Implemented**
3. 2D Stokes Image set (Lat, Lon) x (I, Q, U, V)
4. 3D Stokes Image set (Lat, Lon, Freq) x (I, Q, U, V)

Now that we can append images, CARTA (likely backend) should be able to Load/Append a set of images, associate them with the Stokes parameters (or read from Header information) and serve them into the Stokes widget for visualization.

For example, if we have three files of the same region that have matched RA, Dec, Freq axes corresponding to Stokes I, Q, and U, we should be able to:

1. Load the Stokes I image
2. Append the Stokes Q and U images
3. Use the Stokes widget with the I, Q, U data coming from the separate images

**Comment by arusstaylor** [comment]
Perhaps we could go a step further re the Stokes widget.  It would be nice to be able to register the image that is used for determing the RA,DEC of the Stokes profile.  This would allow for example to load a 2D "continuum" Stokes I image as the reference for the x,y of the profile, I, Q, U profiles.

**Comment by kswang1029** [comment]
related to #611

**Comment by kswang1029** [comment]
Consider this is done? With 2.0, we can use the file browser to select multiple Stokes images and load them as a single Stokes hypercube.

**Comment by kswang1029** [comment]
Consider this is done.
