### ISSUE TITLE
HDF5 load error as use URL command

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#537]
Reproduce:
http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev&folder=set_QA_performance/cube_A&file=cube_A_01600_z00100.hdf5

http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev&folder=set_HDF5&file=cluster_04096.hdf5

Issue:
There is no issue while loading image using UI operation to load HDF5 files. But we have a trouble while using URL command to load HDF5 images.

**Comment by veggiesaurus** [comment]
@confluence can you look into this? It might be related to the fact that when loading from URL directly, we don't first fetch file info

**Comment by confluence** [comment]
Will do.

**Comment by confluence** [comment]
These are two different errors. The second "file does not exist" error is not a bug; there isn't a `cube_A` subdirectory in `set_HDF5`.

I will look into the other error.

**Comment by confluence** [comment]
This is caused by incorrect handling of the default empty HDU value in the backend. I recently encountered a related issue in the scripting wrapper.

**Comment by confluence** [comment]
This should be fixed now.
