### ISSUE TITLE
position offset seen in exported region

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#541]
sorry I did not catch this in the PR #539 

When we create a rectangle region in CARTA, we see
<img width="1177" alt="Screen Shot 2020-06-18 at 10 06 03 AM" src="https://user-images.githubusercontent.com/20819712/84969650-b248cb00-b14b-11ea-8e2e-a891c391152f.png">

Then we export this region as a casa region text file and import it back. We see
<img width="1175" alt="Screen Shot 2020-06-18 at 10 06 17 AM" src="https://user-images.githubusercontent.com/20819712/84969678-c1c81400-b14b-11ea-90ee-78de57713400.png">

The region file reads as

> #CRTFv0 CASA Region Text Format version 0
centerbox [[00:00:00.23094, +029.59.56.0000], [4.0647arcsec, 1.9307arcsec]] coord=J2000, linewidth=1, linestyle=-, symsize=1, symthick=1, color=green, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false

The offset appears to come from rounding of the center position in pixel. It should be (2.7274940773070684, 1.8217011035674615), but when export-then-import, it becomes (1.9999679327011108, 1.000012755393982). I suspect it could be due to rounding (2.7274940773070684, 1.8217011035674615) to (2, 1) before converting to world coordinates. 

This only happens to rectangle region. Point and ellipse regions are fine. 
Same issue happens when exporting to ds9 region format. 

@pford could you have a look?

**Comment by pford** [comment]
I noticed this while testing, and tracked it down to the world->pixel conversion of the center coordinates using casacore::DirectionCoordinate::toPixel which ultimately calls wcslib wcss2p.  Although the pixel coordinates returned are double values, they are not fractional pixels.

**Comment by kswang1029** [comment]
Is this a casacore/wcslib bug or “feature”?

**Comment by pford** [comment]
Possible solution is to use AST instead of WCSLIB for pixel/world conversion

**Comment by veggiesaurus** [comment]
> Possible solution is to use AST instead of WCSLIB for pixel/world conversion

I think switching to AST might help quite a bit for a number of situations

**Comment by kswang1029** [comment]
To highlight the issue a bit more I have done a controlled test.
Initially we make a set of regions with _easy-to-read_ coordinates via the GUI like the following.
<img width="1563" alt="Screen Shot 2021-02-22 at 1 19 52 PM" src="https://user-images.githubusercontent.com/20819712/108666210-90d98380-7511-11eb-873c-e827d4e2b650.png">
Then we export this region set as region files in different formats.

**world+crtf** 
<img width="1565" alt="Screen Shot 2021-02-22 at 1 28 29 PM" src="https://user-images.githubusercontent.com/20819712/108666385-f299ed80-7511-11eb-9f94-d166367e996c.png">
Region 7~12 are imported regions. They all have errors both in position and size. The errors in point, ellipse and polygon regions are small (milli-arcsecond scale). The error in rectangle is large. 

**world+ds9**
same as world+crtf

**pixel+crtf**
<img width="1564" alt="Screen Shot 2021-02-22 at 1 35 44 PM" src="https://user-images.githubusercontent.com/20819712/108666824-04c85b80-7513-11eb-89b4-36b84f7e9ded.png">
Errors are seen in all imported region, likely due to the precision of the pixel coordinate in the region file (ie %.1f). Following is to visualize the error as seen from the point regions (magenta: original, cyan: imported). 
<img width="935" alt="Screen Shot 2021-02-22 at 1 38 15 PM" src="https://user-images.githubusercontent.com/20819712/108667156-8ae4a200-7513-11eb-9fe9-9828bc0af21f.png">

**pixel+ds9**
same as pixel+crtf although the coordinate precision is %.2f.

For pixel coordinate, I suggest we increase the precision to _minimize_ the conversion error (inevitable) from pixel to world coordinate.

**Comment by veggiesaurus** [comment]
@kswang1029 so do you reckon it's just a matter of numeric string precision? or is it more related to wcslib sticking to whole pixel values?

**Comment by kswang1029** [comment]
I am happy to perform more tests if the backend can have a branch with increased precision in region files. Or please let me know where I can easily change in the code then I can make a local build to test with.

**Comment by kswang1029** [comment]
The problem may be twofold. If it is pixel coordinate definitely we need more precision to minimize the error from pixel to world conversion. If it is in world coordinate, then I remember it seems to use integer pixel index for conversion resulting position offset.

**Comment by veggiesaurus** [comment]
@kswang1029 try branch `angus/test_precision_regions`

**Comment by kswang1029** [comment]
@veggiesaurus we need to have more digits in the region file too when exporting in pixel coordinate. Where in the codebase can I easily modify it for experiments?

> #CRTFv0 CASA Region Text Format version 0
symbol [[119.2pix, 277.7pix], .] coord=J2000, corr=[I], linewidth=2, linestyle=-, symsize=1, symthick=1, color=2ee6d6, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
centerbox [[128.2pix, 118.0pix], [33.3pix, 16.7pix]] coord=J2000, corr=[I], linewidth=2, linestyle=-, symsize=1, symthick=1, color=2ee6d6, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
ellipse [[280.8pix, 277.7pix], [33.3pix, 16.7pix], 0.00000000deg] coord=J2000, corr=[I], linewidth=2, linestyle=-, symsize=1, symthick=1, color=2ee6d6, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
poly [[200.0pix, 240.0pix], [236.0pix, 119.6pix], [276.5pix, 197.9pix]] coord=J2000, corr=[I], linewidth=2, linestyle=-, symsize=1, symthick=1, color=2ee6d6, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false

Frontend needs to provide(?) more digits in pixel coordinate for the backend to have a proper conversion from pixel to world coordinate, right?

**Comment by veggiesaurus** [comment]
> @veggiesaurus we need to have more digits in the region file too when exporting in pixel coordinate. Where in the codebase can I easily modify it for experiments?

I thought I'd caught them all :thinking: @pford would know best I think. 

> Frontend needs to provide(?) more digits in pixel coordinate for the backend to have a proper conversion from pixel to world coordinate, right?

No, frontend is sending the coordinates as doubles

**Comment by pford** [comment]
If the region was created in the image from which it was exported, and the image has direction coordinates, then the backend uses imageanalysis CRTF code for the export.  casa::AnnotationBase::_printPixel(const Double& d) sets the precision to 1.

**Comment by pford** [comment]
The wcslib issue happens when a region in image A is exported in pixel coords from image B:
imageA pixel -> imageA world -> imageB world -> imageB pixel

The final world->pixel conversion done by wcslib returns whole pixel values.
