### ISSUE TITLE
Monocolored image display despite slices showing structure

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-backend#549]
I've loaded an image cube, and it displays semi-successfully, but the main image panel is blank - but the data are clearly fine, since the profile tools show signal.

![image](https://user-images.githubusercontent.com/143715/86066020-03579980-ba3f-11ea-9a40-02de5502c074.png)

**Comment by veggiesaurus** [comment]
This looks like a GPU rendering error. Are you using CARTA over VNC or X11-forwarding? If not, what sort of system are you running it on? Could you visit webglreport.com in Chrome from the same machine and paste the output here?

**Comment by keflavich** [comment]
I'm running on xpra, so, yeah, that makes some sense.  I don't think I can even start a browser on this computer.

The ideal solution on this machine is to start a server and access it through ssh tunneling, but it's rh7...

**Comment by veggiesaurus** [comment]
> The ideal solution on this machine is to start a server and access it through ssh tunneling, but it's rh7...

That should be possible on RH7 if you start up the app with the remote flag.

**Comment by keflavich** [comment]
Nice, that's exactly what I needed to know!  However, adding the `--remote` flag seems to have disabled the command-line load function - can I load a file from the cmdline with this approach?  Now I have an active CARTA window on my machine (awesome!), but no filebrowser _or_ file:

![image](https://user-images.githubusercontent.com/143715/86067442-e1f8ac80-ba42-11ea-9e63-0ca905139641.png)

**Comment by keflavich** [comment]
Oh, I see that's not supported:
`Error: Can not open a CASA or MIRIAD image directly if you are also requesting "--remote" mode`

**Comment by keflavich** [comment]
I was able to start a file browser using the shortcut keys `ctrl-O`, but it just hangs:
![image](https://user-images.githubusercontent.com/143715/86067737-8ed32980-ba43-11ea-9942-1e2de2ee30ea.png)

(also, I switched to the dark view mode - thanks for providing that!)

**Comment by veggiesaurus** [comment]
That looks like it's not connecting to the backend correctly. 

When running in remote mode you can specify the file by editing the URL. See here for details: https://carta.readthedocs.io/en/latest/installation_and_configuration.html#command-line-startup

**Comment by keflavich** [comment]
:+1: that's excellent.  Of course, it still doesn't quite work.  I tried to append:
`&file=W51-IRS2_B3_spw0_12M_n2hp.image&folder=/orange/adamginsburg/ALMA_IMF/2017.1.01355.L/imaging_results/`
and two variants, just in case:
`&file=/orange/adamginsburg/ALMA_IMF/2017.1.01355.L/imaging_results/W51-IRS2_B3_spw0_12M_n2hp.image` and `&folder=/orange/adamginsburg/ALMA_IMF/2017.1.01355.L/imaging_results/W51-IRS2_B3_spw0_12M_n2hp.image`, but it didn't load in either case.

No matter what I load, also, the default layout is blank - I'm loading the Cube View preset each time.

**Comment by veggiesaurus** [comment]
How are you connecting? Using an SSH tunnel? If so, are you forwarding both of the required ports? We currently need two ports to be forwarded: the backend runs on one port and the light http server runs on another.

**Comment by keflavich** [comment]
Yep, you nailed it, I didn't realize two ports were required.  Awesome, I now have a cube!

Thanks for walking me through this.  I realize a lot of what you told me is documented [here](https://carta.readthedocs.io/en/latest/installation_and_configuration.html#command-line-startup), but I'm not sure I could've penetrated all of that in finite time without your help.

**Comment by keflavich** [comment]
Uh, another question, along these lines... can I open a *second* file using the web interface?

**Comment by veggiesaurus** [comment]
> Uh, another question, along these lines... can I open a *second* file using the web interface?

I guess you could open it in a new tab, but that's probably not ideal. Is this in order to avoid the slow file browser issue? 

For 1.4, we will actually be including some basic scripting support, so you'd be able to load images either via a python script, or via a new built-in debug scripting dialog.

**Comment by keflavich** [comment]
> I guess you could open it in a new tab, but that's probably not ideal. Is this in order to avoid the slow file browser issue?

Yes.  And because I want to start loading up 3 images at a time: image, model, and residual to do some cube inspection.

Scripted loading would be great.  This process has been... successful, where my attempts with other viewers broadly haven't been, but it is no easy feat.

**Comment by veggiesaurus** [comment]
@keflavich I'm closing this issue, but will create a new issue in the frontend repo for improving the reporting of these sorts of errors. For example, it would have been helpful if the frontend had reported that it had an issue running WebGL, with a list of suggested fixes
