### ISSUE TITLE
save image: backend crash when saving as the casa format if there is no permission to write

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#563]
To reproduce the issue:

1) make sure the user who executes the backend does not have write permission to a certain folder.
2) load an image (small one) and try to save the image in casa format to that non-writable folder.
3) the backend should crash with the message:
Error: Directory: /scratch/images/set_HD163296/test20200728.image does not exist and cannot be created
4) it works fine if we are trying to save the image in FITS format.

**Comment by markccchiang** [comment]
I think it has been solved in the latest commit of #557. @kswang1029 please check that. Thank you!

**Comment by kswang1029** [comment]
Checked. 👍 

Shall we mention "no write permission" in the message? "Can not access the path!" sounds like it cannot "read".

**Comment by markccchiang** [comment]
Ok. Done.

**Comment by veggiesaurus** [comment]
linked to #592
