### ISSUE TITLE
inconsistent 'max' stat in hdf5 spectral profile generation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#571]
In the screenshot, we see different profiles from the same region of different image formats. They are expected to have identical profiles. This happens only in the stat type "max". @zarda and @acdo2002 found this issue from the ICD test ("REGION_SPECTRAL_PROFILE_RECTANGLE" in https://docs.google.com/document/d/15cy03dK0p1OGD5vQtduxNX8gEO-t9rmy5yKPy5z-Ovc/edit#heading=h.57qhgcamorp4). 

<img width="942" alt="Screen Shot 2020-08-03 at 4 12 16 PM" src="https://user-images.githubusercontent.com/20819712/89160832-465bde00-d5a4-11ea-805b-30af8230c99e.png">
<img width="946" alt="Screen Shot 2020-08-03 at 4 12 28 PM" src="https://user-images.githubusercontent.com/20819712/89160842-4b209200-d5a4-11ea-8158-4ea35c2e402e.png">

@confluence could you have a look?

**Comment by veggiesaurus** [comment]
:thinking: the HDF5 file seems to have its max clamped at zero. That's odd

**Comment by kswang1029** [comment]
@zarda could you print out the two profiles here (channel index vs value) ?

**Comment by zarda** [comment]
ok.
The Max profile in CASA:
Float64Array [
      0.006729725748300552,
      0.00971152912825346,
      0.010001501068472862,
      0.010551692917943,
      0.01945009082555771,
      0.010369728319346905,
      0.0073013692162930965,
      0.016142845153808594,
      0.011929483152925968,
      0.0011555807432159781,
      -0.0023696054704487324,
      0.018626390025019646,
      0.023652417585253716,
      0.026994798332452774,
      0.007317899726331234,
      0.0011833782773464918,
      0.005984995514154434,
      0.004887857474386692,
      0.008677548728883266,
      0.014818242751061916,
      0.00997599121183157,
      0.01622902788221836,
      -0.005048169754445553,
      0.0004572080506477505,
      0.004836936481297016 ]

The Max profile in hdf5:
Float64Array [
      0.006729725748300552,
      0.00971152912825346,
      0.010001501068472862,
      0.010551692917943,
      0.01945009082555771,
      0.010369728319346905,
      0.0073013692162930965,
      0.016142845153808594,
      0.011929483152925968,
      0.0011555807432159781,
      **1.1754943508222875e-38**,
      0.018626390025019646,
      0.023652417585253716,
      0.020338332280516624,
      0.007317899726331234,
      0.0011833782773464918,
      0.005984995514154434,
      0.004887857474386692,
      0.008677548728883266,
      0.014818242751061916,
      0.00997599121183157,
      0.01622902788221836,
      **1.1754943508222875e-38,**
      0.0004572080506477505,
      0.004836936481297016 ]

**Comment by veggiesaurus** [comment]
@confluence it's because your starting `max` value is initialised to `FLT_MIN`. It should be `-FLT_MAX`, or to be more C++-ish, `std::numeric_limits<float>::lowest()`. Should be a two or three line change

**Comment by kswang1029** [comment]
confirmed with other images: when stat=max, values < 0 is set to 0.

**Comment by confluence** [comment]
Oh, no. I can't believe it's been like this forever. I will fix it.

**Comment by confluence** [comment]
PR #572 should fix this.
