### ISSUE TITLE
spectral line query: weird line count at different frequency ranges

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#576]
```
Range(GHz)      CARTA.          Splatalogue
345	352.8	FAIL		73135
345	352.9	65770		74022
345	353.0	65626		75003		
345	353.1	FAIL		76044
345	353.2	65340		76941
345	353.3	65202		77880
345	353.4	65067		78799	
345	353.5	64933		79709
345	353.6	64791		80679
345	353.7	64639		81718
```
issues:
1. when frequency range increases, we should have more lines.
2. line count is not consistent with the direct query using the Splatalogue website

is this something to do with the magic number "65535" or "65534"?

**Comment by veggiesaurus** [comment]
> ```
> Range(GHz)      CARTA.          Splatalogue
> 345	353.4	65067		78799	
> 345	353.5	64933		79709
> 345	353.6	64791		80679
> 345	353.7	64639		81718
> ```
> 
> issues:
> 
> 1. when frequency range increases, we should have more lines.
> 2. line count is not consistent with the direct query using the Splatalogue website
> 
> is this something to do with the magic number "65535" or "65534"?

are we consistent with other queries? For example, ones with a much smaller number of lines

**Comment by kswang1029** [comment]
@veggiesaurus yes for example, 345-346 GHz, both gave us 9710 lines.

**Comment by kswang1029** [comment]
@veggiesaurus @duidae I added more test results. Please refer to my initial post.

**Comment by duidae** [comment]
did some experiments:

```
10GHz range:
Range(GHz)      Splatalogue(exported)          Splatalogue
345-352.9          69645		                       74025
345-353.0	  export fail		               75006
345-353.1          export fail                             76048
345-353.2          export fail                             76945
345-353.3          export fail                             77884

5GHz range:
Range(GHz)      Splatalogue(exported)          Splatalogue
345-350              46821                                   46821
350-355              48593                                   48593
355-360              48436                                   48436
360-365              46477                                   46477

```
seems that splatalogue becomes inconsistent & unstable when the query range is too wide(even simply export data from the website, and spectral line widget is depending on the exported data); the curl error also indicates that splatalogue server returns unmatched data size during transferring, downsize to 5GHz usually matches, probably we need to reconsider the range limitation.

**Comment by kswang1029** [comment]
fixed at the Splatalogue service
