### ISSUE TITLE
Re-open image probably uses cache

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta-backend#579]
**System:** Linux, Firefox 79.0-1 via carta.idia.ac.za

**Issue description:** Re-opening CASA image files after re-creation shows the first image not the updated one.

**To reproduce:**
1. Opening a CASA image file in CARTA.
2. Delete the file on the disk.
3. Re-create the CARA image with different image parameters (only tested with same file size).
4. In CARTA: File --> open image will not show the updated file, but the deleted one.

**Workaround:** In CARTA: Before opening the updated image do File --> Close image

**Comment by veggiesaurus** [comment]
@pford is it possible that we're automatically reusing the file because it has the name?

**Comment by veggiesaurus** [comment]
wondering if adding something like a "reload image" entry to the context menu would be a more appropriate way of solving this issue. Changing the raw data of an image while it's open in CARTA seems to be asking for trouble

**Comment by pford** [comment]
There is an underlying casacore table manager which will open the image once and share the same Image object with any threads in the process.  But CLOSE_FILE, sent by the frontend before OPEN_FILE, deletes this object.  It should not be necessary for the user to close the image.

I tried to reproduce this by copying a different CASA image in step 3 to the same name, but the file browser showed the updated size and modified time, and "Open image" in step 4 showed the new image.

**Comment by pford** [comment]
@kswang1029 I cannot reproduce this issue.  Will you try?

**Comment by kswang1029** [comment]
@pford I did some experiments with our dev server with two CASA images with different pixel scales so that they have identical file size. However, following the instructions (for step3 I copy a template image to the test file name.) by @lh-astro I cannot reproduce the issue. 

However, if we use append mode, then we see the issue. I think that is explained by @pford 

> There is an underlying casacore table manager which will open the image once and share the same Image object with any threads in the process. But CLOSE_FILE, sent by the frontend before OPEN_FILE, deletes this object. It should not be necessary for the user to close the image.

I also tried the FITS format and with append mode it works fine without the issue.

**Comment by kswang1029** [comment]
@lh-astro If we use "load" to load an image, all loaded images will be closed first (with the CLOSE_FILE message). This should delete the image object(s) before creating a new one. Could you confirm again with v1.4 the procedure to reproduce the issue? Thanks.

**Comment by kswang1029** [comment]
@kswang1029 to check again

**Comment by jott3077** [comment]
Could this go into an early v3? @kswang1029 mentioned that it would be scheduled for v2, but it seems to be still open and in https://github.com/CARTAvis/carta/issues/45  it is reported still a problem in v2.0

**Comment by veggiesaurus** [comment]
> Could this go into an early v3? @kswang1029 mentioned that it would be scheduled for v2, but it seems to be still open and in [CARTAvis/carta#45](https://github.com/CARTAvis/carta/issues/45) it is reported still a problem in v2.0

if we can find a consistent way to reproduce this, then it should be ok to schedule for the next beta, unless its something inherent in casacore

**Comment by kswang1029** [comment]
temporily add to v3b1 release plan (depending on the issue complexity)

**Comment by pford** [comment]
I spoke to Kumar (on CASA imaging team) about this issue, and he was very puzzled.  He stated that when an existing table is opened in another thread, the table manager will close it in the first thread and reopen in the second thread.  So the second thread should have the new image.

**Comment by pford** [comment]
Tested with tclean script in Append mode, verified that appending an image creates a new Frame, FileLoader, and PagedImage for the new image, but the same tile data is sent from the backend for both images.
