### ISSUE TITLE
hanging tile stream

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#581]
to reproduce the issue with the dev backend + dev frontend
1) load set_HD163296/HD163296_CO_2_1.fits
2) load set_HD163296/HD163296_13CO_2_1.fits
3) load set_HD163296/HD163296_C18O_2_1.fits
4) match them all in xy and z
5) switch to HD163296_CO_2_1.fits (image 0)
6) close it so all matched image becomes unmatched
7) match all image again in xy and z
8) use animator to switch to other channels. The first trial 'may' succeed but the second one will result in hanging tile stream

**Comment by veggiesaurus** [comment]
@kswang1029 here's a frontend script to reproduce the issue reliably:

```
openFile("fits/wcs_spectral_images/HD163296_CO_2-1.fits");
delay(1000);
appendFile("fits/wcs_spectral_images/HD163296_C18O_2-1.fits");
delay(1000);
appendFile("fits/wcs_spectral_images/HD163296_13CO_2-1.fits");
delay(1000);
setActiveFrameByIndex(0);
delay(1000);
closeCurrentFile(false);
delay(1000);
setActiveFrameByIndex(1);
delay(1000);
setSpectralMatchingEnabled($activeFrame, true);
setSpatialMatchingEnabled($activeFrame, true);
delay(1000);
activeFrame.setChannels(50, 0, true);
delay(1000);
activeFrame.setChannels(25, 0, true);
```

What's weird is that it seems the backend is not responding to the `SET_IMAGE_CHANNELS` messages from the frontend:

```
SET_IMAGE_CHANNELS [32] ==>
12:05:59.886 BackendService.ts:820 SetImageChannels {fileId: 2, channel: 25, stokes: 0, requiredTiles: {…}}
12:05:59.886 BackendService.ts:821 

12:05:59.887 BackendService.ts:818 SET_IMAGE_CHANNELS [33] ==>
12:05:59.887 BackendService.ts:820 SetImageChannels {fileId: 1, channel: 59, stokes: 0, requiredTiles: {…}}
12:05:59.887 BackendService.ts:821 
```

(normally there would be a `RASTER_TILE_SYNC` message and `RASTER_TILE_DATA` messages

**Comment by kswang1029** [comment]
and weirdly, at that state, animator works......

**Comment by veggiesaurus** [comment]
@pford it seems to happen after PR #539. Could you look into it please? I suspect it's related to a file being closed.

You can grab the files [here](https://drive.google.com/file/d/111uqgqlDFPVTmMjdHjNBSrq0SLvPogqL/view?usp=sharing).

**Comment by pford** [comment]
@veggiesaurus your instincts were correct, Session was trying to send tiles for the closed file id.  This was one of the few Session message handlers that doesn't check for a valid file id before proceeding.  Fixed in pam/581_hanging_tile.
