### ISSUE TITLE
Change the architecture of moments generation code

### ISSUE THREAD

**Issue by markccchiang** [CARTAvis/carta-backend#586]
Things to do:

- [x] Remove the MomentController and move the MomentGenerator under the Frame
- [x] Move the FileConverter under the Frame
- [x] Keep the file name as a private parameter in the Frame and FileLoader
- [x] Keep the function `ApplyRegionToFile()` as a private function in the RegionHandler
- [x] Apply an `_image_mutex` in the Frame while calculating image moments

Also, the `ImageMoments` should be removed after changes in casa and casacore are done.

**Comment by veggiesaurus** [comment]
@markccchiang since the PR has been approved, I assume this will be a separate PR, not necessarily for the code freeze?

**Comment by markccchiang** [comment]
Yes. I will do it in another PR.
