### ISSUE TITLE
apply region distortion check before applying polygon approximation 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#607]
If we have two matched identical images, slightly different analytics might be derived from an ellipse region due to polygon approximation on the secondary image. We should examine region distortion (by two reference vectors to see if dot product is zero (or smaller than epsilon) and length ratio is the same) and only apply polygon approximation when distortion is not negligible.

**Comment by veggiesaurus** [comment]
@kswang1029 can you determine the exact vectors to test, and then @pford will implement on the backend. 

My initial guess would be to take the vectors _(0, L)_ and _(L, 0)_, where _L_ is the the maximum distance from the center (i.e. the max length or radius).

**Comment by kswang1029** [comment]
I suggest we take three points, center, middle-top, and middle-right, to form two vectors in the _image_ coordinate. In the reference image, the dot product of the two vectors (blue and red) should be zero. Their length ratio (blue/red) is a constant r0.

Now we transform the two vectors to the secondary image in its own image coordinate. Then we compute the dot product and length ratio again. If distortion is negligible, the dot product should be close to 0, and the length ratio should be close to r0 (we can compute absolute difference abs(r0-r0'). If the two conditions fit, we don't apply polygon approximation for the analytics on the secondary image. Same distortion check should be applied to rectangle region too.
 
<img width="726" alt="Screen Shot 2020-08-22 at 3 31 04 PM" src="https://user-images.githubusercontent.com/20819712/90951332-8cfa7500-e48c-11ea-9b63-0d4c4f9d313e.png">


Would the above make sense to you? @veggiesaurus @pford

**Comment by veggiesaurus** [comment]
> I suggest we take three points, center, middle-top, and middle-right, to form two vectors in the _image_ coordinate. In the reference image, the dot product of the two vectors (blue and red) should be zero. Their length ratio (blue/red) is a constant r0.

That sounds good :+1:

**Comment by veggiesaurus** [comment]
I've unassigned myself to this issue, @pford can you look into this for 2.0?

**Comment by pford** [comment]
> the dot product should be close to 0, and the length ratio should be close to r0

@kswang1029 is there a requirement for "close to"?

**Comment by kswang1029** [comment]
> > the dot product should be close to 0, and the length ratio should be close to r0
> 
> @kswang1029 is there a requirement for "close to"?

1e-4 maybe? We might need some experiments to justify it.

**Comment by pford** [comment]
> two vectors in the image coordinate

@kswang1029 does this mean pixel?  In the Edit Region dialog you can select Image or World coordinates.

**Comment by kswang1029** [comment]
Yes, use vectors in image coordinates for the computations.
