### ISSUE TITLE
moment generator: hdf5 is slower than fits by at least a factor of three

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#608]
When generating moment images with hdf5 format, its performance is generally poor than the fits format by at least a factor of three. In addition, the CPU pattern is quite different from the one of the fits format.

fits:
![fits_output](https://user-images.githubusercontent.com/20819712/90978649-f3ad8a80-e581-11ea-9475-c6e126b99e64.png)
hdf5:
![hdf5_output](https://user-images.githubusercontent.com/20819712/90978652-f6a87b00-e581-11ea-9f99-3c43bf46ddd3.png)

**Comment by veggiesaurus** [comment]
Those two seem to have roughly the same runtime though?

**Comment by kswang1029** [comment]
I cancelled the calculations. Here just demonstrating their cpu patterns are different.

**Comment by confluence** [comment]
What are the steps to reproduce this from the frontend?

**Comment by kswang1029** [comment]
1. go to preference and fix the cursor
2. load an image (same image in two different formats)
3. launch the spectral profile widget
4. click the "M" button at the top-right corner
5. click the "Generate" button and the moment calculations should start.

**Comment by veggiesaurus** [comment]
I wonder if it's trying to process things in small 512x512 chunks. It would be useful to see if the performance changes with unchunked HDF5 files

**Comment by confluence** [comment]
I'm going to add a flag to the converter to force contiguous layout; this may come in useful later for performance tests when we merge the tile and mipmap PR.

(Just in a branch; this may not make sense as a long-term feature.)

**Comment by confluence** [comment]
The converter branch is [here](https://github.com/idia-astro/cpp_hdf5converter/tree/confluence/chunks-optional). Use the `-c` flag to force contiguous layout. To verify that the layout is what you expect it to be, use `h5dump -H -p -d 0/DATA your_file_here.hdf5` and check the `STORAGE_LAYOUT` property.

**Comment by kswang1029** [comment]
@confluence thanks for the new convertor. I generate a new set of test images accordingly (1000x1000x584, 2.3 GB as FITS).

The estimated time:
FITS: 27s
HDF5 chunk: ~110s
HDF5 nochunk: 39s

Looks like it has something to do the chunks.

UPDATE with another measurement:
FITS: 22s
HDF5 chunk: 99s
HDF5 nochunk: 35s

**Comment by confluence** [comment]
Right. So it may be possible to change the way that the casacore code iterates over the chunked data, so that it doesn't use an inefficient slice shape.

**Comment by veggiesaurus** [comment]
> @confluence thanks for the new convertor. I generate a new set of test images accordingly (1000x1000x584, 2.3 GB as FITS).
> 
> The estimated time:
> FITS: 27s
> HDF5 chunk: ~110s
> HDF5 nochunk: 39s
> 
> Looks like it has something to do the chunks.
> 
> UPDATE with another measurement:
> FITS: 22s
> HDF5 chunk: 99s
> HDF5 nochunk: 35s

This makes sense: I'd expect the FITS file to be faster than the unchunked HDF5 file, since it's likely that the FITS file will be at least partially cached due to spectral profile requests.

**Comment by kswang1029** [comment]
About cache, in my test I made my cursor frozen initially. Then launched the spectral profiler to show a profile at the cursor position. Then requested moment calculations. So yes I guess these test images are cached differently.

**Comment by veggiesaurus** [comment]
> About cache, in my test I made my cursor frozen initially. Then launched the spectral profiler to show a profile at the cursor position. Then request ed moment calculations. So yes I guess these test images are cached differently.

You'd need to clear the disk cache just before requesting the moment calculation. Even then, casacore might be doing some odd caching

**Comment by veggiesaurus** [comment]
I've just tested with supermosaic.10 (FITS, unchunked HDF5 and chunked HDF5, image size 4224 x 1824 x 222). All three are using a chunk shape of 4224 x 4 (which is a 66 kB contiguous read on a contiguous file). This explains why the chunked files are behaving so poorly: their "nice" cursor shape is not being taken into account properly

**Comment by confluence** [comment]
We fixed a similar problem a while back by implementing the appropriate nice cursor in our casacore-compatible HDF5 image class. Is this another case of missing functionality? What determines the cursor that is used?

**Comment by veggiesaurus** [comment]
@kswang1029 do you know how to check the tile size in a CASA image? Have you tested CASA files as well?

**Comment by kswang1029** [comment]
@veggiesaurus just did the test with casa format. It took 17s.
Regarding the tile size of a CASA image, try (in casa ipython shell)

> ia.open('Oph_A.image')
ia.summary()['tileshape']

the returned value is like

> array([40, 40, 21,  1], dtype=int32)

**Comment by veggiesaurus** [comment]
Should also mention that an entire _image_ moment is a worst-case scenario for a 2D tiled image. If we get this right, the chunked images should generate moments for smaller regions faster than the unchunked files

**Comment by veggiesaurus** [comment]
I've tested supermosaic.10 in FITS, HDF5 (contiguous), HDF5 (512x512 chunks) and CASA, with the `dev` branch and the `angus/moment_cursor_shape` branch. Disk cache cleared between each run, but could not clear the internal CASA cache, so that might account for the speedup there.

## `dev`:

FITS: 46s
CASA: 22 s
HDF5 (contig): 29s
HDF5 (chunked): ~ 6 mins

## `angus/moment_cursor_shape`:

FITS: 49 s
CASA: 42 s
HDF5 (contig): 45s
HDF5 (chunked): 49s

The `angus/moment_cursor_shape` branch basically ensures that the chunk size is taken into account when iterating through the file. There's a clear drop in performance for all formats except chunked HDF5, so it would be best to only apply this to chunked HDF5 file, it seems.

**Comment by veggiesaurus** [comment]
`angus/moment_cursor_shape` can be used as a starting point for one of the assignees (@pford @markccchiang ), but I think we should probably only apply this fix to chunked HDF5 files :thinking: and will need careful testing from @kswang1029 to make sure moments still come out correctly, for full-image and regions.

**Comment by kswang1029** [comment]
any chance to fix this for v1.4? (apply the fix suggested by Angus only to HDF5)

**Comment by veggiesaurus** [comment]
I think this is an essential issue to fix

**Comment by confluence** [comment]
I am going to look at this today -- just making sure we don't all start working on it at once. :)

**Comment by kswang1029** [comment]
addressed with https://github.com/CARTAvis/carta-backend/pull/625
