### ISSUE TITLE
backend support region type: line segment

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#610]
the line segment region can be used for
- spatial profiler
- pv generator

related to https://github.com/CARTAvis/carta-frontend/issues/1149

Requirements doc: https://docs.google.com/document/d/1mE-JeZjczT_GEPfllm-aNWWUZ903wTJy4JurxBq537c/edit#heading=h.pfjlp9m9fqp4

**Comment by kswang1029** [comment]
@pford the frontend implementation of line region is postponed to _early_ v3.0 dev cycle. The backend implementation can still happen in v2.0 if time allows. Otherwise it can be postponed to _early_ v3.0 dev cycle too.

**Comment by kswang1029** [comment]
tagged this as Release 2.0 & 3.0 meaning good to have in 2.0 if time allows, otherwise 3.0 is fine.

**Comment by pford** [comment]
Completed line/polyline region creation, import and export.  Using regions for pV generator (Epic #155) and spatial profiles (no issue created) will be done separately.

**Comment by pford** [comment]
Opened draft PR #771 pending frontend development for testing.
