### ISSUE TITLE
backend crash when closing all images after moment generation and loading a new image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#615]
To reproduce:
1) load an image cube
2) generate a moment 0 image
3) use the image list widget and right click and click "close all image"
4) load the image cube in step 1) again and the backend will crash.

Nothing seems related in the backend log.

update:
this is fixed as part of https://github.com/CARTAvis/carta-backend/pull/606

**Comment by markccchiang** [comment]
I think it has been fixed in the #606. I forgot to erase an image id in the map of moment generators. @kswang1029 please test this branch and see if it is ok.

**Comment by kswang1029** [comment]
this issue is fixed with https://github.com/CARTAvis/carta-backend/pull/606
