### ISSUE TITLE
support exporting a subimage (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#618]
The feature is to be able to export a subimage from the original cube by specifying a rectangle region and a range of channels.

relavent frontend issue: https://github.com/CARTAvis/carta-frontend/issues/1175

Requirement [doc](https://docs.google.com/document/d/1Jpju5UUzyFD98-iTgXomtmmHlfbWSHHokEVPCiA2t3I/edit#)

**Comment by zarda** [comment]
Using the FileLoader::GetSubImage() to chop image or cube, they could works individually. Trying to apply them together but there is a problem.
As we run a new function:
```
bool FileLoader::GetSubImage(
    const casacore::Slicer& slicer, const casacore::LattRegionHolder& region, casacore::SubImage<float>& sub_image) {
    ImageRef image = GetImage();
    if (!image) {
        return false;
    }

    auto temp_image = casacore::SubImage<float>(*image, region);
    sub_image = casacore::SubImage<float>(temp_image, slicer);  // <- stop here
    return true;
}
```
and got
`Error: Slicer error:infer: endResult>=shape`
, which means the given `region` needs to be reshaped.
Otherwise, we interchange the proceeding order:
```
bool FileLoader::GetSubImage(
    const casacore::Slicer& slicer, const casacore::LattRegionHolder& region, casacore::SubImage<float>& sub_image) {
    ImageRef image = GetImage();
    if (!image) {
        return false;
    }

    auto temp_image = casacore::SubImage<float>(*image, slice);
    sub_image = casacore::SubImage<float>(temp_image, region);  // <- stop here
    return true;
}
```
and got 
`Error: Exception: shape of lattice [640, 800, 10, 1] mismatches lattice shape in region [640, 800, 25, 1].`
, which seem to report similar error about channel size.

**Comment by veggiesaurus** [comment]
@zarda perhaps check with @pford?

**Comment by pford** [comment]
Check out RegionHandler::ApplyRegionToFile: 

1. Use Frame::GetImageRegion to apply the region definition to the image to get the region (limit x and y ranges, all channels/stokes)
2. Create a box using Frame::GetImageSlicer (all x/y, limit channels/stokes)
3. Get the intersection of (1) and (2) to create an ImageRegion with all limits (x, y, chan, stokes)
4. Apply the ImageRegion (3) to the image to get the SubImage as in Frame::GetRegionData or Frame::GetRegionStats

So the pieces are mostly already there, you just need to do a slight refactoring to handle multiple stokes in RegionHandler::ApplyRegionToFile and Frame::GetImageSlicer, and move the SubImage code from Frame::GetRegionData and Frame::GetRegionStats to its own function.

**Comment by zarda** [comment]
The cube data could be only resized but the header needs a modification as well.
How do I convert the related information so that the channel reference is correct, 
such as `Image reference coords ` and `Image ref coords (deg)`.

**Comment by kswang1029** [comment]
You can check the moment generator code and the save image code.

**Comment by kswang1029** [comment]
Reference coordinates shouldn’t be changed as there is no reprojection applied.

**Comment by zarda** [comment]
@kswang1029 Please compare the output image to the original file to see if there is any error on the file header so that the z-Matching of channels will be wrong. The output images are `/tmp/M17_SWex_chopped.fits` and `/tmp/M17_SWex_chopped.image`. Thanks.

**Comment by kswang1029** [comment]
@zarda I am not sure what I should be checking as you did not supply sufficient information. 

Instead, the attached images are made with CASA-imsubimage with `box=20,21,56,64` and `chans=4~10` using `M17_SWex.fits`. This means the bottom-left pixel is (20,21) and the top-right corner is (56,64). Channel ranges from 4 to 10.

[tmp.zip](https://github.com/CARTAvis/carta-backend/files/5714637/tmp.zip)

**Comment by zarda** [comment]
I got that the image of FITS has a wrong header for some reason. Will study the code. Thanks.

Here are the list of different parameter:
Wrong header parameters:
```
CRPIX1 = 301.0
CUNIT1 = deg
CTYPE2 = DEC--SIN
CRVAL2 = -1.620277777779E+01
CDELT2 = 1.111111111111E-04
CRPIX2 = 379.0
CUNIT2 = deg
CTYPE3 = VRAD
CRVAL3 = 1.337597140039E+04
CDELT3 = 8.439809908735E+02
CRPIX3 = 1.0
CUNIT3 = m/s

.
.
.
ALTRVAL = 8.675041924585E+10
ALTRPIX = 1.0
```

Correct values from demo file:
```
CRPIX1 = 301.0
CUNIT1 = deg
CTYPE2 = DEC--SIN
CRVAL2 = -1.620277777779E+01
CDELT2 = 1.111111111111E-04
CRPIX2 = 380.0
CUNIT2 = deg
CTYPE3 = FREQ
CRVAL3 = 8.675139618840E+10
CDELT3 = -2.442377011414E+05
CRPIX3 = -3.0
CUNIT3 = Hz
.
.
.
ALTRVAL = 9.999999914171E+03
ALTRPIX = -3.0
```

**Comment by zarda** [comment]
Got an issue: As we pick up a region outside the original image, the backend will crash and get error message:
`Error converting region to file 0: LCPolygon - entire polygon is outside the lattice`

**Comment by kswang1029** [comment]
catch the exception and show the error message on GUI?

**Comment by veggiesaurus** [comment]
> catch the exception and show the error message on GUI?

I suggest we also check for this condition on the frontend before making the request to the backend

**Comment by zarda** [comment]
Suppose there could be a new functionality, which could reject user to create an illegal region, either a check on frontend or backend. How about adding a new issue?

**Comment by kswang1029** [comment]
it is legal to create a region totally outside the image in the view.

**Comment by veggiesaurus** [comment]
> Suppose there could be a new functionality, which could reject user to create an illegal region, either a check on frontend or backend. How about adding a new issue?

There's nothing wrong with creating a region that is entirely out of the image, especially when we're matching multiple images. The issue is rather that we shouldn't allow users to export subimages (or calculate moments) for images when the selected region contains no pixels

**Comment by zarda** [comment]
Got it. There are two solutions
1) We could check the number of pixels of a region on the backend and report an except message when the number is zero.
2) Filter out the regions, which has no pixels, as saving subimage on the frontend.

**Comment by veggiesaurus** [comment]
> Got it. There are two solutions
> 
> 1. We could check the number of pixels of a region on the backend and report an except message when the number is zero.
> 2. Filter out the regions, which has no pixels, as saving subimage on the frontend.

We should do (2) but also catch the exception on the backend

**Comment by zarda** [comment]
From KSW's testing:
Load set_HD163296/HD163296_CO_2_1.image.mom0 [432, 432, 1, 1] and set_HD163296/HD163296_CO_2_1.image.mom1 [432, 432, 1, 1] then match them with the first image as the reference and create a region, the backend will crash when we request a subimage in FITS from the 2nd image using this region. 

```
Error: Exception: shape of lattice [432, 432, 1, 1] mismatches lattice shape in region [432, 432].
... thrown by void casacore::SubLattice<float>::setRegion(const casacore::LatticeRegion &) [T = float] at File: /Users/a10.15/carta-casacore/casa6/casatools/casacore/casacore/lattices/Lattices/SubLattice.tcc, line: 262
```

@pford 
If we apply the region of 1st image on saving 1st image, they are good. But the image being applied on 2nd image will make exception.
As a region for 1st image be cloned for the 2nd image, will it drop the degenerated axis?

`Updated`
If changing the code inside `Region::GetAppliedPolygonRegion()`, from `casacore::IPosition keep_axes(4, 0, 1)` to `casacore::IPosition keep_axes(4, 0, 1, 2, 3)`, there is an error output: `Cannot apply region to file 3: LCPolygon - can only be used as a 2-dim region`.

**Comment by zarda** [comment]
It is a must to extend the shared region upto the dimension of image otherwise the function subimage() will give an exception.
So the workaround is to match the shared region to the object image via casacore::LCExtensive only at this scope.
