### ISSUE TITLE
The build information in the README and the dockerfiles is out of date; the protobuf submodule needs an update

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#619]
* The protobuf submodule needs an update; it's behind the `dev` branch
* The README includes an instruction to check out the `master` branch of the protobuf submodule, which is incorrect for the default `dev` version of the backend
* Some of the dockerfiles are out of date -- for example, the 20.04 dockerfile still has instructions for a source build of `carta-casacore` although a PPA package exists.

I have started a [cleanup branch](https://github.com/CARTAvis/carta-backend/tree/confluence/update-proto-and-readme) for fixing these issues. Please commit changes there.

**Comment by ajm-ska** [comment]
I have updated all the Dockerfiles in the [cleanup branch](https://github.com/CARTAvis/carta-backend/commit/9e3d1556f12e9cdc4bf4ac48c4385c2c48acc726).

They are basically the same as the previously updated ones in [mark/log_messages ](https://github.com/CARTAvis/carta-backend/tree/mark/log_messages) but I have removed `spdlog` installations and changed the carta-casacore installations to our CARTAvis repository (I will re-update mark/log_messages some other time).

I have also changed the main Dockerfile to 20.04 and made it a symlink to `Dockerfiles/Dockerfile-ubuntu-20.04`. I hope it will work.
