### ISSUE TITLE
Dockerhub entry for runable backend

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#620]
Now that the server version has stabilised somewhat, it would be good to create docker files for _running_ the carta-backend directly (not building it). This would allow server maintainers to simply pull the appropriately tagged docker image from Dockerhub (e.g. `docker run carta:v1.4.0 <additional startup arguments>`) in order to deploy the server.

**Comment by veggiesaurus** [comment]
@Jordatious this should help the Pawsey deployment as well (they're wanting to run the backend processes in containers)

**Comment by ajm-ska** [comment]
@veggiesaurus @rwjsimmonds I have created a preliminary Docker container for testing. 

The Dockerfile contains the following: 
```
FROM ubuntu:latest

# Update
RUN \
  apt-get update && apt-get -y upgrade

# Add a non-root user called 'carta'
RUN groupadd -g 1001 carta && \
    useradd -r -u 1001 -g carta carta

# Copy the pre-packaged carta-backend in place
COPY carta-backend /carta-backend
RUN chown -R carta:carta /carta-backend

# Need to source the carta-backend/lib directory
ENV LD_LIBRARY_PATH=/carta-backend/lib:$LD_LIBRARY_PATH
ENV CASAPATH="../../../../carta-backend/bin/../etc linux"

# Copy over the start up script
COPY start.sh /
RUN chown -R carta:carta /start.sh

# Start container as the user 'carta'
USER carta:carta

# Run the start up script by default
ENTRYPOINT ["/start.sh"]
```
I'm not sure if it is necessary or not, but for added security, it does not run as root. I decided to make it run as an internal user called 'carta'.

The "carta-backend" folder is just a pre-packaged ubuntu 20.04 carta-backend. This way the container can build almost instantly and is very small in size.

The start.sh script simply contains:
```
#!/bin/bash

./carta-backend/bin/carta_backend $@
```

It should work something like this:
```
docker run -ti -p 3100:3100 -v $PWD:/container/image/folder ajmasiaa/carta-v140test port=3100 threads=16 base=/container/image/folder root=/container/image/folder
./carta-backend/bin/carta_backend: Version 1.4
Listening on port 5555 with root folder /container/image/folder, base folder /container/image/folder, 16 threads in worker thread pool and 4 OMP threads
```

The `-p 3100:3100` would be the port assigned to the user by carta-node-server. In this case, there would be one backend instance per container. 
(I suppose an alternative way would be running multiple carta-backends in the same container. In that case you need to open a range of ports e.g. `-p 3100-3200:3100-3200`, but it might be a bit more complicated to always have the Docker container running and starting/stopping up backend processes in it).
The `-v $PWD:/container/image/folder` would map the user's directory (e.g. $PWD) inside the container. The carta-backend inside the container would have base/root set as `/container/image/folder`

Each institute could either build the Docker container themselves because it is quite simple (they could just wget the pre-packaged carta-backend, for example), or we supply the container from the Dockerhub. Here is the current test version on Dockerhub:
```
docker pull ajmasiaa/carta-v140test
```

**Comment by Jordatious** [comment]
> @Jordatious this should help the Pawsey deployment as well (they're wanting to run the backend processes in containers)

Are [these](https://github.com/CARTAvis/carta-backend/tree/dev/Dockerfiles) related to building the backend and not running it then?

**Comment by veggiesaurus** [comment]
> > @Jordatious this should help the Pawsey deployment as well (they're wanting to run the backend processes in containers)
> 
> Are [these](https://github.com/CARTAvis/carta-backend/tree/dev/Dockerfiles) related to building the backend and not running it then?

They're for creating an appropriate development environment for building and running the backend.

**Comment by ajm-ska** [comment]
I have created a new Dockerhub entry with a runable backend, exactly as this issue requests. This time it is using the v1.4 release carta_backend: [ajmasiaa/carta_backend_v140](https://hub.docker.com/r/ajmasiaa/carta_backend_v140/tags)

As I mentioned previously, one way to run it is like this:
`docker run -ti -p 3002:3002 -v $PWD:/zzz ajmasiaa/carta_backend_v140 -port 3002 -base /zzz -root /zzz`
In this example, it runs the carta-backend on the default 3002 port, and mounts the current user directory ($PWD) as the starting location of the CARTA file browser. Some thought might be needed as to how to get carta-node-server to run the backend this way, but it should be easy enough.

The above is basically using a pre-packaged carta-backend and casa-data directory copied into a practically empty ubuntu 20.04 container. On Dockerhub, it takes up 145.88MB compressed. If you don't like things done this way, I have made another one too. It is just an extended version of our [Dockerfiles/Dockerfile-ubuntu-20.04](https://github.com/CARTAvis/carta-backend/blob/dev/Dockerfiles/Dockerfile-ubuntu-20.04) where I add in the building of the carta-backend and copying over the start.sh script. All the lib files were installed by apt-get and the PPAs. I was surprised to see that is actually not much larger on Dockhub, only 364.35MB compressed. I have just called it [ajmasiaa/carta_backend_v140_full](https://hub.docker.com/r/ajmasiaa/carta_backend_v140_full/tags) for now. Of course if you agree to this method, we could probably make a new Dockerhub account called "carta" or "cartavis", and use a different name for the containers.

**Comment by veggiesaurus** [comment]
> I have created a new Dockerhub entry with a runable backend, exactly as this issue requests. This time it is using the v1.4 release carta_backend: [ajmasiaa/carta_backend_v140](https://hub.docker.com/r/ajmasiaa/carta_backend_v140/tags)

I think eventually we should aim to have a `carta-backend` package in the PPA (which installs its non-dev dependencies correctly), and then just install that (and the kernsuite `casacore-data` package in an empty ubuntu

**Comment by ajm-ska** [comment]
@veggiesaurus OK, but before that, is the second option that I have shown more acceptable? 
[ajmasiaa/carta_backend_v140_full](https://hub.docker.com/r/ajmasiaa/carta_backend_v140_full/tags)
All lib files were installed correctly from the main repository with apt-get. zfp, uws, casa-data, and carta-casacore were installed with our PPAs. Finally, the carta-backend was built in the same container. Surprisingly this container doesn't appear that big in size.

**Comment by veggiesaurus** [comment]
Yes, I think it's a better approach. I'm not sure how important the container size itself is. I presume only the libraries that are actually utilised will reside in memory

**Comment by ajm-ska** [comment]
@veggiesaurus OK. I deleted the previous "ajmasiaa/carta_backend_v140" and "ajmasiaa/carta_backend_v140_full" test repositories from Dockerhub and have uploaded a new full version renamed to: [ajmasiaa/carta-backend:1.4.0](https://hub.docker.com/repository/docker/ajmasiaa/carta-backend/general)
The tag (1.4.0) indicates the version name. 
(It looks like we could probably automate the process for it to build any new "release" branch versions of the carta_backend)

I also added a brief description in the Dockerhub Readme.

Just to clarify again, this is the "full" version where all library files were installed correctly from the main ubuntu repository with apt-get. zfp, uws, casa-data, and carta-casacore were installed with our PPAs. The carta-backend was then built in the same container and simply runs from it.

I feel this issue has now been solved. We have a "Dockerhub entry for a runable backend" as requested. Do you think we can close the issue now?

**Comment by veggiesaurus** [comment]
@ajm-asiaa I think that should be ok. Should we start a CARTA dockerhub organisational profile?

**Comment by zarda** [comment]
May relate to [#209](https://github.com/CARTAvis/carta-backend-ICD-test/pull/209), we try to make a Dockerfile to deploy on k8s service. This docker will provide the services of both CARTA front-end and back-end.

**Comment by kswang1029** [comment]
@ajm-asiaa any update regarding this?

**Comment by ajm-ska** [comment]
@kswang1029 I'll try to make a Docker container with CARTA v2.0. It should be a bit simpler now that we can use the PPAs for carta-backend.

**Comment by kswang1029** [comment]
ok once this is done and tested we can close this issue

**Comment by ajm-ska** [comment]
We have made a new Dockerfile. It uses the Ubuntu 20.04 Debian packages, starts as a non-root user for security, and calls the `--no_browser` flag by default.

```
FROM ubuntu:focal
# Update
RUN \
  apt update && apt -y upgrade && \
  apt -y install software-properties-common
# Install carta PPA
RUN \
  apt-add-repository -y -s ppa:kernsuite/kern-7 && \
  add-apt-repository -y ppa:cartavis-team/carta && \
  apt update && \
  apt -y install casacore-data carta
# Add a non-root user called 'cartauser'
RUN groupadd -g 1001 cartauser && \
    useradd -r -u 1001 -g cartauser cartauser
# Create the log file directory for 'cartauser'
RUN mkdir -p /home/cartauser/.carta/log/ && \
  chown -R cartauser:cartauser /home/cartauser/.carta/log
# Use the --no_browser flag
RUN \
  mkdir -p /etc/carta && \
  echo '{\n    "no_browser": true\n}' >> /etc/carta/backend.json
# Start container as the user 'cartauser'
USER cartauser:cartauser
# Run the start up script by default
ENTRYPOINT ["/usr/bin/carta"]
```
The resulting Docker container is uploaded to the [cartavis Dockerhub](https://hub.docker.com/r/cartavis/carta).  Usage instructions are mentioned there, but basically you can run it as follows:
```
docker run -ti -p 3002:3002 -v $PWD:/images cartavis/carta:2.0.0 /images
```

Whenever there is a new release, be it v2.0.1 or v2.1.0 etc., we will easily be able to build and upload each new version to Dockerhub.

Now I believe we can close this issue.
