### ISSUE TITLE
hidden axis support

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#629]
as one of NRAO priorities, carta needs to support images with hidden axis. @jott3077 please provide more info here with example images.

**Comment by jott3077** [comment]
That might already be supported. But let me explain. E.g. a cube with RA/DEC/FREQ/Stokes has two hidden axes when looking at an image (usually FREQ and Stokes). They need to be settable for the image to view though, e.g. channel 29 and Stokes U. For movies, three axes are used and one is hidden. If we have animators for all of these then we are good. This would allow to set a hidden axis to a specific value. 
There could be other, additional axes be present, too. But they may be a special case discussed elsewhere (fits extensions may also be present). 
Maybe this is just an exercise to go through CARTA and make sure that all functions can have their hidden (i.e. non-displayed)  axis set at some value.
