### ISSUE TITLE
reduce the progress update cadence of cube histogram calculations

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#640]
Probably due to the previous refactoring of parallelization from TBB to OMP, the progress update cadence of cube histogram calculations now is very high. Updating every 1s should be sufficient.
![Oct-05-2020 17-33-22](https://user-images.githubusercontent.com/20819712/95063655-3346c500-0731-11eb-997a-0d84a124ee08.gif)

**Comment by kswang1029** [comment]
@markccchiang could you help on this issue?

**Comment by markccchiang** [comment]
OK.
