### ISSUE TITLE
global rendering 

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#644]
Add an option to use the same clip min/max rendering, scaling and colormap for all (or a subset of) loaded images.
This is to allow a user to compare two or more images that have only small differences on a common color scale.

**Comment by veggiesaurus** [comment]
@jott3077 is this covered by https://github.com/CARTAvis/carta-frontend/issues/1089 ?

**Comment by jott3077** [comment]
ok, great! feel free to close this ticket then.
