### ISSUE TITLE
Long response time for moment generation

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#651]
_Reproduce_:
Open image "SDC335.579-0.292.spw0.line.image" and lunch a new moment with the parameter: 

axis: SPECTRAL
mask: Include
moments: [0]
pixelRange: {min: 0.1, max: 1}
spectralRange: {min: 2100, max: 2200}

The response was not returned longer than 30 seconds. This functionality works well and sent a correct message.

_Testing_:
The branch `/mark/refactor_moment_generator de94736 5038` on demo server.
 The branch `/dev` on demo server.

**Comment by kswang1029** [comment]
with S255 do you see the same issue? SDC335 is a cube with per-plane-beam and there will be an extra step of doing beam convolution before making moment images. That may be why it needs extra time (thus not an issue/bug)

**Comment by zarda** [comment]
> with S255 do you see the same issue? SDC335 is a cube with per-plane-beam and there will be an extra step of doing beam convolution before making moment images. That may be why it needs extra time (thus not an issue/bug)

For image `S255_IR_sci.spw25.cube.I.pbcor.fits`, testing on the backend `/mark/refactor_moment_generator` the functionality can be done but responding time is longer than 10 seconds.

**Comment by kswang1029** [comment]
did you see S255 needs extra time to report progress? Crashing is a separate issue.

**Comment by zarda** [comment]
After several times of testing on image `S255_IR_sci.spw25.cube.I.pbcor.fits`, the reporting time become about 5 seconds. The extra time for progress may be induced by disk reading.

**Comment by kswang1029** [comment]
S255 does not have per-plane-beam. SDC335 does. We should see some casa log reporting the beam convolution.

**Comment by veggiesaurus** [comment]
@kswang1029 can you compare this to just running the casa task?

**Comment by zarda** [comment]
The image `SDC335.579-0.292.spw0.line.image` is CASA format.

**Comment by kswang1029** [comment]
> @kswang1029 can you compare this to just running the casa task?

@veggiesaurus I tried with two images in the FITS format:
S255: 1920x1920x1917 (uni-beam)
SDC335: 336x350x3840 (per-plane-beam)
and use CASA and CARTA to generate a moment0 image from channel 1000 to 1100. 
The test results are (each obtained with a fresh OS start):
SDC335-CASA: 21s
SDC335-CARTA: 21s
S255-CASA: 16s
S255-CARTA: 11s

Note that with CARTA, we will have to request a spectral profile before requesting moment calculations. So cache might be affecting the test result. However, the the time gap from SDC335 is from beam convolution before moment calculations (as seen in the CASA log). 

@zarda I still suggest you to use other image for the ICD test (not SDC335). There should be some smaller images in set_S255
