### ISSUE TITLE
websocket connection dies when accessing certain directory

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta-backend#659]
I can not access the files in: `/carta_share/groups/mightee/lennart/XMMLSS-target-cubes/`
Using: https://carta.idia.ac.za/ which is version 1.4.0

To me it looks like as if the websocket connection dies when trying to enter this specific directory with the file browser (see screenshot). After accessing that directory and reopening the file browser, no directories are show any more, not even the ones I used to navigate to the problematic one.

**Comment by veggiesaurus** [comment]
@lh-astro can you still reproduce this?

**Comment by lh-astro** [comment]
@veggiesaurus No, can't reproduce it. Everything is working fine atm.

**Comment by veggiesaurus** [comment]
Ok, closing for now. Reopen if it occurs again
