### ISSUE TITLE
handle idle connections

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#660]
Currently, a user can keep a CARTA tab open indefinitely, which would keep the backend session alive. This becomes a problem when they leave it in this idle fashion for a long time with a number of files open, because the process is just sitting there taking up memory.

We should add configurable options to either kill the process after it is idle for a long time, or just kill the idle session. We should also make this idle timeout configurable. If a user's session gets killed, their frontend will immediately reconnect, but will not open files until the user clicks on the "resume" button. Once that happens, the user's files will be reloaded into memory.

This will help the archive and server case quite a bit.

**Comment by kswang1029** [comment]
@markccchiang when you start to work on this issue, please check with @kswang1029 for briefing.
