### ISSUE TITLE
Support UV and pV images

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#663]
These image types occur in all supported CARTA image types (CASA, FITS, HDF5, Miriad).

Adding "requiring_frontend" tag as

    Images with UV coordinates
    pV images

Frontend issue [#1150](https://github.com/CARTAvis/carta-frontend/issues/1150)

**Comment by Kechil** [comment]
@pford please can you estimate this issue?

**Comment by pford** [comment]
@kswang1029 and @veggiesaurus I pushed branch pam/663_pv_uv_images which enables loading PV and UV images.  Please let me know if anything further is needed from the backend for this.

**Comment by kswang1029** [comment]
I tried to generate a pv image with the casaviewer using set_M100/M100_12m_CO_central.image and saved it as M100_12m_CO_central.pv.fits. With the casaviewer, it is rendered as
![Screen Shot 2021-01-07 at 2 25 35 PM](https://user-images.githubusercontent.com/20819712/103859317-d292a400-50f4-11eb-9f6d-be4a63d89ecd.png)
but with CARTA we see a weird pattern such as
![Screen Shot 2021-01-07 at 2 26 27 PM](https://user-images.githubusercontent.com/20819712/103859345-e1795680-50f4-11eb-951b-c3eeaf29125b.png)
It is not related to the compression quality of raster tiles as I have tried 32 and still see the same issue with a different pattern.

The file info derived from the image header has an issue in "Image ref coords (deg)". The unit of the spectral axis is a compound unit but in the header it is just Hz.
![Screen Shot 2021-01-07 at 2 31 27 PM](https://user-images.githubusercontent.com/20819712/103859598-492fa180-50f5-11eb-94b5-c5397ef4a04e.png)
![Screen Shot 2021-01-07 at 2 31 46 PM](https://user-images.githubusercontent.com/20819712/103859613-4fbe1900-50f5-11eb-90d7-8a066e64b322.png)

**Comment by kswang1029** [comment]
With the image set_casaImageVarients/pVimage.image (image from @jott3077), a 3D pv image with offset, stokes, and freq, the loaded axes are not correct (it is offset vs stokes with freq as the iterator in the animator).
![Screen Shot 2021-01-07 at 2 37 38 PM](https://user-images.githubusercontent.com/20819712/103860210-4d0ff380-50f6-11eb-9b11-b76c19fca2c7.png)
![Screen Shot 2021-01-07 at 2 37 55 PM](https://user-images.githubusercontent.com/20819712/103860220-50a37a80-50f6-11eb-8e9e-7d0de3242cd9.png)

**Comment by pford** [comment]
@kswang1029 please try again with the latest commit in the pam/663_pv_uv_images branch.

@veggiesaurus the frontend log gives the ast warning "Problem processing WCS info in file..." for PV and UV images.  Please let me know if any more information is needed from the backend.

**Comment by kswang1029** [comment]
@pford Yes, now the image itself is displayed properly. I will do more tests with other PV images. 👍

**Comment by pford** [comment]
@kswang1029  these images need to support region creation, import, and export, is that correct?

**Comment by kswang1029** [comment]
@pford yes, in image coordinate (pix) only.

**Comment by pford** [comment]
@kswang1029 there is no frontend issue to support UV images.

**Comment by kswang1029** [comment]
@pford sorry I missed it . Please refer to https://github.com/CARTAvis/carta-frontend/issues/1360. Will try to schedule it.
