### ISSUE TITLE
Create CASA LEL images dynamically

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#665]
LEL images are created dynamically. The frontend will have an interface (similar to the CASA viewer) where one can enter the mathematical expression. The frontend will send the expression to the backend, which will create and open the LEL image.

https://casadocs.readthedocs.io/en/stable/notebooks/image_analysis.html?highlight=LEL#Lattice-Expression-Language

Requires [CARTAvis/carta-frontend#1264](https://github.com/CARTAvis/carta-frontend/issues/1264)

**Comment by pford** [comment]
LEL expressions do not work for HDF5 images because casacore::ImageExprParse uses casacore::ImageOpener to test for a valid image name in the expression.  ImageOpener identifies our images as HDF5 but uses casacore::HDF5Image, which fails with the IDIA schema.  There is no  way to work around this in the bison-based parser, and no easy way to implement a parser in CARTA for the complex LEL syntax.  Our options are: (1) do not support LEL for HDF5, or (2) open pull request in casacore to check open function map *first* for casacore-supported images such as HDF5, rather than default to casacore::HDF5Image.

**Comment by kswang1029** [comment]
@jott3077 @veggiesaurus do you think it is okay not to support LEL for the hdf5 format? The new LEL generated cube would need to have meta data, swizzled cube and mip maps. So potentially the LEL cube generation could take a long time compared to other supported image formats

**Comment by pford** [comment]
@kswang1029 the generated image would be casacore::ImageExpr, with HDF5Lattice for data access (if that part works).  But as you point out, this would lose the extra HDF5-IDIA features.

**Comment by pford** [comment]
Correction: ImageExpr saved to CASA format is saved as an LEL image, else as FITS image.  These seem to be the only supported types for SaveFile.

**Comment by pford** [comment]
I just opened a casacore PR to change ImageOpener so that CartaHdf5Image can be used with the ImageExprParser and the parsing succeeds.  With this change installed locally and using TestExprImage, I verified that an LEL expression with an HDF5 image opens as ImageExpr in ExprLoader.

**Comment by pford** [comment]
casacore PR has been merged.  casa6 PR to update casacore is open.
