### ISSUE TITLE
Make carta-backend installable through apt with all dependencies.

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#669]
Aims:

* A single PPA with all CARTA components and dependencies packaged (except specific scientific packages which are already packaged by Kern, e.g. casacore data).
* Separate header and binary packages
* Automatic `dbgsym` packages

This should be part of an epic, together with the corresponding issues in other components.

**Comment by kswang1029** [comment]
shall we close this since v2.0 is out?

**Comment by confluence** [comment]
Yes, we can close all of these (there's also a frontend issue and a controller issue).
