### ISSUE TITLE
allow backend to host static frontend files on same port

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#670]
We need to utilise the new HTTP server features of uWebSockets to serve static frontend files (if found) on the same port. This will allow users to _just_ run `carta-backend` and get a simple single-port solution for remote visualisation. This should remove the need for the "remote" version or the remote flag in the AppImage.

We should display the frontend URL (e.g. `http://localhost:3002`) once the server has been initialised. This will result in a user experience similar to running jupyter-notebook from a terminal, which astronomers are quite comfortable with. For reference:
```
angus@angus-ryzen:~$ jupyter-notebook 
[I 07:58:48.605 NotebookApp] Serving notebooks from local directory: /home/angus
[I 07:58:48.605 NotebookApp] The Jupyter Notebook is running at:
[I 07:58:48.605 NotebookApp] http://localhost:8888/?token=733d04f23175f9b2f3c7bf014bcc583d29e1d02b37f38c06
[I 07:58:48.605 NotebookApp]  or http://127.0.0.1:8888/?token=733d04f23175f9b2f3c7bf014bcc583d29e1d02b37f38c06
[I 07:58:48.605 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:58:48.627 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/angus/.local/share/jupyter/runtime/nbserver-16411-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=733d04f23175f9b2f3c7bf014bcc583d29e1d02b37f38c06
     or http://127.0.0.1:8888/?token=733d04f23175f9b2f3c7bf014bcc583d29e1d02b37f38c06
```

My guess is that we want to check two paths for a `carta-frontend` folder to serve by default: `/usr/local/share/carta` (if the backend is built and installed from source) and `/usr/share/carta` (if the backend is installed via `apt`)

I think we should consider running the HTTP server by _default_ and introduce a `standalone` flag in order to run it without the HTTP server. This should allow us to move closer to the desired approach of being able to simply `apt get install carta` and then run CARTA from the terminal with minimal issues

**Comment by veggiesaurus** [comment]
@confluence please let me know whether you think this approach lines up with your packaging work

**Comment by confluence** [comment]
Regarding the file locations: `/usr/local` should take precedence over `/usr` if they both exist, and there should be a commandline parameter for specifying a custom location.

I agree that the server should be on by default, but the flag should be called something more explicit like `no-frontend` or `no-http-server`. `standalone` is almost as vague as `server`. ;)

It would be nice for the individual desktop case to open the frontend in a browser automatically -- we can decide whether to do this by default and disable it with a flag or vice versa. I'm leaning towards the former because it's how jupyter notebook does it.

**Comment by veggiesaurus** [comment]
@confluence would we just call system("xdg-open http://localhost:3002")?

**Comment by confluence** [comment]
Yes. I don't know what the equivalent is on mac.

**Comment by confluence** [comment]
Apparently there's an `open` command.

**Comment by veggiesaurus** [comment]
Some initial work on this is done in the branch `angus/uuid_token`. 

Example output when running carta-backend with the default arguments:

```
./carta_backend: Version 1.4
Serving CARTA frontend from /usr/local/share/carta/frontend
CARTA is accessible at http://localhost:3002?socketUrl=ws://localhost:3002/token/46dc6e91-0b2a-47be-a37d-56dadb58f2d3
Listening on port 3002 with root folder /, base folder /home/angus/repos/carta-backend/cmake-build-relwithdebinfo, 2 threads in worker thread pool and 4 OMP threads
Opening in existing browser session.
Session 1 (Thu Jan 14 12:38:15 2021): Client 1 [::00:0.0.0.1] Connected. Num sessions: 1
```

The frontend opens up automatically in my default browser (Chrome). In fact, it simply opens in a new tab in my existing session, which is very convenient.

A minor frontend change is required, in order to make use of this new approach. The default socket address should be `http://localhost:3002/token/<token>`, (assuming the frontend is served on port 3002 by the backend, and `<token>` is passed in via a query parameter). After this change, no `socketUrl` argument will be required. The URL would just be `http://localhost:3002?token=46dc6e91-0b2a-47be-a37d-56dadb58f2d3`, which is _very_ similar to the jupyter-notebook approach.
