### ISSUE TITLE
try alternative ports if no port is specified and default port is in use

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#671]
Currently, we default to port 3002. If there's something else (such as another carta-backend process) running on this port, we currently bail out. I propose that after #670 has been implemented, we also automatically try alternative ports, so that users can easily run multiple instances of carta-backend if they absolutely insist on doing so (they really should just be opening multiple tabs in their browser)

Using jupyter-notebook as an example: 

```
angus@angus-ryzen:~$ jupyter-notebook 
[I 08:04:55.573 NotebookApp] The port 8888 is already in use, trying another port.
[I 08:04:55.573 NotebookApp] The port 8889 is already in use, trying another port.
Serving notebooks from local directory: /home/angus
[I 08:04:55.575 NotebookApp] The Jupyter Notebook is running at:
[I 08:04:55.575 NotebookApp] http://localhost:8890/?token=149ba8329501160c9657eccaca73fb943283d0827370a1e3
```

No need for users to manually specify ports or anything.

**Comment by robsimmonds** [comment]
The  node.js controller handles this. Why are we wasting our time with this?

**Comment by ajm-ska** [comment]
I think this functionality would primarily be used by scripting interface, wouldn't it @veggiesaurus? I don't think it would be using the node.js server. The scripting interface would only need to start up a carta-backend (hopefully with an incorporated uwebsockets HTTP server to automatically host its own carta-frontend). Unless I'm wrong?

**Comment by markccchiang** [comment]
From my understanding (current studying result), we can apply `<sys/socket.h>` and check if the port number `3002` is available. If not, we then choose a random port number and repeat the check. Finally, assign the port number which is free, or otherwise return an error.

**Comment by veggiesaurus** [comment]
> From my understanding (current studying result), we can apply `<sys/socket.h>` and check if the port number `3002` is available. If not, we then choose a random port number and repeat the check. Finally, assign the port number which is free, or otherwise return an error.

not a random port, but rather increment from 3002 upwards, I think.

**Comment by veggiesaurus** [comment]
> From my understanding (current studying result), we can apply `<sys/socket.h>` and check if the port number `3002` is available. If not, we then choose a random port number and repeat the check. Finally, assign the port number which is free, or otherwise return an error.

using `bind` seems like a straightforward solution. I wonder if we could also just use `uWS::App::Listen` and check if the returned `us_listen_socket_t*` is null?

**Comment by markccchiang** [comment]
> using `bind` seems like a straightforward solution. I wonder if we could also just use `uWS::App::Listen` and check if the returned `us_listen_socket_t*` is null?

Looks like also the way. I will try it first.

**Comment by markccchiang** [comment]
I have roughly implemented the `uWS::App::listen` to get a free port in the branch [mark/671_try_alt_ports](https://github.com/CARTAvis/carta-backend/tree/mark/671_try_alt_ports). @veggiesaurus and @ajm-asiaa could you please try does it works if you have the time? Thank you!

**Comment by ajm-ska** [comment]
@markccchiang It certainly seems to work! I had one instance running on port 3002 and started another. It starts the second backend on port 3003. The only thing needed now is for the token URL to pick up the incremented port number too (at the moment it is still at 3002)

```
./carta_backend: Version 2.0.0-dev.4
Serving CARTA frontend from /Users/acdc/carta-frontend/build
CARTA is accessible at http://localhost:3002?token=E6CDC598-60E1-4CFD-986A-1D56AACAA815
Listening on port 3003 with root folder /, base folder /Users/acdc/carta-backend/build, 2 threads in worker thread pool and 4 OMP threads
```

**Comment by veggiesaurus** [comment]
> I have roughly implemented the `uWS::App::listen` to get a free port in the branch [mark/671_try_alt_ports](https://github.com/CARTAvis/carta-backend/tree/mark/671_try_alt_ports). @veggiesaurus and @ajm-asiaa could you please try does it works if you have the time? Thank you!

@markccchiang nice work! Shall we move this to a PR? I have a few comments:
- If the user specifies a port, we should not try other ports. We should only automatically find a free port if the port has not been specified.
- We should indicate to the user that we could not listen on port 3002, and are trying other ports
- If we fail to find a free port in the 100 tries, we should report that we were unable to listen on the port range 3002-3103 (not just the last port)
- `ntry` should be something more verbose like `num_listen_retries`

One last question: are we absolutely sure that the callback passed to `uWS::App::listen` _always_ runs synchronously?
edit: I checked the source code, I can't see how it wouldn't, so I'm not worried there
