### ISSUE TITLE
HDF5 cube: no max stat from a single pixel square region 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#674]
If we create a single-pixel square region and request the region spectral profile with different stats, we don't see profiles from  stdDev and max. The former is understandable. The later is unexpected and affects extrema stat as well.

In the stat widget, we do see max but in the spectral profile we see an empty plot.
![Screen Shot 2020-12-11 at 8 54 29 PM](https://user-images.githubusercontent.com/20819712/101905953-2ba11200-3bf3-11eb-9041-c42ceac03547.png)

**Comment by confluence** [comment]
This should be fixed in the current PR.
