### ISSUE TITLE
Investigate implementing asynchronous replies in the gRPC server

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#675]
Handling requests which are expected to take a long time (e.g. requesting rendered image data) requires increasing the global scripting timeout in the backend to something absurd. We could add a customisable timeout, but the correct way to do this is probably to implement the async flag which we already have.

This will require modifications both to the backend and to the wrapper.

**Comment by veggiesaurus** [comment]
closing due to #952
