### ISSUE TITLE
retain spectral convention when saving as a FITS image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#678]
Thanks @zarda to spot this issue.

To reproduce:
1) load the FITS image M17_SWex.fits
2) use the "save image" menu to save the image as another FITS image
3) load the image and check the header. The spectral axis should be in FREQ but the saved FITS is in VRAD.  

Saving as the CASA format does not have this issue.

**Comment by zarda** [comment]
The default value of preferVelocity = True in the Frame::SaveFile(){ casacore::ImageFITSConverter::ImageToFITS(...) }, if we change to false, it will save a unit as frequency for spectral axis.

**Comment by kswang1029** [comment]
For subimage, the spectral convention needs to be the same as the input image (can be as FREQ, VRAD, AWAV, etc) regardless the output image formats.
