### ISSUE TITLE
performance degradation of cube histogram calculations from v1.3.1 to v1.4

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#680]
With same test image and same machine (mac), v1.3.1 takes 57s and v1.4 takes 80s. 

In addition, in v1.4, the progress updating cadence is still a bit too high (1s). Maybe every 2s/5s is better (need some tests).

I guess this is related to https://github.com/CARTAvis/carta-backend/issues/642

**Comment by kswang1029** [comment]
update: the progress update cadence is addressed in #681

**Comment by kswang1029** [comment]
I tried different progress update cadences as 1s, 2s, and 10s, and don't see any changes in the performance. So I guess we can probably rule out the possibility due to the mechanism of progress update.

**Comment by veggiesaurus** [comment]
@kswang1029 any chance this is due to having a different number of threads active?

**Comment by kswang1029** [comment]
with same data and same laptop and same OMP setup (all cores), we see different memory footprints. Left is with v1.3.1 and right is v1.4.0. v1.3.1 is faster in computing the histogram overall!
![Screen Shot 2021-01-21 at 7 06 24 PM](https://user-images.githubusercontent.com/20819712/105343226-4e740c80-5c1c-11eb-9e79-a8803e4edcd5.png)

**Comment by kswang1029** [comment]
@acdo2002 could you test the cube histogram performance using v1.3.1 (electron app), v1.4 (electron app) and `angus/use_histogram_add` built in release mode with a linux box? Please make sure there is no cache affecting the test.

**Comment by acdo2002** [comment]
@kswang1029 I have the backend `v1.4` and `angus/use_histogram_add` on my Ubuntu laptop, does `v1.3.1` refer to the backend `v1.3` release?

**Comment by veggiesaurus** [comment]
> @kswang1029 I have the backend `v1.4` and `angus/use_histogram_add` on my Ubuntu laptop, does `v1.3.1` refer to the backend `v1.3` release?

Yes, the 1.3.1 patch release only had frontend changes, so you can just `git checkout release/1.3` on the backend (and protobuf)

**Comment by acdo2002** [comment]
I run the histogram per cube and per channel with `dev`, `v1.4`, & `v1.3` on Ubuntu linux.
All run with omp_threads/threads=4
per cube:
`dev`: 42.86+-1.1 sec
`1.4`: 44.5+-0.4 sec
`1.3`: 40.14+-0.5 sec
per channel:
`dev`: 4.8+-0.1 sec
`1.4`: 5.1+-0.1 sec
`1.3`: 5.2 +-0.1 sec

I would say there is no significant difference on my laptop ubuntu with different backend version.
Before running each test, I have restart a new backend, clean jest cache, clean disk cache(via sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'), in principle it could has no cache influence.

**Comment by kswang1029** [comment]
sounds like 5-10% slower, roughly same degradation as I see from macOS.

**Comment by kswang1029** [comment]
this is too old and not worth to investigate further. Just need to monitor this with performance regression test.
