### ISSUE TITLE
create example images for compressed FITS files

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#682]

**Comment by kswang1029** [comment]
A set of test images is prepared:
tu2310418.fits.fz : this is retried from [NOAO](http://archive1.dm.noao.edu/search/query/) in the fz format. **13.4 MB**
tu2310418.fits: this is the normal FITS image converted from the fz format via ds9. **89.6 MB**
tu2310418.fits.gz: this is created with gzip using tu2310418.fits. **82.9 MB**
tu2310418.fits.bz2: this is created with bzip2 using tu2310418.fits. **84.8 MB**

[example images](https://drive.google.com/file/d/1goAkFNcjAk1MBTz7gwi2Ep36ZH7Ocuh_/view?usp=sharing)
These test images are also available on the mix n match server at `set_compressed_fits`

**Comment by kswang1029** [comment]
considered done.
