### ISSUE TITLE
session expires with 120sec

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#683]
Situation:
When I run the long-term performance test, I found that the cube_histogram failed with very large images.
Passed: cube_B_04800_z00100.fits -> cube_B_04800_z00100.image -> cube_B_04800_z00100.hdf5
Failed: cube_B_09600_z00100.fits -> cube_B_09600_z00100.image -> cube_B_09600_z00100.hdf5

I wrote a simple typescript to test how long the backend session can be alive without any action. The backend session will automatically disconnect after 120sec (ICD test does not send any close_session request).

This is the main reason why large images in the long-term performance test may fail.
TypeScript requests the sessions for all images at the beginning (I wrote them at the same layer, because it is a for loop). 
If the image is too large (i.e. running time exceed 120sec), the following session automatically close before the test code request the cube_histogram.

This behavior only occurs with the current dev branch, I check the previous dev commit (323c5c8), all tests with large images work fine.
And I know the updated websocket has been merge to the current dev branch, then I ask Mark for help.

Solution: 
After we test few parameters, Mark found this behavior relates to "idle timeout", and then we set idle timeout to 2500 sec in order to make sure the test can be passed with very large image.
Issue solved and Mark will send PR later.

**Comment by kswang1029** [comment]
I am able to spend 6mins to generate the cube histogram from a 60GB cube with the dev+dev branches (mix n match). While a cube histogram is being generated, the backend should constantly update the progress+a partial histogram with a message to the frontend. Did I miss something? Setting the timeout to 2500 s without a proper justification may not be a good idea (and not scalable to even bigger images).

**Comment by kswang1029** [comment]
by launching CARTA with http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev and then doing nothing, I have been staring at the browser for more than 3mins and the session is still alive.

**Comment by veggiesaurus** [comment]
> I am able to spend 6mins to generate the cube histogram from a 60GB cube with the dev+dev branches (mix n match). While a cube histogram is being generated, the backend should constantly update the progress+a partial histogram with a message to the frontend. Did I miss something? Setting the timeout to 2500 s without a proper justification may not be a good idea (and not scalable to even bigger images).

right, this seems like an arbitrary limitation :thinking:

**Comment by acdo2002** [comment]
It only happens in ICD test (at least I don't know how to regenerate the situation with UI). The UI frontend only open one session once, however ICD tests open several session (e.g. 3 images => open 3 sessions at the beginning) at once, then run each image by sequence (the problem always happened in the second large image, not the first one) 

I think the question should be, how big image we would like to test for long-term performance? If ICD test runs cube_B_04800_z00100* as a limitation, then the initial setting would be fine, no further change is needed.

If we would like to run cube_B_09600_z00100* or bigger images, there are two solutions to let the ICD test passed:
(1) adjust the parameter that Mark found
(2) change ICD tests (although they are all passed with previous dev branch including 1.4release backend), let typescript open session one by one with large image (e.g. don't write it with for loop).

**Comment by kswang1029** [comment]
It feels like it is the test script itself causing the problem and not related to the image size, nor the backend codebase. What’s the ws setup in the test script? There should be quite some configurable parameters controlling how ws should behave (eg timeout, data size etc).

**Comment by markccchiang** [comment]
> by launching CARTA with http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev and then doing nothing, I have been staring at the browser for more than 3mins and the session is still alive.

I guess the normal frontend sends a `ping` to the backend regularly, and the backend also responses with a `pong`. Due to this heartbeat mechanism exists, we will not encounter such a timeout problem.

**Comment by acdo2002** [comment]
Today we had a discussion and decided to change the ICD typescript test. 
With wrapping a for-loop & two description boxes, the ICD typescript now can simulate the UI frontend: 
open 1 session - open image - run cube histogram - close 1 session, then open the next session...etc
(i.e. 1 session only for 1 image)
Perhaps we can just keep in mind that if the session opened without any request (without any ping/pong heart beating sequence), it may automatically expire after 120 sec. 

So far there is NO backend modification is needed.

**Comment by veggiesaurus** [comment]
Shall we close this issue then?

**Comment by acdo2002** [comment]
Yes, please close it, thank you very much!!!
