### ISSUE TITLE
Cleanup histogram code

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#696]
(possibly related to #680)

The histogram code needs to be cleaned up a bit. We have a `HistogramResults` struct and a `Histogram` class that could easily be combined. In its current state, it's probably leading to needless copies. We just need a `Histogram` struct with the following:
- a constructor that takes an existing set of bounds and bins (for use with HDF5 files)
- a constructor that takes a min, max, num_bins and a const ref to the data, which it uses to calculate the bins
- a join function for combining multiple histograms of the same size

This could be combined with some sensible histogram unit tests so we know when issues crop up

**Comment by veggiesaurus** [comment]
@jolopezl has pointed out that the current code simply clamps a value's bin to between the first and last bins, even if the value is out of the range of the histogram. This hasn't been an issue yet, because our histograms are automatically calculated using the min and max bounds, but we should adjust this behaviour. @jolopezl suggests we just reject all values outside of the histogram range. I am inclined to agree. @kswang1029 is that ok?

In terms of implementation, it would just be replacing a single `std::clamp` call with an `if/else`

**Comment by kswang1029** [comment]
@veggiesaurus @jolopezl Yes, in the future we should allow users to define 
- bin starting value
- bin width
- number of bins
- (or the alternative as bin starting and ending values, number of bins)
to construct a histogram from a region in the histogram widget.

**Comment by veggiesaurus** [comment]
ok, then @jolopezl please go ahead with just rejecting out-of-bounds values. Could we combine this with the `isFinite` call and just use `if (val >= min_value && val <= max_value)`? (since `NaN >= val` and `NaN <= val` are both false for any finite `val`)

 Would we then not need `std::clamp` at all?

**Comment by jolopezl** [comment]
For keeping the values right, I would change the condition to `if (std::isfinite(val) && _min_val <= val && val < _max_val)` and keep the `std::clamp` to get the bin number. It works fine because it's receiving the integer part so that the upper bound is never reached except for values above the range. Still, we could replace it with an if/else (`std::clamp` implementation is just that) to be sure that we keep an open-bound for the upper limit of each bin and ensure the behavior of `_min_val <= val < _max_val`. Note that I would add `_max_val` as a member of the class for simplicity.

**Comment by veggiesaurus** [comment]
> For keeping the values right, I would change the condition to `if (std::isfinite(val) && _min_val <= val && val < _max_val)` 

If you rearrange those arguments a bit, you can do without the `std::isfinite` call. Why do we need the `std::clamp` if we've already checked the range above?

@kswang1029 I'd imagine we want inclusive bounds, right?

**Comment by kswang1029** [comment]
@veggiesaurus If I understand the usual histogram calculation right, per bin it is bin_lower <= x < bin_upper and only the last bin is bin_lower <= x <= bin_upper.

**Comment by veggiesaurus** [comment]
> @veggiesaurus If I understand the usual histogram calculation right, per bin it is bin_lower <= x < bin_upper and only the last bin is bin_lower <= x <= bin_upper.

it's that last `<= bin_upper` that I'm referring to.

**Comment by jolopezl** [comment]
Hi @kswang1029, @veggiesaurus, let's agree on the upper bounds. As far as I have seen before, bin limits are usually semi-open, see for example [boost histogram](https://www.boost.org/doc/libs/1_70_0/libs/histogram/doc/html/histogram/getting_started.html) and [CERN's ROOT histograms](https://root.cern.ch/doc/master/classTH1.html#binning). On the other hand, Matplotlib's histogram has closed bounds for the upper limit.

This choice plays a minor negligible systematic for large datasets, and we should just make a decision and stick to it. 

I prefer semi-open bounds. For instance, an unlikely and corner case example: if you ever want to join histograms with different start and end bin ranges and same bin width, the merge could be consistent.

**Comment by veggiesaurus** [comment]
> Hi @kswang1029, @veggiesaurus, let's agree on the upper bounds. As far as I have seen before, bin limits are usually semi-open, see for example [boost histogram]
> I prefer semi-open bounds. For instance, an unlikely and corner case example: if you ever want to join histograms with different start and end bin ranges and same bin width, the merge could be consistent.

The most common case for us is to use the min and max values of the image as our bounds. If we have semi-open bounds, it would mean that we would _always_ reject at least one pixel (the one with the max value), wouldn't it? kvis and DS9 both use closed ranges for histograms for this reason

**Comment by jolopezl** [comment]
> > Hi @kswang1029, @veggiesaurus, let's agree on the upper bounds. As far as I have seen before, bin limits are usually semi-open, see for example [boost histogram]
> > I prefer semi-open bounds. For instance, an unlikely and corner case example: if you ever want to join histograms with different start and end bin ranges and same bin width, the merge could be consistent.
> 
> The most common case for us is to use the min and max values of the image as our bounds. If we have semi-open bounds, it would mean that we would _always_ reject at least one pixel (the one with the max value), wouldn't it? kvis and DS9 both use closed ranges for histograms for this reason

Fair enough. We keep then the histogram bounds closed and bins semi-open as they are defined now.
