### ISSUE TITLE
Inconsistency of region spectral_profile_data for CARTA.StatsType.Extrema in HDF5 cube

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#707]
Situation: 
This issue only occurs in HDF5.

If I select a very small rectangle region (just covers 1 pix) in *.hdf5, then request the region spectral profile and click Statistic: StdDev, it returns NaN (after fp64 decode) and the spectral profile widget shows nothing (see below).  
![single-pixel-hdf5](https://user-images.githubusercontent.com/34430648/106554359-23f84c80-6556-11eb-9817-aefa61e0029c.png)

*.fits and *.image return 0, which is more make sense to us. Because single pixel only have 1 value, the stddev should be zero (i.e. sqrt( (1 value - mean(1 vale))/1)) (see below).

![single-pixel-fits](https://user-images.githubusercontent.com/34430648/106554232-e72c5580-6555-11eb-9df6-0b114b450568.png) 

The statistic widget is correct and other CARTA.StatsType types all work fine in spectral profile.

**Comment by kswang1029** [comment]
this should not be a problem in general. Users should know what stddev means when there is only one pixel. 

As for consistency I don’t have strong opinion.

**Comment by acdo2002** [comment]
Yes, it is not a big issue. For a region contains many pixels, *.hdf5, *.image, and *.fits are all consistent :)

Please let me know whether you would like to fix this issue (for a consistency)? or decide to leave it as NaN?
Because it may influence the my ICD test implementation...

**Comment by veggiesaurus** [comment]
I think@confluence should fix it. It's probably a very easy fix 🙂

**Comment by confluence** [comment]
@acdo2002 please confirm that #708 fixes this, and approve the PR if yes.

**Comment by acdo2002** [comment]
Sorry the socketdev server is failed now, so I use another server to test it. 
Yes, now it works very well. Thank you very much!!!
![single-pixel-hdf5-update](https://user-images.githubusercontent.com/34430648/106573612-d17a5880-6574-11eb-9ff8-53453c9e2f61.png)
