### ISSUE TITLE
JSON-based config support

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#716]
We need to add support for system- and user-based config files for the backend. We already use JSON for the frontend and carta-node-server configurations, and JSON schema allow us to easily validate things.

The backend should look for a system config file in `/etc/carta/backend.json`, and a user config file in `~/.carta/backend.json`. We should also allow a command-line parameter `no_user_config` parameter to disable the user config (useful for the server use case). This will leave us with 4 sources of settings:

0) default settings
1) system config file
2) user config file
3) command-line arguments

In terms of precedence, anything specified in (3) should override (2). Anything specified in (2, 3) should override (1). The only exception being the `no_user_config` argument, which will always disable (2). One nice way to handle this is by storing the resultant settings as a JSON object, formed by merging multiple JSON sources. We'd need a JSON object for the defaults and the command-line arguments.

I suggest we use the modern and widely used [nlohmann/json](https://github.com/nlohmann/json) header-only package for this. It's easily installable on ubuntu, centOS (as `json-devel`) and homebrew. I think we'd need to support both versions 2 and 3, though, since ubuntu bionic has version 2.1..1, rather than 3.7.3 in focal.

We should have a well-defined JSON schema for the backend configuration. This will make it easier to ensure that our config files are valid, and we can also use it to generate documentation (we've done this for carta-node-server).

This feature would really benefit from extensive unit tests to ensure that the correct options get set when using various config sources.

**Comment by confluence** [comment]
I have previously expressed my concerns about users hand-editing JSON. I think that this can be mitigated if we have an option to generate a default / example config file, perhaps accessible through a flag to the backend, and include this when we package the backend (not in the location which activates it; as `/etc/carta/backend.json-example`, or something like that).

JSON doesn't natively support comments (although there are dialects / parsers that do). `nlohmann/json` has them disabled by default, but it's possible to enable C-like comments. It may be useful to allow this for hand-editable config files, but it may affect interoperability if they ever need to be parsed or written by another library (e.g. in future it may be useful to have a UI for editing this file in the frontend). Also, trailing commas are not allowed in JSON, which can make selective commenting tricky.

Despite my reservations, I think that if we're already using JSON for all our other configuration files, it would be good to be consistent.

I think that the override hierarchy that you have described makes sense.

**Comment by veggiesaurus** [comment]
I'm also open to the idea of adding the dependency as a simple github submodule, allowing us to use the same version across all platforms and simplify dependencies. They have instructions on this approach [here](https://github.com/nlohmann/json#embedded).

**Comment by jolopezl** [comment]
> We should have a well-defined JSON schema for the backend configuration. This will make it easier to ensure that our config files are valid, and we can also use it to generate documentation (we've done this for carta-node-server).

I want to discuss this part here, aside from the pull-request, since it needs another placeholder. I defined the following JSON schema for the backend configuration:

```JSON
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Backend preferences",
    "description": "Schema for CARTA backend preferences (Version 1)",
    "$id": "carta_backend_preferences_1",
    "required": [],
    "properties": {
        "verbosity": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "default": 4
        },
        "no_log": {
            "type": "boolean",
            "default": true
        },
        "log_performance": {
            "type": "boolean",
            "default": false
        },
        "log_protocol_messages": {
            "type": "boolean",
            "default": false
        },
        "no_http": {
            "type": "boolean",
            "default": false
        },
        "no_browser": {
            "type": "boolean",
            "default": false
        },
        "host": {
            "type": "string",
            "minLength": 1,
            "default": "0.0.0.0"
        },
        "port": {
            "type": "integer",
            "default": 3002
        },
        "grpc_port": {
            "type": "integer",
            "default": -1
        },
        "omp_threads": {
            "type": "integer",
            "default": -1
        },
        "top_level_folder": {
            "type": "string",
            "minLength": 1,
            "default": "/"
        },
        "frontend_folder": {
            "type": "string",
            "minLength": 1,
            "default": ""
        },
        "exit_timeout": {
            "type": "integer",
            "default": -1
        },
        "initial_timeout": {
            "type": "integer",
            "default": -1
        },
        "idle_timeout": {
            "type": "integer",
            "default": -1
        }
    },
    "additionalProperties": false,
    "oneOf": []
}
```

I would add what's missing, modify it according to your suggestions, and then place it where it's appropriate. We can also open a pull-request for commenting on this inline, maybe that's the right thing to do.

**Comment by veggiesaurus** [comment]
@jolopezl some of those fields don't make sense for a system/user config. In particular: `help`, `version` and `files`.

**Comment by jolopezl** [comment]
> @jolopezl some of those fields don't make sense for a system/user config. In particular: `help`, `version` and `files`.

Good point. I just edited the schema above. We can follow this up at https://github.com/CARTAvis/CARTAvis.github.io/pull/8.
