### ISSUE TITLE
Move message handling code to a separate class

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#744]
`Main.cc` is currently far too large, and has a variety of responsibilities. The majority of message-handling code can be moved to a new class `SessionManager`

**Comment by veggiesaurus** [comment]
Increasing to 2 because we need to extract some of the code from `Session` that manages the exit timeouts (previously done with static variables)

**Comment by pford** [comment]
We have FileListHandler and RegionHandler, should they be Manager instead for consistency?  Or is there a difference between "managing" a Session vs "handling" a file list request or region request?

**Comment by veggiesaurus** [comment]
> We have FileListHandler and RegionHandler, should they be Manager instead for consistency? Or is there a difference between "managing" a Session vs "handling" a file list request or region request?

That's a good question. I do sort of feel like the region requests and file list requests are handled rather than managed, whereas the sesssion manager should manage all incoming requests, creating and deleting sessions when necessary. I'm open to counterarguments though :smile:

**Comment by confluence** [comment]
This was closed in #923.
