### ISSUE TITLE
cannot read one line of header in hdf5

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#747]
When we check the image "M17_SWex.hdf5" Header, we realize there is a line in fileInfoResponse.fileInfoExtended['0'].headerEntries shows
{ value: "1", entryType: 2, numericValue: 1 }.

We expect to see every attribute has its own name (like other lines in the Header):
{ name:"XXX", value: "1", entryType: 2, numericValue: 1 }

from carta header, you can see there is one attribute cannot render:
![hdf5-header-name-missing](https://user-images.githubusercontent.com/34430648/109165787-ed110180-77b6-11eb-84f7-0c5da3d23b67.png)

I check the result with executing `h5dump -H M17_SWex.hdf5`, it constrains the missing attribute could be 

>       ATTRIBUTE "EXTEND" {
>          DATATYPE  H5T_STD_U8LE
>          DATASPACE  SCALAR
>       }
(I match each attribute, only "DATE", "EXTEND", and "ORIGIN" has no match with carta Header. However only "EXTEND" has no string data inside the attribute, which is consistent to what we see on the missing attribute "1")

I put "M17_SWex.hdf5"  on google [drive ](https://drive.google.com/drive/folders/1qj53HcB_6KNjQcxWM_gKhwh0ybqNXmFI?usp=sharing). Or going to [carta-backend-ICD-test](https://github.com/CARTAvis/carta-backend-ICD-test) code:public/set_QA/M17_SWex.hdf5.zip, there also provides the image we tested (hdf5 converter version 0.1.13).

**Comment by confluence** [comment]
Yes, I think this is triggered by the `EXTEND` keyword, and also the `BLOCKED` keyword in certain files. A casacore error message is logged for this. I will see if I can figure out what the problem is.

**Comment by confluence** [comment]
The issue is that we are storing boolean values as integers in HDF5 (because HDF5 doesn't really have a boolean type). For some reason our special case for detecting booleans is working for `SIMPLE` but not the other headers.
