### ISSUE TITLE
Log adjustments

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#751]
Some small adjustments to the logging code:

* Change the level of performance messages to debug
* Log performance to a separate file
* Flush logs regularly
* Flush logs before exiting
* Misc. refactoring

**Comment by kswang1029** [comment]
Shall we make performance log more concise?

**Comment by confluence** [comment]
@kswang1029 What did you have in mind? I see that we have some entries like `Fill spatial profile in 0.11900000000000001 ms`; we can fix that with better float formatting.

**Comment by kswang1029** [comment]
I remembered we have one log per tile generation not one log per generation of all tiles. Do you think it is worth to make it concise?

**Comment by kswang1029** [comment]
Contours seem to behave the same

**Comment by confluence** [comment]
I'll have a look; it may be a good idea.

**Comment by confluence** [comment]
This is going to be at the debug level now, though, so it's OK for it to be verbose.

**Comment by veggiesaurus** [comment]
> This is going to be at the debug level now, though, so it's OK for it to be verbose.

Yes, that's true. But logging performance per tile will affect performance itself (it's inside a parallel for)

**Comment by confluence** [comment]
Ah. Then I will try moving it.
