### ISSUE TITLE
Catalog data stream stopped after first return 

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-backend#758]
https://user-images.githubusercontent.com/22226157/109909406-49669c00-7c63-11eb-8938-19a13117a423.mp4

**Comment by kswang1029** [comment]
could this be due to uWS update?

**Comment by kswang1029** [comment]
@markccchiang could you investigate this?

**Comment by markccchiang** [comment]
> @markccchiang could you investigate this?

Ok.

**Comment by markccchiang** [comment]
This problem can be solved if I enlarge the max backpressure for the uWebSockets. Say, setting `.maxBackpressure = 256 * 1024 * 1024`. Does this new value make sense?

**Comment by veggiesaurus** [comment]
@markccchiang what exactly does the max backpressure setting do? Does it limit the buffer size while sending? That might be essential when streaming large catalogs to slow networks

**Comment by markccchiang** [comment]
> @markccchiang what exactly does the max backpressure setting do? Does it limit the buffer size while sending? That might be essential when streaming large catalogs to slow networks

Yes, the max backpressure limits the buffer size while sending. According to the code:
![截圖 2021-03-04 下午4 54 37](https://user-images.githubusercontent.com/5379602/109937957-71f5a100-7d0a-11eb-906e-395623a1f4b7.png)

**Comment by veggiesaurus** [comment]
> > @markccchiang what exactly does the max backpressure setting do? Does it limit the buffer size while sending? That might be essential when streaming large catalogs to slow networks
> 
> Yes, the max backpressure limits the buffer size while sending. According to the code:
> ![截圖 2021-03-04 下午4 54 37](https://user-images.githubusercontent.com/5379602/109937957-71f5a100-7d0a-11eb-906e-395623a1f4b7.png)
> 

Ok, go ahead and increase it then. We've done the same sort of thing for the reverse direction anyway
