### ISSUE TITLE
Moment generator ICD test problem

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#759]
There is a problem with part of the `MOMENTS_GENERATOR_PROFILE_STREAM.test.ts` ICD test.

Some times it passes, but most times it fails.

 > ✕ Request moment image and receive a few SpectralProfileData

    Expected: <= 2
    Received:    31

      90 |             ack = await Connection.streamUntil(type => type == CARTA.MomentResponse);
      91 |             FileId = ack.RegionHistogramData.map(data => data.fileId);
    > 92 |             expect(ack.SpectralProfileData.length).toBeLessThanOrEqual(2);
         |                                                    ^

Each time it fails, the `Received` value is different e.g. 37, 43, 40, 35, 61.

Does anyone know why?

**Comment by veggiesaurus** [comment]
can you `console.log(ack.SpectralProfileData)`?

**Comment by kswang1029** [comment]
that's probably because the spectral profile is still streaming and the request of moment map generation is queued up. Once the profile stream finishes, moment calculation will start.

**Comment by kswang1029** [comment]
On the GUI, when there is streaming profile data, the generate button of moment generation is disabled. However, there is a tiny window in time that it is still possible to click the generate button just before the start of data stream. When this happens, the moment generation request is queued. That part of test can be modified.

**Comment by kswang1029** [comment]
@ajm-asiaa is this still a problem?

**Comment by ajm-ska** [comment]
@kswang1029 I'm not 100% sure, but there does still seem to be an intermittent issue with the Moment generator ICD tests.
For example, a problem 12 days ago on the 'dev' branch: 
https://carta.asiaa.sinica.edu.tw/blue/organizations/jenkins/carta-backend/detail/dev/360/pipeline/1593
But no problem for the 'dev' branch commits before and after it.

**Comment by kswang1029** [comment]
@ajm-asiaa @acdo2002 is this still a problem?

**Comment by ajm-ska** [comment]
@kswang1029 It looks like this is no longer a problem. I believe the ICD tests never fail in the Moment Generator stage now. So we can close this issue.
