### ISSUE TITLE
Frame::WaitForTaskCancellation infinite loop

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#769]
A difficult-to-reproduce bug: Sometimes `Frame::WaitForTaskCancellation` gets stuck in an infinite loop (sleeping most of the time), because `_z_profile_count` is stuck at 1. I'm not really sure why this is happening.  

The problem is that this prevents new sessions from being created, as the main thread is entirely taken up by this infinite loop.

**Comment by veggiesaurus** [comment]
not sure if this is related, but I also get `Session 1 reference count is not 0 (0) on deletion!` warnings when closing a session if it's still doing region calcs (in `dev` branch)

**Comment by kswang1029** [comment]
Believe or not, I found a more reliable way (not 100% but close) to reproduce the issue.
The procedure is (with v1.4):
1) load a large cube
2) make a large region and request spectral profile
3) right after the request, quickly use the file browser to load a new image (not append)
4) possibly a dead lock is present. The carta_backend process sits there doing nothing particular (with CPU usage 0.3% in my test).

Update: wait for my confirmation of the crash.

**Comment by veggiesaurus** [comment]
Hurrah, if we can reproduce it, we can fix it 🙂

**Comment by kswang1029** [comment]
@markccchiang in your branch I seem not be able to reproduce the issue so the fix appears to work properly 🚀
