### ISSUE TITLE
hdf5 header entry OBSGEO-X, OBSGEO-Y & OBSGEO-Z does not always match to fits header entry

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend#779]
I found this issue when I implement a ICD test.

The example images put in [here](https://drive.google.com/drive/folders/1mewxY0ZOMQbTGBgz8WfS7b5MdP25XD8i?usp=sharing)

For `M17_SWex.hdf5`, the value of `OBSGEO-X, OBSGEO-Y & OBSGEO-Z `match to the `M17_SWex.fits` header value.

However, for `SDC335.579-0.292.spw0.line.hdf5`, the value of `OBSGEO-X, OBSGEO-Y & OBSGEO-Z` do not match to the `SDC335.579-0.292.spw0.line.fits` value.

I try to execute
`h5dump -H -A -m "%.10f" SDC335.579-0.292.spw0.line.hdf5`
OBSGEO-X: 2225061.8731840001; (<= this number is more similar to what I found in fits header with carta backend & fitsheader : "2.225061873184E+06")
In contrast, the carta backend shows SDC335.579-0.292.spw0.line.hdf5 header:
OBSGEO-X: 2.225142180269E+06;

**Comment by kswang1029** [comment]
@acdo2002 could try to with the latest dev to see if this is still an issue?

**Comment by acdo2002** [comment]
I confirm this issue has been solved.

I test `SDC335.579-0.292.spw0.line.fits`:
OBSGEO-X = 2.225061873184E+06
OBSGEO-Y = -5.440061952280E+06
OBSGEO-Z = -2.481682085791E+06

while `SDC335.579-0.292.spw0.line.hdf5`:
OBSGEO-X = 2225061.873184
OBSGEO-Y = -5440061.952280
OBSGEO-Z = -2481682.085791

I also test `G14.114-0.574.continuum.image.pbcor.fits`:
OBSGEO-X = 2.225142180269E+06
OBSGEO-Y = -5.440307370349E+06
OBSGEO-Z = -2.481029851874E+06

while `G14.114-0.574.continuum.image.pbcor.hdf5`:
OBSGEO-X = 2225142.180269
OBSGEO-Y = -5440307.370349
OBSGEO-Z = -2481029.851874

Although the presentation style is different, the number is consistent.
