### ISSUE TITLE
support preview of a pv image from a downsampled cube (backend)

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#795]
As part of the PV generator feature, the backend needs to support streaming pv images when the pv cut is updating on the GUI. This is only possible if the backend generates a downsampled cube in _memory_ so that image slicing can be much more efficient than from HDD/SSD. 

More detailed doc will be provided soon.

**Comment by kswang1029** [comment]
```
x	y	z	reduction_factor
========================================
1	1	1	1
1	1	2	2
2	2	1	4
2	2	2	8
2	2	4	16
4	4	2	32
4	4	4	64
4	4	8	128
8	8	4	256
8	8	8	512
```
Here is an initial idea of how we can (block averaging in xy, rebin or decimation in z) downsample the cube for pv preview. We could consider two approaches: 1) try to compute the final file size of the downsampled cube according to the sequence of the list before it exceeds the memory budget then we adopt the set of the downsampling factors. 2) we offer all possible options (xy: 1, 2, 4, 8; z:1, 2, 4, 8) as dropdown menus for users to select.

The 1) appears smarter (less user configuration) but it might be generating an improper downsampled cube for preview due the complexity in source structures in spatial (compact vs extended) and spectral (narrow line vs broad line) domains. With 2) users can adjust how the cube should be downsampled based on their knowledge about the source feature.

At the moment I prefer having option 2) as it has flexibilities to handle various source features despite we need additional UI elements.

**Comment by veggiesaurus** [comment]
surely some situations would call for e.g. 2x2x8 or 1x1x8? If you have situations where you have many channels and a small spatial region. 

I suggest we provide users with _options_ to choose from that result in the required downsampled size. For example if we need to achieve a reduction factor of 100, we could have a single dropdown that has the following:

- 1 x 1 x 128
- 2 x 2 x 32
- 4 x 4 x 8
- 8 x 8 x 2
- 16 x 16 x 1

And possibly we automatically select the one which results in the largest _minimum_ axis length. For example,if you select a very small region and a large number of channels, it would favour spectral downsampling. if you select a large region and few channels, it would favour spatial downsampling

**Comment by veggiesaurus** [comment]
@kswang1029 I don't think we can realistically do this in beta-2
