### ISSUE TITLE
image archive use case: disable write request

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#798]
pairing to https://github.com/CARTAvis/carta-frontend/issues/1406

For a read-only system such as the ALMA archive, we need to strictly disable write request from users.

**Comment by veggiesaurus** [comment]
So that would be:
- exporting regions
- saving images
- generating moment maps to disk
- saving layouts and preferences to server side storage

Am I missing any?

**Comment by kswang1029** [comment]
> So that would be:
> 
> * exporting regions
> * saving images
> * generating moment maps to disk
> * saving layouts and preferences to server side storage
> 
> Am I missing any?

"generating moment maps to disk" requires "saving image" so double-counting.

**Comment by veggiesaurus** [comment]
> > So that would be:
> > 
> > * exporting regions
> > * saving images
> > * generating moment maps to disk
> > * saving layouts and preferences to server side storage
> > 
> > Am I missing any?
> 
> "generating moment maps to disk" requires "saving image" so double-counting. 

Right.. sorry I meant saving a sub image

**Comment by kswang1029** [comment]
> > > So that would be:
> > > 
> > > * exporting regions
> > > * saving images
> > > * generating moment maps to disk
> > > * saving layouts and preferences to server side storage
> > > 
> > > Am I missing any?
> > 
> > 
> > "generating moment maps to disk" requires "saving image" so double-counting.
> 
> Right.. sorry I meant saving a sub image

save sub image is integrated with save image at the frontend 🙂 The backend still needs to reject the request though.
