### ISSUE TITLE
Allow the user to customise the browser command

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#806]
At the moment we always use `xdg-open` / `open` to open the frontend in a browser. We should convert the boolean `--no-browser` flag to a `--browser` flag which can be set to an arbitrary string. If it is unset, we use the default. If it is set to `none`, we disable the browser. The string should allow an optional wildcard in an arbitrary position to be replaced by the URL, in case the user wants to do something complicated with quotes, etc..

This will allow users to open CARTA in a specific browser and to pass additional custom parameters to the browser, which will allow for a smoother transition away from the bundled electron app.

**Comment by veggiesaurus** [comment]
@jolopezl can you take care of this? We'd need to make (minor) changes to the config files as well.

**Comment by confluence** [comment]
A small clarification of what I mean about the wildcard substitution: the user should be able to insert a placeholder like `%u` (as in the FreeDesktop spec) or `CARTA_URL` in the middle of the command like this: `'firefox %u --foo --bar '`, and then we should run `firefox url_goes_here --foo --bar`. If we can't find the placeholder, we default to appending the URL at the end: if the user sets the browser to `'firefox --foo --bar'`  we should run `firefox --foo --bar url_goes_here`.

I don't have a strong opinion about the format of the placeholder.

**Comment by confluence** [comment]
(I may be overcomplicating this preemptively; I don't have a specific use case for this in mind. We could leave this out until someone complains.)

**Comment by veggiesaurus** [comment]
using the freedesktop spec'd placeholder (`%u`) sounds entirely sensible to me 👍

**Comment by confluence** [comment]
Wait, I've just realised a problem -- we _can't_ use the FreeDesktop placeholder, because we want to be able to put this in a desktop file, and if we do, it will be interpreted by FreeDesktop. So we should use our own custom placeholder.
