### ISSUE TITLE
[CMakeLists]MacOSX needs a LINK of "uv"

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#81]
While building backend on MacOSX, the CMakeLists file need to add "uv" following the line "set(LINK_LIBS ${LINK_LIBS} carta-protobuf ${PROTOBUF_LIBRARY} " or the "make" will fail.

**Comment by ajm-asiaa** [comment]
I have modified CMakelists.txt with the following:
```
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  target_link_libraries(carta_backend uv ${LINK_LIBS})
endif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  target_link_libraries(carta_backend ${LINK_LIBS})
endif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
```

**Comment by pford** [comment]
This works on the Mac, I can compile without manually changing CMakeLists.txt.  Has anyone tried it on Linux (@markccchiang , @confluence , @veggiesaurus ) ?

**Comment by ajm-asiaa** [comment]
I can confirm that it works on Linux (Tested through ubuntu and CentOS6 Docker containers). I guess we can close the issue now.
