### ISSUE TITLE
Generate random FITS and HDF5 files for unit tests

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#813]
Many unit tests which need to be added require files with specific large dimensions (e.g. tests of tile or chunk behaviour). It would be impractical to store these files. Instead, we should integrate the unit tests with the [random FITS file generator](https://github.com/idia-astro/image-generator) and the [HDF5 converter](https://github.com/idia-astro/fits2idia/), create these files as they are needed, and delete them afterwards.

- [x] Enhance the FITS generator to allow specifying arbitrary headers (for header tests) and a random seed (for file reproducibility)
- [x] Add generator and converter repos as submodules (to be used only for the test build). This may mean that there are additional dependencies for building and running the tests.
- [ ] Rewrite existing tests which use files so that they generate files instead

**Comment by veggiesaurus** [comment]
I suggest we split the last checkbox into a separate issue
