### ISSUE TITLE
cannot save layout

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#815]
thanks for the help from @acdo2002 @YuHsuan-Hwang and @ajm-asiaa 

The issue here is: if we have a global installation of CARTA on a server and every user just types carta to launch it, it appears that a layout cannot be saved which might depend on the permission of CARTA's "pwd". 

Can anyone try and see if it is also reproducible from your side? If it is confirmed, we will need to fix this before v2.0 release. 

edit by @veggiesaurus: This is an issue with the older backend rejecting auth tokens, as they have been overwritten with the token from the newer backend

**Comment by kswang1029** [comment]
I just tried again and I cannot reproduce it......
@acdo2002 @YuHsuan-Hwang @ajm-asiaa could you try again with almat5?

**Comment by YuHsuan-Hwang** [comment]
I can reproduce it only when launching two carta

**Comment by kswang1029** [comment]
> I can reproduce it only when launching two carta

from one backend process or two backend processes?

**Comment by YuHsuan-Hwang** [comment]
> > I can reproduce it only when launching two carta
> 
> from one backend process or two backend processes?

two backend processes

**Comment by YuHsuan-Hwang** [comment]
reproduce steps:
1. launch two carta backend using different terminals and access them using browsers
2. try saving layout using the _first_ launched carta

**Comment by acdo2002** [comment]
I can reproduce this issue:

1) ssh to server, type "carta" to start up 1st backend, copy 1st url(included token) to browser(google-chrome), then I can save the layout.
2) open another terminal, type "carta" to start up 2nd backend, copy 2nd url(include token) to brower(google-chrome), at this stage, the second (newest url) can save the layout, however the original(1st url) cannot save the layout.

I try to open the third terminal with the 3rd backend, it seems I only can save the layout with the latest URL, the older will show
`Saving user-defined layout failed!`

**Comment by veggiesaurus** [comment]
@kswang1029 should we backport this to 2.0?

**Comment by kswang1029** [comment]
> @kswang1029 should we backport this to 2.0?

Yes good idea

**Comment by veggiesaurus** [comment]
reopening for 2.0 backport
