### ISSUE TITLE
statistics and histogram from an ellipse region in a PV image are not available 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#820]
this should be fixed for v2.0

<img width="937" alt="Screen Shot 2021-05-14 at 1 48 00 PM" src="https://user-images.githubusercontent.com/20819712/118227430-1ccccd00-b4bb-11eb-80cd-d24322bf5611.png">

**Comment by veggiesaurus** [comment]
@pford can you look into this for the 2.0 final release?

**Comment by pford** [comment]
I have fixed this for the reference image.  It looks like you cannot do spatial matching of PV images so it is not necessary to convert regions to another image?

**Comment by kswang1029** [comment]
> I have fixed this for the reference image. It looks like you cannot do spatial matching of PV images so it is not necessary to convert regions to another image?

Right, matching pv image is not allowed.
