### ISSUE TITLE
custom histogram calculations

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#829]
At the moment a histogram is computed with range and n_bin derived automatically. To make the histogram widget be more useful for analysis, custom
- n_bin
- bin_width
- range
need to be configurable.

related to frontend: https://github.com/CARTAvis/carta-frontend/issues/1488

**Comment by veggiesaurus** [comment]
I think this might already actually be supported on the backend

edit: no, currently the histogram config only supports `num_bins`, not the range itself

**Comment by kswang1029** [comment]
and need ICD changes I suppose

**Comment by veggiesaurus** [comment]
> and need ICD changes I suppose

yes, non-breaking ones though, and probably pretty trivial

**Comment by kswang1029** [comment]
Done with #1254
