### ISSUE TITLE
Don't establish readlocks on CASA images

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-backend#830]
I'd like to prevent CARTA from establishing a "read lock" on image cubes.

I've had several (dozen) experiences where I open an image to inspect it, find something to fix, re-run the imaging, then find my supercomputer has been spinning its wheels for days waiting for a read/write lock.  It would be better not to establish those locks.

If needed, this may be doable with https://github.com/radio-astro-tools/casa-formats-io instead of casacore, though the implementation in casa-formats-io is not 100% complete (I think it doesn't read _all_ of the header information as of today)

**Comment by veggiesaurus** [comment]
I've done a quick test using `lsof` after opening a FITS file, HDF5 file and CASA file in CARTA.

FITS files open with read-only access and no lock. HDF5 files open with read-only access _and_ a read lock. CASA images open `table.f0_TSM0` and `mask0/table.f0_TSM0` with read-only access and no lock, as well as `table.lock` and `mask0/table.lock` in read-write access and a read lock on part of the file.

I'm not really too clued up on the CASA file format, so @pford should be able to clarify whether those locks are really necessary.

In terms of removing the read locks entirely, I'm not sure how we should approach it. It seems you can build with `HDF5_USE_FILE_LOCKING=FALSE` to disable the read locks, but I haven't investigated that.

edit: opening `carta_backend` with then env variable `HDF5_USE_FILE_LOCKING=FALSE` works, it results in removing the read lock

**Comment by veggiesaurus** [comment]
Also, I guess one thing we should expect is that things may go horribly wrong with CARTA if you attempt to continue reading from a file after its been rewritten!

**Comment by keflavich** [comment]
I think I've already done this in some cases; I used the filesystem to move a file that had a lock on it (`mv` ignores readlocks, at least on this filesystem?) and... CARTA just used what was cached, I think.  It just redisplayed the same data.  It was weird, but no major crashes happened.  Again, not sure I can reproduce _exactly_ what I did...

**Comment by veggiesaurus** [comment]
@pford is this fixed now?

**Comment by kswang1029** [comment]
should be fixed now.
