### ISSUE TITLE
fix homebrew packages

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#836]
This is to address issues encountered from the v2.0 release.

**Comment by veggiesaurus** [comment]
@ajm-asiaa and @veggiesaurus agreed that the solution is to just do away with bottles altogether.

**Comment by veggiesaurus** [comment]
@ajm-asiaa can I close this? Have you disabled the bottles feature?

**Comment by ajm-ska** [comment]
@veggiesaurus OK. I removed reference to the bottles from the `carta-cascacore.rb` and `carta.rb` files so hopefully it will be OK now.
