### ISSUE TITLE
Documentation: summarise default settings

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#838]
@veggiesaurus please help to fill in details.

**Comment by confluence** [comment]
Default settings for all the config values / commandline parameters? And where should this be summarised -- more details in the body of the commandline help?

**Comment by veggiesaurus** [comment]
@kswang1029 can you remember what this issue was for? Was it for documenting the JSON config options in the user manual itself?

**Comment by kswang1029** [comment]
Hmm I cannot remember. We already have the auto-generated json doc in the appendix of the user manual (@confluence helped me on this part while I was working on the user manual revision before the release)

**Comment by veggiesaurus** [comment]
I propose we close this issue then, and reopen if needed.
