### ISSUE TITLE
performance degradation when animating raster + two sets of contours

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#849]
test images: HD163296_CO_2_1.fits and HD163296_13CO_2_1.fits. Both spatial sizes are 432 px x 432 px.

If we animate one raster + one contour at fps 15, we see the performance is okay (raster and contour are a bit out of sync as already a known issue).

If we animator one raster + two sets of contours (from each cube) at fps 15, the animation becomes extremely slow and is not usable. 

This might be something to do with OMP or task scheduling when generating tile data and contour data at the same time.

**Comment by veggiesaurus** [comment]
@kswang1029 I can't reproduce this on my Ubuntu 20.04 machine :thinking: I'm able to run the animation at (target frame rate of) 15 fps, with two contour sets and one raster. My CPU usage was < 10 % total :shrug: 

Did you notice this on MacOS?

**Comment by kswang1029** [comment]
> @kswang1029 I can't reproduce this on my Ubuntu 20.04 machine 🤔 I'm able to run the animation at (target frame rate of) 15 fps, with two contour sets and one raster. My CPU usage was < 10 % total 🤷
> 
> Did you notice this on MacOS?

Yes I tested with macOS. 🤔

**Comment by veggiesaurus** [comment]
> Yes I tested with macOS. thinking

I'm trying to isolate the cause of this. Can you see if any of the following prevent the performance degradation?
1. Using block or no smoothing instead of Gaussian
2. Just generating a single contour levels per image
3. Changing the contour levels so that they are almost entirely empty (e.g. a level that is far higher than the max value of the image)
4. Using a the cube histogram instead of channel

**Comment by kswang1029** [comment]
> > Yes I tested with macOS. thinking
> 
> I'm trying to isolate the cause of this. Can you see if any of the following prevent the performance degradation?
> 
> 1. Using block or no smoothing instead of Gaussian
> 2. Just generating a single contour levels per image
> 3. Changing the contour levels so that they are almost entirely empty (e.g. a level that is far higher than the max value of the image)
> 4. Using a the cube histogram instead of channel

A quick response to 2 and 3, degradation is more significant if there more contour levels being rendered per channel. If there is no contour rendered at all, no degradation is seen. Will test others cases

**Comment by kswang1029** [comment]
> > Yes I tested with macOS. thinking
> 
> I'm trying to isolate the cause of this. Can you see if any of the following prevent the performance degradation?
> 
> 1. Using block or no smoothing instead of Gaussian

=> using block or no smoothing does not improve the situation 


> 2. Just generating a single contour levels per image

=> helps a little bit but still the degradation is significant and have impact to usability a lot

> 3. Changing the contour levels so that they are almost entirely empty (e.g. a level that is far higher than the max value of the image)

=> I tried a level so that only one or two channels have a contour. In this case, no performance degradation is seen. I think this is correlated with how many contour levels are rendered: the more contours are rendered, the prominent the problem is. 

> 4. Using a the cube histogram instead of channel

=> does not improve the situation.

**Comment by kswang1029** [comment]
@markccchiang do you have time to investigate this performance issue?

**Comment by kswang1029** [comment]
Odd. with the macOS electron build v3b2 I cannot reproduce the problem.

**Comment by kswang1029** [comment]
@acdo2002 @markccchiang could you give this a try with the computers that you have access to? We may see contours out of sync a bit but  that's a separate issue. If you cannot reproduce the issue then we can close this for now. 🤞

**Comment by kswang1029** [comment]
My last attempt to reproduce this issue was Nov 2021. In December 2021 I upgraded my macOS to Monterey (clean install) and reset my CARTA dev env. It might be due to my previous dev env.

**Comment by acdo2002** [comment]
I quick check with my laptop Ubuntu 20.04.
Yes, I see contours out of sync a little bit, but I did not feel any animator becomes extremely slow when I load these two images (and set one of them as two contours and animate it).

I will check MacOS later.

**Comment by acdo2002** [comment]
I check two MacOS (backend and frontend are both current dev branch), and omp set to 4 when I start the backend.
I repeat the behavior that I performed earlier today on Ubuntu 20.04. 
Two MacOS (Monterey & Big Sur) don't show any extreme slow performance when I set 2 contour levels and animate it.

**Comment by kswang1029** [comment]
@acdo2002 thank you for checking this out. 

OK we can close this issue.

**Comment by kswang1029** [comment]
with macOS Monterey and v3b3 release, I can reproduce the issue. @acdo2002 could you repeat the test again to see if it can be reproduced?


https://user-images.githubusercontent.com/20819712/169017377-c9bdae9b-4b56-43f2-9e67-9f0d2adbe2a0.mov

**Comment by kswang1029** [comment]
tried with m1 Mac mini and the animation playback works fine (except the the contour sync issue). Odd, so this might be just my intel laptop?

UPDATE: with my intel Mac laptop without an external monitor (using intel GPU), I see the animation playback performs better considerably. However, if there is an external monitor (using AMD discrete GPU), the animation playback performs much worse! So this might well be a frontend issue (or GPU related issue).

**Comment by acdo2002** [comment]
Steps:
(1) open "HD163296_CO_2_1.fits", go to channel 88, using "min_max" in "Contours" tool and plot 5 contour levels (color: green)
(2)  open "HD163296_13CO_2_1.fits", and spatial and spectral matching to (1), then using "min_max" in "Contours" tool and plot 5 contour levels (color: white)
(3) Go to "HD163296_CO_2_1.fits" channel 0, setting Frame Rate = 15 and playing animator
(4) Record

MacOS 11.6 + M1 chip (omp_threads=4 when I set up the carta_backend): 
Looks fine (no slow performance), although contour level may exceed the image, but if I press "stop", two images look good.

https://user-images.githubusercontent.com/34430648/169031284-8616e2c8-4373-45d3-94d4-ef8a5ad9383a.mov

Ubuntu 20.04 + intel i5 core (omp_threads=4 when I set up the carta_backend):
Looks fine (no slow performance), although the non-active frame may loose the tile, the active frame looks good.

https://user-images.githubusercontent.com/34430648/169032398-189dc918-534a-4c0c-a4f3-09a69fb8a24b.mov

**Comment by veggiesaurus** [comment]
> UPDATE: with my intel Mac laptop without an external monitor (using intel GPU), I see the animation playback performs better considerably. However, if there is an external monitor (using AMD discrete GPU), the animation playback performs much worse! So this might well be a frontend issue (or GPU related issue).

same device pixel ratio?

**Comment by kswang1029** [comment]
> > UPDATE: with my intel Mac laptop without an external monitor (using intel GPU), I see the animation playback performs better considerably. However, if there is an external monitor (using AMD discrete GPU), the animation playback performs much worse! So this might well be a frontend issue (or GPU related issue).
> 
> same device pixel ratio?

yes

**Comment by kswang1029** [comment]
with an entry-level old intel Mac laptop without an external monitor, I cannot reproduce the issue.... So it seems this is specific to a certain hardware configuration. 

<img width="316" alt="Screen Shot 2022-05-18 at 21 30 35" src="https://user-images.githubusercontent.com/20819712/169051281-534093ca-b4c6-445a-bdaa-0de4b69967aa.png">
