### ISSUE TITLE
generic HTTP proxy for resources without CORS

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#871]
We have a number of scenarios where we need to pull data from external sources: 
- Splatalogue
- NED, SIMBAD, etc
- ADS

Those resources are out of our control. They may not have HTTPS or CORS enabled, which means we cannot query them directly from the browser. This means a lot of the asynchronous requests have to be made via the backend. At the moment, we've only implemented this for Splatalogue, and it required a number of ICD changes. It will get extremely frustrating to do this each time we need to get around this issue. I propose we have a more generic solution, where the frontend can pass a URL to the backend to fetch _asynchronously_ with curl, and wait for a response. We can use regex to check the URL against a whitelist of allowed domains, to avoid the server being used to request data arbitrarily. 

I feel like this would make more sense than constantly handling a lot of the request logic on the backend in C++, which is pretty unwieldy for this sort of thing compared to simply using async functions on the frontend. 

@duidae, what do you think? You've implemented the Splatalogue stuff. In terms of a security risk, we can mitigate that by limiting the allowed URLs carefully.

**Comment by veggiesaurus** [comment]
@panchyo0 will need to use the backend for grabbing data for the online catalogue query tool, so he may have input on this issue too.

**Comment by duidae** [comment]
Maintaining a small proxy could be a solution as the demand of requesting external resources increases, and I think those pain in the neck in the development may possibly due to we are trying to integrate those services dedicated to "human" rather than applications(i.e. lack of API), so they would update in any time and in any form without considering others, which may increase our development & maintenance efforts.

**Comment by veggiesaurus** [comment]
> and I think those pain in the neck in the development may possibly due to we are trying to integrate those services dedicated to "human" rather than applications(i.e. lack of API), so they would update in any time and in any form without considering others, which may increase our development & maintenance efforts.

That's certainly true of splatalogue, but NED, SIMBAD and ADS are designed as APIs specifically. However, the major problem is that they're often designed with python/bash scripts in mind, rather than in-browser execution.

**Comment by veggiesaurus** [comment]
Ok, I think we should aim to add this in v3.0-beta.2. I suggest we use the following approach

![image](https://user-images.githubusercontent.com/592504/126117495-017b77d7-7695-4cf6-baf7-0321af199111.png)

It would be nice to eventually migrate to using asynchronous `cURL` handling, but I don't think that's strictly necessary in our case, because of our single-user-per-process approach.

**Comment by veggiesaurus** [comment]
closing as a "bad idea" due to (a) complexity and (b) security issues with generic HTTP proxying bypassing all firewalls
