### ISSUE TITLE
double click to load an image results in incorrect header extraction

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#873]
if we use the load button to load an image, it works fine. However, if we load the same image with double click the returned header becomes weird. 

test image: https://drive.google.com/file/d/1T6DwUKsOrFs9SB8dnhYkiiwEls9zS0VM/view?usp=sharing

with the load button
![Screen Shot 2021-07-20 at 3 12 07 PM](https://user-images.githubusercontent.com/20819712/126277632-da858deb-78c8-4cca-9dc6-6f076e86d638.png)

with double click to load
![Screen Shot 2021-07-20 at 3 12 19 PM](https://user-images.githubusercontent.com/20819712/126277668-55940f22-fa85-409c-85b9-64026313afc4.png)

**Comment by veggiesaurus** [comment]
@kswang1029 what happens if you load the same image using the URL parameters?

**Comment by veggiesaurus** [comment]
The frontend may be partly to blame here. When you double click on a file, it spams the backend with requests:
- Two `FileInfoRequest` messages (one for each click :man_facepalming: )
- One `OpenFile` message (for the double-click action itself)

Ideally it should just be a single `OpenFile` message when you double-click. However, I do think we should still make sure the results are consistent.

**Comment by kswang1029** [comment]
> @kswang1029 what happens if you load the same image using the URL parameters?

hmm same wrong header as the case with double click

**Comment by veggiesaurus** [comment]
> hmm same wrong header as the case with double click

Ok, so it seems like calling `OpenFile` without first calling `FileInfoRequest` causes the issue, rather than some sort of race condition.

Does the same thing happen with HDF5?

**Comment by kswang1029** [comment]
This appears only happening with the attached test image. I tried other images with multiple HDUs and others without, all work fine so far.

**Comment by pford** [comment]
It looks like it is loading the primary header/array (which is an image?) with the double click: `SIMPLE = T` rather than `XTENSION = IMAGE` and the filename does not show the HDU and EXTNAME.

If the HDU is not specified in OpenFile, the backend opens the first HDU which is an image.

**Comment by veggiesaurus** [comment]
> It looks like it is loading the primary header/array (which is an image?) with the double click: `SIMPLE = T` rather than `XTENSION = IMAGE` and the filename does not show the HDU and EXTNAME.
> 
> If the HDU is not specified in OpenFile, the backend opens the first HDU which is an image.

The HDU is not specified in `OpenFile`, so it should load the first image HDU. From the image data, it's clearly loading the first image HDU correctly, but the _header_ info is the first HDU, not the first image HDU.

The first HDU for this image is

```
SIMPLE  =                    T /FITS format                                     
BITPIX  =                   16 /Dummy primary header                            
NAXIS   =                    0 /No data is associated with this header          
EXTEND  =                    T /Extensions may (will!) be present               
RESOLUTN=                   10 /Resolution index                                
PIXTYPE = 'HEALPIX '           /Pixel algorigthm                                
ORDERING= 'NESTED  '           /Ordering scheme                                 
NSIDE   =                 1024 /Resolution parameter                            
FIRSTPIX=                    0 /First pixel (0 based)                           
LASTPIX =             12582911 /Last pixel (0 based)                            
HISTORY FITS_REPROJ_HEALPIX:Tue Jan  2 12:20:21 2018 Converted to Flat Map Proje
HISTORY This FITS file contains a reprojection of WMAP HealPix data into        
HISTORY a flat map; this changes the noise properties of the CMB data.          
HISTORY Therefore this map should not be used for a CMB analysis           
```

which is definitely not an image (`NAXIS = 0`)

**Comment by veggiesaurus** [comment]
> This appears only happening with the attached test image. I tried other images with multiple HDUs and others without, all work fine so far.

My guess it it will occur whenever the _first_ HDU is not an image

**Comment by kswang1029** [comment]
if we load the image spire250_ext.fits with double-click, the displayed name in the image list widget is **spire250_ext.fits**.
![Screen Shot 2021-07-27 at 1 28 10 PM](https://user-images.githubusercontent.com/20819712/127100552-780bc000-e5cc-4dff-909d-71d4dd6643e1.png)
However, if we load the image spire250_ext.fits with the load button, the displayed name in the image list widget is **spire250_ext.fits_HDU1_image** which is fine.
![Screen Shot 2021-07-27 at 1 28 31 PM](https://user-images.githubusercontent.com/20819712/127100562-2b5405a7-560a-4b5d-aacd-248731d54569.png)

If we have two images loaded with double-click and two images loaded with the load button and match all four identical images, with the cursor info widget we see the world coordinates and reported pixel values are identical as expected BUT the image coordinates differ a bit. I guess this is because the extracted headers of the two loading methods are _different_. For example, the coordinate systems are different (FK5 vs ICRS). So when performing coordinate transformation we see errors.

**Comment by veggiesaurus** [comment]
> If we have two images loaded with double-click and two images loaded with the load button and match all four identical images, with the cursor info widget we see the world coordinates and reported pixel values are identical as expected BUT the image coordinates differ a bit. I guess this is because the extracted headers of the two loading methods are _different_. For example, the coordinate systems are different (FK5 vs ICRS). So when performing coordinate transformation we see errors.  

It's the same issue, isn't it? NAXIS=0

**Comment by kswang1029** [comment]
> > If we have two images loaded with double-click and two images loaded with the load button and match all four identical images, with the cursor info widget we see the world coordinates and reported pixel values are identical as expected BUT the image coordinates differ a bit. I guess this is because the extracted headers of the two loading methods are _different_. For example, the coordinate systems are different (FK5 vs ICRS). So when performing coordinate transformation we see errors.
> 
> It's the same issue, isn't it? NAXIS=0

yes. I just provide my other test result here.
