### ISSUE TITLE
backend crash when exporting region file including polyline

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#891]
@YuHsuan-Hwang found this while implementing the frontend support of polyline (https://github.com/CARTAvis/carta-frontend/pull/1592). After some investigations, it appears that exporting a polyline with specific numbers of points would cause the backend crash. They are 4, 8, 12 and so on.

**Comment by pford** [comment]
I need more information @YuHsuan-Hwang @kswang1029 .  Using frontend commit `origin/yuhsuan/1149_polyline_region 5e4870d` and backend `dev`, I opened set_QA/set_QA_regionTest/M17_SWex.image and created a 4-point polyline region and an 8-point polyline region then exported them in CRTF pixel and world and DS9 pixel and world coordinates without a backend crash.  Backend was running in Docker with Ubuntu 20.04.

**Comment by pford** [comment]
I did the same as above on Mix 'n Match with a 4-pt polyline, exported testpolyline4pt.crtf (pixel) and testpolyline4pt_world.crtf (world).

**Comment by kswang1029** [comment]
@pford hmmm, have you tried the native mac build? It appears that this only happens on mac...
