### ISSUE TITLE
Support other polarization types

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-backend#895]
Support all the stokes value of fits files:
![Screen Shot 2021-08-04 at 2 53 46 PM](https://user-images.githubusercontent.com/43841102/128664733-7644f102-d156-4cbc-928a-6a0ef13a8686.png)
This includes:

- [x] Extend protobuf message `StokesType`
- [x] Extend stokes type of Z profile, XY profile, histogram data, and statistics data
- [x] Extend types of hypercube

requiring frontend: https://github.com/CARTAvis/carta-frontend/issues/1606

**Comment by veggiesaurus** [comment]
@kswang1029 can we close this now?

**Comment by kswang1029** [comment]
yes
