### ISSUE TITLE
backend crash when loading multiple HDF5 images in one shot

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#896]
with my local mac build, loading four hdf5 images in one shot would "usually" crash the backend. Sometimes I see

> [2021-08-09 14:21:53.639] [error] Error loading image data: HDF5 error: reading slab from data set array DATA
[2021-08-09 14:21:53.640] [error] Error opening HDF5 image: HDF5 error: Unknown data type of scalar attribute PC02_03
[2021-08-09 14:21:53.641] [error] Error loading image data: HDF5 error: reading slab from data set array DATA
[2021-08-09 14:21:53.787] [error] Error loading image data: HDF5 error: reading slab from data set array DATA
Segmentation fault: 11

<img width="1196" alt="Screen Shot 2021-08-09 at 2 31 02 PM" src="https://user-images.githubusercontent.com/20819712/128667690-83f63475-095a-4c38-aaca-53f9a1996d63.png">

Tested the the demo server and it can be reproduced.

**Comment by kswang1029** [comment]
As a note here, occasionally this issue can happen with multiple FITS images too but I cannot find a robust way to reproduce the problem.

**Comment by veggiesaurus** [comment]
probably related to HDF5 library thread safety. I saw something similar with FITS files on Windows if you load lots of files across lots of threads.

**Comment by confluence** [comment]
I'm having trouble reproducing this. Does it happen more frequently with particular files, file sizes, etc.?

**Comment by kswang1029** [comment]
I can still reproduce the issue with my local Mac build. Crash report attached. 

> Thread 2 Crashed:
0   libhdf5.200.dylib             	0x00000001102daa7d H5S_select_iter_init + 61
1   libhdf5.200.dylib             	0x000000011019a253 H5D__select_io + 951
2   libhdf5.200.dylib             	0x0000000110199e44 H5D__select_read + 41
3   libhdf5.200.dylib             	0x0000000110174770 H5D__chunk_read + 767
4   libhdf5.200.dylib             	0x00000001101940af H5D__read + 928
5   libhdf5.200.dylib             	0x0000000110383433 H5VL__native_dataset_read + 108
6   libhdf5.200.dylib             	0x000000011036fb10 H5VL__dataset_read + 76
7   libhdf5.200.dylib             	0x000000011036f98d H5VL_dataset_read + 150
8   libhdf5.200.dylib             	0x0000000110193315 H5Dread + 681
9   libcasa_casa.5.dylib          	0x000000010e387e13 casacore::HDF5DataSet::get(casacore::Slicer const&, void*) + 243
10  carta_backend                 	0x000000010bf27327 casacore::HDF5Lattice<float>::doGetSlice(casacore::Array<float>&, casacore::Slicer const&) + 71 (HDF5Lattice.tcc:185)
11  libcasa_lattices.5.dylib      	0x000000010f0ab745 casacore::Lattice<float>::getSlice(casacore::Array<float>&, casacore::Slicer const&, bool) + 117
12  libcasa_lattices.5.dylib      	0x000000010f0b9d54 casacore::SubLattice<float>::doGetSlice(casacore::Array<float>&, casacore::Slicer const&) + 420
13  libcasa_lattices.5.dylib      	0x000000010f0ab745 casacore::Lattice<float>::getSlice(casacore::Array<float>&, casacore::Slicer const&, bool) + 117
14  libcasa_lattices.5.dylib      	0x000000010f08e917 casacore::Lattice<float>::getSlice(casacore::Array<float>&, casacore::IPosition const&, casacore::IPosition const&, casacore::IPosition const&, bool) + 71
15  libcasa_lattices.5.dylib      	0x000000010f08e607 casacore::LatticeIterInterface<float>::readData(bool) + 487
16  libcasa_lattices.5.dylib      	0x000000010f08e11e casacore::LatticeIterInterface<float>::cursor(bool, bool) + 62
17  carta_backend                 	0x000000010bf37562 carta::CartaHdf5Image::doGetMaskSlice(casacore::Array<bool>&, casacore::Slicer const&) + 482
18  libcasa_lattices.5.dylib      	0x000000010f0bac27 casacore::SubLattice<float>::getMaskDataSlice(casacore::Array<bool>&, casacore::Slicer const&) + 311
19  libcasa_lattices.5.dylib      	0x000000010f0ba2b4 casacore::SubLattice<float>::doGetMaskSlice(casacore::Array<bool>&, casacore::Slicer const&) + 500
20  carta_backend                 	0x000000010bed1099 casacore::MaskedLattice<float>::getMaskSlice(casacore::Array<bool>&, casacore::Slicer const&, bool) + 57 (MaskedLattice.tcc:224)
21  carta_backend                 	0x000000010bf10190 casacore::MaskedLattice<float>::getMaskSlice(casacore::Slicer const&, bool) const + 64 (MaskedLattice.tcc:267)
22  carta_backend                 	0x000000010bf05600 casacore::RO_MaskedLatticeIterator<float>::getMask(bool) const + 112 (MaskedLatticeIterator.tcc:134)
23  carta_backend                 	0x000000010bf04fb8 carta::FileLoader::GetSlice(casacore::Array<float>&, casacore::Slicer const&) + 440 (FileLoader.cc:330)
24  carta_backend                 	0x000000010bf26799 carta::Hdf5Loader::GetChunk(std::__1::vector<float, std::__1::allocator<float> >&, int&, int&, int, int, int, int, std::__1::mutex&) + 1001 (Hdf5Loader.cc:493)
25  carta_backend                 	0x000000010c0bbd53 TileCache::LoadChunk(TileCacheKey, std::__1::shared_ptr<carta::FileLoader>, std::__1::mutex&) + 115
26  carta_backend                 	0x000000010c0bbbbb TileCache::Get(TileCacheKey, std::__1::shared_ptr<carta::FileLoader>, std::__1::mutex&) + 315
27  carta_backend                 	0x000000010bec9bfb Frame::FillSpatialProfileData(PointXy, std::__1::vector<CARTA::SetSpatialRequirements_SpatialConfig, std::__1::allocator<CARTA::SetSpatialRequirements_SpatialConfig> >, std::__1::vector<CARTA::SpatialProfileData, std::__1::allocator<CARTA::SpatialProfileData> >&) + 3227 (Frame.cc:1194)
28  carta_backend                 	0x000000010bec8ef4 Frame::FillSpatialProfileData(std::__1::vector<CARTA::SpatialProfileData, std::__1::allocator<CARTA::SpatialProfileData> >&) + 68
29  carta_backend                 	0x000000010beab71c Session::SendSpatialProfileData(int, int) + 1244 (Session.cc:1420)
30  carta_backend                 	0x000000010beae29f Session::OnSetSpatialRequirements(CARTA::SetSpatialRequirements const&) + 1055 (Session.cc:834)
31  carta_backend                 	0x000000010c0a5464 GeneralMessageTask<CARTA::SetSpatialRequirements>::execute() + 20 (OnMessageTask.tcc:36)
32  libtbb.dylib                  	0x000000010de2ac92 tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop(tbb::internal::context_guard_helper<false>&, tbb::task*, long) + 344
33  libtbb.dylib                  	0x000000010de2a3da tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) + 216
34  libtbb.dylib                  	0x000000010de244f0 tbb::internal::arena::process(tbb::internal::generic_scheduler&) + 258
35  libtbb.dylib                  	0x000000010de23e43 tbb::internal::market::process(rml::job&) + 51
36  libtbb.dylib                  	0x000000010de20056 tbb::internal::rml::private_worker::run() + 126
37  libtbb.dylib                  	0x000000010de1ffd3 tbb::internal::rml::private_worker::thread_routine(void*) + 9
38  libsystem_pthread.dylib       	0x00007fff6d2d1109 _pthread_start + 148
39  libsystem_pthread.dylib       	0x00007fff6d2ccb8b thread_start + 15

[hdf5_crash.txt](https://github.com/CARTAvis/carta-backend/files/7284270/hdf5_crash.txt)

**Comment by kswang1029** [comment]
if I change the order, the backend does not crash but gives different kinds of errors
![Screen Shot 2021-10-05 at 4 53 10 PM](https://user-images.githubusercontent.com/20819712/135992117-eae91faa-9876-470c-b5e7-af485443400e.png)

![Screen Shot 2021-10-05 at 4 54 27 PM](https://user-images.githubusercontent.com/20819712/135992303-a16ad981-78e0-4fa2-b9d3-00346d032e06.png)
