### ISSUE TITLE
Use ZYXW dataset for point region z-profile if it is available in HDF5 file

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#90]
Part of #45. Described in https://docs.google.com/document/d/1T1T85zvGHy7IsePwztN7SjrMPJ4hQJv8X5ihZKf5XA8/edit#heading=h.2fonicmwctib

**Comment by veggiesaurus** [comment]
@confluence should we rename this issue to make it clear it refers to _only_ the single-pixel spectral profiles? And create a second one for closed regions

**Comment by confluence** [comment]
Sounds like a good idea.
