### ISSUE TITLE
cursor info widget does not show updated values for all matched images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#900]
To reproduce:
1) load two matchable images and match them
2) launch the cursor info widget
3) move cursor around and observe the reported pixel values. We should see pixel values from the two images are updating but there is only one updating.

**Comment by acdo2002** [comment]
I also noticed this with Jenkins ICD tests.
This problem shows up from the backend dev commit: `a8831fc`
(previous one `aee910a` works fine)

**Comment by kswang1029** [comment]
@markccchiang could you help on this for v3b1?

**Comment by markccchiang** [comment]
> @markccchiang could you help on this for v3b1?

Ok.

**Comment by confluence** [comment]
Please also add this to the changelog.
