### ISSUE TITLE
Backend make fails with error temporary of non-literal type ‘CARTA::script::ActionRequest’ in a constant expression

### ISSUE THREAD

**Issue by DhanrajIuc** [CARTAvis/carta-backend#901]
We are trying to set up a Cartavis server on our HPC, Specifications are given below:
**Operating system** : Centos 7.4
**GCC** : 7.2.0
**Issue** : Carta backend Make failed
**Error** : 
/carta-backend/build/carta-scripting-grpc/carta_service.pb.cc: In constructor ‘constexpr CARTA::script::ActionRequestDefaultTypeInternal::ActionRequestDefaultTypeInternal()’:
/carta-backend/build/carta-scripting-grpc/carta_service.pb.cc:30:76: error: temporary of non-literal type ‘CARTA::script::ActionRequest’ in a constant expression
     : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
                                                                            ^
In file included from /carta-backend/build/carta-scripting-grpc/carta_service.pb.cc:4:0:
/carta-backend/build/carta-scripting-grpc/carta_service.pb.h:75:7: note: ‘CARTA::script::ActionRequest’ is not literal because:
 class ActionRequest final :

Note: All the dependencies are installed from Github back-end link : https://github.com/CARTAvis/carta-backend

**Comment by veggiesaurus** [comment]
@confluence any ideas?

**Comment by veggiesaurus** [comment]
@DhanrajIuc which branch are you using? Could you try the `release/2.0` branch and run `git submodule update --init --recursive` to grab the correct submodules.


If you just want to get the backend up and running on centos 7, you can also install the prebuilt packages (see [here](https://carta.readthedocs.io/en/latest/installation_and_configuration.html#installation-via-package-managers))

**Comment by confluence** [comment]
What versions of gRPC and protocol buffers are you using?

**Comment by confluence** [comment]
Actually, I think the issue may be the GCC version. The minimum that we support is GCC 8 -- the [dockerfile for CentOS 7](https://github.com/CARTAvis/carta-backend/blob/dev/Dockerfiles/Dockerfile-CentOS7) has more details about the dependencies and the build process.

But we do recommend using our prebuilt packages if you are on one of our supported systems.

**Comment by DhanrajIuc** [comment]
Hi, Thank you for the update. Will try with GCC-8 and get back to you.

**Comment by kswang1029** [comment]
Any further update about this issue? Are you able to build carta_backend now?

**Comment by DhanrajIuc** [comment]
Dear Team, 

Thanks to the support from [ https://secure-web.cisco.com/18imdhMtfkE-8jRc_3JU1TqSuE41olsZxbndSU6r2ExRyJV1Rq_FgGmU1eQxO0TKk50WTy1nH6NVVDJmsMp7Dsjp4Dwx4mifuMr_pnIrTxfFYMgySgHPIbOZkXnUoulhUh6fGk18mQsjmCaXhK5Z8cULv_hDdOOYJvftZmZpx3QdZoPskcPis73hwdmb6OBMihcHBWljE6URmFryBOejqhj8K04pg-Dn7-LXNrS3MVPMjx7Zpo7ctegqxVKxckmOMnW9F9I9OUFkn8wpkgtQcXQe2ROsRZ61p49IqrsTAYuW7VslPBn1sGL-dh0YTw1jBuDDVtcxDiBFo9SRSXO1kQsb5BSDZFNrBeYRya8brmw7oH-VKYg7IChnz3YX5GwRblLvaofoEtb0i4qUUCqHN9_tFcjJjBhUpVH5-x3YywinpcmpRT3IxQDOhxttXFpyYf_fR8sWrGxXhutPoQxokq0J07Y1b43-e-m68g5RlKTA/https%3A%2F%2Fcartausers.slack.com%2Fx-p2123776628931-2606605989124-2686932440032%2Fmessages%2FC023JEWBCHK%2Fteam%2FU023JE9SZ2R | Angus Comrie ] and team, the build has been completed log time ago and CARTA server is also up and running. 

Thanks & Regards, 
Dhanraj 
============================================================= 
Inter-University Centre for Astronomy & Astrophysics (IUCAA), 
Pune - 411007, MAHARASHTRA, INDIA 
=============================================================

**Comment by kswang1029** [comment]
nice~
