### ISSUE TITLE
crash when opening a region file on CentOS8

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#909]
Our ICD tests have revealed a crash that only occurs on CentOS8.

When a carta_backend running on CentOS8 tries to open our region test file `M17_SWex_regionSet1_world.crtf` it results in an immediate crash of the backend:

```
 2021-08-24 01:57:14	INFO	RegionTextParser::_determineVersion	RegionTextParser::_determineVersion: Found spec version 0
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

It is strange because the same region file can be opened without problems on CentOS7, Ubuntu 18.04, and Ubuntu 20.04.

At first I thought it was the GCC version used to build the backend. CentOS8 uses gcc 8.4.1.
(CentOS7 uses gcc 8.3.1, Ubuntu 18.04 uses gcc 8.4.0, and Ubuntu 20.04 uses gcc 9.3.0)
I tried installing devtoolset-9 and devtoolset-10 on CentOS8. They use gcc 9.2.1 and 10.2.1, respectively, but the problem remains.

Do you have any idea what could be wrong? I guess something small needs to be adjusted in `CrtfImportExport.cc` to make it more robust?

**Comment by kswang1029** [comment]
> #symbol [[275.13653085deg, -16.17909524deg], .] coord=ICRS, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=green, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
> #centerbox [[275.13683271deg, -16.18844433deg], [30.0324arcsec, 30.0324arcsec]] coord=ICRS, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=green, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false
> centerbox [[275.13683271deg, -16.18844433deg], [30.0324arcsec, 30.0324arcsec]]

the first one “symbol” (aka point region) works fine.
problem starts from the 2nd region. If we remove those decoration related parameters (ie the 2nd centerbox in the above region def), it loads fine.

**Comment by kswang1029** [comment]
@pford could you help?

**Comment by ajm-ska** [comment]
If it is any help for debugging, I was using this Docker container `ajmasiaa/centos8-carta-jenkins-builder` (It is on DockerHub)

**Comment by pford** [comment]
@ajm-asiaa I created a docker image from the CentOS8 dockerfile, then built carta-casacore (Release) and carta-backend (Debug, then Release) in the container.  When I opened M17_SWex.fits (or .image) and imported the M17_SWex_regionSet1_world.crtf region file, the 16 regions were successfully loaded in the list.

**Comment by pford** [comment]
It was using gcc 8.4.1

**Comment by ajm-ska** [comment]
@pford Thank you for investigating this. I tried with a new Docker container from the CentOS8 Dockerfile and the issue appears to be gone now! The region file opened successfully. The old Docker container still exhibits the issue, so something is different, but I haven't figured what it is yet. 

I have added the new Docker container to the draft Docker Jenkins CI and region tests now pass.

I can not remember at the moment, but perhaps I built the old Docker container using the RHEL8 RPMs and that is why @kswang1029  was also able to reproduce the issue. I better check that scenario. In this case I will reassign myself to investigate from here.

**Comment by ajm-ska** [comment]
I investigated and it turns out that there was something wrong with el8 carta-casacore RPM (`carta-casacore-3.4.0+5.8.0+2021.4.23-1.el8.x86_64.rpm`).
I rebuilt the RPM from scratch, and now the problem is gone.
I have uploaded the new RPM to the repository as the number '2' release: `carta-casacore-3.4.0+5.8.0+2021.4.23-2.el8.x86_64.rpm`.
Although I still can't understand exactly what was wrong with the original RPM, I guess we can close this issue now as it should no longer be a problem.

**Comment by ajm-ska** [comment]
This exact same issue has cropped up again in the new carta-casacore-devel-3.4.0+6.4.4+2022.3.9-1.el8.x86_64.rpm.

A search on Google reveals another team had the same issue, and they presented a [small demo program that can reproduce the issue](https://github.com/rstudio/httpuv/issues/133#issuecomment-387499519). From that issue, it looks like rpmbuild must have used `_GLIBCXX_ASSERTIONS` when I created the RPM. 

Maybe the first time I built the carta-casacore RPM in 'Debug' mode, and that uses `_GLIBCXX_ASSERTIONS`. 
The second time I built it in 'Release' mode, similar to how @pford built it, and the issue was hidden. 
Then maybe I built the new 2022.3.9 carta-casacore RPM in 'Debug' mode, and now the problem is back. 
It feels like a bug that should not be occurring at all.

Could it be we are using casacore incorrectly or could it be a real bug in casacore?

**Comment by pford** [comment]
As noted in the Slack build channel, I could not make a CentOS8 container in Docker using the Dockerfile since CentOS removed the packages from the official mirrors.  Using ajmasiaa/centos8-4-carta-jenkins-builder from Dockerhub, building carta-casacore from source in Debug mode, and building carta-backend from source in Release then Debug mode, I could not cause a crash when importing the region file.

When I tried to install the carta-casacore rpm with `yum -y install carta-casacore-devel-3.4.0+6.4.4_2022.3.9-1.el8.x86_64.rpm` I got the error described in Slack, "Failed to download metadata for repo 'centos-ceph-nautilus': Cannot prepare internal mirrorlist: No URLs in mirrorlist"

**Comment by pford** [comment]
@ajm-asiaa you were correct.  When a 2D region is extended by channel and stokes ("corr=[I]"), two regions are created: one for the 2D region (e.g. WCPolygon for a centerbox), and an extension or stretch WCBox region.  casacore::WCExtension determines which axes need to be stretched/extended, puts them in a std::vector, and sorts them using the address of the first element e.g. &(tmpstretch[0]).  If tmpstretch is an empty vector, this fails with the std::vector error and core dump.  Will open a casacore PR.

**Comment by pford** [comment]
https://github.com/casacore/casacore/pull/1178

**Comment by pford** [comment]
Confirmed fixed in carta-casacore [PR 19](https://github.com/CARTAvis/carta-casacore/pull/19) merged 11 April.
