### ISSUE TITLE
Incorrect projection in v3b1 when CROTA keys present

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-backend#912]
An IDIA user has some mosaics created from CASA and WSClean images, which both include the deprecated CROTA FITS header keys. I've asked for a copy of these images to provide for @kswang1029.

carta.idia (v2.0.1) projects it fine, including with diagonal grid lines for the mosaic of the WSClean images. But carta-beta.idia (v3.0.0-beta.1b) incorrectly projects it without the diagonal grid lines. Spatially matching them doesn’t change it either.

**Comment by kswang1029** [comment]
> Strangely enough, the CARTA backend now seems to replace `CROTA2` with `CROTA` 🤷 not sure why.
> 
> I noticed that converting the file to HDF5 using `fits2idia` solves the issue (`CROTA2` is no longer replaced with `CROTA` and the overlay renders correctly):
> 
> ![image](https://user-images.githubusercontent.com/592504/131859879-e23810e1-c18c-4a23-82ab-af43bc9eb76f.png)

Hmm so it is actually a backend issue?🤔
