### ISSUE TITLE
file info inconsistency

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#916]
The generated file info from FITS and CASA images has inconsistent entries, likely due to truncation error:

<img width="504" alt="Screen Shot 2021-09-08 at 10 03 35 AM" src="https://user-images.githubusercontent.com/20819712/132434788-dc07c0fa-43d1-4221-9628-078cd01af8d3.png">
<img width="504" alt="Screen Shot 2021-09-08 at 10 03 22 AM" src="https://user-images.githubusercontent.com/20819712/132434800-e17c3b78-3ffc-491b-b91d-c02c12798aa3.png">

**Comment by kswang1029** [comment]
@markccchiang would you be able to investigate this? This is also related to the unit test of file info extraction.

**Comment by markccchiang** [comment]
> @markccchiang would you be able to investigate this? This is also related to the unit test of file info extraction.

Ok.
