### ISSUE TITLE
load fz and fits.gz via the command line 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#924]
Reported by a user with v3b1 release:

It seems not being able to load fits.gz image directly via the command line (eg `carta xxx.fits.gz`). Tested with the ubuntu package 

<img width="400" alt="Screen Shot 2021-09-23 at 1 43 53 PM" src="https://user-images.githubusercontent.com/20819712/134459573-17f48760-56ac-4f2e-8421-bfc9355a809b.png">

(The same issue can be reproduced by loading the image in URL such as
`http://localhost:3002/?file=/Users/SpongeBob/carta_image_pool/set_compressed_fits/spire500_ext.fits.gz`. If we use double-click to load the image, we see the same issue too)

and the macOS electron app (`Error: Possibly an unsupported file type`).

We should also need to ensure fz can be loaded via the command line.

**Comment by kswang1029** [comment]
@ajm-asiaa would you be able to investigate the electron app for this? Not sure it is the electron wrapper or it is the carta_backend causing the issue.

**Comment by kswang1029** [comment]
@markccchiang would you be able to investigate this issue?

**Comment by veggiesaurus** [comment]
@kswang1029 can you load a fits.gz image using the URL query parameter?

**Comment by kswang1029** [comment]
> @kswang1029 can you load a fits.gz image using the URL query parameter?

nope. fz works fine.

**Comment by kswang1029** [comment]
I think as long as we load the image "quickly", the issue exists. By quickly I mean 
1) via URL query parameter
2) via double click
3) via command line 

If we load the image by single-click to see file info then single click the load button, everything is fine. Something odd in the file info/header gathering step?

**Comment by markccchiang** [comment]
> @markccchiang would you be able to investigate this issue?

Ok.

**Comment by veggiesaurus** [comment]
> I think as long as we load the image "quickly", the issue exists. By quickly I mean
> 
> 1. via URL query parameter
> 2. via double click
> 3. via command line
> 
> If we load the image by single-click to see file info then single click the load button, everything is fine. Something odd in the file info/header gathering step?

ok, then it must be a backend issue, not the electron app

**Comment by ajm-ska** [comment]
I'm suspicious of the Electron app. We were only allowing it to open fits and hdf5 files through the command line (folders were handled differently). I will investigate in more detail later.

```
       if (fs.statSync(arg1).isFile() === true) {
          if ( arg1.endsWith('.fits') || arg1.endsWith('.hdf5') )  {
            var filemode = 1
          } else {
            console.log('Error: Possibly an unsupported file type');
            process.exit()
         }
       }

**Comment by kswang1029** [comment]
> > I think as long as we load the image "quickly", the issue exists. By quickly I mean
> > 
> > 1. via URL query parameter
> > 2. via double click
> > 3. via command line
> > 
> > If we load the image by single-click to see file info then single click the load button, everything is fine. Something odd in the file info/header gathering step?
> 
> ok, then it must be a backend issue, not the electron app

with the electron app and an alias to the executable, I see `Error: Possibly an unsupported file type` from the terminal and the app does not launch. So I am not sure it is the backend or the electron wrapper. @ajm-asiaa are we able to pass all possible command line flags to the electron app executable?

**Comment by kswang1029** [comment]
> I'm suspicious of the Electron app. We were only allowing it to open fits and hdf5 files through the command line (folders were handled differently). I will investigate in more detail later.
> 
> ```
>        if (fs.statSync(arg1).isFile() === true) {
>           if ( arg1.endsWith('.fits') || arg1.endsWith('.hdf5') )  {
>             var filemode = 1
>           } else {
>             console.log('Error: Possibly an unsupported file type');
>             process.exit()
>          }
>        }
> ```

ok then this is it. We will also need to support `fz` and `fits.gz`

**Comment by ajm-ska** [comment]
OK. For the next release I will expand that line with the newly supported file types:
```
if ( arg1.endsWith('.fits') || arg1.endsWith('.hdf5') || arg1.endsWith('.fz') || arg1.endsWith('.fits.gz') )  {
```

**Comment by kswang1029** [comment]
@ajm-asiaa I created a separate issue https://github.com/CARTAvis/carta-backend/issues/925

**Comment by veggiesaurus** [comment]
> OK. For the next release I will expand that line with the newly supported file types:
> 
> ```
> if ( arg1.endsWith('.fits') || arg1.endsWith('.hdf5') || arg1.endsWith('.fz') || arg1.endsWith('.fits.gz') )  {
> ```

why are we not just using the backend for this? We don't use file extensions to deterime file type elsewhere in CARTA

**Comment by ajm-ska** [comment]
> 
> why are we not just using the backend for this? We don't use file extensions to deterime file type elsewhere in CARTA

This was from the early days. I thought it was a good idea to stop it from trying to open an incompatible file, accidentally or otherwise. If that were to be done, the Electron app would open with the frontend, the backend would immediately crash, but the Electron window would remain on screen with an unusable frontend. It may not be clear to the user what went wrong.

This way, it checks if the file _should_ be compatible, and immediately reports the problem to the user without starting Electron or the carta_backend.  

Don't forget that the Electron version requires its own wrapper script.

Maybe checking the file type is no longer necessary? I think it is still handy here to stop everything opening up and then crashing.

**Comment by veggiesaurus** [comment]
We shouldn't be checking the file type by extension though. And if the frontend tries to open an invalid file there will just be an error message, surely?

**Comment by kswang1029** [comment]
> We shouldn't be checking the file type by extension though. And if the frontend tries to open an invalid file there will just be an error message, surely?


It appears that if we feed unsupported files, the backend will die...
https://github.com/CARTAvis/carta-backend/issues/926

**Comment by ajm-ska** [comment]
> We shouldn't be checking the file type by extension though. And if the frontend tries to open an invalid file there will just be an error message, surely?

I just tried it with an incompatible file. The error message does not indicate what the problem is. I could press "retry" a million times and it would never reconnect.

![Screen Shot 2021-09-23 at 3 27 54 PM](https://user-images.githubusercontent.com/20802551/134469294-f8b17c5c-2a4d-4d34-a614-38713e60850f.png)

I still think it is a better user experience to immediately report the potential problem to the user on the command line (Remember this extra check only happens when the user is using the Electron app through the command line) and not proceed to open the Electron window at all.

**Comment by veggiesaurus** [comment]
Ok, I stand corrected, we clearly need to fix the crash. But if we want to check if files can be opened, we should take the same approach the backend uses (file content, not extension).

I wonder if we should add a --checkfiles command line to the backend that we can call from the electron wrapper to validate files

**Comment by ajm-ska** [comment]
I see. I didn't consider file content. Then when the backend handling of this is improved, we can remove the file extension checks from the Electron wrapper script.

**Comment by ajm-ska** [comment]
I think a `--checkfiles` flag would be just as useful to the new 'carta' wrapper script for the Debian version when using the command line. It would be even better if the file could be the first thing to check and not open the frontend if an incompatible file is used.
