### ISSUE TITLE
load fz and fits.gz from electron app via command line

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#925]
at the moment fz and fits.gz are not allowed to be loaded via electron app started via the command line

**Comment by ajm-ska** [comment]
Originally we had the Electron `main.js` filtering file formats by name when opening them from the command line. e.g. only allowing files ending in `.fits` and `.hdf5` to be opened. 
That restriction has now been removed from `main.js` and instead we can rely on the carta_backend itself to determine whether it can open a file or not.
I just tested this on a pre-v3.0.0-beta.3 macOS Electron version. It can now open `.fits.gz` and `.fz` directly via the command line. So this problem will be gone in any new releases and we can close the issue now.
