### ISSUE TITLE
backend crash when loading a non-image via the command line

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#926]
Tested with Ubuntu package. If we do something like `carta Jy_per_beam_TO_Kelvin.png`, the frontend loads up in the browser but we will immediately see a pop up due to backend crash.

**Comment by kswang1029** [comment]
@markccchiang could you investigate this?

**Comment by markccchiang** [comment]
> @markccchiang could you investigate this?

Ok.
