### ISSUE TITLE
Human-distinguishable security tokens

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#931]
As suggested in user feedback to initial testing of the scripting interface.

We now have two unrelated security tokens (for the websocket connection and for the gRPC connection), which have the exact same format and are difficult to tell apart. It would be helpful if we prepended a human-readable string (e.g. `WS_` or `GRPC_`) to the tokens that we generate to make them easier to distinguish by a human.

I think that at the moment the tokens can be arbitrary strings, and no part of the code expects them to be limited to a particular format, so this should be a small change to the backend code which generates tokens.

**Comment by veggiesaurus** [comment]
this may be unneccessary if we remove gRPC, right @confluence ?

**Comment by confluence** [comment]
Yes; then we will very sensibly have only one token.

**Comment by kswang1029** [comment]
then we can close this one.
