### ISSUE TITLE
Use carta namespaces consistently

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#933]
We currently don't consistently put all of our classes in the `carta` namespace. We should decide what structure the namespace should have (should there be nested namespaces corresponding to subdirectories?) and apply this system consistently.

**Comment by confluence** [comment]
I suggest that we include in this issue a review of the current subdirectory structure, and possibly move some files around. (For example:  `ProgramSettings` is global, not per-session, so it's unclear why it is in the `SessionManager` subdirectory.)

**Comment by jolopezl** [comment]
Hi @confluence, I like the idea of using consistent namespaces, and I agree that the current code organization needs changes (with `ProgramSettings` being an excellent example). So, we need to decide on two aspects: 

- namespace convention, and
- folder structure changes.

I tend to believe that one namespace is enough for our current needs, but this can change anytime in the near or far future. Therefore, I propose using at least two namespace levels, one for the project `carta` and one for each first level folder in the source code. For example:

```
namespace carta { // project namespace
namespace sessionmanager { // first-unique-additional level relative to src/folder
...
} // end of namespace sessionmanager
} // end of namespace carta.
```

Here, I like to follow the Google Style Guide for both the [namespaces organization](https://google.github.io/styleguide/cppguide.html#Namespaces) and the [namespaces naming](https://google.github.io/styleguide/cppguide.html#Namespace_Names), but we can do whatever we think it's better. For instance, `namespace sessionmanager` could be the same naming as the folder `namespace SessionManager`, and so on.

Regarding the folder structure and the current tree, I don't have any strong preference, but we can create a mapping somewhere else. The only suggestion I have in mind is to move `ProgramSettings` to `Util`, but it could be something else.

**Comment by confluence** [comment]
I think `ProgramSettings` definitely needs to move out of `SessionManager`; my suggestion would be to group it with `FileSettings` in a new `Settings` subdirectory. I don't want `Util` to turn into a catch-all location -- it should be for simple generic functions, particularly if they are used in multiple locations but don't clearly "belong" in any other place. It may be a good idea to move some of the files currently in `Util` to more specifically named subdirectories.

Other suggestions (very much up for debate):

* Move `Session`, `OnMessageTask`, `AnimationObject`, `SessionContext` and possibly `Frame` into `SessionManager` and rename it to `Session`
* Move `RequirementsCache` and `TileCache` in a `Cache` subdirectory
* Move `Concurrency` into `Util`
* Rename `Threading` to `ThreadManager` and move it to a subdirectory with the same name, or possibly move it to Util

**Comment by jolopezl** [comment]
I was looking at the code right now and I find that `Frame` could go somewhere else since it includes much more than just session management, and it's an essential part of the backend. I am thinking of putting it under something else as `Core` or `Engine`. Open to more suggestions @confluence, @veggiesaurus, @kswang1029.

**Comment by veggiesaurus** [comment]
> * Move `Concurrency` into `Util`
> * Rename `Threading` to `ThreadManager` and move it to a subdirectory with the same name, or possibly move it to Util

I'd quite like the threading and concurrency bits to be in the same dir.

**Comment by veggiesaurus** [comment]
> I was looking at the code right now and I find that `Frame` could go somewhere else since it includes much more than just session management, and it's an essential part of the backend. I am thinking of putting it under something else as `Core` or `Engine`. Open to more suggestions @confluence, @veggiesaurus, @kswang1029.

I guess the argument for keeping it as `Session` is that they are all per-session objects.

**Comment by jolopezl** [comment]
> > I was looking at the code right now and I find that `Frame` could go somewhere else since it includes much more than just session management, and it's an essential part of the backend. I am thinking of putting it under something else as `Core` or `Engine`. Open to more suggestions @confluence, @veggiesaurus, @kswang1029.
> 
> I guess the argument for keeping it as `Session` is that they are all per-session objects.

But almost everything else is a per-session object. If we were making that separation we would have two main levels, and then make another division.
