### ISSUE TITLE
FITS header extraction of BMAJ, BMIN, BPA

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#935]
reported by a user:

If the header does not contain BMAJ, BMIN, BPA as keys but these strings are stored as part of the HISTORY context, the backend still picks them up. The backend should ignore any keys from HISTORY.

> SIMPLE  =                    T /                                                
BITPIX  =                  -32 /                                                
NAXIS   =                    3 /                                                
NAXIS1  =                  585 /                                                
NAXIS2  =                  587 /                                                
NAXIS3  =                    1 /                                                
EXTEND  =                    T /Tables following main image                     
BLOCKED =                    T /Tape may be blocked                             
OBJECT  = '        '           /Source name                                     
TELESCOP= '        '           /                                                
INSTRUME= '        '           /                                                
OBSERVER= '        '           /                                                
DATE-OBS= '1987-05-26'         /Obs start date YYYY-MM-DD                       
DATE-MAP= '2017-08-14'         /Last processing date YYYY-MM-DD                 
BSCALE  =    1.00000000000E+00 /REAL = TAPE * BSCALE + BZERO                    
BZERO   =    0.00000000000E+00 /                                                
BUNIT   = 'JY/BEAM '           /Units of flux                                   
EQUINOX =      1.950000000E+03 /Epoch of RA DEC                                 
DATAMAX =      7.697948813E-01 /Maximum pixel value                             
DATAMIN =     -5.964934826E-03 /Minimum pixel value                             
CTYPE1  = 'RA---SIN'           /                                                
CRVAL1  =    8.28809244186E+01 /                                                
CDELT1  =     -2.777777845E-04 /                                                
CRPIX1  =      2.980000000E+02 /                                                
CROTA1  =      0.000000000E+00 /                                                
CTYPE2  = 'DEC--SIN'           /                                                
CRVAL2  =    2.19817385450E+01 /                                                
CDELT2  =      2.777777845E-04 /                                                
CRPIX2  =      2.750000000E+02 /                                                
CROTA2  =      0.000000000E+00 /                                                
CTYPE3  = 'FREQ    '           /                                                
CRVAL3  =    1.41000000000E+09 /                                                
CDELT3  =      1.000000000E+00 /                                                
CRPIX3  =      1.000000000E+00 /                                                
CROTA3  =      0.000000000E+00 /                                                
HISTORY --------------------------------------------------------------------    
HISTORY /Begin "HISTORY" information found in fits tape header by FITLD         
HISTORY EXTEND  =                    T /Tables following main image             
HISTORY BLOCKED =                    T /Tape may be blocked                     
HISTORY --------------------------------------------------------------------    
HISTORY /Begin "HISTORY" information found in fits tape header by FITLD         
HISTORY BLOCKED =                    T /Tape may be blocked                     
HISTORY --------------------------------------------------------------------    
HISTORY /Begin "HISTORY" information found in fits tape header by FITLD         
HISTORY BLOCKED =                    T /Tape may be blocked                     
HISTORY --------------------------------------------------------------------    
HISTORY /Begin "HISTORY" information found in fits tape header by FITLD         
HISTORY BLOCKED =                    T /TAPE MAY BE BLOCKED                     
HISTORY /--------------------------------------------------------------------   
HISTORY /BEGIN "HISTORY" INFORMATION FOUND IN WERONG FILEHEADER BY IMWER        
HISTORY /--------------------------------------------------------------------   
HISTORY /BEGIN "HISTORY" INFORMATION FOUND IN FITS TAPE HEADER BY UVLOD         
HISTORY BLOCKED =                    T /TAPE MAY BE BLOCKED                     
HISTORY  / WHERE BASELINE = 256*ANT1 + ANT2 + (ARRAY#-1)/100                    
HISTORY /--------------------------------------------------------------------   
HISTORY /BEGIN "HISTORY" INFORMATION FOUND IN FITS TAPE HEADER BY UVLOD         
HISTORY /--------------------------------------------------------------------   
HISTORY /BEGIN "HISTORY" INFORMATION FOUND IN FITS TAPE HEADER BY UVLOD         
HISTORY BLOCKED =                    T /TAPE MAY BE BLOCKED                     
HISTORY  / WHERE BASELINE = 256*ANT1 + ANT2 + (ARRAY#-1)/100                    
HISTORY /--------------------------------------------------------------------   
HISTORY /BEGIN "HISTORY" INFORMATION FOUND IN FITS TAPE HEADER BY UVLOD         
HISTORY (UVCOPY)                                                                
HISTORY UVCOPY Input file = INFIT1                                              
HISTORY UVCOPY Bcount=      1, Ncount= 272538, Weight= 1.000E+00                
HISTORY ASCAL (WERONG)                                                          
HISTORY ASCAL Visin = INFIT1                                                    
HISTORY ASCAL Input image model = INFIT2                                        
HISTORY ASCAL Visout = OUTFIT1                                                  
HISTORY ASCAL Clip level =  0.0000E+00                                          
HISTORY ASCAL Solution interval =  5.0000E+00 minutes                           
HISTORY ASCAL Solution type = phase                                             
HISTORY ASCAL Minimum no. of antennas =   3                                     
HISTORY ASCAL Sigma clip =  5.0000E+01                                          
HISTORY ASCAL Solution type = all                                               
HISTORY ASCAL Uvrange =  7.5000E+02 to  4.0000E+04 wavelengths                  
HISTORY ASCAL Exterior weight factor =  1.0000E-01                              
HISTORY ASCAL (WERONG)                                                          
HISTORY ASCAL Visin = INFIT1                                                    
HISTORY ASCAL Input image model = INFIT2                                        
HISTORY ASCAL Visout = OUTFIT1                                                  
HISTORY ASCAL Clip level =  0.0000E+00                                          
HISTORY ASCAL Solution interval =  2.0000E+00 minutes                           
HISTORY ASCAL Solution type = phase                                             
HISTORY ASCAL Minimum no. of antennas =   3                                     
HISTORY ASCAL Sigma clip =  5.0000E+01                                          
HISTORY ASCAL Solution type = all                                               
HISTORY ASCAL Uvrange =  7.5000E+02 to  5.0000E+04 wavelengths                  
HISTORY ASCAL Exterior weight factor =  1.0000E-01                              
HISTORY ASCAL (WERONG)                                                          
HISTORY ASCAL Visin = INFIT1                                                    
HISTORY ASCAL Input image model = INFIT2                                        
HISTORY ASCAL Visout = OUTFIT1                                                  
HISTORY ASCAL Clip level =  0.0000E+00                                          
HISTORY ASCAL Solution interval =  5.0000E+00 minutes                           
HISTORY ASCAL Solution type = amphase                                           
HISTORY ASCAL Minimum no. of antennas =   4                                     
HISTORY ASCAL Sigma clip =  5.0000E+01                                          
HISTORY ASCAL Solution type = all                                               
HISTORY ASCAL Uvrange =  7.5000E+02 to  5.0000E+04 wavelengths                  
HISTORY ASCAL Exterior weight factor =  1.0000E-01                              
HISTORY /END FITS TAPE HEADER "HISTORY" INFORMATION                             
HISTORY UVLOD RELEASE= '15OCT87 ' /-------------------------------------------- 
HISTORY UVLOD OUTNAME='L82A-D SC3  '   OUTCLASS='UVDATA'                        
HISTORY UVLOD OUTSEQ=    1   OUTDISK=  1                                        
HISTORY UVLOD  INFILE='DA01:MFB.L87UV3                                 '        
HISTORY /END FITS TAPE HEADER "HISTORY" INFORMATION                             
HISTORY UVLOD RELEASE= '15APR88 ' /-------------------------------------------- 
HISTORY UVLOD OUTNAME='L87A-D SC3  '   OUTCLASS='UVSRT '                        
HISTORY UVLOD OUTSEQ=    1   OUTDISK=  1                                        
HISTORY UVSUB RELEASE ='15APR88 '  /********* START 02-JUN-1988   13:15:21      
HISTORY UVSUB INNAME='L87A-D SC3  '   INCLASS='UVSRT '                          
HISTORY UVSUB INSEQ=    1   INDISK=  1                                          
HISTORY UVSUB IN2NAME='L82A-D SC3  '   IN2CLASS='ICLN  '                        
HISTORY UVSUB IN2SEQ=    3   IN2DISK=  2                                        
HISTORY UVSUB  VER =   0 /CC FILE VER. NO.                                      
HISTORY UVSUB  NMAPS =   1 / NUMBER OF MODEL IMAGES                             
HISTORY UVSUB  BCOMP( 1) =     1, NCOMP( 1) =    10 /FIRST-LAST COMP. NO.       
HISTORY UVSUB OUTNAME='L87A-D SC3- '   OUTCLASS='UVSRT '                        
HISTORY UVSUB OUTSEQ=    1   OUTDISK=  2                                        
HISTORY UVSUB  /STOKES TYPE OF MODEL = I                                        
HISTORY UVSUB  CHANNEL =   1,NCHAN=   1 / CHANNEL(S)                            
HISTORY UVSUB  CMETHOD = 'DFT ' / MODEL METHOD                                  
HISTORY UVSUB  CMODEL = 'COMP' / MODEL TYPE                                     
HISTORY UVSUB  OPCODE = 'SUB ' / OPERATION TYPE                                 
HISTORY UVSUB  FACTOR =     1.000 /MODEL FACTOR                                 
HISTORY ASCAL (WERONG)                                                          
HISTORY ASCAL Visin = INFIT1                                                    
HISTORY ASCAL Input image model = INFIT2                                        
HISTORY ASCAL Visout = OUTFIT1                                                  
HISTORY ASCAL Clip level =  1.0000E-04                                          
HISTORY ASCAL Solution interval =  2.0000E+00 minutes                           
HISTORY ASCAL Solution type = amphase                                           
HISTORY ASCAL Minimum no. of antennas =   4                                     
HISTORY ASCAL Sigma clip =  1.0000E+01                                          
HISTORY ASCAL Solution type = all                                               
HISTORY ASCAL Uvrange =  7.5000E+02 to  6.0000E+04 wavelengths                  
HISTORY ASCAL Exterior weight factor =  1.0000E-01                              
HISTORY /END FITS TAPE HEADER "HISTORY" INFORMATION                             
HISTORY UVLOD RELEASE= '15OCT87 ' /-------------------------------------------- 
HISTORY UVLOD OUTNAME='L87A-D SC4  '   OUTCLASS='UVDATA'                        
HISTORY UVLOD OUTSEQ=    1   OUTDISK=  1                                        
HISTORY UVLOD  INFILE='DA01:MFB.L87UV4                                 '        
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL=  4- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS. FLAGGED=     754    3016           
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL= 17- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS UNFLAGGED=       0       0          
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL=  4- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS UNFLAGGED=     754    3016          
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL=  7- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS UNFLAGGED=     678       0          
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL=  7- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS. FLAGGED=     678    2712           
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVFLG /   1 TIME=  0 23 59 58. TO   2  0  0  2. BL= 19- *  FLAGS=tt     
HISTORY UVFLG /   1 # SAMPLES SELECTED, VIS. FLAGGED=     738    2804           
HISTORY UVFLG     1 BCHAN=   1 ECHAN=  1 BIF=  1 EIF=  1                        
HISTORY UVMAP (WERONG)                                                          
HISTORY UVMAP Visin = INFIT1                                                    
HISTORY UVMAP Output image = OUTFIT1                                            
HISTORY UVMAP Output beam = OUTFIT2                                             
HISTORY UVMAP Cellx,y =  5.0000E-01,  5.0000E-01 arcsec                         
HISTORY UVMAP Imsizx,y =  2048,  2048 pixels                                    
HISTORY UVMAP Supx,y =  1.0240E+03,  1.0240E+03                                 
HISTORY UVMAP Uvrange =  3.3000E+02 to  1.0000E+06 wavelengths                  
HISTORY UVMAP Taperx,y =  0.0000E+00,  0.0000E+00                               
HISTORY UVMAP Gridding convolution function is spheroidal                       
HISTORY UVMAP Gridding parameters: alpha =  1.0000E+00, width =  6              
HISTORY VM (WERONG)                                                             
HISTORY VM Input image = INFIT1                                                 
HISTORY VM Beam image = INFIT2                                                  
HISTORY VM Model = INFIT3                                                       
HISTORY VM Output image = OUTFIT1                                               
HISTORY VM Alpha =  7.8240E+02, Beta =  0.0000E+00, Tol =  1.0000E-02           
HISTORY VM Measure = gull     Niter =  17                                       
HISTORY VM Begin rms =  1.8000E-04, Flux = -8.8740E+00                          
HISTORY VM End rms =  1.7879E-04, Flux =  8.6676E+02                            
HISTORY VM Q =  2.4001E+01                                                      
HISTORY VM Window =  499, 626 -> 1514,1644                                      
HISTORY RESTOR (WERONG)                                                         
HISTORY RESTOR Input image = INFIT1                                             
HISTORY RESTOR Input beam = INFIT2                                              
HISTORY RESTOR Input model = INFIT3                                             
HISTORY RESTOR Output image = OUTFIT1                                           
HISTORY RESTOR Beam =  2.000E+00 x  1.800E+00 arcsec, pa =  8.000E+01 degrees   
HISTORY RESTOR Restoration type = restore                                       
HISTORY /END WERONG FILE HEADER "HISTORY" INFORMATION                           
HISTORY /--------------------------------------------------------------------   
HISTORY IMWER OUTNAME ='14.87 SC5   '      OUTCLASS ='IVMR  '                   
HISTORY IMWER OUTSEQ =    1     OUTDISK= 1                                      
HISTORY IMWER RELEASE = '15OCT87 '                                              
HISTORY SUBIM RELEASE ='15APR88 '  /********* START 08-DEC-1988   18:14:07      
HISTORY SUBIM INNAME='14.87 SC5   '   INCLASS='IVMR  '                          
HISTORY SUBIM INSEQ=    1   INDISK=  1                                          
HISTORY SUBIM INTYPE ='MA'      USERID= 1477                                    
HISTORY SUBIM OUTNAME='14.87 SC5   '   OUTCLASS='UVMR  '                        
HISTORY SUBIM OUTSEQ=    3   OUTDISK=  1                                        
HISTORY SUBIM BLC =  431,  476,   1,   1,   1,   1,   1                         
HISTORY SUBIM TRC = 1600, 1650,   1,   1,   1,   1,   1                         
HISTORY SUBIM XINC =    1      YINC =    1                                      
HISTORY RENAM INNAME='14.87 SC5   '   INCLASS='UVMR  '                          
HISTORY RENAM INSEQ=    3   INDISK=  1                                          
HISTORY RENAM OUTNAME='14.87 SC5   '   OUTCLASS='IVMR  '                        
HISTORY RENAM OUTSEQ=    2   OUTDISK=  1                                        
HISTORY /END FITS tape header "HISTORY" information                             
HISTORY --------------------------------------------------------------------    
HISTORY FITLD OUTNAME ='            '      OUTCLASS ='      '                   
HISTORY FITLD OUTSEQ =    0     INTAPE = 0     OUTDISK= 1                       
HISTORY FITLD INFILE = 'DA01:CX1.FTS                                    '       
HISTORY FITLD RELEASE = '15JAN95'                                               
HISTORY /END FITS tape header "HISTORY" information                             
HISTORY --------------------------------------------------------------------    
HISTORY FITLD OUTNAME ='            '      OUTCLASS ='POLF  '                   
HISTORY FITLD OUTSEQ =    1     INTAPE = 0     OUTDISK= 8                       
HISTORY FITLD RELEASE = '31DEC01'                                               
HISTORY RENAM INNAME='14.87 SC5   '   INCLASS='POLF  '                          
HISTORY RENAM INSEQ=    1   INDISK=  8                                          
HISTORY RENAM OUTNAME='14.87 SC5   '   OUTCLASS='IVMR  '                        
HISTORY RENAM OUTSEQ=    1   OUTDISK=  8                                        
HISTORY PUTHEAD BMAJ     =  0.00000E+00      / old                              
HISTORY PUTHEAD BMAJ     =  5.55556E-04      / new                              
HISTORY PUTHEAD BMIN     =  0.00000E+00      / old                              
HISTORY PUTHEAD BMIN     =  5.00000E-04      / new                              
HISTORY PUTHEAD BPA      =  0.00000E+00      / old                              
HISTORY PUTHEAD BPA      =  8.00000E+01      / new                              
HISTORY AXDEF INNAME='14.87 SC5   '   INCLASS='IVMR  '                          
HISTORY AXDEF INSEQ=    1   INDISK=  8                                          
HISTORY AXDEF CTYPE3  = 'FREQ    '          / NEW Axis type                     
HISTORY AXDEF CRVAL3  =  1.410000000E+09    / NEW Reference pixel value         
HISTORY AXDEF CDELT3  =  1.00000E+00        / NEW Axis increment                
HISTORY AXDEF CRPIX3  =     1.000           / NEW Reference pixel loc           
HISTORY PUTHEAD EPOCH    =  0.00000E+00      / old                              
HISTORY PUTHEAD EPOCH    =  1.95000E+03      / new                              
HISTORY PUTHEAD NITER    =        0          / old                              
HISTORY PUTHEAD NITER    =       17          / new                              
HISTORY /END FITS tape header "HISTORY" information                             
HISTORY --------------------------------------------------------------------    
HISTORY FITLD OUTNAME ='            '      OUTCLASS ='      '                   
HISTORY FITLD OUTSEQ =   -1     INTAPE = 0     OUTDISK= 8                       
HISTORY FITLD INFILE = 'INFITS:DISK08C0006                              '       
HISTORY FITLD RELEASE = '31DEC05'                                               
HISTORY MOVE  INNAME='14.87 SC5   '   INCLASS='IVMR  '                          
HISTORY MOVE  INSEQ=    1   INDISK=  8                                          
HISTORY MOVE  OUTNAME='14.87 SC5   '   OUTCLASS='IVMR  '                        
HISTORY MOVE  OUTSEQ=    1   OUTDISK=  7                                        
HISTORY MOVE  INNAME='14.87 SC5   '   INCLASS='IVMR  '                          
HISTORY MOVE  INSEQ=    1   INDISK=  7                                          
HISTORY MOVE  OUTNAME='14.87 SC5   '   OUTCLASS='IVMR  '                        
HISTORY MOVE  OUTSEQ=    1   OUTDISK=  7                                        
HISTORY /END FITS tape header "HISTORY" information                             
HISTORY --------------------------------------------------------------------    
HISTORY FITLD OUTNAME ='            '      OUTCLASS ='      '                   
HISTORY FITLD OUTSEQ =   -1     INTAPE = 0     OUTDISK= 1                       
HISTORY FITLD INFILE = 'HOME:crab.fits'                                         
HISTORY FITLD RELEASE = '31DEC09'                                               
HISTORY CONVL RELEASE ='31DEC17 '  /********* Start 14-AUG-2017   07:13:16      
HISTORY CONVL INNAME='14.87 SC5   '   INCLASS='IVMR  '                          
HISTORY CONVL INSEQ=    1   INDISK=  1                                          
HISTORY CONVL OUTNAME='14.87 SC5   '   OUTCLASS='CONVL '                        
HISTORY CONVL OUTSEQ=    1   OUTDISK=  1                                        
HISTORY CONVL BLC=    1.    1.    1.    1.    1.    1.    1./BLC                
HISTORY CONVL TRC= 1170. 1175.    1.    1.    1.    1.    1./TRC                
HISTORY CONVL FACTOR= 6.94439E+00 / Units scaling factor                        
HISTORY CONVL BMAJ=  5.0000 BMIN=  5.0000 BPA=   0.0/Output beam                
HISTORY CONVL / plane     1 conv with   4.66476 x   4.58257 at 170.0            
HISTORY CONVL OPCODE='    ' /Operation requested                                
HISTORY CONVL DOBLANK = 1   / Blanks restored after FFT                         
HISTORY SUBIM RELEASE ='31DEC17 '  /********* Start 14-AUG-2017   07:29:59      
HISTORY SUBIM INNAME='14.87 SC5   '   INCLASS='CONVL '                          
HISTORY SUBIM INSEQ=    1   INDISK=  1                                          
HISTORY SUBIM INTYPE ='MA'      USERID= 1577                                    
HISTORY SUBIM OUTNAME='14.87 SC5   '   OUTCLASS='SUBIM '                        
HISTORY SUBIM OUTSEQ=    2   OUTDISK=  1                                        
HISTORY SUBIM BLC    =    1,    2,    1,    1,    1,    1,    1                 
HISTORY SUBIM TRC    = 1170, 1175,    1,    1,    1,    1,    1                 
HISTORY SUBIM XINC   =    2                                                     
HISTORY SUBIM YINC   =    2                                                     
HISTORY SUBIM ZINC   =    1                                                     
HISTORY SUBIM OPCODE = 'AVE '                                                   
HISTORY RENAM INNAME='14.87 SC5   '   INCLASS='SUBIM '                          
HISTORY RENAM INSEQ=    2   INDISK=  1                                          
HISTORY RENAM OUTNAME='14.87 SC5   '   OUTCLASS='IVMRCS'                        
HISTORY RENAM OUTSEQ=    3   OUTDISK=  1                                        
HISTORY FITTP DATAOUT = 'HOME:crab_1.4GHz.fits' / data written to disk file     
HISTORY PBCOR RELEASE ='31DEC17 '  /********* Start 14-AUG-2017   07:33:21      
HISTORY PBCOR INNAME='14.87 SC5   '   INCLASS='IVMRCS'                          
HISTORY PBCOR INSEQ=    0   INDISK=  1                                          
HISTORY PBCOR OUTNAME='14.87 SC5   '   OUTCLASS='PBCOR '                        
HISTORY PBCOR OUTSEQ=    0   OUTDISK=  1                                        
HISTORY PBCOR BLC=   1,   1,   1,  1,  1, 1, 1 TRC= 585, 587,   1,  1,  1, 1, 1 
HISTORY PBCOR PRA=  05 31 31.422  PDec=  21 58 54.26                            
HISTORY PBCOR Beamcut=  0.02300   /Clip outside this beam value                 
HISTORY PBCOR DOINVERS =-1.0   / > 0 multiply by beam                           
HISTORY PBCOR / Beam =  1.000000E+00 +     / Beam  model                        
HISTORY PBCOR /        -1.449000E-03 * X +                                      
HISTORY PBCOR /         8.020000E-07 * X*X +                                    
HISTORY PBCOR /        -1.740000E-10 * X*X*X +                                  
HISTORY PBCOR / Where X = [Angle(arcmin) * f(GHz)]**2                           
HISTORY PBCOR / above from EVLA 2016 model interpolated between   1.360 GHz     
HISTORY PBCOR / and   1.424 GHz parameters below                                
HISTORY PBCOR / Beam =  1.000000E+00 +     / Beam  model                        
HISTORY PBCOR /        -1.462000E-03 * X +                                      
HISTORY PBCOR /         8.230000E-07 * X*X +                                    
HISTORY PBCOR /        -1.830000E-10 * X*X*X +                                  
HISTORY PBCOR / Where X = [Angle(arcmin) * f(GHz)]**2                           
HISTORY FITTP DATAOUT = 'HOME:crab_1.4GHz_PB.fits' / data written to disk file  
ORIGIN  = 'AIPSdailyalice   YORKASTRO            31DEC18'    /                  
DATE    = '2018-01-31'   / File written on Greenwich yyyy-mm-dd                 
HISTORY AIPS   IMNAME='14.87 SC5   ' IMCLASS='PBCOR ' IMSEQ=   3     /          
HISTORY AIPS   USERNO= 1577            /                                        
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
HISTORY AIPS   CLEAN BMAJ=  1.3889E-03 BMIN=  1.3889E-03 BPA=   0.00            
HISTORY AIPS   CLEAN NITER=       17 PRODUCT=1   / NORMAL                       
END                                                                             

In the above case, this line `HISTORY CONVL BMAJ=  5.0000 BMIN=  5.0000 BPA=   0.0/Output beam                ` is picked up and used to compute the restoring beam size for the file info. So it is 18000" displayed. In this case, the restoring beam should be undefined.

**Comment by pford** [comment]
This is an intentional "feature" of casacore::FITSImage, which has this comment:

// Try and find the restoring beam in the history cards if
// its not in the header

@kswang1029 do you want to override the casacore behavior?

**Comment by pford** [comment]
Another comment indicates that setting the beam from HISTORY is a result of AIPS writing the beam there, rather than in the header keywords.  CONVL is an AIPS task so this behavior makes sense and should be a valid beam.

**Comment by kswang1029** [comment]
> Another comment indicates that setting the beam from HISTORY is a result of AIPS writing the beam there, rather than in the header keywords. CONVL is an AIPS task so this behavior makes sense and should be a valid beam.

The example obtained from the user is an example of quoting an incorrect beam size from the history header unfortunately. Is it possible to switch off this guessing “feature”? If beam is not defined with BMAJ, BMIN, and BPA explicitly in the header, we should set them undefined. History is only trustworthy after parsing by human brain I think.
