### ISSUE TITLE
cfitsio 3.47 dependency for RHEL7/CentOS7

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#940]
I will put this here for now even though technically it should go to the fits2idia repository?

For RHEL7/CentOS7 we can not build the carta-backend with the unit-tests (-Dtest=on). This is because RHEL7 comes with cfitsio 3.37 by default (through the [EPEL repository](https://centos.pkgs.org/7/epel-x86_64/cfitsio-3.370-10.el7.x86_64.rpm.html)). The older cfitsio 3.37 works fine if simply building the carta-backend as a release version, but there is a problem if we try to build it with the unit-tests.

A workaround is to install a newer cfitsio, such as version 3.47 (the same version used by Ubuntu 20.04 and RHEL8). That could be easily supplied on our cartavis rpm repository. However, it is not ideal. As @veggiesaurus points out, installing a newer cfitsio on a users machine could conflict with other astronomy software that use that library, plus we should ensure that we run the tests using the same version of cfitsio as the packaged version. This is important because cfitsio is quite a crucial library for CARTA and we don't want it to potentially produce incorrect results.

The error at build time is:
```
/root/carta-backend/third-party/fits2idia/Util.cc: In function 'void readFitsStringAttribute(fitsfile*, const string&, std::string&)':
/root/carta-backend/third-party/fits2idia/Util.cc:142:5: error: 'fits_read_string_key' was not declared in this scope; did you mean 'fits_read_key'?
  142 |     fits_read_string_key(filePtr, name.c_str(), 1, 255, strValueTmp, &strLen, NULL, &status);
      |     ^~~~~~~~~~~~~~~~~~~~
      |     fits_read_key
make[5]: *** [CMakeFiles/fits2idia.dir/Util.cc.o] Error 1
make[4]: *** [CMakeFiles/fits2idia.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [test/fits2idia-prefix/src/fits2idia-stamp/fits2idia-build] Error 2
make[1]: *** [test/CMakeFiles/fits2idia.dir/all] Error 2
make: *** [all] Error 2
```

It is a bit awkward to reproduce through the current [Dockerfile-CentOS7](https://github.com/CARTAvis/carta-backend/blob/dev/Dockerfiles/Dockerfile-CentOS7) as it requires some other updates (Now needs gtest 1.10, plus there appears to be a gcc problem). For now the fastest way may be:

1. Remove the lines 20-27 that install cfitsio 3.47 from source.
2. Add `cfitsio-devel` to the yum install command at line 16.
3. Instead of building the carta-backend, try building fits2idia converter directly e.g.
```
cd /root/carta-backend/third-party/fits2idia
mkdir build
cd build
cmake ..
make
```

**Comment by confluence** [comment]
It looks like this is _only_ a dependency for building the converter. Removing this function from the converter would be non-trivial. I think that the most sensible approach would be to stop building the converter from the test build and add it as a runtime binary dependency -- we could then create a patched CentOS7 package for the converter (possibly with a static CFITSIO) and eliminate this build issue from the backend. It is not necessary for the converter and the backend to be built using the same CFITSIO version.

**Comment by veggiesaurus** [comment]
@confluence can I leave this to you, then? You can make the converter a runtime dependency, and then you can make a new issue for @ajm-asiaa to package the converter with a statically-linked cftisio?

**Comment by confluence** [comment]
Yes. I will create a branch and make the change in our cmake config. (We can use [`find_program`](https://cmake.org/cmake/help/latest/command/find_program.html).)

**Comment by confluence** [comment]
@ajm-asiaa I have made a draft PR [here](https://github.com/CARTAvis/carta-backend/pull/941). If you make the appropriate packages and test them with that branch, we should also modify the dockerfiles before merging the PR.
