### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#95]
Intentionally vague epic for performance improvements. Performance in this case is related to five major areas of concern:
- I/O performance of the backend
- Memory use of the backend
- CPU use and core utilisation of the backend
- Network efficiency
- CPU use of the frontend

In the short term, these include some fixes to how files are read and how analysis tasks are calculated. 

In the medium term, improvements will require adjustments to the threading model and implementation of some missing ICD features (animation messages)

In the medium-to-long-term, changes to how data is delivered to the frontend will need to be made, including:
- Switching to a tiled data delivery and rendering system
- Introducing alternative compression approaches, such as NVENC, for high efficiency image compression.

**Comment by zarda** [comment]
For the backend, the intel VTune amplifier is a powerful tool to monitor almost everything.
