### ISSUE TITLE
votable catalog column with unicodeChar is not recognized 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#950]
as reported by a user.

[carta_votable_test.xml.zip](https://github.com/CARTAvis/carta-backend/files/7422901/carta_votable_test.xml.zip)

all formats in https://www.ivoa.net/documents/VOTable/20191021/REC-VOTable-1.4-20191021.pdf Section 2.1

**Comment by veggiesaurus** [comment]
There's an easy way to "support" unicode chars in CARTA (a one-line fix), which just treats columns of type `unicodeChar` as `char`. But I'm not sure this will actually work properly with unicode strings. It works fine with the file above, but that doesn't contain any special characters.

**Comment by veggiesaurus** [comment]
actually it seems to work ok with a brief check:

![image](https://user-images.githubusercontent.com/592504/139070641-a7c92f13-d8fe-4511-87c7-b0185a385c53.png)

**Comment by kswang1029** [comment]
If we support Unicode char how do we do filtering?

**Comment by veggiesaurus** [comment]
> If we support Unicode char how do we do filtering?

It seems to just work :shrug: 

![image](https://user-images.githubusercontent.com/592504/139082663-61a748b4-acda-4e05-b87b-c99e447cb7ed.png)

**Comment by kswang1029** [comment]
> > If we support Unicode char how do we do filtering?
> 
> It seems to just work 🤷
> 
> ![image](https://user-images.githubusercontent.com/592504/139082663-61a748b4-acda-4e05-b87b-c99e447cb7ed.png)

😂😂😂
