### ISSUE TITLE
Remove gRPC

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend#952]
gRPC is an unnecessarily complex solution for the current scripting design. Our wrapper (and potential other wrappers) only needs to send one kind of message to the backend, and this could be done via a new endpoint in the existing HTTP server. This would give us asynchronous scripting requests for free, allow scripting commands to be issued via standard HTTP tools, make SDM integration of the scripting wrapper much easier, and also remove the gRPC dependency from both the wrapper and the backend.

This has a [companion issue in the wrapper](https://github.com/idia-astro/carta-python/issues/26).

**Comment by kswang1029** [comment]
I remembered gRPC was also added to casacode when we add it to carta codebase?

**Comment by confluence** [comment]
Maybe they can also remove a dependency. 🙈 They should be able to use the same simple HTTP request to use the proposed new API.

IIRC when we first added scripting support we didn't even have a built-in HTTP server, so this wouldn't have been possible at the start.
