### ISSUE TITLE
rounding errors in world coordinates of exported polyline region as ds9 format

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#953]
if a polyline is exported as casa format in world coordinate, we see

> #CRTFv0 CASA Region Text Format version 0
polyline [[17:56:21.67061, -021.57.16.6090], [17:56:21.69974, -021.57.21.6747], [17:56:21.56575, -021.57.19.4053], [17:56:21.57449, -021.57.23.8226], [17:56:21.48419, -021.57.22.9715], [17:56:21.49001, -021.57.25.6867]] coord=J2000, corr=[I], linewidth=2, linestyle=-, symsize=1, symthick=1, color=2ee6d6, font=Helvetica, fontsize=10, fontstyle=bold, usetex=false

However, if the format is ds9 we see

> #Region file format: DS9 CARTA 3.0.0-beta.1b
global color=green dashlist=8 3 width=1 font="helvetica 10 normal roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 include=1 source=1
fk5
polyline(269.0903, -21.9546, 269.0904, -21.9560, 269.0899, -21.9554, 269.0899, -21.9566, 269.0895, -21.9564, 269.0895, -21.9571) # color=#2EE6D6 width=2

As this is in degree, we will need more digits to prevent rounding errors. 

![Screen Shot 2021-10-28 at 11 37 53 AM](https://user-images.githubusercontent.com/20819712/139182854-850910cd-12c0-4f8c-ac71-cbfc78118b26.png)

**Comment by pford** [comment]
This is likely an issue with other DS9 regions as well, such as polygon.
