### ISSUE TITLE
Migrate 2D image cache away from std::vector<float>

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#967]
We currently use a `std::vector<float>` for `Frame::_image_cache`. However, the ability to resize the image cache is not of any use, because a new cache is made for each separate image, and all image channels have the same 2D slice size. The main problem with using a `std::vector` is that we end up allocating memory _and_ initialising to zero before we fill it with values from disk. This means it will always be slower than something like a simple c-style array.

This is not a problem for small images, but for large images it can become a substantial portion of the initial image load time.

**Comment by jolopezl** [comment]
@veggiesaurus, do we have any design constraint to resist introducing c-style arrays here in favor of a significant performance gain for large images?

**Comment by veggiesaurus** [comment]
No, thats totally fine, as long as they are carefully cleaned up. We don't actually ever need to resize the image cache if I recall correctly
