### ISSUE TITLE
Hard crash when animation messages are received in unexpected order

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#981]
@robsimmonds to fill in description shortly...

**Comment by robsimmonds** [comment]
I believe the issue is due to something slightly different. I think that if an animation task is still running when a new one is created, the pointer to the animation object in the session object can be left in a bad state. In this case serialising the update of that pointer should resolve this.

**Comment by confluence** [comment]
This was fixed in previous commits.
