### ISSUE TITLE
backend crash when requesting statistics from gz or fz FITS image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#999]
**Describe the bug**
backend crash when requesting statistics from gz or fz FITS image

**To Reproduce**
1. Load one of the attached images
2. Enable the statistics widget
3. Should see backend crash

**Expected behavior**
backend should not crash

**Screenshots or videos**
n/a

**Platform info (please complete the following information):**
 - OS: macOS Monterey (intel)
 - Browser: chrome
 - Version:  97.0.4692.71

**Additional context**
test image:
https://drive.google.com/file/d/1RC7CzRIsgC9XSIco4flIc1FoOrTjc2Jf/view?usp=sharing
https://drive.google.com/file/d/1SUAGtcgEavjirm7yK87GU_1UaU5khMLU/view?usp=sharing

**Comment by confluence** [comment]
Was this fixed by #1119?

**Comment by kswang1029** [comment]
yes
